# Summary of best models for given numbers of layers

In [ ]:
# Each row is the output for a model in the following format. Different lines for different model structures. See the cell below for the excecuted codes.
# print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {tloss:.4f}, {torch.Tensor(loss).mean():.4f}, {N_step}],')
# Example: [16layers, 12(6)heads, hidden-dim=696, inter-layer-dim = 696x4, head-dim=224, #param=218million, train_loss, val_loss, Num-steps]

[ 36, 4, 2, 624, 2496, 256, 268.8, 2.6873,+2.4216, 180000], # valx4 env1 2.4205(valx8)  minGemma-hidden_layers36-att_heads4-kv_heads2-hidden624-intermediate2496-head_dim256-T1024--2026-01-29-10-22.pth
[ 30, 6, 3, 648, 2592, 192, 251.1, 2.6060,+2.4177, 180000], # valx4 env1 2.4170(valx8)  minGemma-hidden_layers30-att_heads6-kv_heads3-hidden648-intermediate2592-head_dim192-T1024--2026-04-23-19-31.pth
[ 24, 6, 3, 600, 2400, 224, 192.1, 2.5905, 2.4330, 360000], # valx1 env1 2.4339(valx8)  minGemma-hidden_layers24-att_heads6-kv_heads3-hidden600-intermediate2400-head_dim224-T1024--2025-12-28-10-16.pth
[ 20, 8, 2, 688, 2752, 224, 210.0, 2.5680,+2.4208, 360000], # valx4 env1 2.4195(valx8)  minGemma-hidden_layers20-att_heads8-kv_heads2-hidden688-intermediate2752-head_dim224-T1024--2026-03-13-04-59.pth
[ 18,10, 5, 720, 2880, 224, 235.4, 2.6025,+2.4197, 360000], # valx1 env1 2.4199(valx8)  minGemma-hidden_layers18-att_heads10-kv_heads5-hidden720-intermediate2880-head_dim224-T1024--2026-01-06-22-19.pth
[ 16, 9, 3, 684, 2736, 320, 208.4, 2.5844,+2.4195, 360000], # valx4 env1 2.4177(valx8)  minGemma-hidden_layers16-att_heads9-kv_heads3-hidden684-intermediate2736-head_dim320-T1024--2026-05-11-09-41.pth
[ 12,10, 5, 760, 3040, 224, 182.8, 2.6251,+2.4285, 360000], # valx1 env1 2.4291(valx8)  minGemma-hidden_layers12-att_heads10-kv_heads5-hidden760-intermediate3040-head_dim224-T1024--2026-01-11-04-23.pth

# L36 (Models with 36 Layers)

In [ ]:
# L36 Normal T1024 Baby100M (default: B28//2 N90000 lr16e-4 WD0.5)  # H4(2): 2.4205, H3(3): 2.4236(valx1), H3(1): 2.4230

# local best for H4(2): 2.4213(valx4), 2.4205(valx8)
[ 36, 4, 2, 720, 2880, 192, 320.1, 2.8341, 2.4250, 180000], # 56.9h 38.3G valx1 env1 ### bad in valx4
[ 36, 4, 2, 720, 2880, 192, 320.1, 2.8110, 2.4304, 180000], # 57.3h 39.0G valx4 env1 ### bad in valx4
[ 36, 4, 2, 720, 2880, 160, 310.2, 2.7314, 2.4272, 180000], # 54.0h 39.4G valx1 env1 ### valx1: B2=12 and Repeat=5300
[ 36, 4, 2, 720, 2880, 144, 305.2, 2.7696, 2.4264, 180000], # 52.8h       valx1 env1

[ 36, 4, 2, 672, 2688, 256, 303.4, 2.8326, 2.4260, 180000], # 61.1h 38.8G valx1 env1 ### bad in valx4
[ 36, 4, 2, 672, 2688, 256, 303.4, 2.8888, 2.4297, 180000], # 61.6h again valx4 env1 ### bad in valx4
[ 36, 4, 2, 672, 2688, 224, 294.2, 2.7181, 2.4244, 180000], # 58.2h       valx1 env1 ### bad in valx4
[ 36, 4, 2, 672, 2688, 224, 294.2, 2.6624, 2.4273, 180000], # 58.7h 38.5G valx4 env1 ### bad in valx4
[ 36, 4, 2, 672, 2688, 192, 284.9, 2.7215, 2.4227, 180000], # 54.8h 38.2G valx1 env1 ### bad in valx4
[ 36, 4, 2, 672, 2688, 192, 284.9, 2.8551, 2.4300, 180000], # 54.9h 38.0G valx4 env1 ### bad in valx4
#[36, 4, 2, 672, 2688, 192, 284.9, 2.6718, 2.4507, 180000], # 45.2h again valx4 env2 ### by default: valx4(=env2)
#[36, 4, 2, 672, 2688, 192, 284.9, 2.8225, 2.4510, 180000], # 45.0h again valx4 env2 WD2/3
[ 36, 4, 2, 672, 2688, 160, 275.6, 2.7233, 2.4234, 180000], # 51.5h       valx1 env1 ### bad in valx4
[ 36, 4, 2, 672, 2688, 160, 275.6, 2.6948, 2.4252, 180000], # 51.9h 36.7G valx4 env1 ### bad in valx4
#[36, 4, 2, 672, 2688, 160, 275.6, 2.7565, 2.4378, 180000], # 43.5h again valx4 env2 WD2/3
[ 36, 4, 2, 672, 2688, 144, 270.9, 2.6856, 2.4242, 180000], # 50.3h 37.6G valx1 env1 ### bad in valx4 but marginal
[ 36, 4, 2, 672, 2688, 144, 270.9, 2.6673, 2.4239, 180000], # 50.6h 36.9G valx4 env1 ### bad in valx4 but marginal

#[36, 4, 2, 624, 2496, 288, 277.5, 2.6975, 2.4566, 180000], # 53.4h 38.3G valx4 env2
[ 36, 4, 2, 624, 2496, 288, 277.5, 2.7914, 2.4303, 180000], # 66.1h 38.3G valx4 env1
[+36, 4, 2, 624, 2496, 256, 268.8, 2.6873,+2.4216, 180000], # 58.4h 36.9G valx4 env1  minGemma-hidden_layers36-att_heads4-kv_heads2-hidden624-intermediate2496-head_dim256-T1024--2026-01-29-10-22.pth
# valx8: 2.4205 +- 0.0034 # torch.Tensor([2.4226, 2.4198, 2.4156, 2.4213, 2.4264, 2.4216, 2.4169, 2.4199]).std()
[ 36, 4, 2, 624, 2496, 224, 260.2, 2.6556, 2.4229, 180000], # 55.6h 38.1G valx1 env1
[ 36, 4, 2, 624, 2496, 224, 260.2, 2.6524,+2.4213, 180000], # 56.0h again valx4 env1  minGemma-hidden_layers36-att_heads4-kv_heads2-hidden624-intermediate2496-head_dim224-T1024--2026-03-17-23-37.pth
# valx8: 2.4221 +- 0.0052 # torch.Tensor([2.4318, 2.4189, 2.4230, 2.4221, 2.4231, 2.4135, 2.4200, 2.4247]).std()
#[36, 4, 2, 624, 2496, 224, 260.2, 2.7034, 2.4452, 180000], # 46.4h again valx4 env2
[ 36, 4, 2, 624, 2496, 192, 251.6, 2.7248, 2.4303, 180000], # 52.1h 37.1G valx1 env1
[ 36, 4, 2, 624, 2496, 160, 242.9, 2.7269, 2.4288, 180000], # 49.0h 35.8G valx3 env1 # [2.4263, 2.4340, 2.4261]

[ 36, 4, 2, 576, 2304, 320, 252.1, 2.7255, 2.4276, 180000], # 67.0h 37.1G valx4 env1
#[36, 4, 2, 576, 2304, 288, 244.2, 2.5844, 2.4447, 180000], # 50.4h 35.7G valx4 env2
[ 36, 4, 2, 576, 2304, 288, 244.2, 2.6341,+2.4226, 180000], # 63.9h       valx4 env1  minGemma-hidden_layers36-att_heads4-kv_heads2-hidden576-intermediate2304-head_dim288-T1024--2026-02-24-07-14.pth
# valx8: 2.4212 +- 0.0032 # torch.Tensor([2.4215, 2.4238, 2.4220, 2.4261, 2.4210, 2.4214, 2.4181, 2.4155]).std()
#[36, 4, 2, 576, 2304, 256, 236.2, 2.6106, 2.4392, 180000], # 45.0h 35.6G valx4 env2
[ 36, 4, 2, 576, 2304, 256, 236.2, 2.6889, 2.4297, 180000], # 56.7h again valx4 env1
#[36, 4, 2, 576, 2304, 224, 228.2, 2.5822, 2.4419, 180000], # 43.8h       valx4 env2
[ 36, 4, 2, 576, 2304, 224, 228.2, 2.6121, 2.4245, 180000], # 53.8h 32.1G valx4 env1
[ 36, 4, 2, 576, 2304, 192, 220.3, 2.7431, 2.4253, 180000], # 50.0h 32.8G valx1 env1 ### bad in valx4
[ 36, 4, 2, 576, 2304, 192, 220.3, 2.6727, 2.4255, 180000], # 50.2h again valx4 env1 ### bad in valx4

[ 36, 4, 2, 528, 2112, 320, 220.2, 2.6526, 2.4275, 180000], # 65.4h 33.4G valx4 env1
[ 36, 4, 2, 528, 2112, 288, 212.9, 2.6403,+2.4220, 180000], # 62.2h 32.5G valx4 env1  minGemma-hidden_layers36-att_heads4-kv_heads2-hidden528-intermediate2112-head_dim288-T1024--2026-03-23-11-47.pth
# valx8: 2.4227 +- 0.0026 # torch.Tensor([2.4218, 2.4229, 2.4259, 2.4188, 2.4228, 2.4194, 2.4251, 2.4250]).std()
[ 36, 4, 2, 528, 2112, 256, 205.6, 2.6643, 2.4313, 180000], # 55.2h       valx4 env1
[ 36, 4, 2, 528, 2112, 192, 191.0, 2.7496, 2.4370, 180000], # 48.5h 32.3G valx1 env1
[ 36, 4, 2, 480, 1920, 320, 190.2, 2.7384, 2.4506, 180000], # 62.1h 31.5G valx4 env1
[ 36, 4, 2, 480, 1920, 288, 183.6, 2.7409, 2.4571, 180000], # 59.1h 31.6G valx4 env1


# local best for H3(3): 2.4236(valx1)
[ 36, 3, 3, 720, 2880, 192, 320.1, 2.8427, 2.4311, 180000], # 51.9h       valx1 env1

[ 36, 3, 3, 672, 2688, 192, 284.9, 2.8572, 2.4340, 180000], # 49.5h 38.9G valx1 env1

[ 36, 3, 3, 624, 2496, 192, 251.6, 2.6975, 2.4299, 180000], # 47.0h 35.0G valx1 env1
[ 36, 3, 3, 624, 2496, 160, 242.9, 2.7825, 2.4318, 180000], # 44.4h       valx1 env1

[ 36, 3, 3, 576, 2304, 224, 228.2, 2.7888, 2.4358, 180000], # 47.6h       valx1 env1
[ 36, 3, 3, 576, 2304, 192, 220.3, 2.6527,+2.4236, 180000], # 44.9h 32.5G valx1 env1 ### bad in valx4
[ 36, 3, 3, 576, 2304, 192, 220.3, 2.8369, 2.4393, 180000], # 45.0h again valx4 env1
[ 36, 3, 3, 576, 2304, 160, 212.3, 2.7325, 2.4303, 180000], # 42.3h 31.8G valx1 env1

[ 36, 3, 3, 528, 2112, 224, 198.3, 2.6810, 2.4277, 180000], # 46.0h 34.5G valx1 env1
[ 36, 3, 3, 528, 2112, 192, 191.0, 2.7240, 2.4375, 180000], # 43.4h 31.2G valx1 env1


# local best for H3(1): 2.4211(valx1), 2.4230(valx8)
[ 36, 3, 1, 768, 3072, 192, 336.2, 2.7997, 2.4330, 180000], # 51.5h 39.7G valx1 env1  # 768 256 57.4h 39.6G //2 (//4 7%-slower)

[ 36, 3, 1, 720, 2880, 192, 300.2, 2.7481, 2.4264, 180000], # 50.2h 38.7G valx1 env1

[ 36, 3, 1, 672, 2688, 192, 266.3, 2.7216,+2.4250, 180000], # 47.7h 37.3G valx1 env1 ### bad in valx4
[ 36, 3, 1, 672, 2688, 192, 266.3, 2.6527, 2.4257, 180000], # 47.8h again valx4 env1

[ 36, 3, 1, 624, 2496, 192, 234.3, 2.7157, 2.4288, 180000], # 45.1h       valx1 env1
[ 36, 3, 1, 624, 2496, 160, 228.6, 2.6797,+2.4236, 180000], # 43.0h 32.8G valx1 env1 ### bad in valx4
[ 36, 3, 1, 624, 2496, 160, 228.6, 2.7253, 2.4307, 180000], # 43.1h again valx4 env1

[ 36, 3, 1, 576, 2304, 224, 209.7, 2.7287, 2.4334, 180000], # 45.9h 32.2G valx1 env1
[+36, 3, 1, 576, 2304, 192, 204.4, 2.6341,+2.4211, 180000], # 43.0h       valx1 env1  minGemma-hidden_layers36-att_heads3-kv_heads1-hidden576-intermediate2304-head_dim192-T1024--2025-11-24-06-44.pth
# valx8: 2.4230 +- 0.0022 # torch.Tensor([2.4254, 2.4210, 2.4255, 2.4213, 2.4197, 2.4223, 2.4247, 2.4240]).std()
[ 36, 3, 1, 576, 2304, 160, 199.0, 2.6091, 2.4264, 180000], # 41.0h 31.3G valx1 env1

[ 36, 3, 1, 528, 2112, 224, 181.2, 2.6944, 2.4295, 180000], # 44.2h 31.0G valx1 env1
[ 36, 3, 1, 528, 2112, 192, 176.4, 2.6398,+2.4247, 180000], # 41.5h       valx1 env1 ### bad in valx4
[ 36, 3, 1, 528, 2112, 192, 176.4, 2.6518, 2.4306, 180000], # 41.6h again valx4 env1

[ 36, 3, 1, 480, 1920, 192, 150.4, 2.6080, 2.4279, 180000], # 38.6h       valx1 env1

In [18]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  36 # 8 # G28 G18 #blocks
num_attention_heads = 4 # 4 # G16 G8
num_key_value_heads = 2 # 4 # G16 G1
hidden_size = num_attention_heads*156 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 256 # 32 # G256 # dim in attention # Doesn't affect time
rms_norm_eps = 1e-4 # 1e-6
rope_theta = 4000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)
        
class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_100M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=28//2; N_step=90000*2; print(T * B * N_step / 1000000) # 0.25? B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')
torch.cuda.empty_cache();

# Normal Model with Hand-eval   # 100M-T512: lr10e-4 WD1/4
training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=16e-4, weight_decay=0.5, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
result = trainer.train(); tloss=result[2]["train_loss"]
loss = []; model.eval(); B2=12//1; torch.cuda.empty_cache();
for k in range(5300 *1):
    val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
    loss += [model(common.to('cuda', non_blocking=True))[0].item()]
if torch.Tensor(loss).mean() < 2.4235:
    torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
model.train(); del common; print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {tloss:.4f}, {torch.Tensor(loss).mean():.4f}, {N_step}],')

2580.48
L36 att4 kv_heads2 hidden624 intermediate2496 head_dim256 T1024

[ 36, 4, 2, 624, 2496, 256, 268.8, 2.6873, 2.4195, 180000],

In [12]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  36 # 8 # G28 G18 #blocks
num_attention_heads = 4 # 4 # G16 G8
num_key_value_heads = 2 # 4 # G16 G1
hidden_size = num_attention_heads*156 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 224 # 32 # G256 # dim in attention # Doesn't affect time
rms_norm_eps = 1e-4 # 1e-6
rope_theta = 4000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)
        
class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_100M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=28//2; N_step=90000*2; print(T * B * N_step / 1000000) # 0.25? B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')
torch.cuda.empty_cache();

# Normal Model with Hand-eval   # 100M-T512: lr10e-4 WD1/4
training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=16e-4, weight_decay=0.5, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
result = trainer.train(); tloss=result[2]["train_loss"]
loss = []; model.eval(); B2=12//1; torch.cuda.empty_cache();
for k in range(5300 *4):
    val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
    loss += [model(common.to('cuda', non_blocking=True))[0].item()]
if torch.Tensor(loss).mean() < 2.4235:
    torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
model.train(); del common; print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {tloss:.4f}, {torch.Tensor(loss).mean():.4f}, {N_step}],')

2580.48
L36 att4 kv_heads2 hidden624 intermediate2496 head_dim224 T1024

[ 36, 4, 2, 624, 2496, 224, 260.2, 2.6524, 2.4213, 180000],

In [3]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  36 # 8 # G28 G18 #blocks
num_attention_heads = 4 # 4 # G16 G8
num_key_value_heads = 2 # 4 # G16 G1
hidden_size = num_attention_heads*144 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 288 # 32 # G256 # dim in attention # Doesn't affect time
rms_norm_eps = 1e-4 # 1e-6
rope_theta = 4000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)
        
class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_100M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=28//2; N_step=90000*2; print(T * B * N_step / 1000000) # 0.25? B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')
torch.cuda.empty_cache();

# Normal Model with Hand-eval   # 100M-T512: lr10e-4 WD1/4
training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=16e-4, weight_decay=0.5, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
result = trainer.train(); tloss=result[2]["train_loss"]
loss = []; model.eval(); B2=12//1; torch.cuda.empty_cache();
for k in range(5300 *4):
    val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
    loss += [model(common.to('cuda', non_blocking=True))[0].item()]
if torch.Tensor(loss).mean() < 2.4235:
    torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
model.train(); del common; print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {tloss:.4f}, {torch.Tensor(loss).mean():.4f}, {N_step}],')

2580.48
L36 att4 kv_heads2 hidden576 intermediate2304 head_dim288 T1024

[ 36, 4, 2, 576, 2304, 288, 244.2, 2.6341, 2.4226, 180000],

In [14]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  36 # 8 # G28 G18 #blocks
num_attention_heads = 4 # 4 # G16 G8
num_key_value_heads = 2 # 4 # G16 G1
hidden_size = num_attention_heads*132 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 288 # 32 # G256 # dim in attention # Doesn't affect time
rms_norm_eps = 1e-4 # 1e-6
rope_theta = 4000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)
        
class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_100M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=28//2; N_step=90000*2; print(T * B * N_step / 1000000) # 0.25? B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')
torch.cuda.empty_cache();

# Normal Model with Hand-eval   # 100M-T512: lr10e-4 WD1/4
training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=16e-4, weight_decay=0.5, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
result = trainer.train(); tloss=result[2]["train_loss"]
loss = []; model.eval(); B2=12//1; torch.cuda.empty_cache();
for k in range(5300 *4):
    val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
    loss += [model(common.to('cuda', non_blocking=True))[0].item()]
if torch.Tensor(loss).mean() < 2.4235:
    torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
model.train(); del common; print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {tloss:.4f}, {torch.Tensor(loss).mean():.4f}, {N_step}],')

2580.48
L36 att4 kv_heads2 hidden528 intermediate2112 head_dim288 T1024

[ 36, 4, 2, 528, 2112, 288, 212.9, 2.6403, 2.4220, 180000],

In [12]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  36 # 8 # G28 G18 #blocks
num_attention_heads = 3 # 4 # G16 G8
num_key_value_heads = 1 # 4 # G16 G1
hidden_size = num_attention_heads*192 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 192 # 32 # G256 # dim in attention # Doesn't affect time
rms_norm_eps = 1e-4 # 1e-6
rope_theta = 4000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)
        
class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_100M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=28//2; N_step=90000*2; print(T * B * N_step / 1000000) # 0.25? B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')
torch.cuda.empty_cache();

# Normal Model with Hand-eval   # 100M-T512: lr10e-4 WD1/4
training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=16e-4, weight_decay=0.5, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
result = trainer.train(); tloss=result[2]["train_loss"]
loss = []; model.eval(); B2=12//1; torch.cuda.empty_cache();
for k in range(5300*1 *4):
    val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
    loss += [model(common.to('cuda', non_blocking=True))[0].item()]
if torch.Tensor(loss).mean() < 2.4235:
    torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
model.train(); del common; print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {tloss:.4f}, {torch.Tensor(loss).mean():.4f}, {N_step}],')

2580.48
L36 att3 kv_heads1 hidden576 intermediate2304 head_dim192 T1024

[ 36, 3, 1, 576, 2304, 192, 204.4, 2.6341, 2.4211, 180000],

# L30

In [ ]:
# L30 Normal Models T1024 Baby100M (default: B28//4 N90000 x4 lr16e-4 WD0.5)  # H6(3): 2.4170, H5(1): 2.4215, H4(2): 2.4207

# local best for H6(3): 2.4177(valx4), 2.4170(valx8)
[ 30, 6, 3, 744, 2976, 192, 314.0, 2.6181, 2.4260, 180000], # 60.2h 36.7G valx4 env1

[ 30, 6, 3, 696, 2784, 224, 293.8, 2.8172, 2.4267, 180000], # 63.4h 37.5G valx4 env1
[ 30, 6, 3, 696, 2784, 192, 281.8, 2.6854, 2.4250, 180000], # 58.4h 35.9G valx4 env1
[ 30, 6, 3, 696, 2784, 176, 275.7, 2.6700,+2.4197, 180000], # 57.0h 35.4G valx4 env1  minGemma-hidden_layers30-att_heads6-kv_heads3-hidden696-intermediate2784-head_dim176-T1024--2026-05-08-20-53.pth
# valx8: 2.4192 +- 0.0019 # torch.Tensor([2.4182, 2.4178, 2.4185, 2.4188, 2.4193, 2.4206, 2.4232, 2.4173]).std()
[ 30, 6, 3, 696, 2784, 160, 269.7, 2.6196,+2.4223, 180000], # 54.9h 36.1G valx4 env1  minGemma-hidden_layers30-att_heads6-kv_heads3-hidden696-intermediate2784-head_dim160-T1024--2026-06-01-21-21.pth
# valx8: 2.4238 +- 0.0031 # torch.Tensor([2.4266, 2.4232, 2.4179, 2.4237, 2.4223, 2.4285, 2.4234, 2.4248]).std()

[ 30, 6, 3, 648, 2592, 288, 284.7, 2.8144, 2.4370, 180000], # 74.0h 38.1G valx4 env1
[ 30, 6, 3, 648, 2592, 256, 273.5, 2.6374,+2.4201, 180000], # 65.3h 36.4G valx4 env1  minGemma-hidden_layers30-att_heads6-kv_heads3-hidden648-intermediate2592-head_dim256-T1024--2026-05-19-08-23.pth
# valx8: 2.4200 +- 0.0032 # torch.Tensor([2.4250, 2.4162, 2.4183, 2.4186, 2.4220, 2.4214, 2.4225, 2.4162]).std()
[ 30, 6, 3, 648, 2592, 224, 262.3, 2.6095,+2.4219, 180000], # 61.7h 34.9G valx4 env1  minGemma-hidden_layers30-att_heads6-kv_heads3-hidden648-intermediate2592-head_dim224-T1024--2026-05-01-12-40.pth
# valx8: 2.4215 +- 0.0024 # torch.Tensor([2.4220, 2.4240, 2.4200, 2.4195, 2.4237, 2.4242, 2.4208, 2.4177]).std()
[+30, 6, 3, 648, 2592, 192, 251.1, 2.6060,+2.4177, 180000], # 57.1h 34.9G valx4 env1  minGemma-hidden_layers30-att_heads6-kv_heads3-hidden648-intermediate2592-head_dim192-T1024--2026-04-23-19-31.pth
# valx8: 2.4170 +- 0.0043 # torch.Tensor([2.4254, 2.4177, 2.4138, 2.4190, 2.4136, 2.4136, 2.4133, 2.4199]).std()
[ 30, 6, 3, 648, 2592, 176, 245.5, 2.5975,+2.4183, 180000], # 55.6h 31.5G valx4 env1  minGemma-hidden_layers30-att_heads6-kv_heads3-hidden648-intermediate2592-head_dim176-T1024--2026-05-03-21-45.pth
# valx8: 2.4197 +- 0.0044 # torch.Tensor([2.4260, 2.4200, 2.4210, 2.4162, 2.4253, 2.4193, 2.4155, 2.4140]).std()
[ 30, 6, 3, 648, 2592, 160, 239.9, 2.5861, 2.4236, 180000], # 53.4h 31.1G valx4 env1

[ 30, 6, 3, 600, 2400, 288, 253.3, 2.6262,+2.4222, 180000], # 71.5h 37.5G valx4 env1  minGemma-hidden_layers30-att_heads6-kv_heads3-hidden600-intermediate2400-head_dim288-T1024--2026-05-28-06-13.pth
# valx8: 2.4238 +- 0.0026 # torch.Tensor([2.4240, 2.4196, 2.4216, 2.4275, 2.4250, 2.4227, 2.4267, 2.4236]).std()
[ 30, 6, 3, 600, 2400, 256, 242.9, 2.6148,+2.4186, 180000], # 62.9h 34.7G valx4 env1  minGemma-hidden_layers30-att_heads6-kv_heads3-hidden600-intermediate2400-head_dim256-T1024--2026-05-16-13-26.pth
# valx8: 2.4191 +- 0.0033 # torch.Tensor([2.4166, 2.4186, 2.4203, 2.4236, 2.4177, 2.4188, 2.4232, 2.4138]).std()
[ 30, 6, 3, 600, 2400, 224, 232.5, 2.6766, 2.4379, 180000], # 59.1h       valx4 env1
[ 30, 6, 3, 600, 2400, 192, 222.2, 2.7765, 2.4405, 180000], # 54.5h 31.1G valx4 env1

[ 30, 6, 3, 552, 2208, 192, 194.8, 2.6004, 2.4259, 180000], # 52.8h 29.1G valx4 env1

[ 30, 6, 3, 504, 2016, 192, 169.2, 2.6622, 2.4400, 180000], # 50.1h 28.0G valx4 env1


# local best for H5(1): 2.4209(valx4), 2.4215(valx8)
[ 30, 5, 1, 720, 2880, 192, 272.8, 2.8556, 2.4391, 360000], # 37.2h       valx4 env1

[ 30, 5, 1, 680, 2720, 192, 247.9, 2.6861, 2.4244, 360000], # 36.5h       valx4 env1

[ 30, 5, 1, 640, 2560, 192, 224.1, 2.6013, 2.4238, 360000], # 35.1h       valx4 env1

[ 30, 5, 1, 600, 2400, 224, 208.3, 2.6911, 2.4291, 360000], # 37.3h       valx4 env1
[ 30, 5, 1, 600, 2400, 192, 201.4, 2.6227, 2.4271, 360000], # 34.7h       valx4 env1
[ 30, 5, 1, 600, 2400, 160, 194.5, 2.6957, 2.4326, 360000], # 32.5h       valx4 env1

[ 30, 5, 1, 560, 2240, 256, 192.8, 2.6685, 2.4305, 360000], # 38.0h 17.8G valx4 env1
[+30, 5, 1, 560, 2240, 224, 186.4, 2.6021,+2.4209, 360000], # 35.8h       valx4 env1  minGemma-hidden_layers30-att_heads5-kv_heads1-hidden560-intermediate2240-head_dim224-T1024--2026-04-01-21-19.pth
# valx8: 2.4215 +- 0.0047 # torch.Tensor([2.4132, 2.4214, 2.4218, 2.4162, 2.4251, 2.4242, 2.4230, 2.4274]).std()
[ 30, 5, 1, 560, 2240, 192, 179.9, 2.6189, 2.4234, 360000], # 33.3h       valx4 env1  minGemma-hidden_layers30-att_heads5-kv_heads1-hidden560-intermediate2240-head_dim192-T1024--2026-03-25-06-07.pth
# valx8: 2.4248 +- 0.0043 # torch.Tensor([2.4159, 2.4242, 2.4289, 2.4286, 2.4276, 2.4219, 2.4241, 2.4269]).std()
[ 30, 5, 1, 560, 2240, 160, 173.5, 2.6759, 2.4286, 360000], # 31.0h 17.0G valx4 env1

[ 30, 5, 1, 520, 2080, 256, 171.6, 2.6882, 2.4407, 360000], # 37.9h       valx4 env1
[ 30, 5, 1, 520, 2080, 224, 165.6, 2.6218, 2.4273, 360000], # 35.6h 17.0G valx4 env1
[ 30, 5, 1, 520, 2080, 192, 159.6, 2.6528, 2.4360, 360000], # 33.0h       valx4 env1


# local best for H4(2): 2.4188(valx1), 2.4207(valx8)
[ 30, 4, 2, 784, 3136, 256, 333.2, 2.8746, 2.4330, 360000], # 40.0h 22.0G valx1 env1

[ 30, 4, 2, 720, 2880, 224, 281.1, 2.7762, 2.4271, 360000], # 35.2h 20.6G valx1 env1

[ 30, 4, 2, 680, 2720, 192, 247.9, 2.8001, 2.4372, 360000], # 32.2h 19.9G valx1 env1

[ 30, 4, 2, 640, 2560, 256, 238.8, 2.8074, 2.4369, 360000], # 34.8h       valx1 env1
[ 30, 4, 2, 640, 2560, 224, 231.4, 2.7140, 2.4241, 360000], # 33.1h       valx1 env1 ### bad in valx4
[ 30, 4, 2, 640, 2560, 224, 231.4, 2.7327, 2.4310, 360000], # 33.8h 18.4G valx4 env1 ### bad in valx4
[ 30, 4, 2, 640, 2560, 192, 224.1, 2.6786, 2.4218, 360000], # 30.9h       valx1 env1 ### bad in valx4
[ 30, 4, 2, 640, 2560, 192, 224.1, 2.7169, 2.4269, 360000], # 31.6h       valx4 env1 ### bad in valx4
[ 30, 4, 2, 640, 2560, 160, 216.7, 2.6926, 2.4237, 360000], # 29.2h       valx1 env1 ### bad in valx4
[ 30, 4, 2, 640, 2560, 160, 216.7, 2.7466, 2.4367, 360000], # 29.8h 17.8G valx4 env1 ### bad in valx4

[ 30, 4, 2, 600, 2400, 224, 208.3, 2.6894, 2.4238, 360000], # 32.6h       valx1 env1 ### bad in valx4
[ 30, 4, 2, 600, 2400, 224, 208.3, 2.6198, 2.4237, 360000], # 33.4h       valx4 env1 ### bad in valx4
[ 30, 4, 2, 600, 2400, 192, 201.4, 2.6266, 2.4234,  400000],#             valx1 env1  # N-search not so promissing...
[ 30, 4, 2, 600, 2400, 192, 201.4, 2.6611,+2.4188,  380000],#             valx1 env1 ?minGemma-hidden_layers30-att_heads4-kv_heads2-hidden600-intermediate2400-head_dim192-T1024--2025-11-26-08-38.pth
# valx8: 2.4228 +- 0.0021 # torch.Tensor([2.4186, 2.4223, 2.4241, 2.4217, 2.4255, 2.4230, 2.4225, 2.4246]).std()
[+30, 4, 2, 600, 2400, 192, 201.4, 2.6814,+2.4199, 360000], # 30.4h 17.8G valx1 env1  minGemma-hidden_layers30-att_heads4-kv_heads2-hidden600-intermediate2400-head_dim192-T1024--2025-11-11-14-00.pth
# valx8: 2.4207 +- 0.0041 # torch.Tensor([2.4227, 2.4205, 2.4154, 2.4264, 2.4150, 2.4254, 2.4198, 2.4204]).std()
[ 30, 4, 2, 600, 2400, 192, 201.4, 2.7364, 2.4311,  340000],#       17.4G valx1 env1
[ 30, 4, 2, 600, 2400, 160, 194.5, 2.7789, 2.4413, 360000], # 28.7h 16.8G valx1 env1

[ 30, 4, 2, 560, 2240, 224, 186.4, 2.6700, 2.4238, 360000], # 30.9h 17.2G valx1 env1 ### bad in valx4
[ 30, 4, 2, 560, 2240, 224, 186.4, 2.6257, 2.4237, 360000], # 31.9h 17.2G valx4 env1 ### bad in valx4
[ 30, 4, 2, 560, 2240, 192, 179.9, 2.6446, 2.4255, 360000], # 29.1h 16.9G valx1 env1 ### bad in valx4
[ 30, 4, 2, 560, 2240, 192, 179.9, 2.5901, 2.4248, 360000], # 29.7h 17.3G valx4 env1 ### bad in valx4

[ 30, 4, 2, 480, 1920, 128, 129.3, 2.5866, 2.4322, 360000], # 16.8h 15.0G valx1 env1

In [4]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  30 # 8 # G28 G18 #blocks
num_attention_heads = 6 # 4 # G16 G8
num_key_value_heads = 3 # 4 # G16 G1
hidden_size = num_attention_heads*108 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 192 # 32 # G256 # dim in attention # Doesn't affect time
rms_norm_eps = 1e-4 # 1e-6
rope_theta = 4000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)
        
class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_100M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=28//2; N_step=90000*2; print(T * B * N_step / 1000000) # 0.25? B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')
torch.cuda.empty_cache();

# Normal Model with Hand-eval   # 100M-T512: lr10e-4 WD1/4
training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=16e-4, weight_decay=0.5, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
result = trainer.train(); tloss=result[2]["train_loss"]
loss = []; model.eval(); B2=12//2; torch.cuda.empty_cache();
for k in range(5300*2 *4):
    val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
    loss += [model(common.to('cuda', non_blocking=True))[0].item()]
if torch.Tensor(loss).mean() < 2.4235:
    torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
model.train(); del common; print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {tloss:.4f}, {torch.Tensor(loss).mean():.4f}, {N_step}],')

2580.48
L30 att6 kv_heads3 hidden648 intermediate2592 head_dim192 T1024

[ 30, 6, 3, 648, 2592, 192, 251.1, 2.6060, 2.4177, 180000],

In [8]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  30 # 8 # G28 G18 #blocks
num_attention_heads = 6 # 4 # G16 G8
num_key_value_heads = 3 # 4 # G16 G1
hidden_size = num_attention_heads*108 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 176 # 32 # G256 # dim in attention # Doesn't affect time
rms_norm_eps = 1e-4 # 1e-6
rope_theta = 4000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)
        
class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_100M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=28//2; N_step=90000*2; print(T * B * N_step / 1000000) # 0.25? B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')
torch.cuda.empty_cache();

# Normal Model with Hand-eval   # 100M-T512: lr10e-4 WD1/4
training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=16e-4, weight_decay=0.5, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
result = trainer.train(); tloss=result[2]["train_loss"]
loss = []; model.eval(); B2=12//2; torch.cuda.empty_cache();
for k in range(5300*2 *4):
    val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
    loss += [model(common.to('cuda', non_blocking=True))[0].item()]
if torch.Tensor(loss).mean() < 2.4235:
    torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
model.train(); del common; print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {tloss:.4f}, {torch.Tensor(loss).mean():.4f}, {N_step}],')

2580.48
L30 att6 kv_heads3 hidden648 intermediate2592 head_dim176 T1024

[ 30, 6, 3, 648, 2592, 176, 245.5, 2.5975, 2.4183, 180000],

In [13]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  30 # 8 # G28 G18 #blocks
num_attention_heads = 6 # 4 # G16 G8
num_key_value_heads = 3 # 4 # G16 G1
hidden_size = num_attention_heads*100 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 256 # 32 # G256 # dim in attention # Doesn't affect time
rms_norm_eps = 1e-4 # 1e-6
rope_theta = 4000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)
        
class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_100M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=28//2; N_step=90000*2; print(T * B * N_step / 1000000) # 0.25? B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')
torch.cuda.empty_cache();

# Normal Model with Hand-eval   # 100M-T512: lr10e-4 WD1/4
training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=16e-4, weight_decay=0.5, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
result = trainer.train(); tloss=result[2]["train_loss"]
loss = []; model.eval(); B2=12//2; torch.cuda.empty_cache();
for k in range(5300*2 *4):
    val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
    loss += [model(common.to('cuda', non_blocking=True))[0].item()]
if torch.Tensor(loss).mean() < 2.4235:
    torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
model.train(); del common; print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {tloss:.4f}, {torch.Tensor(loss).mean():.4f}, {N_step}],')

2580.48
L30 att6 kv_heads3 hidden600 intermediate2400 head_dim256 T1024

[ 30, 6, 3, 600, 2400, 256, 242.9, 2.6148, 2.4186, 180000],

In [28]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  30 # 8 # G28 G18 #blocks
num_attention_heads = 5 # 4 # G16 G8
num_key_value_heads = 1 # 4 # G16 G1
hidden_size = num_attention_heads*112 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 224 # 32 # G256 # dim in attention # Doesn't affect time
rms_norm_eps = 1e-4 # 1e-6
rope_theta = 4000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)
        
class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_100M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=28//4; N_step=90000*4; print(T * B * N_step / 1000000) # 0.25? B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')
torch.cuda.empty_cache();

# Normal Model with Hand-eval   # 100M-T512: lr10e-4 WD1/4
training_args = TrainingArguments(gradient_accumulation_steps=4, learning_rate=16e-4, weight_decay=0.5, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
result = trainer.train(); tloss=result[2]["train_loss"]
loss = []; model.eval(); B2=12//2; torch.cuda.empty_cache();
for k in range(5300*2 *4):
    val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
    loss += [model(common.to('cuda', non_blocking=True))[0].item()]
if torch.Tensor(loss).mean() < 2.4235:
    torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
model.train(); del common; print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {tloss:.4f}, {torch.Tensor(loss).mean():.4f}, {N_step}],')

2580.48
L30 att5 kv_heads1 hidden560 intermediate2240 head_dim224 T1024

[ 30, 5, 1, 560, 2240, 224, 186.4, 2.6021, 2.4209, 360000],

In [7]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  30 # 8 # G28 G18 #blocks
num_attention_heads = 4 # 4 # G16 G8
num_key_value_heads = 2 # 4 # G16 G1
hidden_size = num_attention_heads*150 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 192 # 32 # G256 # dim in attention # Doesn't affect time
rms_norm_eps = 1e-4 # 1e-6
rope_theta = 4000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)
        
class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_100M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=28//4; N_step=95000*4; print(T * B * N_step / 1000000) # 0.25? B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')
torch.cuda.empty_cache();

# Normal Model with Hand-eval   # 100M-T512: lr10e-4 WD1/4
training_args = TrainingArguments(gradient_accumulation_steps=4, learning_rate=16e-4, weight_decay=0.5, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
result = trainer.train(); tloss=result[2]["train_loss"]
loss = []; model.eval(); B2=12//2; torch.cuda.empty_cache();
for k in range(5300 *2):
    val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
    loss += [model(common.to('cuda', non_blocking=True))[0].item()]
if torch.Tensor(loss).mean() < 2.4188:
    torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
model.train(); del common; print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {tloss:.4f}, {torch.Tensor(loss).mean():.4f}, {N_step}],')

2723.84
L30 att4 kv_heads2 hidden600 intermediate2400 head_dim192 T1024

[ 30, 4, 2, 600, 2400, 192, 201.4, 2.6611, 2.4188, 380000],

In [19]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  30 # 8 # G28 G18 #blocks
num_attention_heads = 4 # 4 # G16 G8
num_key_value_heads = 2 # 4 # G16 G1
hidden_size = num_attention_heads*150 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 192 # 32 # G256 # dim in attention # Doesn't affect time
rms_norm_eps = 1e-4 # 1e-6
rope_theta = 4000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)
        
class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_100M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=28//4; N_step=90000*4; print(T * B * N_step / 1000000) # 0.25? B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')
torch.cuda.empty_cache();

# Normal Model with Hand-eval   # 100M-T512: lr10e-4 WD1/4
training_args = TrainingArguments(gradient_accumulation_steps=4, learning_rate=16e-4, weight_decay=0.5, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
result = trainer.train(); tloss=result[2]["train_loss"]
loss = []; model.eval(); B2=12//2; torch.cuda.empty_cache();
for k in range(5300*2 *4):
    val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
    loss += [model(common.to('cuda', non_blocking=True))[0].item()]
if torch.Tensor(loss).mean() < 2.4235:
    torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
model.train(); del common; print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {tloss:.4f}, {torch.Tensor(loss).mean():.4f}, {N_step}],')

2580.48
L30 att4 kv_heads2 hidden600 intermediate2400 head_dim192 T1024

[ 30, 4, 2, 600, 2400, 192, 201.4, 2.6814, 2.4199, 360000],

# L24

In [ ]:
# L24 Normal Model T1024 Baby100M (default: x4 B28//4 lr16e-4 WD0.5 N90000)  # H6(3): 2.4339, H5(1): 2.4368

# local best for H6(3): 2.4330(valx1), 2.4339(valx8) (No need to consider valx4 as all bad)  # default: valx1 env1
[ 24, 6, 3, 744, 2976, 192, 258.7, 2.7400, 2.4474, 360000], # 55.4h 18.8G

[ 24, 6, 3, 696, 2784, 192, 232.4, 2.6939, 2.4454, 360000], # 53.7h

[ 24, 6, 3, 648, 2592, 224, 216.4, 2.5769, 2.4342, 360000], # 56.9h 16.9G
[ 24, 6, 3, 648, 2592, 192, 207.4, 2.6089, 2.4372, 360000], # 52.5h

[ 24, 6, 3, 600, 2400, 256, 200.3, 2.5660, 2.4351, 360000], # 55.1h 16.4G
[+24, 6, 3, 600, 2400, 224, 192.1, 2.5905, 2.4330, 360000], # 52.8h       minGemma-hidden_layers24-att_heads6-kv_heads3-hidden600-intermediate2400-head_dim224-T1024--2025-12-28-10-16.pth
# valx8: 2.4339 +- 0.0041 # torch.Tensor([2.4312, 2.4313, 2.4355, 2.4282, 2.4381, 2.4306, 2.4397, 2.4365]).std()
[ 24, 6, 3, 600, 2400, 192, 183.8, 2.6347, 2.4335, 360000], # 48.8h 16.2G

#[24, 6, 3, 552, 2208, 256, 176.7, 2.5871, 2.4397, 360000], # 43.3h 15.9G valx4 env2 # +-0.0037:[2.4377, 2.4452, 2.4373, 2.4386]  # WD0.5 kept wrongly
#[24, 6, 3, 552, 2208, 224, 169.1, 2.5892, 2.4388, 360000], # 41.6h       valx4 env2 # +-0.0037:[2.4367, 2.4442, 2.4362, 2.4380]  # WD0.5 kept wrongly
[ 24, 6, 3, 552, 2208, 192, 161.4, 2.6021, 2.4344, 360000], # 46.6h 15.2G


# local best for H5(1): 2.4341(valx1), 2.4368(valx8) (No need to consider valx4 as all bad)  # default: valx1 env1
#[24, 5, 1, 780, 3120, 288, 279.3, 2.7830, 2.4645, 360000], # 54.2h       valx4 env2 # +-0.0037:[2.4623, 2.4700, 2.4620, 2.4636]
[ 24, 5, 1, 780, 3120, 256, 272.1, 2.7824, 2.4349, 360000], # 36.2h 19.7G
#[24, 5, 1, 780, 3120, 224, 264.9, 2.7282, 2.4581, 360000], # 48.6h 19.2G valx4 env2 # +-0.0039:[2.4556, 2.4638, 2.4557, 2.4572]
[ 24, 5, 1, 780, 3120, 192, 257.8, 2.6485, 2.4431, 360000], # 53.4h
[ 24, 5, 1, 780, 3120, 160, 250.6, 2.6180, 2.4362, 360000], # 51.2h 18.6G
#[24, 5, 1, 780, 3120, 128, 243.4, 2.6880, 2.4531, 360000], # 39.4h       valx4 env2 # +-0.0037:[2.4511, 2.4586, 2.4505, 2.4523]

[ 24, 5, 1, 720, 2880, 224, 232.1, 2.6595, 2.4406, 360000], # 51.7h 17.0G
[ 24, 5, 1, 720, 2880, 192, 225.5, 2.6139, 2.4346, 360000], # 49.6h 17.3G
#[24, 5, 1, 720, 2880, 192, 225.5, 2.7554, 2.4410, 360000], # 42.4h again valx4 env2 WD2/3    # Reproducible although slightly worse
[ 24, 5, 1, 720, 2880, 160, 218.9, 2.6660, 2.4404, 360000], # 46.2h 16.5G

[ 24, 5, 1, 680, 2720, 224, 211.4, 2.6091, 2.4359, 360000], # 51.1h 16.9G
[ 24, 5, 1, 680, 2720, 192, 205.1, 2.6051, 2.4391, 360000], # 48.2h
[ 24, 5, 1, 680, 2720, 160, 198.9, 2.7214, 2.4523, 360000], # 45.4h 16.6G

[ 24, 5, 1, 640, 2560, 256, 197.5, 2.5740, 2.4355, 360000], # 49.2h 16.8G
[+24, 5, 1, 640, 2560, 224, 191.6, 2.6000,+2.4341, 360000], # 47.1h 16.4G
#[24, 5, 1, 640, 2560, 224, 191.6, 2.6147, 2.4417, 360000], # 39.3h 16.2G valx4 env2
#[24, 5, 1, 640, 2560, 224, 191.6, 2.6954, 2.4354, 360000], # 39.4h again valx4 env2 WD2/3    # Reproducible!!! Best
#[24, 5, 1, 640, 2560, 224, 191.6, 2.8687, 2.4621, 360000], # 39.3h again valx4 env2 WD1(x2)
[+24, 5, 1, 640, 2560, 192, 185.7, 2.5938,+2.4341, 360000], # 44.1h 16.3G  minGemma-hidden_layers24-att_heads5-kv_heads1-hidden640-intermediate2560-head_dim192-T1024--2025-11-28-17-30.pth
# valx8: 2.4368 +- 0.0032 # torch.Tensor([2.4372, 2.4386, 2.4406, 2.4318, 2.4329, 2.4359, 2.4367, 2.4404]).std()
[ 24, 5, 1, 640, 2560, 160, 179.8, 2.5991, 2.4381, 360000], # 41.5h 15.9G

[ 24, 5, 1, 600, 2400, 256, 178.2, 2.5980, 2.4387, 360000], # 47.8h 16.1G
[ 24, 5, 1, 600, 2400, 224, 172.7, 2.6072, 2.4357, 360000], # 46.1h 15.8G
[ 24, 5, 1, 600, 2400, 192, 167.2, 2.5813, 2.4342, 360000], # 43.3h
[ 24, 5, 1, 600, 2400, 160, 161.6, 2.5846, 2.4354, 360000], # 40.6h 15.3G

[ 24, 5, 1, 560, 2240, 224, 154.7, 2.5873, 2.4388, 360000], # 44.7h 15.5G
[ 24, 5, 1, 560, 2240, 192, 149.6, 2.5783, 2.4394, 360000], # 41.7h

[ 24, 5, 1, 520, 2080, 192, 132.9, 2.5741, 2.4361, 360000], # 40.8h

[ 24, 5, 1, 480, 1920, 192, 117.1, 2.5831, 2.4419, 360000], # 37.8h

In [12]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  24 # 8 # G28 G18 #blocks
num_attention_heads = 5 # 4 # G16 G8
num_key_value_heads = 1 # 4 # G16 G1
hidden_size = num_attention_heads*128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 192 # 32 # G256 # dim in attention # Doesn't affect time
rms_norm_eps = 1e-4 # 1e-6
rope_theta = 4000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)
        
class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_100M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=28//4; N_step=90000*4; print(T * B * N_step / 1000000) # 0.25? B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')
torch.cuda.empty_cache();

# Normal Model with Hand-eval   # 100M-T512: lr10e-4 WD1/4
training_args = TrainingArguments(gradient_accumulation_steps=4, learning_rate=16e-4, weight_decay=0.5, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
result = trainer.train(); tloss=result[2]["train_loss"]
loss = []; model.eval(); B2=12//2; torch.cuda.empty_cache();
for k in range(5300 *2):
    val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
    loss += [model(common.to('cuda', non_blocking=True))[0].item()]
if torch.Tensor(loss).mean() < 2.4341:
    torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
model.train(); del common; print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {tloss:.4f}, {torch.Tensor(loss).mean():.4f}, {N_step}],')

2580.48
L24 att5 kv_heads1 hidden640 intermediate2560 head_dim192 T1024

[ 24, 5, 1, 640, 2560, 192, 185.7, 2.5938, 2.4341, 360000],

# L20

In [ ]:
# L20 Normal Models T1024 Baby100M (default: B28//4 N90000 x4 lr16e-4 WD0.5)  # H8(2): 2.4195, H7(1): 2.4242, H6(3): 2.4262, H5(1): 2.4289(valx1)

# local best for H8(2): 2.4208(valx4), 2.4195(valx8)
[ 20, 8, 2, 736, 2944, 224, 233.1, 2.7490, 2.4272, 360000], # 57.6h       valx4 env1
[ 20, 8, 2, 736, 2944, 192, 223.7, 2.7597, 2.4317, 360000], # 52.9h 16.8G valx4 env1 # +-0.0037:[2.4296, 2.4372, 2.4292, 2.4308]

[ 20, 8, 2, 688, 2752, 256, 218.8, 2.6897, 2.4263, 360000], # 59.2h       valx4 env1
[ 20, 8, 2, 688, 2752, 224, 210.0, 2.9856,    nan, 360000], # 56.1h 16.6G valx4 env1
[+20, 8, 2, 688, 2752, 224, 210.0, 2.5680,+2.4208, 360000], # 56.1h 16.8G valx4 env1  minGemma-hidden_layers20-att_heads8-kv_heads2-hidden688-intermediate2752-head_dim224-T1024--2026-03-13-04-59.pth
# valx8: 2.4195 +- 0.0042 # torch.Tensor([2.4147, 2.4163, 2.4267, 2.4195, 2.4219, 2.4143, 2.4221, 2.4204]).std()
[ 20, 8, 2, 688, 2752, 192, 201.2, 2.6944, 2.4278, 360000], # 51.6h 16.4G valx1 env1
#[20, 8, 2, 688, 2752, 192, 201.2, 2.6660, 2.4363, 360000], #             valx4 env2 WD2/3
#[20, 8, 2, 688, 2752, 160, 192.4, 2.6304, 2.4466, 360000], # 40.3h       valx4 env2
[ 20, 8, 2, 688, 2752, 160, 192.4, 2.6578, 2.4302, 360000], # 48.4h 16.3G valx4 env1

[ 20, 8, 2, 640, 2560, 256, 196.1, 2.5582, 2.4238, 360000], # 55.6h 16.6G valx4 env1
#[20, 8, 2, 640, 2560, 224, 188.0, 2.6090, 2.4393, 360000], # 41.8h       valx4 env2
[ 20, 8, 2, 640, 2560, 224, 188.0, 2.5622,+2.4210, 360000], # 52.3h 16.2G valx4 env1  minGemma-hidden_layers20-att_heads8-kv_heads2-hidden640-intermediate2560-head_dim224-T1024--2026-02-21-17-06.pth
# valx8: 2.4216 +- 0.0037 # torch.Tensor([2.4269, 2.4198, 2.4235, 2.4216, 2.4223, 2.4196, 2.4147, 2.4246]).std()
[ 20, 8, 2, 640, 2560, 192, 179.8, 2.6413, 2.4261, 360000], # 47.9h 15.7G valx1 env1 ## bad in valx4
[ 20, 8, 2, 640, 2560, 192, 179.8, 2.5869, 2.4248, 360000], # 48.2h 16.2G valx4 env1 ## bad in valx4
#[20, 8, 2, 640, 2560, 192, 179.8, 2.7221, 2.4502, 360000], # 38.9h again valx4 env2 WD2/3
[ 20, 8, 2, 640, 2560, 160, 171.6, 2.5686, 2.4244, 360000], # 44.8h again valx4 env1
#[20, 8, 2, 640, 2560, 160, 171.6, 2.6246, 2.4423, 360000], # 36.4h 15.1G valx4 env2
#[20, 8, 2, 640, 2560, 160, 171.6, 2.6339, 2.4362, 360000], # 36.4h       valx4 env2 WD0.6(x1.2)   Bingo! But not reproducibly good.
#[20, 8, 2, 640, 2560, 160, 171.6, 2.7872, 2.4430, 360000], # 36.4h 15.1G valx4 env2 WD0.8(x1.6)
[ 20, 8, 2, 640, 2560, 144, 167.5, 2.6618, 2.4274, 360000], # 43.4h       valx4 env1

[ 20, 8, 2, 592, 2368, 256, 174.6, 2.5738, 2.4258, 360000], # 54.4h       valx4 env1
[ 20, 8, 2, 592, 2368, 224, 167.0, 2.5671, 2.4250, 360000], # 51.2h 15.8G valx4 env1 # NaN again w/ different data
[ 20, 8, 2, 592, 2368, 192, 159.5, 2.6096, 2.4275, 360000], # 46.8h 15.6G valx1 env1
[ 20, 8, 2, 592, 2368, 160, 151.9, 2.5836, 2.4341, 360000], # 43.7h       valx4 env1


# local best for H7(1): 2.4218(valx1), 2.4242(valx8) # No need to consider valx4 as all bad
[ 20, 7, 1, 812, 3248, 192, 249.1, 343.6128,  nan, 360000], # 52.1h 18.5G valx1 env1 # 812-288 20.3G

[ 20, 7, 1, 756, 3024, 192, 221.8, 2.5895, 2.4266, 360000], # 50.3h 16.9G valx1 env1 ## bad in valx4
[ 20, 7, 1, 756, 3024, 192, 221.8, 2.7065, 2.4360, 360000], # 50.7h again valx4 env1

[ 20, 7, 1, 700, 2800, 192, 195.9, 2.6841, 2.4354, 360000], # 48.6h 16.8G valx1 env1
[ 20, 7, 1, 700, 2800, 160, 188.8, 2.6238, 2.4276, 360000], # 45.9h       valx1 env1

[ 20, 7, 1, 644, 2576, 224, 178.2, 2.6135, 2.4284, 360000], # 50.5h       valx1 env1
[+20, 7, 1, 644, 2576, 192, 171.6, 2.5761,+2.4218, 360000], # 47.3h 16.4G valx1 env1  minGemma-hidden_layers20-att_heads7-kv_heads1-hidden644-intermediate2576-head_dim192-T1024--2025-12-24-23-20.pth
# valx8: 2.4242 +- 0.0033 # torch.Tensor([2.4195, 2.4221, 2.4224, 2.4293, 2.4224, 2.4272, 2.4242, 2.4268]).std()
[ 20, 7, 1, 644, 2576, 160, 165.0, 2.6040, 2.4279, 360000], # 44.7h 15.1G valx1 env1

[ 20, 7, 1, 588, 2352, 224, 154.8, 2.6299, 2.4321, 360000], # 47.3h 15.6G valx1 env1
[ 20, 7, 1, 588, 2352, 192, 148.8, 2.6099, 2.4311, 360000], # 43.9h 16.1G valx1 env1


# local best for H6(3): 2.4251(valx1), 2.4262(valx8)
[ 20, 6, 3, 768, 3072, 192, 233.4, 2.8709, 2.4377, 360000], # 47.6h 17.5G valx1 env1 # 816-288 19.8G

[ 20, 6, 3, 720, 2880, 192, 210.5, 2.7567, 2.4295, 360000], # 46.9h 16.1G valx1 env1

[ 20, 6, 3, 672, 2688, 192, 188.8, 2.7607, 2.4314, 360000], # 45.2h 15.8G valx1 env1
[ 20, 6, 3, 672, 2688, 160, 181.0, 2.6575,+2.4263, 360000], # 42.5h 15.6G valx1 env1 ## bad in valx4
[ 20, 6, 3, 672, 2688, 160, 181.0, 2.7168, 2.4350, 360000], # 43.0h again valx4 env1

[ 20, 6, 3, 624, 2496, 224, 175.3, 2.7447, 2.4365, 360000], # 45.3h 15.7G valx1 env1
[+20, 6, 3, 624, 2496, 192, 168.1, 2.5963,+2.4251, 360000], # 42.0h 15.6G valx1 env1  minGemma-hidden_layers20-att_heads6-kv_heads3-hidden624-intermediate2496-head_dim192-T1024--2025-11-28-03-52.pth
# valx8: 2.4262 +- 0.0042 # torch.Tensor([2.4324, 2.4235, 2.4291, 2.4215, 2.4296, 2.4262, 2.4269, 2.4204]).std()
[ 20, 6, 3, 624, 2496, 160, 160.9, 2.6725, 2.4295, 360000], # 39.3h 15.4G valx1 env1

[ 20, 6, 3, 576, 2304, 224, 155.2, 2.6476, 2.4354, 360000], # 43.9h 15.4G valx1 env1
[ 20, 6, 3, 576, 2304, 192, 148.5, 2.6391, 2.4364, 360000], # 40.3h 15.6G valx1 env1

[ 20, 6, 3, 528, 2112, 192, 130.1, 2.5872, 2.4338, 360000], # 39.2h       valx1 env1


# local best for H5(1): 2.4289(valx1)
[ 20, 5, 1, 720, 2880, 160, 188.4, 2.7239, 2.4380, 360000], # 39.6h 15.6G valx1 env1
#[20, 5, 1, 720, 2880, 144, 185.6, 2.6232, 2.4478, 360000], # 34.0h 14.9G valx4 env2 # +-0.0037:[2.4458, 2.4533, 2.4453, 2.4469]
#[20, 5, 1, 720, 2880, 128, 182.9, 2.6087, 2.4467, 360000], # 30.8h       valx4 env2 # +-0.0038:[2.4446, 2.4523, 2.4441, 2.4457]

[ 20, 5, 1, 680, 2720, 192, 176.6, 2.6646, 2.4375, 360000], # 40.9h 15.8G valx1 env1
[ 20, 5, 1, 680, 2720, 160, 171.4, 2.7436, 2.4525, 360000], # 38.8h 15.7G valx1 env1
[ 20, 5, 1, 680, 2720, 144, 168.8, 2.6063,+2.4297, 360000], # 38.1h       valx1 env1
[ 20, 5, 1, 680, 2720, 128, 166.2, 2.7614, 2.4418, 360000], # 30.4h 14.9G valx1 env1

[ 20, 5, 1, 640, 2560, 224, 165.0, 2.6633, 2.4338, 360000], # 40.1h 15.8G valx1 env1
[+20, 5, 1, 640, 2560, 192, 160.1, 2.5848,+2.4289, 360000], # 37.4h 15.4G valx1 env1 ### BEST but still bad in valx1 because the best is 2.4188@L30 (+-0.0038, SEM for valx1)
[ 20, 5, 1, 640, 2560, 160, 155.2, 2.6122, 2.4355, 360000], # 35.5h 15.3G valx1 env1
#[20, 5, 1, 640, 2560, 144, 152.7, 2.6138, 2.4478, 360000], # 29.6h 14.5G valx4 env2 # +-0.0037:[2.4455, 2.4533, 2.4454, 2.4469]

[ 20, 5, 1, 600, 2400, 224, 148.9, 2.6096, 2.4328, 360000], # 39.2h 15.5G valx1 env1
[ 20, 5, 1, 600, 2400, 192, 144.3, 2.5936, 2.4306, 360000], # 36.8h 15.0G valx1 env1

In [6]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  20 # 8 # G28 G18 #blocks
num_attention_heads = 8 # 4 # G16 G8
num_key_value_heads = 2 # 4 # G16 G1
hidden_size = num_attention_heads*86 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 224 # 32 # G256 # dim in attention # Doesn't affect time
rms_norm_eps = 1e-4 # 1e-6
rope_theta = 4000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)
        
class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_100M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=28//4; N_step=90000*4; print(T * B * N_step / 1000000) # 0.25? B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')
torch.cuda.empty_cache();

# Normal Model with Hand-eval   # 100M-T512: lr10e-4 WD1/4
training_args = TrainingArguments(gradient_accumulation_steps=4, learning_rate=16e-4, weight_decay=0.5, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
result = trainer.train(); tloss=result[2]["train_loss"]
loss = []; model.eval(); B2=12//2; torch.cuda.empty_cache();
for k in range(5300*2 *4):
    val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
    loss += [model(common.to('cuda', non_blocking=True))[0].item()]
if torch.Tensor(loss).mean() < 2.4235:
    torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
model.train(); del common; print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {tloss:.4f}, {torch.Tensor(loss).mean():.4f}, {N_step}],')

2580.48
L20 att8 kv_heads2 hidden688 intermediate2752 head_dim224 T1024

[ 20, 8, 2, 688, 2752, 224, 210.0, 2.5680, 2.4208, 360000],

In [2]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  20 # 8 # G28 G18 #blocks
num_attention_heads = 8 # 4 # G16 G8
num_key_value_heads = 2 # 4 # G16 G1
hidden_size = num_attention_heads*80 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 224 # 32 # G256 # dim in attention # Doesn't affect time
rms_norm_eps = 1e-4 # 1e-6
rope_theta = 4000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)
        
class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_100M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=28//4; N_step=90000*4; print(T * B * N_step / 1000000) # 0.25? B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')
torch.cuda.empty_cache();

# Normal Model with Hand-eval   # 100M-T512: lr10e-4 WD1/4
training_args = TrainingArguments(gradient_accumulation_steps=4, learning_rate=16e-4, weight_decay=0.5, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
result = trainer.train(); tloss=result[2]["train_loss"]
loss = []; model.eval(); B2=12//2; torch.cuda.empty_cache();
for k in range(5300*2 *4):
    val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
    loss += [model(common.to('cuda', non_blocking=True))[0].item()]
if torch.Tensor(loss).mean() < 2.4235:
    torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
model.train(); del common; print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {tloss:.4f}, {torch.Tensor(loss).mean():.4f}, {N_step}],')

2580.48
L20 att8 kv_heads2 hidden640 intermediate2560 head_dim224 T1024

[ 20, 8, 2, 640, 2560, 224, 188.0, 2.5622, 2.4210, 360000],

In [112]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  20 # 8 # G28 G18 #blocks
num_attention_heads = 7 # 4 # G16 G8
num_key_value_heads = 1 # 4 # G16 G1
hidden_size = num_attention_heads*92 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 192 # 32 # G256 # dim in attention # Doesn't affect time
rms_norm_eps = 1e-4 # 1e-6
rope_theta = 4000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)
        
class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_100M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=28//4; N_step=90000*4; print(T * B * N_step / 1000000) # 0.25? B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')
torch.cuda.empty_cache();

# Normal Model with Hand-eval   # 100M-T512: lr10e-4 WD1/4
training_args = TrainingArguments(gradient_accumulation_steps=4, learning_rate=16e-4, weight_decay=0.5, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
result = trainer.train(); tloss=result[2]["train_loss"]
loss = []; model.eval(); B2=12//2; torch.cuda.empty_cache();
for k in range(5300*2 *4):
    val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
    loss += [model(common.to('cuda', non_blocking=True))[0].item()]
if torch.Tensor(loss).mean() < 2.4235:
    torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
model.train(); del common; print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {tloss:.4f}, {torch.Tensor(loss).mean():.4f}, {N_step}],')

2580.48
L20 att7 kv_heads1 hidden644 intermediate2576 head_dim192 T1024

[ 20, 7, 1, 644, 2576, 192, 171.6, 2.5761, 2.4218, 360000],

# L18

In [ ]:
# L18 Normal Models T1024 Baby100M (default: B28//4 N90000 x4 lr16e-4 WD0.5)  # H10(5): 2.4199, H8(4): 2.4238, H6(3): 2.4256

# local best for H10(5): 2.4193(valx1), 2.4199(valx8)
[ 18,10, 5, 760, 3040, 256, 268.2, 2.9087, 2.4296, 360000], # 43.7h 19.5G valx1 env1 # valx1: B2=12//2 x 5300*2 Repeats
[ 18,10, 5, 760, 3040, 224, 255.0, 2.8753, 2.4377, 360000], # 41.0h 19.8G valx1 env1
[ 18,10, 5, 760, 3040, 192, 241.9, 2.7670, 2.4416, 360000], # 37.5h       valx1 env1
[ 18,10, 5, 760, 3040, 160, 228.8, 2.7602, 2.4306, 360000], # 33.8h 18.3G valx1 env1

[ 18,10, 5, 720, 2880, 288, 260.3, 2.8049, 2.4384, 360000], # 50.0h 18.4G valx1 env1 # +-0.0056:[2.4345, 2.4424]
[ 18,10, 5, 720, 2880, 256, 247.8, 2.6019, 2.4206, 360000], # 43.4h 19.8G valx1 env1         ## bad in valx4  # Why so good???
[ 18,10, 5, 720, 2880, 256, 247.8, 2.8495, 2.4463, 360000], # 44.0h again valx4 env1         ## bad in valx4
[ 18,10, 5, 720, 2880, 256, 247.8, 2.8144, 2.4361, 360000], # 44.0h 19.0G valx4 env1 againx1 ## bad in valx4  # againx2??? Not needed...
[+18,10, 5, 720, 2880, 224, 235.4, 2.6025,+2.4197, 360000], # 40.6h 19.2G valx1 env1  minGemma-hidden_layers18-att_heads10-kv_heads5-hidden720-intermediate2880-head_dim224-T1024--2026-01-06-22-19.pth
# valx8: 2.4199 +- 0.0020 # torch.Tensor([2.4206, 2.4180, 2.4201, 2.4178, 2.4239, 2.4195, 2.4207, 2.4185]).std()
[ 18,10, 5, 720, 2880, 192, 223.0, 2.5907, 2.4228, 360000], # 37.0h 17.3G valx1 env1 ## bad in valx4
[ 18,10, 5, 720, 2880, 192, 223.0, 2.6555, 2.4256, 360000], # 37.2h 17.0G valx4 env1 ## bad in valx4
[ 18,10, 5, 720, 2880, 160, 210.5, 2.6914, 2.4296, 360000], # 33.7h 17.0G valx1 env1
#[18,10, 5, 720, 2880, 144, 204.3, 2.6075, 2.4433, 360000], # 20.4h       valx4 env2

#[18,10, 5, 680, 2720, 288, 239.9, 2.6928, 2.4538, 360000], # 31.1h 18.2G valx4 env2
[ 18,10, 5, 680, 2720, 256, 228.2, 2.7085, 2.4333, 360000], # 42.9h       valx1 env1
[ 18,10, 5, 680, 2720, 224, 216.4, 2.6259, 2.4227, 360000], # 40.0h       valx1 env1 ### bad in valx4 although marginal
[ 18,10, 5, 680, 2720, 224, 216.4, 2.6069, 2.4236, 360000], # 40.4h 17.1G valx4 env1 ### bad in valx4 although marginal
#[18,10, 5, 680, 2720, 224, 216.4, 2.7185, 2.4483, 360000], # 25.1h again valx4 env2 WD2/3
[ 18,10, 5, 680, 2720, 192, 204.7, 2.5941, 2.4215, 360000], # 36.5h 17.1G valx1 env1 ### bad in valx4 although marginal
[ 18,10, 5, 680, 2720, 192, 204.7, 2.6059, 2.4241, 360000], # 36.7h again valx4 env1 ### bad in valx4 although marginal
#[18,10, 5, 680, 2720, 192, 204.7, 2.7857, 2.4554, 360000], # 22.7h       valx4 env2 WD2/3
[ 18,10, 5, 680, 2720, 160, 192.9, 2.5830, 2.4227, 360000], # 33.2h 16.6G valx1 env1 ### bad in valx4
[ 18,10, 5, 680, 2720, 160, 192.9, 2.6244, 2.4278, 360000], # 33.2h again valx4 env1 ### bad in valx4
[ 18,10, 5, 680, 2720, 144, 187.1, 2.7099, 2.4274, 360000], # 31.3h 16.0G valx1 env1
[ 18,10, 5, 680, 2720, 128, 181.2, 2.6046, 2.4256, 360000], # 18.0h       valx1 env1 ### again??? Not promissing
[ 18,10, 5, 680, 2720,  96, 169.4, 2.6976, 2.4440, 360000], # 15.0h       valx1 env1

[ 18,10, 5, 640, 2560, 256, 209.2, 2.6648, 2.4319, 360000], # 41.5h       valx1 env1
[+18,10, 5, 640, 2560, 224, 198.2, 2.5804,+2.4193, 360000], # 38.7h 16.8G valx1 env1  minGemma-hidden_layers18-att_heads10-kv_heads5-hidden640-intermediate2560-head_dim224-T1024--2026-01-26-05-46.pth
# valx8: 2.4230 +- 0.0036 # torch.Tensor([2.4185, 2.4274, 2.4184, 2.4263, 2.4230, 2.4218, 2.4269, 2.4215]).std()
[ 18,10, 5, 640, 2560, 192, 187.1, 2.6126, 2.4266, 360000], # 35.3h 16.5G valx1 env1 ### bad in valx4
[ 18,10, 5, 640, 2560, 192, 187.1, 2.5943, 2.4307, 360000], # 35.5h again valx4 env1
[ 18,10, 5, 640, 2560, 160, 176.1, 2.6528, 2.4263, 360000], # 31.9h 16.0G valx1 env1 ## again??? Not promissing

#[18,10, 5, 600, 2400, 256, 191.0, 2.5708, 2.4386, 360000], # 25.3h 15.5G valx4 env2 # +-0.0038:[2.4365, 2.4442, 2.4360, 2.4377]
[ 18,10, 5, 600, 2400, 256, 191.0, 2.6773, 2.4457, 360000], # 41.8h 16.6G valx4 env1
#[18,10, 5, 600, 2400, 224, 180.6, 2.5656, 2.4410, 360000], # 23.9h       valx4 env2 # +-0.0038:[2.4389, 2.4466, 2.4385, 2.4401]
[ 18,10, 5, 600, 2400, 224, 180.6, 2.5770, 2.4272, 360000], # 38.9h       valx4 env1
[ 18,10, 5, 600, 2400, 192, 170.2, 2.5973, 2.4267, 360000], # 35.0h       valx1 env1 ## again??? Not promissing


# local best for H8(4): 2.4205(valx1), 2.4238(valx8) # as all bad
[ 18, 8, 4, 768, 3072, 192, 229.9, 2.7594, 2.4390, 360000], # 31.6h       valx5 env1 # +-0.0035:[2.4363, 2.4413, 2.4376, 2.4438, 2.4358] # 562.1s
#[18, 8, 4, 768, 3072, 160, 219.2, 2.6775, 2.4563, 360000], # 19.5h       valx4 env2
#[18, 8, 4, 768, 3072, 144, 213.9, 2.6542, 2.4497, 360000], # 19.0h 15.5G valx4 env2
#[18, 8, 4, 768, 3072, 128, 208.6, 2.6962, 2.4491, 360000], # 15.2h       valx4 env2

[ 18, 8, 4, 736, 2944, 224, 225.4, 2.7673, 2.4428, 360000], # 34.5h 16.9G valx1 env1
[ 18, 8, 4, 736, 2944, 192, 215.2, 2.7262, 2.4332, 360000], # 31.6h 16.5G valx1 env1
#[18, 8, 4, 736, 2944, 160, 205.0, 2.6905, 2.4566, 360000], # 18.9h 15.5G valx4 env2 WD0.5
#[18, 8, 4, 736, 2944, 160, 205.0, 2.6159, 2.4420, 360000], # 18.7h again valx4 env2 WD0.525(x1.05)
#[18, 8, 4, 736, 2944, 160, 205.0, 2.6579, 2.4522, 360000], # 18.9h again valx4 env2 WD0.55(x1.1)
#[18, 8, 4, 736, 2944, 160, 205.0, 2.6109, 2.4386, 360000], # 18.8h again valx4 env2 WD0.575 better
#[18, 8, 4, 736, 2944, 160, 205.0, 2.7044, 2.4416, 360000], # 18.9h again valx4 env2 WD0.6(x1.2) better!
#[18, 8, 4, 736, 2944, 160, 205.0, 2.6562,+2.4353, 360000], # 18.8h again valx4 env2 WD0.625  Reproduced???
#[18, 8, 4, 736, 2944, 160, 205.0, 2.7092, 2.4395, 360000], # 18.7h again valx4 env2 WD2/3
[ 18, 8, 4, 736, 2944, 160, 205.0, 2.6007, 2.4249, 360000], # 29.1h 16.2G valx1 env1 ## bad in valx4
[ 18, 8, 4, 736, 2944, 160, 205.0, 2.6016, 2.4246, 360000], # 29.3h again valx4 env1 ## bad in valx4
[ 18, 8, 4, 736, 2944, 144, 199.9, 2.6040, 2.4246, 360000], # 28.1h 16.3G valx1 env1 ## bad in valx4
[ 18, 8, 4, 736, 2944, 144, 199.9, 2.6376, 2.4284, 360000], # 28.2h again valx4 env1 ## bad in valx4
#[18, 8, 4, 736, 2944, 144, 199.9, 2.6479, 2.4493, 360000], # 18.5h again valx4 env2
[ 18, 8, 4, 736, 2944, 128, 194.8, 2.6310, 2.4276, 360000], # 17.3h 15.5G valx5 env2 # +-0.0034: [2.4251, 2.4299, 2.4263, 2.4324, 2.4244] # 481.6s

[ 18, 8, 4, 704, 2816, 256, 220.4, 2.7162, 2.4376, 360000], # 36.4h 16.9G valx1 env1
[ 18, 8, 4, 704, 2816, 224, 210.7, 2.5856,+2.4205, 360000], # 33.7h       valx1 env1  minGemma-hidden_layers18-att_heads8-kv_heads4-hidden704-intermediate2816-head_dim224-T1024--2025-12-10-11-02.pth
# valx8: 2.4239 +- 0.0043 # torch.Tensor([2.4213, 2.4224, 2.4206, 2.4255, 2.4228, 2.4332, 2.4255, 2.4200]).std()
[ 18, 8, 4, 704, 2816, 192, 201.0, 2.7438, 2.4332, 360000], # 30.7h 16.0G valx1 env1
[ 18, 8, 4, 704, 2816, 160, 191.2, 2.5927, 2.4210, 360000], # 28.8h       valx1 env1 ## bad in valx4
[ 18, 8, 4, 704, 2816, 160, 191.2, 2.6184, 2.4257, 360000], # 28.7h again valx4 env1 ## bad in valx4
#[18, 8, 4, 704, 2816, 160, 191.2, 2.6286, 2.4463, 360000], # 18.2h again valx4 env2
#[18, 8, 4, 704, 2816, 160, 191.2, 2.6563, 2.4372, 360000], # 18.1h again valx4 env2 WD2/3
[ 18, 8, 4, 704, 2816, 144, 186.4, 2.7056, 2.4302, 360000], # 27.7h       valx1 env1

[ 18, 8, 4, 672, 2688, 288, 215.1, 2.7720, 2.4336, 360000], # 41.5h 16.5G valx1 env1
[+18, 8, 4, 672, 2688, 256, 205.8, 2.5809,+2.4218, 360000], # 35.8h 16.3G valx1 env1  minGemma-hidden_layers18-att_heads8-kv_heads4-hidden672-intermediate2688-head_dim256-T1024--2025-12-11-23-01.pth
# valx8: 2.4238 +- 0.0040 # torch.Tensor([2.4252, 2.4170, 2.4285, 2.4205, 2.4216, 2.4245, 2.4290, 2.4239]).std()
[ 18, 8, 4, 672, 2688, 224, 196.5, 2.5784,+2.4223, 360000], # 33.1h       valx1 env1  minGemma-hidden_layers18-att_heads8-kv_heads4-hidden672-intermediate2688-head_dim224-T1024--2025-12-05-08-41.pth
# valx8: 2.4248 +- 0.0045 # torch.Tensor([2.4226, 2.4182, 2.4258, 2.4243, 2.4221, 2.4227, 2.4304, 2.4319]).std()
[ 18, 8, 4, 672, 2688, 192, 187.2, 2.6132, 2.4247, 360000], # 30.2h 15.6G valx1 env1 ## bad in valx4
[ 18, 8, 4, 672, 2688, 192, 187.2, 2.6500, 2.4289, 360000], # 30.8h again valx4 env1 ## bad in valx4
#[18, 8, 4, 672, 2688, 192, 187.2, 2.6060, 2.4443, 360000], # 19.0h again valx4 env2
#[18, 8, 4, 672, 2688, 192, 187.2, 2.6624, 2.4357, 360000], # 18.8h again valx4 env2 WD2/3
[ 18, 8, 4, 672, 2688, 160, 177.9, 2.6844, 2.4284, 360000], # 27.9h 15.4G valx1 env1

[ 18, 8, 4, 640, 2560, 288, 200.4, 2.7759, 2.4414, 360000], # 40.9h 16.2G valx1 env1
[ 18, 8, 4, 640, 2560, 256, 191.5, 2.6084, 2.4266, 360000], # 35.4h 16.2G valx1 env1 ## bad in valx4
[ 18, 8, 4, 640, 2560, 256, 191.5, 2.6092, 2.4239, 360000], # 35.6h again valx4 env1 ## bad in valx4
[ 18, 8, 4, 640, 2560, 224, 182.7, 2.6078, 2.4274, 360000], # 32.7h 16.0G valx1 env1
[ 18, 8, 4, 640, 2560, 192, 173.8, 2.5914, 2.4248, 360000], # 29.4h 15.2G valx1 env1 ## bad in valx4
[ 18, 8, 4, 640, 2560, 192, 173.8, 2.5938, 2.4328, 360000], # 30.0h again valx4 env1 ## bad in valx4
#[18, 8, 4, 640, 2560, 192, 173.8, 2.6981, 2.4486, 360000], # 18.1h again valx4 env2 WD2/3
[ 18, 8, 4, 640, 2560, 160, 165.0, 2.6428, 2.4275, 360000], # 27.3h 15.0G valx1 env1

[ 18, 8, 4, 608, 2432, 224, 169.4, 2.6116, 2.4262, 360000], # 32.7h       valx1 env1 ## bad in valx4
[ 18, 8, 4, 608, 2432, 224, 169.4, 2.5763, 2.4294, 360000], # 32.8h again valx4 env1 ## bad in valx4
[ 18, 8, 4, 608, 2432, 192, 161.0, 2.6762, 2.4384, 360000], # 29.0h       valx1 env1


# local best for H6(3): 2.4255(valx1), 2.4256(valx8) # valx1 env1 # as all bad
[ 18, 6, 3, 768, 3072, 192, 213.9, 2.7611, 2.4323, 360000], # 26.3h

[ 18, 6, 3, 720, 2880, 192, 193.1, 2.8275, 2.4434, 360000], # 25.8h 14.9G
[ 18, 6, 3, 720, 2880, 160, 185.6, 2.6878, 2.4325, 360000], # 24.3h

[ 18, 6, 3, 672, 2688, 224, 180.2, 2.6852, 2.4303, 360000], # 27.1h
[+18, 6, 3, 672, 2688, 192, 173.3, 2.5948,+2.4255, 360000], # 25.1h 14.8G  minGemma-hidden_layers18-att_heads6-kv_heads3-hidden672-intermediate2688-head_dim192-T1024--2025-11-18-11-59.pth
# valx8: 2.4256 +- 0.0047 # torch.Tensor([2.4275, 2.4264, 2.4271, 2.4245, 2.4284, 2.4152, 2.4310, 2.4246]).std()
[ 18, 6, 3, 672, 2688, 160, 166.3, 2.6241,+2.4274, 360000], # 23.5h

[ 18, 6, 3, 624, 2496, 224, 160.9, 2.5896,+2.4271, 360000], # 26.1h        ## again??? Not promissing
[ 18, 6, 3, 624, 2496, 192, 154.4, 2.6306, 2.4302, 360000], # 24.2h 14.5G  # 160 with //2 out-VRAM # So use //4

[ 18, 6, 3, 576, 2304, 192, 136.6, 2.6139, 2.4303, 360000], # 23.1h 13.7G

[ 18, 6, 3, 528, 2112, 192, 119.7, 2.5892, 2.4396, 360000],

In [36]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  18 # 8 # G28 G18 #blocks
num_attention_heads =10 # 4 # G16 G8
num_key_value_heads = 5 # 4 # G16 G1
hidden_size = num_attention_heads*72 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 224 # 32 # G256 # dim in attention # Doesn't affect time
rms_norm_eps = 1e-4 # 1e-6
rope_theta = 4000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)
        
class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_100M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=28//4; N_step=90000*4; print(T * B * N_step / 1000000) # 0.25? B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')
torch.cuda.empty_cache();

# Normal Model with Hand-eval   # 100M-T512: lr10e-4 WD1/4
training_args = TrainingArguments(gradient_accumulation_steps=4, learning_rate=16e-4, weight_decay=0.5, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
result = trainer.train(); tloss=result[2]["train_loss"]
loss = []; model.eval(); B2=12//2; torch.cuda.empty_cache();
for k in range(5300 *2):
    val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
    loss += [model(common.to('cuda', non_blocking=True))[0].item()]
if torch.Tensor(loss).mean() < 2.4197:
    torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
model.train(); del common; print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {tloss:.4f}, {torch.Tensor(loss).mean():.4f}, {N_step}],')

2580.48
L18 att10 kv_heads5 hidden720 intermediate2880 head_dim224 T1024

[ 18, 10, 5, 720, 2880, 224, 235.4, 2.6025, 2.4197, 360000],

In [6]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  18 # 8 # G28 G18 #blocks
num_attention_heads =10 # 4 # G16 G8
num_key_value_heads = 5 # 4 # G16 G1
hidden_size = num_attention_heads*64 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 224 # 32 # G256 # dim in attention # Doesn't affect time
rms_norm_eps = 1e-4 # 1e-6
rope_theta = 4000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)
        
class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_100M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=28//4; N_step=90000*4; print(T * B * N_step / 1000000) # 0.25? B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')
torch.cuda.empty_cache();

# Normal Model with Hand-eval   # 100M-T512: lr10e-4 WD1/4
training_args = TrainingArguments(gradient_accumulation_steps=4, learning_rate=16e-4, weight_decay=0.5, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
result = trainer.train(); tloss=result[2]["train_loss"]
loss = []; model.eval(); B2=12//2; torch.cuda.empty_cache();
for k in range(5300 *2):
    val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
    loss += [model(common.to('cuda', non_blocking=True))[0].item()]
if torch.Tensor(loss).mean() < 2.4197:
    torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
model.train(); del common; print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {tloss:.4f}, {torch.Tensor(loss).mean():.4f}, {N_step}],')

2580.48
L18 att10 kv_heads5 hidden640 intermediate2560 head_dim224 T1024

[ 18, 10, 5, 640, 2560, 224, 198.2, 2.5804, 2.4193, 360000],

In [18]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  18 # 8 # G28 G18 #blocks
num_attention_heads = 8 # 4 # G16 G8
num_key_value_heads = 4 # 4 # G16 G1
hidden_size = num_attention_heads*88 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 224 # 32 # G256 # dim in attention # Doesn't affect time
rms_norm_eps = 1e-4 # 1e-6
rope_theta = 4000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)
        
class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_100M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=28//4; N_step=90000*4; print(T * B * N_step / 1000000) # 0.25? B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')
torch.cuda.empty_cache();

# Normal Model with Hand-eval   # 100M-T512: lr10e-4 WD1/4
training_args = TrainingArguments(gradient_accumulation_steps=4, learning_rate=16e-4, weight_decay=0.5, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
result = trainer.train(); tloss=result[2]["train_loss"]
loss = []; model.eval(); B2=12//2; torch.cuda.empty_cache();
for k in range(5300 *2):
    val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
    loss += [model(common.to('cuda', non_blocking=True))[0].item()]
if torch.Tensor(loss).mean() < 2.4235:
    torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
model.train(); del common; print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {tloss:.4f}, {torch.Tensor(loss).mean():.4f}, {N_step}],')

2580.48
L18 att8 kv_heads4 hidden704 intermediate2816 head_dim224 T1024

[ 18, 8, 4, 704, 2816, 224, 210.7, 2.5856, 2.4205, 360000],

In [6]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  18 # 8 # G28 G18 #blocks
num_attention_heads = 6 # 4 # G16 G8
num_key_value_heads = 3 # 4 # G16 G1
hidden_size = num_attention_heads*112 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 192 # 32 # G256 # dim in attention # Doesn't affect time
rms_norm_eps = 1e-4 # 1e-6
rope_theta = 4000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)
        
class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_100M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=28//4; N_step=90000*4; print(T * B * N_step / 1000000) # 0.25? B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')
torch.cuda.empty_cache();

# Normal Model with Hand-eval   # 100M-T512: lr10e-4 WD1/4
training_args = TrainingArguments(gradient_accumulation_steps=4, learning_rate=16e-4, weight_decay=0.5, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
result = trainer.train(); tloss=result[2]["train_loss"]
loss = []; model.eval(); B2=12//2; torch.cuda.empty_cache();
for k in range(5300 *2):
    val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
    loss += [model(common.to('cuda', non_blocking=True))[0].item()]
if torch.Tensor(loss).mean() < 2.4255:
    torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
model.train(); del common; print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {tloss:.4f}, {torch.Tensor(loss).mean():.4f}, {N_step}],')

2580.48
L18 att6 kv_heads3 hidden672 intermediate2688 head_dim192 T1024

[ 18, 6, 3, 672, 2688, 192, 173.3, 2.5948, 2.4255, 360000],

# L16

In [ ]:
# L16 Normal Models T1024 Baby100M (default: B28//4 N90000 lr16e-4 WD0.5)  # H9(3): 2.4177, H8(4): 2.4271, H7(1): 2.4308(valx1)

# local best for H9(3): 2.4195(valx4), 2.4177(valx8)
[ 16, 9, 3, 720, 2880, 288, 215.5, 2.7287, 2.4421, 360000], # 61.4h 16.1G valx4 env1
[ 16, 9, 3, 720, 2880, 256, 206.6, 2.5847, 2.4262, 360000], # 53.7h 16.1G valx4 env1
[ 16, 9, 3, 720, 2880, 224, 197.8, 2.6569, 2.4283, 360000], # 50.6h 15.9G valx4 env1
#[16, 9, 3, 720, 2880, 192, 188.9, 2.6873, 2.4504, 360000], # 37.6h 14.6G valx4 env2 # +-0.0038:[2.4481, 2.4559, 2.4478, 2.4496]
[ 16, 9, 3, 720, 2880, 192, 188.9, 2.7145, 2.4420, 360000], # 47.0h 15.4G valx4 env1
[ 16, 9, 3, 720, 2880, 160, 180.1, 2.6585, 2.4310, 360000], # 43.8h       valx4 env1

[ 16, 9, 3, 684, 2736, 352, 216.8, 2.7534, 2.4539, 360000], # 63.1h 16.4G valx4 env1
[+16, 9, 3, 684, 2736, 320, 208.4, 2.5844,+2.4195, 360000], # 59.5h       valx4 env1  minGemma-hidden_layers16-att_heads9-kv_heads3-hidden684-intermediate2736-head_dim320-T1024--2026-05-11-09-41.pth
# valx8: 2.4177 +- 0.0033 # torch.Tensor([2.4205, 2.4174, 2.4196, 2.4195, 2.4220, 2.4135, 2.4127, 2.4168]).std()
[ 16, 9, 3, 684, 2736, 288, 200.0, 2.5843,+2.4219, 360000], # 60.5h 15.8G valx4 env1  minGemma-hidden_layers16-att_heads9-kv_heads3-hidden684-intermediate2736-head_dim288-T1024--2026-03-22-03-48.pth
# valx8: 2.4251 +- 0.0034 # torch.Tensor([2.4246, 2.4263, 2.4258, 2.4230, 2.4231, 2.4250, 2.4321, 2.4205]).std()
[ 16, 9, 3, 684, 2736, 256, 191.6, 2.5816,+2.4201, 360000], # 53.3h       valx4 env1  minGemma-hidden_layers16-att_heads9-kv_heads3-hidden684-intermediate2736-head_dim256-T1024--2026-03-15-03-42.pth
# valx8: 2.4212 +- 0.0042 # torch.Tensor([2.4172, 2.4190, 2.4175, 2.4260, 2.4261, 2.4160, 2.4233, 2.4246]).std()
[ 16, 9, 3, 684, 2736, 224, 183.2, 2.6058,+2.4233, 360000], # 50.1h 16.0G valx4 env1  minGemma-hidden_layers16-att_heads9-kv_heads3-hidden684-intermediate2736-head_dim224-T1024--2026-03-04-13-09.pth
# valx8: 2.4220 +- 0.0047 # torch.Tensor([2.4232, 2.4236, 2.4286, 2.4155, 2.4234, 2.4226, 2.4244, 2.4146]).std()
#[16, 9, 3, 684, 2736, 224, 183.2, 2.6135,+2.4149, 360000], ############# valx4 env1  minGemma-hidden_layers16-att_heads9-kv_heads3-hidden684-intermediate2736-head_dim224-T1024--2026-03-17-07-00.pth # rms1e-1 rope64000 SPECIAL
##valx8: 2.4168 +- 0.0023 # torch.Tensor([2.4196, 2.4164, 2.4189, 2.4181, 2.4127, 2.4174, 2.4174, 2.4142]).std()
#[16, 9, 3, 684, 2736, 192, 174.8, 2.6025, 2.4289, 360000], # 45.7h 15.1G valx4 env2 # +-0.0037:[2.4269, 2.4343, 2.4263, 2.4280]
#[16, 9, 3, 684, 2736, 192, 174.8, 2.6735, 2.4409, 360000], # 36.2h WD2/3 valx4(=env2)
[ 16, 9, 3, 684, 2736, 192, 174.8, 2.6094, 2.4253, 360000], # 46.4h 15.2G valx4 env1
[ 16, 9, 3, 684, 2736, 160, 166.4, 2.6439, 2.4295, 360000], # 43.4h 15.0G valx4 env1

[ 16, 9, 3, 648, 2592, 320, 192.9, 2.5884, 2.4280, 360000], # 58.1h 15.7G valx4 env1
[ 16, 9, 3, 648, 2592, 288, 185.0, 2.7359, 2.4379, 360000], # 59.5h       valx4 env1
[ 16, 9, 3, 648, 2592, 256, 177.0, 2.5968, 2.4253, 360000], # 52.2h 15.6G valx4 env1
[ 16, 9, 3, 648, 2592, 224, 169.0, 2.5944, 2.4284, 360000], # 49.2h       valx4 env1
[ 16, 9, 3, 648, 2592, 192, 161.1, 2.5915, 2.4278, 360000], # 44.7h       valx1 env1
#[16, 9, 3, 612, 2448, 192, 147.9, 2.5977, 2.4454, 360000], # 33.1h 14.1G valx4 env2


# local best for H8(4): 2.4245(valx1), 2.4271(valx8)
[ 16, 8, 4, 768, 3072, 192, 208.6, 2.7345, 2.4449, 360000], # 45.0h 15.3G valx1 env1   ## 784-272 44.0h 23.3G giri ## 816-256 VRAM-out
[ 16, 8, 4, 768, 3072, 160, 199.2, 2.7802, 2.4368, 360000], # 42.0h 15.1G valx1 env1
[ 16, 8, 4, 768, 3072, 144, 194.4, 2.7061, 2.4334, 360000], # 40.6h       valx1 env1
[ 16, 8, 4, 768, 3072, 128, 189.7, 2.6428, 2.4296, 360000], # 31.8h       valx1 env1

[ 16, 8, 4, 720, 2880, 192, 188.9, 2.7207, 2.4452, 360000], # 44.3h       valx1 env1
[ 16, 8, 4, 720, 2880, 160, 180.1, 2.6851, 2.4312, 360000], # 41.3h 14.9G valx1 env1
[ 16, 8, 4, 720, 2880, 144, 175.7, 2.6662, 2.4273, 360000], # 40.1h 14.6G valx1 env1
[ 16, 8, 4, 720, 2880, 128, 171.2, 2.6815, 2.4296, 360000], # 31.0h       valx1 env1

[ 16, 8, 4, 672, 2688, 304, 199.0, 2.7491, 2.4450, 360000], # 58.1h 15.2G valx4 env1
[ 16, 8, 4, 672, 2688, 288, 194.9, 2.7921, 2.4447, 360000], # 55.2h 15.0G valx1 env1
[ 16, 8, 4, 672, 2688, 256, 186.7, 2.7757, 2.4444, 360000], # 49.1h 15.3G valx1 env1
[ 16, 8, 4, 672, 2688, 224, 178.4, 2.7405, 2.4472, 360000], # 46.5h 15.0G valx1 env1
[ 16, 8, 4, 672, 2688, 192, 170.1, 2.6206, 2.4290, 360000], # 43.0h 14.7G valx1 env1
[ 16, 8, 4, 672, 2688, 176, 166.0, 2.6604, 2.4322, 360000], # 41.7h       valx1 env1
[ 16, 8, 4, 672, 2688, 160, 161.9, 2.6089, 2.4292, 360000], # 40.1h       valx1 env1
[ 16, 8, 4, 672, 2688, 144, 157.8, 2.6092, 2.4298, 360000], # 38.7h 13.5G valx1 env1
[ 16, 8, 4, 672, 2688, 128, 153.6, 2.6277, 2.4325, 360000], # 29.8h       valx1 env1

[ 16, 8, 4, 624, 2496, 320, 182.9, 2.7013, 2.4442, 360000], # 55.3h 14.8G valx1 env1
[ 16, 8, 4, 624, 2496, 304, 179.1, 2.6017, 2.4273, 360000], # 53.9h 14.7G valx1 env1
[ 16, 8, 4, 624, 2496, 288, 175.2, 2.5858, 2.4259, 360000], # 52.7h 14.8G valx1 env1            ### bad in valx4
[ 16, 8, 4, 624, 2496, 288, 175.2, 2.5854, 2.4268, 360000], # 53.3h again valx4 env1 ### bad in valx4
#[16, 8, 4, 624, 2496, 288, 175.2, 2.5943, 2.4430, 360000], # 41.6h again valx4 env2
#[16, 8, 4, 624, 2496, 288, 175.2, 2.6208, 2.4393, 360000], # 41.3h again valx4 env2 WD0.6(x1.2) 14.6G  Bingo!
#[16, 8, 4, 624, 2496, 288, 175.2, 2.6495, 2.4403, 360000], # 41.6h again valx4 env2 WD0.7(x1.4) 14.6G
[ 16, 8, 4, 624, 2496, 272, 171.4, 2.5819, 2.4255, 360000], # 51.1h 14.3G valx1 env1            ### bad in valx4
[ 16, 8, 4, 624, 2496, 272, 171.4, 2.5943, 2.4265, 360000], # 52.0h again valx4 env1 ### bad in valx4
#[16, 8, 4, 624, 2496, 272, 171.4, 2.6105, 2.4447, 360000], # 41.1h again valx4 env2
#[16, 8, 4, 624, 2496, 272, 171.4, 2.6551, 2.4412, 360000], # 40.7h again valx4 env2 WD2/3
[+16, 8, 4, 624, 2496, 256, 167.6, 2.5971,+2.4245, 360000], # 46.1h 15.2G valx1 env1  minGemma-hidden_layers16-att_heads8-kv_heads4-hidden624-intermediate2496-head_dim256-T1024--2025-12-12-01-08.pth
# valx8: 2.4271 +- 0.0037 # torch.Tensor([2.4292, 2.4270, 2.4227, 2.4236, 2.4255, 2.4284, 2.4258, 2.4345]).std()
[ 16, 8, 4, 624, 2496, 224, 159.9, 2.5902, 2.4282, 360000], # 43.5h 15.0G valx1 env1
[ 16, 8, 4, 624, 2496, 192, 152.2, 2.6160, 2.4289, 360000], # 40.3h       valx1 env1
[ 16, 8, 4, 624, 2496, 160, 144.6, 2.6008, 2.4336, 360000], # 37.5h 14.2G valx1 env1
[ 16, 8, 4, 624, 2496, 144, 140.7, 2.7276, 2.4489, 360000], # 36.0h 13.9G valx1 env1

[ 16, 8, 4, 576, 2304, 320, 163.5, 2.6275, 2.4322, 360000], # 53.7h 14.3G valx1 env1
[ 16, 8, 4, 576, 2304, 288, 156.5, 2.6062, 2.4278, 360000], # 51.5h 14.1G valx1 env1
[ 16, 8, 4, 576, 2304, 256, 149.4, 2.5949, 2.4327, 360000], # 44.7h 14.4G valx1 env1
[ 16, 8, 4, 576, 2304, 224, 142.3, 2.6017, 2.4309, 360000], # 42.2h 14.2G valx1 env1
[ 16, 8, 4, 576, 2304, 192, 135.2, 2.6057, 2.4378, 360000], # 39.1h       valx1 env1

[ 16, 8, 4, 544, 2176, 320, 151.1, 2.6084, 2.4360, 360000], # 53.1h 14.1G valx1 env1
[ 16, 8, 4, 544, 2176, 288, 144.4, 2.5877, 2.4325, 360000], # 50.6h 13.8G valx1 env1
[ 16, 8, 4, 544, 2176, 256, 137.7, 2.6100, 2.4325, 360000], # 43.7h       valx1 env1
[ 16, 8, 4, 544, 2176, 224, 131.0, 2.6022, 2.4372, 360000], # 41.3h 13.9G valx1 env1
[ 16, 8, 4, 544, 2176, 192, 124.4, 2.6676, 2.4559, 360000], # 25.0h 13.7G valx1 env1


# local best for H7(1): 2.4308(valx1)  # Probably too small so not explored
#[16, 7, 1, 700, 2800, 224, 169.5, 2.6493, 2.4434, 360000], # 34.5h 14.6G valx4 env2
#[16, 7, 1, 700, 2800, 192, 163.8, 2.6290, 2.4475, 360000], # 32.1h       valx4 env2
[+16, 7, 1, 644, 2576, 256, 154.3, 2.5808,+2.4308, 360000], # 43.0h       valx1 env1
#[16, 7, 1, 644, 2576, 192, 143.8, 2.5978, 2.4505, 360000], # 30.9h 13.9G valx4 env2 # +-0.0038:[2.4483, 2.4561, 2.4480, 2.4497]


# rms1e-1 rope64000 SPECIAL
[+16, 9, 3, 684, 2736, 224, 183.2, 2.6135,+2.4149, 360000], # 50.1h again valx4 env1  minGemma-hidden_layers16-att_heads9-kv_heads3-hidden684-intermediate2736-head_dim224-T1024--2026-03-17-07-00.pth

In [11]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  16 # 8 # G28 G18 #blocks
num_attention_heads = 9 # 4 # G16 G8
num_key_value_heads = 3 # 4 # G16 G1
hidden_size = num_attention_heads*76 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 320 # 32 # G256 # dim in attention # Doesn't affect time
rms_norm_eps = 1e-4 # 1e-6
rope_theta = 4000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)
        
class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_100M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=28//4; N_step=90000*4; print(T * B * N_step / 1000000) # 0.25? B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')
torch.cuda.empty_cache();

# Normal Model with Hand-eval   # 100M-T512: lr10e-4 WD1/4
training_args = TrainingArguments(gradient_accumulation_steps=4, learning_rate=16e-4, weight_decay=0.5, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
result = trainer.train(); tloss=result[2]["train_loss"]
loss = []; model.eval(); B2=12//2; torch.cuda.empty_cache();
for k in range(5000*2 *4):
    val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
    loss += [model(common.to('cuda', non_blocking=True))[0].item()]
if torch.Tensor(loss).mean() < 2.4235:
    torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
model.train(); del common; print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {tloss:.4f}, {torch.Tensor(loss).mean():.4f}, {N_step}],')

2580.48
L16 att9 kv_heads3 hidden684 intermediate2736 head_dim320 T1024

[ 16, 9, 3, 684, 2736, 320, 208.4, 2.5844, 2.4195, 360000],

In [15]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  16 # 8 # G28 G18 #blocks
num_attention_heads = 9 # 4 # G16 G8
num_key_value_heads = 3 # 4 # G16 G1
hidden_size = num_attention_heads*76 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 288 # 32 # G256 # dim in attention # Doesn't affect time
rms_norm_eps = 1e-4 # 1e-6
rope_theta = 4000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)
        
class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_100M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=28//4; N_step=90000*4; print(T * B * N_step / 1000000) # 0.25? B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')
torch.cuda.empty_cache();

# Normal Model with Hand-eval   # 100M-T512: lr10e-4 WD1/4
training_args = TrainingArguments(gradient_accumulation_steps=4, learning_rate=16e-4, weight_decay=0.5, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
result = trainer.train(); tloss=result[2]["train_loss"]
loss = []; model.eval(); B2=12//2; torch.cuda.empty_cache();
for k in range(5300*2 *4):
    val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
    loss += [model(common.to('cuda', non_blocking=True))[0].item()]
if torch.Tensor(loss).mean() < 2.4235:
    torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
model.train(); del common; print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {tloss:.4f}, {torch.Tensor(loss).mean():.4f}, {N_step}],')

2580.48
L16 att9 kv_heads3 hidden684 intermediate2736 head_dim288 T1024

[ 16, 9, 3, 684, 2736, 288, 200.0, 2.5843, 2.4219, 360000],

In [12]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  16 # 8 # G28 G18 #blocks
num_attention_heads = 9 # 4 # G16 G8
num_key_value_heads = 3 # 4 # G16 G1
hidden_size = num_attention_heads*76 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 256 # 32 # G256 # dim in attention # Doesn't affect time
rms_norm_eps = 1e-4 # 1e-6
rope_theta = 4000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)
        
class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_100M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=28//4; N_step=90000*4; print(T * B * N_step / 1000000) # 0.25? B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')
torch.cuda.empty_cache();

# Normal Model with Hand-eval   # 100M-T512: lr10e-4 WD1/4
training_args = TrainingArguments(gradient_accumulation_steps=4, learning_rate=16e-4, weight_decay=0.5, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
result = trainer.train(); tloss=result[2]["train_loss"]
loss = []; model.eval(); B2=12//2; torch.cuda.empty_cache();
for k in range(5300*2 *4):
    val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
    loss += [model(common.to('cuda', non_blocking=True))[0].item()]
if torch.Tensor(loss).mean() < 2.4235:
    torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
model.train(); del common; print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {tloss:.4f}, {torch.Tensor(loss).mean():.4f}, {N_step}],')

2580.48
L16 att9 kv_heads3 hidden684 intermediate2736 head_dim256 T1024

[ 16, 9, 3, 684, 2736, 256, 191.6, 2.5816, 2.4201, 360000],

In [7]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  16 # 8 # G28 G18 #blocks
num_attention_heads = 9 # 4 # G16 G8
num_key_value_heads = 3 # 4 # G16 G1
hidden_size = num_attention_heads*76 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 224 # 32 # G256 # dim in attention # Doesn't affect time
rms_norm_eps = 1e-4 # 1e-6
rope_theta = 4000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)
        
class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_100M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=28//4; N_step=90000*4; print(T * B * N_step / 1000000) # 0.25? B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')
torch.cuda.empty_cache();

# Normal Model with Hand-eval   # 100M-T512: lr10e-4 WD1/4
training_args = TrainingArguments(gradient_accumulation_steps=4, learning_rate=16e-4, weight_decay=0.5, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
result = trainer.train(); tloss=result[2]["train_loss"]
loss = []; model.eval(); B2=12//2; torch.cuda.empty_cache();
for k in range(5300*2 *4):
    val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
    loss += [model(common.to('cuda', non_blocking=True))[0].item()]
if torch.Tensor(loss).mean() < 2.4235:
    torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
model.train(); del common; print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {tloss:.4f}, {torch.Tensor(loss).mean():.4f}, {N_step}],')

2580.48
L16 att9 kv_heads3 hidden684 intermediate2736 head_dim224 T1024

[ 16, 9, 3, 684, 2736, 224, 183.2, 2.6058, 2.4233, 360000],

In [39]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  16 # 8 # G28 G18 #blocks
num_attention_heads = 8 # 4 # G16 G8
num_key_value_heads = 4 # 4 # G16 G1
hidden_size = num_attention_heads*78 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 256 # 32 # G256 # dim in attention # Doesn't affect time
rms_norm_eps = 1e-4 # 1e-6
rope_theta = 4000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)
        
class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_100M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=28//4; N_step=90000*4; print(T * B * N_step / 1000000) # 0.25? B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')
torch.cuda.empty_cache();

# Normal Model with Hand-eval   # 100M-T512: lr10e-4 WD1/4
training_args = TrainingArguments(gradient_accumulation_steps=4, learning_rate=16e-4, weight_decay=0.5, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
result = trainer.train(); tloss=result[2]["train_loss"]
loss = []; model.eval(); B2=12//2; torch.cuda.empty_cache();
for k in range(5300 *2):
    val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
    loss += [model(common.to('cuda', non_blocking=True))[0].item()]
if torch.Tensor(loss).mean() < 2.4245:
    torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
model.train(); del common; print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {tloss:.4f}, {torch.Tensor(loss).mean():.4f}, {N_step}],')

2580.48
L16 att8 kv_heads4 hidden624 intermediate2496 head_dim256 T1024

[ 16, 8, 4, 624, 2496, 256, 167.6, 2.5971, 2.4245, 360000],

In [13]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  16 # 8 # G28 G18 #blocks
num_attention_heads = 9 # 4 # G16 G8
num_key_value_heads = 3 # 4 # G16 G1
hidden_size = num_attention_heads*76 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 224 # 32 # G256 # dim in attention # Doesn't affect time
rms_norm_eps = 1e-1 # 1e-6
rope_theta = 64000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)
        
class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_100M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=28//4; N_step=90000*4; print(T * B * N_step / 1000000) # 0.25? B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')
torch.cuda.empty_cache();

# Normal Model with Hand-eval   # 100M-T512: lr10e-4 WD1/4
training_args = TrainingArguments(gradient_accumulation_steps=4, learning_rate=16e-4, weight_decay=0.5, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
result = trainer.train(); tloss=result[2]["train_loss"]
loss = []; model.eval(); B2=12//2; torch.cuda.empty_cache();
for k in range(5300*2 *4):
    val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
    loss += [model(common.to('cuda', non_blocking=True))[0].item()]
if torch.Tensor(loss).mean() < 2.4235:
    torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
model.train(); del common; print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {tloss:.4f}, {torch.Tensor(loss).mean():.4f}, {N_step}],')

2580.48
L16 att9 kv_heads3 hidden684 intermediate2736 head_dim224 T1024

[ 16, 9, 3, 684, 2736, 224, 183.2, 2.6135, 2.4149, 360000],

# L12

In [ ]:
# L12 Normal Models T1024 Baby100M (default: x4 B28//4 lr16e-4 WD0.5 N90000)  # H12(6): 2.4351(valx1), H10(5): 2.4291, H10(2): 2.4345(valx1), H9(3): 2.4344

# local best for H12(6): 2.4351
[ 12,12, 6, 720, 2880, 192, 170.7, 2.6881, 2.4471, 360000], # 43.9h 13.7G valx4 env1
[ 12,12, 6, 672, 2688, 224, 163.9, 2.6879, 2.4567, 360000], # 46.8h 13.7G valx4 env1
[ 12,12, 6, 672, 2688, 192, 154.6, 2.6577, 2.4456, 360000], # 42.8h       valx4 env1
[ 12,12, 6, 624, 2496, 224, 147.9, 2.6044, 2.4397, 360000], # 44.4h 13.5G valx4 env1
[+12,12, 6, 624, 2496, 192, 139.3, 2.5938,+2.4351, 360000], # 40.6h 13.1G valx4 env1
[ 12,12, 6, 576, 2304, 256, 140.5, 148.8862,  nan, 360000], # 45.2h 13.4G valx4 env1 # again? but not promissing
[ 12,12, 6, 576, 2304, 224, 132.5, 2.6066, 2.4465, 360000], # 43.2h 13.0G valx4 env1
[ 12,12, 6, 576, 2304, 192, 124.6, 2.5929, 2.4398, 360000], # 39.6h 12.6G valx4 env1


# local best for H10(5): 2.4285(valx1), 2.4291(valx8)
#[12,10, 5, 840, 3360, 160, 192.3, 2.8832, 2.4688, 360000], # 23.2h       valx4 env2: latest environment (=faster, but requires new hyperparameters for tuning)
#[12,10, 5, 840, 3360, 128, 182.6, 2.7988, 2.4632, 360000], # 19.6h       valx4 env2

[ 12,10, 5, 800, 3200, 224, 197.0, 2.7433, 2.4531, 360000], # 38.6h       valx1 env1: same environment as 2025 FORGETTER paper
[ 12,10, 5, 800, 3200, 192, 187.8, 2.6571, 2.4399, 360000], # 35.7h       valx1 env1
[ 12,10, 5, 800, 3200, 160, 178.6, 2.6195,+2.4305, 360000], # 32.9h 14.3G valx1 env1  minGemma-hidden_layers12-att_heads10-kv_heads5-hidden800-intermediate3200-head_dim160-T1024--2026-01-25-23-08.pth
# valx8: 2.4318 +- 0.0027 # torch.Tensor([2.4294, 2.4375, 2.4325, 2.4295, 2.4330, 2.4299, 2.4326, 2.4302]).std()

#[12,10, 5, 760, 3040, 256, 191.5, 2.7914, 2.4541, 360000], # 25.2h 13.9G valx4 env2
[+12,10, 5, 760, 3040, 224, 182.8, 2.6251,+2.4285, 360000], # 36.9h 14.5G valx1 env1 # erased? minGemma-hidden_layers12-att_heads10-kv_heads5-hidden760-intermediate3040-head_dim224-T1024--2026-01-11-04-23.pth
# valx8: 2.4291 +- 0.0051 # torch.Tensor([2.4407, 2.4289, 2.4277, 2.4257, 2.4289, 2.4297, 2.4231, 2.4285]).std()
#[12,10, 5, 760, 3040, 224, 182.8, 2.7171, 2.4673, 360000], # 24.2h again valx4 env2 WD2/3
[ 12,10, 5, 760, 3040, 192, 174.0, 2.6988, 2.4410, 360000], # 34.3h 14.3G valx1 env1
#[12,10, 5, 760, 3040, 160, 165.2, 2.7015, 2.4632, 360000], # 20.8h       valx4 env2

#[12,10, 5, 720, 2880, 256, 177.3, 2.6995, 2.4676, 360000], # 24.7h 13.8G valx4 env2
[ 12,10, 5, 720, 2880, 224, 169.0, 2.6985, 2.4433, 360000], # 36.2h 14.4G valx1 env1
[ 12,10, 5, 720, 2880, 192, 160.7, 2.6209, 2.4358, 360000], # 33.7h 14.1G valx1 env1
[ 12,10, 5, 720, 2880, 160, 152.4, 2.6237, 2.4342, 360000], # 30.7h 13.8G valx1 env1

[ 12,10, 5, 680, 2720, 192, 147.9, 2.6242, 2.4375, 360000], # 33.1h       valx1 env1
#[12,10, 5, 680, 2720, 160, 140.0, 2.6116, 2.4466, 360000], # 19.7h       valx4 env2

[ 12,10, 5, 640, 2560, 192, 135.5, 2.6364, 2.4387, 360000], # 31.3h 13.6G valx1 env1

[ 12,10, 5, 600, 2400, 192, 123.5, 2.6035, 2.4393, 360000], # 31.1h 13.8G valx1 env1

[ 12,10, 5, 560, 2240, 192, 112.1, 2.6080, 2.4452, 360000], # 30.4h 12.1G valx1 env1


# local best for H10(2): 2.4345(valx1)
[ 12,10, 2, 720, 2880, 192, 150.7, 2.5993, 2.4357, 360000], # 32.5h 14.2G valx4 env1 # +-0.0038:[2.4336, 2.4412, 2.4330, 2.4349]
[ 12,10, 2, 680, 2720, 192, 138.5, 2.6097, 2.4358, 360000], # 31.9h 14.0G valx1 env1
[ 12,10, 2, 680, 2720, 160, 132.2, 2.6097, 2.4359, 360000], # 29.4h       valx1 env1
[ 12,10, 2, 680, 2720, 144, 129.1, 2.6092, 2.4404, 360000], # 28.4h       valx1 env1
[ 12,10, 2, 640, 2560, 224, 132.5, 2.6050, 2.4352, 360000], # 33.0h 14.0G valx1 env1
[+12,10, 2, 640, 2560, 192, 126.6, 2.6071,+2.4345, 360000], # 30.9h 13.8G valx1 env1
[ 12,10, 2, 640, 2560, 160, 120.7, 2.6016, 2.4365, 360000], # 28.3h       valx1 env1
#[12,10, 2, 600, 2400, 224, 120.8, 2.6000, 2.4491, 360000], # 19.7h       valx4 env2
[ 12,10, 2, 600, 2400, 192, 115.3, 2.6006, 2.4439, 360000], # 30.4h 12.2G valx1 env1
[ 12,10, 2, 560, 2240, 192, 104.3, 2.6005, 2.4429, 360000], # 29.7h       valx1 env1


# local best for H9(3): 2.4325(valx1), 2.4344(valx8)
[ 12, 9, 3, 792, 3168, 192, 174.0, 2.6776, 2.4364, 360000], # 33.2h 14.3G valx1 env1   # 792-320: 14.8G 46.6h

[ 12, 9, 3, 756, 3024, 192, 162.2, 2.6320, 2.4374, 360000], # 31.6h 14.0G valx1 env1
[ 12, 9, 3, 756, 3024, 160, 155.2, 2.6431, 2.4354, 360000], # 29.2h 14.0G valx1 env1
[ 12, 9, 3, 756, 3024, 128, 148.3, 2.6143, 2.4370, 360000], # 18.8h       valx1 env1
#[12, 9, 3, 756, 3024,  96, 141.3, 2.6155, 2.4517, 360000], # 15.8h       valx4 env2

[ 12, 9, 3, 720, 2880, 224, 157.4, 2.6273, 2.4357, 360000], # 33.7h 14.1G valx1 env1
[ 12, 9, 3, 720, 2880, 192, 150.7, 2.6202, 2.4334, 360000], # 31.0h       valx1 env1  minGemma-hidden_layers12-att_heads9-kv_heads3-hidden720-intermediate2880-head_dim192-T1024--2025-11-11-19-24.pth
# valx8: 2.4370 +- 0.0029 # torch.Tensor([2.4382, 2.4356, 2.4374, 2.4373, 2.4312, 2.4355, 2.4406, 2.4399]).std()
[ 12, 9, 3, 720, 2880, 192, 150.7,         2.4347        ], #        only-valx4 env2 (env1 and env2 make no difference in evaluation)
[ 12, 9, 3, 720, 2880, 176, 147.4, 2.6216, 2.4365, 360000], # 29.9h 13.8G valx1 env1
[+12, 9, 3, 720, 2880, 160, 144.1, 2.6058, 2.4323, 360000], # 28.6h 13.6G valx1 env1  minGemma-hidden_layers12-att_heads9-kv_heads3-hidden720-intermediate2880-head_dim160-T1024--2025-11-15-17-27.pth
# valx8: 2.4344 +- 0.0038 # torch.Tensor([2.4322, 2.4315, 2.4327, 2.4422, 2.4345, 2.4334, 2.4380, 2.4310]).std()
[ 12, 9, 3, 720, 2880, 160, 144.1,         2.4347        ], #        only-valx4 env2
[ 12, 9, 3, 720, 2880, 144, 140.8, 2.6533, 2.4411, 360000], # 27.6h 13.4G valx1 env1
[ 12, 9, 3, 720, 2880, 128, 137.5, 2.6265,+2.4325, 360000], # 18.4h 12.4G valx1 env1  Q:Reproducible on env2? -> 2.4286@B28, 2.4263@B24  ### Criteria:2.4339
[ 12, 9, 3, 720, 2880, 112, 134.2, 2.6108,+2.4339, 360000], # 17.9h 12.4G valx1 env1
[ 12, 9, 3, 720, 2880,  96, 130.8, 2.6152, 2.4400, 360000], # 15.8h 12.2G valx1 env1

[ 12, 9, 3, 684, 2736, 224, 146.0, 2.6383, 2.4404, 360000], # 33.3h 14.0G valx1 env1
[ 12, 9, 3, 684, 2736, 192, 139.7, 2.6219, 2.4431, 360000], # 30.6h       valx1 env1
[ 12, 9, 3, 684, 2736, 160, 133.4, 2.6150, 2.4364, 360000], # 28.2h       valx1 env1
[ 12, 9, 3, 684, 2736, 144, 130.2, 2.6181, 2.4398, 360000], # 26.9h 12.0G valx1 env1
[ 12, 9, 3, 684, 2736, 128, 127.1, 2.6151, 2.4382, 360000], # 17.9h       valx1 env1
[ 12, 9, 3, 684, 2736, 112, 123.9, 2.6210, 2.4416, 360000], # 17.5h 12.4G valx1 env1
[ 12, 9, 3, 684, 2736,  96, 120.7, 2.6230, 2.4459, 360000], # 15.3h 12.2G valx1 env1

[ 12, 9, 3, 648, 2592, 224, 134.9, 2.6069, 2.4381, 360000], # 32.7h       valx1 env1
[ 12, 9, 3, 648, 2592, 192, 129.0, 2.6112, 2.4379, 360000], # 30.1h       valx1 env1
[ 12, 9, 3, 648, 2592, 160, 123.0, 2.6083, 2.4359, 360000], # 27.8h       valx1 env1
[ 12, 9, 3, 648, 2592, 144, 120.0, 2.6155, 2.4420, 360000], # 26.5h 11.7G valx1 env1

[ 12, 9, 3, 612, 2448, 192, 118.6, 2.6166, 2.4449, 360000], # 28.9h       valx1 env1
[ 12, 9, 3, 612, 2448, 160, 113.0, 2.6068, 2.4384, 360000], # 26.1h       valx1 env1

[ 12, 9, 3, 576, 2304, 192, 108.7, 2.6123, 2.4444, 360000], # 27.9h       valx1 env1

[ 12, 9, 3, 540, 2160, 192,  99.1, 2.5964, 2.4488, 360000], # 27.7h       valx1 env1

[ 12, 9, 3, 504, 2016, 192,  89.8, 2.5992, 2.4554, 360000], # 26.0h 11.0G valx1 env1

[ 12, 9, 3, 468, 1872, 128,  72.4, 2.6134, 2.4677, 360000], # 13.5h  9.6G valx1 env1


## B searched (default: B32 N70000 lr18e-4 WD0.5) valx1 env1
[ 12, 9, 3, 648, 2592, 224, 134.9, 2.6076, 2.4384, 300000], # B36 26.7h 15.2G
[ 12, 9, 3, 648, 2592, 224, 134.9, 2.5938, 2.4358, 280000], # B36 24.9h 15.2G
[ 12, 9, 3, 648, 2592, 224, 134.9, 2.6300, 2.4381, 248888], # B36 22.1h 15.2G ~N62222

[ 12, 9, 3, 648, 2592, 224, 134.9, 2.5798,+2.4346, 400000], # B32 31.7h 13.9G
[+12, 9, 3, 648, 2592, 224, 134.9, 2.5931,+2.4321, 376000], # B32 29.8h 13.8G  minGemma-hidden_layers12-att_heads9-kv_heads3-hidden648-intermediate2592-head_dim224-T1024--2025-10-17-04-02.pth
# valx8: 2.4340 +- 0.0049 # torch.Tensor([2.4317, 2.4332, 2.4305, 2.4285, 2.4399, 2.4428, 2.4315, 2.4343]).std()
[ 12, 9, 3, 648, 2592, 224, 134.9, 2.5639,+2.4342, 376000], # B32 29.4h 13.7G lr16e-4 of above
[ 12, 9, 3, 648, 2592, 224, 134.9, 2.6078, 2.4350, 352000], # B32 27.8h 13.8G
[ 12, 9, 3, 648, 2592, 224, 134.9, 2.6044, 2.4355, 328000], # B32 26.0h 13.8G
[ 12, 9, 3, 648, 2592, 224, 134.9, 2.6157, 2.4362, 304000], # B32 24.0h 13.9G
[ 12, 9, 3, 648, 2592, 224, 134.9, 2.6375, 2.4361, 280000], # B32 22.1h 13.8G ~N70000
[ 12, 9, 3, 648, 2592, 224, 134.9, 2.6527, 2.4417, 256000], # B32 20.2h 13.9G

[ 12, 9, 3, 648, 2592, 224, 134.9, 2.6512, 2.4485, 240000], # B30 23.6h
[ 12, 9, 3, 648, 2592, 224, 134.9, 2.6286, 2.4386, 225000], # B30 22.1h 16.7G ~N74666
[ 12, 9, 3, 648, 2592, 224, 134.9, 2.6434, 2.4420, 210000], # B30 20.6h 16.8G

[ 12, 9, 3, 648, 2592, 224, 134.9, 2.6180, 2.4365, 384000], # B28 26.8h 13.7G
[ 12, 9, 3, 648, 2592, 224, 134.9, 2.6357, 2.4377, 360000], # B28 25.1h lr20e-4
[ 12, 9, 3, 648, 2592, 224, 134.9, 2.6223, 2.4355, 360000], # B28 25.1h 13.6G
[+12, 9, 3, 648, 2592, 224, 134.9, 2.6031,+2.4346, 360000], # B28 25.1h lr16e-4
[ 12, 9, 3, 648, 2592, 224, 134.9, 2.5745, 2.4376, 360000], # B28 24.8h lr14e-4
[ 12, 9, 3, 648, 2592, 224, 134.9, 2.6415, 2.4360, 344000], # B28 24.0h
[ 12, 9, 3, 648, 2592, 224, 134.9, 2.6761, 2.4452, 160000], # B28 22.3h 22.4G ~N80000 copied

[ 12, 9, 3, 648, 2592, 224, 134.9, 2.6808, 2.4503, 324000], # B27 28.9h 15.2G
[ 12, 9, 3, 648, 2592, 224, 134.9, 2.6141,+2.4348, 306000], # B27 27.3h 15.2G
[ 12, 9, 3, 648, 2592, 224, 134.9, 2.6451, 2.4390, 288000], # B27 25.7h
[ 12, 9, 3, 648, 2592, 224, 134.9, 2.6470, 2.4390, 270000], # B27 24.1h 15.2G
[ 12, 9, 3, 648, 2592, 224, 134.9, 2.6629, 2.4484, 249000], # B27 22.2h 15.2G ~N82962

[ 12, 9, 3, 648, 2592, 224, 134.9, 2.6684, 2.4437, 216000], # B24 25.8h 19.7G
[ 12, 9, 3, 648, 2592, 224, 134.9, 2.6509, 2.4438, 200000], # B24 23.9h 19.6G
[ 12, 9, 3, 648, 2592, 224, 134.9, 2.6816, 2.4482, 186000], # B24 22.2h 19.6G ~N93333

## WD searched (default: B28 N80000 lr18e-4 ->WD0.5?) valx1 env1
[ 12, 9, 3, 648, 2592, 224, 134.9, 2.7088, 2.4551, 160000], # WD0.7 22.3h 22.4G
[ 12, 9, 3, 648, 2592, 224, 134.9, 2.6848, 2.4512, 160000], # WD0.6
[ 12, 9, 3, 648, 2592, 224, 134.9, 2.7028, 2.4540, 160000], # WD0.55
[+12, 9, 3, 648, 2592, 224, 134.9, 2.6761,+2.4452, 160000], # WD0.5
[+12, 9, 3, 648, 2592, 224, 134.9, 2.6437,+2.4449, 160000], # WD0.45
[ 12, 9, 3, 648, 2592, 224, 134.9, 2.6383, 2.4455, 160000], # WD0.4
[ 12, 9, 3, 648, 2592, 224, 134.9, 3.2240, 2.5297, 160000], # WD0.2

## N, lr searched (guess: B28 lr18e-4 WD0.3 ->N80000) valx1 env1
[ 12, 9, 3, 648, 2592, 224, 134.9, 2.8367, 2.4828, 160000], #xlr21e-4 22.5h
[ 12, 9, 3, 648, 2592, 224, 134.9, 2.6242, 2.4597, 192000], # lr18e-4 27.0h
[ 12, 9, 3, 648, 2592, 224, 134.9, 2.6489, 2.4588, 176000], # lr18e-4 24.7h 22.5G
[ 12, 9, 3, 648, 2592, 224, 134.9, 2.6333, 2.4611, 168000], # lr18e-4 23.6h 22.6G
[ 12, 9, 3, 648, 2592, 224, 134.9, 2.6313,+2.4557, 160000], # lr18e-4 22.5h 22.4G
[ 12, 9, 3, 648, 2592, 224, 134.9, 2.6759, 2.4637, 160000], # lr18e-4 again
[ 12, 9, 3, 648, 2592, 224, 134.9, 2.8382, 2.4821, 144000], # lr18e-4 20.2h 22.5G
[ 12, 9, 3, 648, 2592, 224, 134.9, 2.6849, 2.4665, 160000], #xlr16e-4 22.5h 22.6G
[ 12, 9, 3, 648, 2592, 224, 134.9, 2.6047, 2.4629, 160000], #xlr15e-4 22.5h 22.5G

In [28]:
### For searching B
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  12 # 8 # G28 G18 #blocks
num_attention_heads = 9 # 4 # G16 G8
num_key_value_heads = 3 # 4 # G16 G1
hidden_size = num_attention_heads*72 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 224 # 32 # G256 # dim in attention # Doesn't affect time
rms_norm_eps = 1e-4 # 1e-6
rope_theta = 4000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)
        
class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_100M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=32//4; N_step=94000*4; print(T * B * N_step / 1000000) # 0.25? B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')
torch.cuda.empty_cache();

# Normal Model with Hand-eval   # 100M-T512: lr10e-4 WD1/4
training_args = TrainingArguments(gradient_accumulation_steps=4, learning_rate=18e-4, weight_decay=0.5, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
result = trainer.train(); tloss=result[2]["train_loss"]
loss = []; model.eval(); B2=12; torch.cuda.empty_cache();
for k in range(5300):
    val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
    loss += [model(common.to('cuda', non_blocking=True))[0].item()]
if torch.Tensor(loss).mean() < 2.4361:
    torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
model.train(); del common; print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {tloss:.4f}, {torch.Tensor(loss).mean():.4f}, {N_step}],')

3080.192
L12 att9 kv_heads3 hidden648 intermediate2592 head_dim224 T1024

[ 12, 9, 3, 648, 2592, 224, 134.9, 2.5931, 2.4321, 376000],