# Summary of best models for given numbers of layers

In [ ]:
# Each row is the output for a model in the following format. Different lines for different model structures. See the cell below for the excecuted codes.
# print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}, {criteria:.4f}],')
# Example: [16layers, 12(6)heads, hidden-dim=696, inter-layer-dim = 696x4, head-dim=224, #param=218million, val_loss_prev, #epochs, val_loss_current, val_loss_prev_prev, train_loss, Num-steps]

[ 24, 6, 3, 648, 2592, 224, 216.4, 2.4000,18, 2.4003,+2.3994, 2.3115, 168000], # 2.4005(valx8) minGemma-hidden_layers24-att_heads6-kv_heads3-hidden648-intermediate2592-head_dim224-T1024--2026-08-18-15-39.pth
[ 20, 9, 3, 720, 2880, 224, 238.2, 2.3999, 9, 2.4002,+2.3997, 2.3069, 112000], # 2.3978(valx8) minGemma-hidden_layers20-att_heads9-kv_heads3-hidden720-intermediate2880-head_dim224-T1024--2026-09-01-05-17.pth
[ 18,10, 5, 680, 2720, 208, 210.6, 2.3998,14, 2.4005, 2.3994, 2.3376, 168000], # 2.3998(valx8) minGemma-hidden_layers18-att_heads10-kv_heads5-hidden680-intermediate2720-head_dim208-T1024--2026-08-14-02-28


### below 10M # please erase
[ 16, 8, 4, 736, 2944, 208, 199.9, 2.9779, 7, 2.9853,+2.9779, 2.6630,  10500], # 2.9776(valx8) minGemma-hidden_layers16-att_heads8-kv_heads4-hidden736-intermediate2944-head_dim208-T1024--2026-05-17-22-02.pth
[ 12,15, 5, 660, 2640, 192, 156.8, 2.9836, 6, 2.9899,+2.9827, 2.6713,  10500], # 2.9857(valx8) minGemma-hidden_layers12-att_heads15-kv_heads5-hidden660-intermediate2640-head_dim192-T1024--2026-06-13-20-20.pth

# L24 (Models with 24 Layers)

In [ ]:
# L24 FORGETTER T1024 Baby100M (default: B24 N56000 lr6e-4 WD0.75) # H6(3): 2.4005    ### Criteria < 2.4048

# local best for H6(3): 2.4005 (valx8)
[ 24, 6, 3, 720, 2880, 256, 265.3, 2.3980,18, 2.3985,+2.3975, 2.2977, 168000], # 13.5h 21.9G    ### NEW need to evalx8
# 2.3989 minGemma-hidden_layers24-att_heads6-kv_heads3-hidden720-intermediate2880-head_dim256-T1024--2026-09-05-10-59
# 2.3991 minGemma-hidden_layers24-att_heads6-kv_heads3-hidden720-intermediate2880-head_dim256-T1024--2026-09-06-00-44
# 2.3990 minGemma-hidden_layers24-att_heads6-kv_heads3-hidden720-intermediate2880-head_dim256-T1024--2026-09-06-14-28
# 2.3975 minGemma-hidden_layers24-att_heads6-kv_heads3-hidden720-intermediate2880-head_dim256-T1024--2026-09-07-04-13
# 2.3980 minGemma-hidden_layers24-att_heads6-kv_heads3-hidden720-intermediate2880-head_dim256-T1024--2026-09-07-17-57
# 2.3985 minGemma-hidden_layers24-att_heads6-kv_heads3-hidden720-intermediate2880-head_dim256-T1024--2026-09-08-07-41
[ 24, 6, 3, 720, 2880, 224, 255.3, 2.4041,15, 2.4041, 2.4040, 2.2987, 168000], # 12.9h 20.1G
# 2.4040: minGemma-hidden_layers24-att_heads6-kv_heads3-hidden720-intermediate2880-head_dim224-T1024--2026-08-27-08-27
# valx8: 2.4067 +- 0.0051 # torch.Tensor([2.4040, 2.4111, 2.4081, 2.4062, 2.4132, 2.4034, 2.4021, 2.4134, 2.3988]).std()
# 2.4041: minGemma-hidden_layers24-att_heads6-kv_heads3-hidden720-intermediate2880-head_dim224-T1024--2026-08-27-21-34
# valx8: 2.4071 +- 0.0027 # torch.Tensor([2.4041, 2.4069, 2.4109, 2.4092, 2.4050, 2.4056, 2.4109, 2.4067, 2.4043]).std()
# 2.4041: minGemma-hidden_layers24-att_heads6-kv_heads3-hidden720-intermediate2880-head_dim224-T1024--2026-08-28-10-39
# valx8: 2.4054 +- 0.0032 # torch.Tensor([2.4041, 2.4095, 2.4107, 2.4050, 2.4046, 2.4029, 2.4057, 2.4061, 2.4001]).std()
[ 24, 6, 3, 684, 2736, 224, 235.5, 2.4058, 9, 2.4059, 2.4058, 2.3041, 168000], # 12.4h 19.7G
[+24, 6, 3, 648, 2592, 224, 216.4, 2.4000,18, 2.4003,+2.3994, 2.3115, 168000], # 12.5h 19.0G
# 2.4008: minGemma-hidden_layers24-att_heads6-kv_heads3-hidden648-intermediate2592-head_dim224-T1024--2026-08-16-00-11
# valx8: 2.4017 +- 0.0021 # torch.Tensor([2.4008, 2.4027, 2.4010, 2.4027, 2.4004, 2.4011, 2.4007, 2.4064, 2.3994]).std()
# 2.4006: minGemma-hidden_layers24-att_heads6-kv_heads3-hidden648-intermediate2592-head_dim224-T1024--2026-08-16-12-52
# valx8: 2.4012 +- 0.0043 # torch.Tensor([2.4006, 2.3964, 2.4037, 2.4007, 2.3998, 2.4037, 2.4090, 2.4022, 2.3944]).std()
# 2.4001: minGemma-hidden_layers24-att_heads6-kv_heads3-hidden648-intermediate2592-head_dim224-T1024--2026-08-17-01-34
# valx8: 2.4005 +- 0.0045 # torch.Tensor([2.4001, 2.4019, 2.4046, 2.3965, 2.3995, 2.4032, 2.3964, 2.4082, 2.3939]).std()
# 2.4006: minGemma-hidden_layers24-att_heads6-kv_heads3-hidden648-intermediate2592-head_dim224-T1024--2026-08-17-14-16
# valx8: 2.4031 +- 0.0024 # torch.Tensor([2.4006, 2.4051, 2.4031, 2.4028, 2.4016, 2.4012, 2.4056, 2.4073, 2.4003]).std()
# 2.4006: minGemma-hidden_layers24-att_heads6-kv_heads3-hidden648-intermediate2592-head_dim224-T1024--2026-08-18-02-58
# valx8: 2.4029 +- 0.0030 # torch.Tensor([2.4006, 2.4062, 2.4023, 2.4048, 2.4020, 2.4055, 2.4039, 2.4044, 2.3965]).std()
# 2.3994: minGemma-hidden_layers24-att_heads6-kv_heads3-hidden648-intermediate2592-head_dim224-T1024--2026-08-18-15-39
# valx8: 2.4005 +- 0.0025 # torch.Tensor([2.3994, 2.4039, 2.3994, 2.3990, 2.4017, 2.4011, 2.4046, 2.3980, 2.3978]).std()
# 2.4000: minGemma-hidden_layers24-att_heads6-kv_heads3-hidden648-intermediate2592-head_dim224-T1024--2026-08-19-04-21
# valx8: 2.4018 +- 0.0031 # torch.Tensor([2.4000, 2.4026, 2.4039, 2.4084, 2.4011, 2.4012, 2.3991, 2.4025, 2.3977]).std()
# 2.4003: minGemma-hidden_layers24-att_heads6-kv_heads3-hidden648-intermediate2592-head_dim224-T1024--2026-08-19-17-03
# valx8: 2.4025 +- 0.0023 # torch.Tensor([2.4003, 2.4015, 2.4042, 2.4073, 2.4039, 2.4006, 2.4027, 2.4010, 2.4006]).std()
[ 24, 6, 3, 612, 2448, 224, 198.0, 2.4055, 17, 2.4057, 2.4060, 2.3337, 168000], # 11.7h 18.4G stopped

In [87]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  24 # 8 # G28 G18 #blocks
num_attention_heads = 6 # 4 # G16 G8
num_key_value_heads = 3 # 4 # G16 G1
hidden_size = num_attention_heads*120 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 256 # 32 # G256 # dim in attention # Doesn't affect time
rms_norm_eps = 1e-1 # 1e-6
rope_theta = 64000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)
        
class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_100M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=24//3; N_step=96000*3 *7//6 //2; print(T * B * N_step / 1000000) # 0.25? B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')
torch.cuda.empty_cache();

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=3, learning_rate=6.0e-4, weight_decay=0.75, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//3*2 # Evaluation follows
    for k in range(5000*3//2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.4048:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0007)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

1376.256
L24 att6 kv_heads3 hidden720 intermediate2880 head_dim256 T1024

1 2.680884765625 tensor(2.4347)

2 2.361471819196429 tensor(2.4091)

3 2.3258816964285716 tensor(2.4044)

4 2.314600167410714 tensor(2.4032)

5 2.308961356026786 tensor(2.4036)

6 2.3034828404017857 tensor(2.4032)

7 2.2995675223214285 tensor(2.4027)

8 2.296428989955357 tensor(2.4023)

9 2.2946043526785713 tensor(2.4022)

10 2.2936273716517857 tensor(2.4014)

11 2.2929716796875 tensor(2.4015)

12 2.2910227399553573 tensor(2.3999)

13 2.2920364118303573 tensor(2.4000)

14 2.2935616629464284 tensor(2.3989)

15 2.2930101841517856 tensor(2.3991)

16 2.2952763671875 tensor(2.3990)

17 2.297918387276786 tensor(2.3975)

18 2.2977427455357144 tensor(2.3980)

19 2.3016886160714285 tensor(2.3985)
[ 24, 6, 3, 720, 2880, 256, 265.3, 2.3980, 18, 2.3985, 2.3975, 2.2977, 168000],

In [85]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  24 # 8 # G28 G18 #blocks
num_attention_heads = 6 # 4 # G16 G8
num_key_value_heads = 3 # 4 # G16 G1
hidden_size = num_attention_heads*108 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 224 # 32 # G256 # dim in attention # Doesn't affect time
rms_norm_eps = 1e-1 # 1e-6
rope_theta = 64000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)
        
class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_100M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=24//3; N_step=96000*3 *7//6 //2; print(T * B * N_step / 1000000) # 0.25? B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')
torch.cuda.empty_cache();

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=3, learning_rate=6.0e-4, weight_decay=0.75, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//3*2 # Evaluation follows
    for k in range(5000*3//2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.4048:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0007)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

1376.256
L24 att6 kv_heads3 hidden648 intermediate2592 head_dim224 T1024

1 2.694068917410714 tensor(2.4450)

2 2.3625320870535713 tensor(2.4168)

3 2.3424575892857145 tensor(2.4094)

4 2.3310545479910716 tensor(2.4071)

5 2.3262020089285715 tensor(2.4056)

6 2.3210277622767856 tensor(2.4045)

7 2.3171183035714287 tensor(2.4039)

8 2.3140340401785715 tensor(2.4030)

9 2.3122322823660713 tensor(2.4033)

10 2.3108038504464288 tensor(2.4024)

11 2.3097470703125 tensor(2.4021)

12 2.307381277901786 tensor(2.4008)

13 2.3079231305803574 tensor(2.4006)

14 2.308230887276786 tensor(2.4001)

15 2.3086255580357142 tensor(2.4006)

16 2.314972377232143 tensor(2.4006)

17 2.312352260044643 tensor(2.3994)

18 2.311513392857143 tensor(2.4000)

19 2.313213448660714 tensor(2.4003)
[ 24, 6, 3, 648, 2592, 224, 216.4, 2.4000, 18, 2.4003, 2.3994, 2.3115, 168000],

# L20

In [ ]:
# L20 FORGETTER T1024 Baby100M (default: B24 N56000 lr6e-4 WD0.75) # H9(3): 2.3978, H8(4): 2.4025, H6(3): 2.4044

# local best for H9(3): 2.3978 (valx8)
[ 20, 9, 3, 720, 2880, 224, 238.2, 2.3999,  9, 2.4002,+2.3997, 2.3069,112000], # 23.3h 27.1G
# 2.3997: minGemma-hidden_layers20-att_heads9-kv_heads3-hidden720-intermediate2880-head_dim224-T1024--2026-09-01-05-17
# valx8: 2.3978 +- 0.0040 # torch.Tensor([2.3997, 2.3987, 2.3982, 2.3963, 2.3971, 2.3930, 2.4025, 2.4036, 2.3913]).std()
# 2.3999: minGemma-hidden_layers20-att_heads9-kv_heads3-hidden720-intermediate2880-head_dim224-T1024--2026-09-02-04-53
# valx8: 2.4032 +- 0.0031 # torch.Tensor([2.3999, 2.4024, 2.4013, 2.4070, 2.4056, 2.4018, 2.4021, 2.3995, 2.4088]).std()
# 2.4002: minGemma-hidden_layers20-att_heads9-kv_heads3-hidden720-intermediate2880-head_dim224-T1024--2026-09-03-04-29
# valx8: 2.4012 +- 0.0032 # torch.Tensor([2.4002, 2.4033, 2.4039, 2.4000, 2.4024, 2.3983, 2.4047, 2.4031, 2.3949]).std()
[+20, 9, 3, 684, 2736, 208, 215.1, 2.3987, 15, 2.3992,+2.3987, 2.3116, 56000], # 21.5h 45.6G
# 2.4000: minGemma-hidden_layers20-att_heads9-kv_heads3-hidden684-intermediate2736-head_dim208-T1024--2026-08-07-11-06
# valx8: 2.4021 +- 0.0041 # torch.Tensor([2.4000, 2.4002, 2.4068, 2.4017, 2.4015, 2.4091, 2.3980, 2.4048, 2.3965]).std()
# 2.3994: minGemma-hidden_layers20-att_heads9-kv_heads3-hidden684-intermediate2736-head_dim208-T1024--2026-08-08-09-02
# valx8: 2.4027 +- 0.0034 # torch.Tensor([2.3994, 2.4055, 2.4055, 2.4040, 2.3994, 2.4007, 2.4039, 2.4078, 2.3978]).std()
# 2.3987: minGemma-hidden_layers20-att_heads9-kv_heads3-hidden684-intermediate2736-head_dim208-T1024--2026-08-09-06-57
# valx8: 2.3997 +- 0.0040 # torch.Tensor([2.3987, 2.4064, 2.4022, 2.3994, 2.4036, 2.4008, 2.3957, 2.3962, 2.3940]).std()
# 2.3997: minGemma-hidden_layers20-att_heads9-kv_heads3-hidden684-intermediate2736-head_dim208-T1024--2026-08-10-04-53
# valx8: 2.4026 +- 0.0039 # torch.Tensor([2.3997, 2.4039, 2.4023, 2.4008, 2.4095, 2.4000, 2.3998, 2.4084, 2.3989]).std()
# 2.3992: minGemma-hidden_layers20-att_heads9-kv_heads3-hidden684-intermediate2736-head_dim208-T1024--2026-08-11-02-48
# valx8: 2.4006 +- 0.0032 # torch.Tensor([2.3992, 2.4043, 2.3976, 2.3993, 2.4050, 2.4044, 2.4003, 2.3998, 2.3958]).std()

# local best for H8(4): 2.4025 (valx8), 2.4017 (valx1)
[ 20, 8, 4, 672, 2688, 208, 209.4, 2.4017, 16, 2.4017, 2.4013, 2.3291, 56000], # 20.3h 44.8G
# 2.4013: minGemma-hidden_layers20-att_heads8-kv_heads4-hidden672-intermediate2688-head_dim208-T1024--2026-07-26-15-30
# valx8: 2.4025 +- 0.0039 # torch.Tensor([2.4013, 2.4080, 2.4051, 2.4021, 2.3997, 2.4019, 2.4051, 2.4045, 2.3946]).std()
# 2.4017: minGemma-hidden_layers20-att_heads8-kv_heads4-hidden672-intermediate2688-head_dim208-T1024--2026-07-27-12-07
# valx8: 2.4038 +- 0.0030 # torch.Tensor([2.4017, 2.4054, 2.4016, 2.4070, 2.4050, 2.4054, 2.4038, 2.4066, 2.3978]).std()
[ 20, 8, 4, 608, 2432, 208, 180.1, 2.4020, 15, 2.4023, 2.4017, 2.3274, 56000], # 19.6h 42.8G

# local best for H6(3): 2.4044
[ 20, 6, 3, 684, 2736, 224, 202.0, 2.4043, 11, 2.4044, 2.4050, 2.3186, 56000], # 18.1h 44.7G  ###  Need to eval???
# 2.4043: minGemma-hidden_layers20-att_heads6-kv_heads3-hidden684-intermediate2736-head_dim224-T1024--2026-09-10-19-56
# 2.4044: minGemma-hidden_layers20-att_heads6-kv_heads3-hidden684-intermediate2736-head_dim224-T1024--2026-09-11-14-17
[ 20, 6, 3, 612, 2448, 192, 163.1, 2.3999, 14, 2.3999,+2.3998, 2.3249, 56000], # 15.5h 41.0G
# 2.3998: minGemma-hidden_layers20-att_heads6-kv_heads3-hidden612-intermediate2448-head_dim192-T1024--2026-07-12-10-39
# valx8: 2.4044 +- 0.0048 # torch.Tensor([2.3998, 2.4077, 2.4015, 2.3992, 2.4007, 2.4099, 2.4014, 2.4118, 2.4073]).std()

In [3]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  20 # 8 # G28 G18 #blocks
num_attention_heads = 9 # 4 # G16 G8
num_key_value_heads = 3 # 4 # G16 G1
hidden_size = num_attention_heads*80 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 224 # 32 # G256 # dim in attention # Doesn't affect time
rms_norm_eps = 1e-1 # 1e-6
rope_theta = 64000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)
        
class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_100M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=24//2; N_step=96000*2 *7//6 //2; print(T * B * N_step / 1000000) # 0.25? B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')
torch.cuda.empty_cache();

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=6.0e-4, weight_decay=0.75, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//1 # Evaluation follows
    for k in range(5000*1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.4048:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0007)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

1376.256
L20 att9 kv_heads3 hidden720 intermediate2880 head_dim224 T1024

1 2.6966342075892857 tensor(2.4375)

2 2.3507918526785714 tensor(2.4120)

3 2.3313611886160714 tensor(2.4050)

4 2.325581612723214 tensor(2.4026)

5 2.323354910714286 tensor(2.4019)

6 2.322172572544643 tensor(2.4011)

7 2.3271251395089285 tensor(2.4021)
back to previous

8 2.312330636160714 tensor(2.3997)

9 2.3068920200892857 tensor(2.3999)

10 2.317264090401786 tensor(2.4002)
[ 20, 9, 3, 720, 2880, 224, 238.2, 2.3999, 9, 2.4002, 2.3997, 2.3069, 112000],

In [1]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  20 # 8 # G28 G18 #blocks
num_attention_heads = 9 # 4 # G16 G8
num_key_value_heads = 3 # 4 # G16 G1
hidden_size = num_attention_heads*76 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 208 # 32 # G256 # dim in attention # Doesn't affect time
rms_norm_eps = 1e-1 # 1e-6
rope_theta = 64000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)
        
class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_100M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=24//1; N_step=96000*1 *7//6 //2; print(T * B * N_step / 1000000) # 0.25? B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')
torch.cuda.empty_cache();

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=1, learning_rate=6.0e-4, weight_decay=0.75, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12*2//1 # Evaluation follows
    for k in range(5000*1//2): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.4048:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0007)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

C:\Users\miura\miniconda3\envs\minGemma2\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

1376.256
L20 att9 kv_heads3 hidden684 intermediate2736 head_dim208 T1024

1 2.691677455357143 tensor(2.4377)

2 2.3538498883928574 tensor(2.4137)

3 2.336129185267857 tensor(2.4074)

4 2.3263292410714285 tensor(2.4045)

5 2.321675362723214 tensor(2.4029)

6 2.319220424107143 tensor(2.4017)

7 2.3166607142857143 tensor(2.4017)

8 2.3141142578125 tensor(2.4010)

9 2.312232840401786 tensor(2.4009)

10 2.3115645926339288 tensor(2.4004)

11 2.311114676339286 tensor(2.4001)

12 2.3115703125 tensor(2.4000)

13 2.310735630580357 tensor(2.3994)

14 2.314590122767857 tensor(2.3987)

15 2.3115919363839286 tensor(2.3997)
back to previous

16 2.311322265625 tensor(2.3992)
[ 20, 9, 3, 684, 2736, 208, 215.1, 2.3987, 15, 2.3992, 2.3987, 2.3116, 56000],

In [2]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  20 # 8 # G28 G18 #blocks
num_attention_heads = 8 # 4 # G16 G8
num_key_value_heads = 4 # 4 # G16 G1
hidden_size = num_attention_heads*84 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 208 # 32 # G256 # dim in attention # Doesn't affect time
rms_norm_eps = 1e-1 # 1e-6
rope_theta = 64000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)
        
class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_100M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=24//1; N_step=96000*1 *7//6 //2; print(T * B * N_step / 1000000) # 0.25? B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')
torch.cuda.empty_cache();

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=1, learning_rate=6.0e-4, weight_decay=0.75, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12*2//1 # Evaluation follows
    for k in range(5000*1//2): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.4048:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0007)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

1376.256
L20 att8 kv_heads4 hidden672 intermediate2688 head_dim208 T1024

1 2.694898995535714 tensor(2.4412)

2 2.3604246651785714 tensor(2.4175)

3 2.344245814732143 tensor(2.4102)

4 2.333466796875 tensor(2.4070)

5 2.3334921875 tensor(2.4056)

6 2.3276244419642858 tensor(2.4043)

7 2.3242967354910715 tensor(2.4039)

8 2.3244342912946427 tensor(2.4032)

9 2.3446626674107143 tensor(2.4036)

10 2.32955859375 tensor(2.4031)

11 2.3440047433035716 tensor(2.4026)

12 2.3422087053571428 tensor(2.4019)

13 2.3279499162946427 tensor(2.4021)

14 2.3328018973214286 tensor(2.4020)

15 2.336753487723214 tensor(2.4013)

16 2.329078125 tensor(2.4017)

KeyboardInterrupt:

In [2]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  20 # 8 # G28 G18 #blocks
num_attention_heads = 8 # 4 # G16 G8
num_key_value_heads = 4 # 4 # G16 G1
hidden_size = num_attention_heads*76 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 208 # 32 # G256 # dim in attention # Doesn't affect time
rms_norm_eps = 1e-1 # 1e-6
rope_theta = 64000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)
        
class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_100M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=24//1; N_step=96000*1 *7//6 //2; print(T * B * N_step / 1000000) # 0.25? B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')
torch.cuda.empty_cache();

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=1, learning_rate=6.0e-4, weight_decay=0.75, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12*2//1 # Evaluation follows
    for k in range(5000*1//2): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.3998:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0007)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

1376.256
L20 att8 kv_heads4 hidden608 intermediate2432 head_dim208 T1024

1 2.6888074776785715 tensor(2.4467)

2 2.3705424107142856 tensor(2.4183)

3 2.353891183035714 tensor(2.4105)

4 2.3440337611607145 tensor(2.4071)

5 2.3398472377232142 tensor(2.4048)

6 2.3351095145089285 tensor(2.4038)

7 2.3318063616071427 tensor(2.4027)

8 2.329993722098214 tensor(2.4023)

9 2.3299369419642857 tensor(2.4021)

10 2.329519112723214 tensor(2.4021)

11 2.332582310267857 tensor(2.4021)

12 2.3273436104910714 tensor(2.4017)

13 2.328224330357143 tensor(2.4018)

14 2.3296473214285713 tensor(2.4017)

15 2.327414760044643 tensor(2.4020)

16 2.3315238560267857 tensor(2.4023)
[ 20, 8, 4, 608, 2432, 208, 180.1, 2.4020, 15, 2.4023, 2.4017, 2.3274, 56000],

In [4]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  20 # 8 # G28 G18 #blocks
num_attention_heads = 6 # 4 # G16 G8
num_key_value_heads = 3 # 4 # G16 G1
hidden_size = num_attention_heads*114 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 224 # 32 # G256 # dim in attention # Doesn't affect time
rms_norm_eps = 1e-1 # 1e-6
rope_theta = 64000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)
        
class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_100M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=24//1; N_step=96000*1 *7//6 //2; print(T * B * N_step / 1000000) # 0.25? B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')
torch.cuda.empty_cache();

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=1, learning_rate=6.0e-4, weight_decay=0.75, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12*2//1 # Evaluation follows
    for k in range(5000*1//2): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.4048:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0007)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

1376.256
L20 att6 kv_heads3 hidden684 intermediate2736 head_dim224 T1024

1 2.7093058035714286 tensor(2.4410)

2 2.3616595982142856 tensor(2.4174)

3 2.344501395089286 tensor(2.4106)

4 2.3334083426339287 tensor(2.4080)

5 2.329554129464286 tensor(2.4065)

6 2.3243521205357145 tensor(2.4048)

7 2.3208374720982143 tensor(2.4050)

8 2.3180905412946426 tensor(2.4046)

9 2.320091517857143 tensor(2.4050)

10 2.3159500558035715 tensor(2.4043)

11 2.3185661272321427 tensor(2.4044)

KeyboardInterrupt:

In [1]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  20 # 8 # G28 G18 #blocks
num_attention_heads = 6 # 4 # G16 G8
num_key_value_heads = 3 # 4 # G16 G1
hidden_size = num_attention_heads*102 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 192 # 32 # G256 # dim in attention # Doesn't affect time
rms_norm_eps = 1e-1 # 1e-6
rope_theta = 64000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)
        
class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_100M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=24//1; N_step=96000*1 *7//6 //2; print(T * B * N_step / 1000000) # 0.25? B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')
torch.cuda.empty_cache();

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=1, learning_rate=6.0e-4, weight_decay=0.75, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12*2//1 # Evaluation follows
    for k in range(5000*1//2): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.4048:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0007)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

C:\Users\miura\miniconda3\envs\minGemma2\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

1376.256
L20 att6 kv_heads3 hidden612 intermediate2448 head_dim192 T1024

1 2.700965401785714 tensor(2.4464)

2 2.3703119419642857 tensor(2.4169)

3 2.3532059151785716 tensor(2.4081)

4 2.34389453125 tensor(2.4048)

5 2.339066824776786 tensor(2.4027)

6 2.334421316964286 tensor(2.4020)

7 2.3315219029017857 tensor(2.4018)

8 2.329363978794643 tensor(2.4007)

9 2.3279655412946427 tensor(2.4005)

10 2.3271784319196427 tensor(2.4003)

11 2.3267717633928573 tensor(2.4001)

12 2.3242179129464287 tensor(2.3998)

13 2.324741489955357 tensor(2.3998)

14 2.324860770089286 tensor(2.3999)

15 2.3231967075892856 tensor(2.3999)
[ 20, 6, 3, 612, 2448, 192, 163.1, 2.3999, 14, 2.3999, 2.3998, 2.3249, 56000],

# L18

In [ ]:
# L18 FORGETTER T1024 Baby100M (default: B24 N56000 lr6e-4 WD0.75) # H10(5): 2.3998

# local best for H10(5): 2.3998 (valx8)
[ 18, 10, 5, 720, 2880, 224, 235.4, 2.4010, 8, 2.4014, 2.4008, 2.3321, 168000], # 25.2h 18.1G
# 2.4012: minGemma-hidden_layers18-att_heads10-kv_heads5-hidden720-intermediate2880-head_dim224-T1024--2026-08-02-21-11
# valx8: 2.4029 +- 0.0039 # torch.Tensor([2.4012, 2.4088, 2.4074, 2.4036, 2.4030, 2.4058, 2.3987, 2.3992, 2.3982]).std()
# 2.4008: minGemma-hidden_layers18-att_heads10-kv_heads5-hidden720-intermediate2880-head_dim224-T1024--2026-08-03-22-20
# valx8: 2.4025 +- 0.0032 # torch.Tensor([2.4008, 2.4053, 2.4079, 2.4005, 2.4025, 2.4026, 2.4024, 2.4039, 2.3966]).std()
# 2.4010: minGemma-hidden_layers18-att_heads10-kv_heads5-hidden720-intermediate2880-head_dim224-T1024--2026-08-04-23-29
# valx8: 2.4028 +- 0.0026 # torch.Tensor([2.4010, 2.4023, 2.4023, 2.4048, 2.4061, 2.4069, 2.4019, 2.4013, 2.3987]).std()
# 2.4014: minGemma-hidden_layers18-att_heads10-kv_heads5-hidden720-intermediate2880-head_dim224-T1024--2026-08-06-00-39
# valx8: 2.4047 +- 0.0026 # torch.Tensor([2.4014, 2.4028, 2.4026, 2.4078, 2.4037, 2.4070, 2.4036, 2.4090, 2.4042]).std()
[+18, 10, 5, 680, 2720, 208, 210.6, 2.3998,14, 2.4005, 2.3994, 2.3376, 168000], # 23.9h 17.6G
# 2.4004: minGemma-hidden_layers18-att_heads10-kv_heads5-hidden680-intermediate2720-head_dim208-T1024--2026-08-14-02-28
# valx8: 2.3998 +- 0.0024 # torch.Tensor([2.4004, 2.3986, 2.3991, 2.3992, 2.3986, 2.3961,  2.3997, 2.4023, 2.4043]).std()
# 2.4004: minGemma-hidden_layers18-att_heads10-kv_heads5-hidden680-intermediate2720-head_dim208-T1024--2026-08-15-02-41
# valx8: 2.4026 +- 0.0029 # torch.Tensor([2.4004, 2.4035, 2.4048, 2.3984, 2.4036,  2.4060, 2.4004, 2.4067, 2.4000]).std()
# 2.3999: minGemma-hidden_layers18-att_heads10-kv_heads5-hidden680-intermediate2720-head_dim208-T1024--2026-08-16-02-55
# valx8: 2.4015 +- 0.0034 # torch.Tensor([2.3999, 2.4002, 2.4010, 2.4001, 2.3985, 2.4071, 2.4037, 2.4061, 2.3970]).std()
# 2.4004: minGemma-hidden_layers18-att_heads10-kv_heads5-hidden680-intermediate2720-head_dim208-T1024--2026-08-17-03-08
# valx8: 2.4013 +- 0.0050 # torch.Tensor([2.4004, 2.4037, 2.4010, 2.3991, 2.3946, 2.4053, 2.4080, 2.3934, 2.4061]).std()
# 2.3996: minGemma-hidden_layers18-att_heads10-kv_heads5-hidden680-intermediate2720-head_dim208-T1024--2026-08-18-03-21
# valx8: 2.4013 +- 0.0036 # torch.Tensor([2.3996, 2.4004, 2.4045, 2.4065, 2.3972, 2.3992, 2.4055, 2.4021, 2.3963]).std()
# 2.3994: minGemma-hidden_layers18-att_heads10-kv_heads5-hidden680-intermediate2720-head_dim208-T1024--2026-08-19-03-35
# valx8: 2.4002 +- 0.0017 # torch.Tensor([2.3994, 2.4015, 2.4015, 2.4019, 2.4021, 2.3984, 2.3994, 2.4002, 2.3972]).std()
# 2.3998: minGemma-hidden_layers18-att_heads10-kv_heads5-hidden680-intermediate2720-head_dim208-T1024--2026-08-20-03-49
# valx8: 2.4006 +- 0.0036 # torch.Tensor([2.3998, 2.4058, 2.3997, 2.4032, 2.3973, 2.4036, 2.4014, 2.4010, 2.3939]).std()
# 2.4005: minGemma-hidden_layers18-att_heads10-kv_heads5-hidden680-intermediate2720-head_dim208-T1024--2026-08-21-04-03
# valx8: 2.4022 +- 0.0027 # torch.Tensor([2.4005, 2.4067, 2.3987, 2.4027, 2.4050, 2.4022, 2.4019, 2.4032, 2.3986]).std()
[ 18, 10, 5, 640, 2560, 192, 187.1, 2.4027, 9, 2.4028, 2.4027, 2.3464, 168000], # 20.3h 16.7G
# 2.4027: minGemma-hidden_layers18-att_heads10-kv_heads5-hidden640-intermediate2560-head_dim192-T1024--2026-09-05-18-00
# valx8: 2.4043 +- 0.0031 # torch.Tensor([2.4027, 2.4059, 2.4048, 2.4019, 2.4040, 2.4041, 2.4092, 2.3985, 2.4073]).std()
# 2.4027: minGemma-hidden_layers18-att_heads10-kv_heads5-hidden640-intermediate2560-head_dim192-T1024--2026-09-06-14-35
# valx8: 2.4031 +- 0.0036 # torch.Tensor([2.4027, 2.4000, 2.4010, 2.4021, 2.4064, 2.4025, 2.4051, 2.3980, 2.4098]).std()
# 2.4028: minGemma-hidden_layers18-att_heads10-kv_heads5-hidden640-intermediate2560-head_dim192-T1024--2026-09-07-11-11
# valx8: 2.4043 +- 0.0030 # torch.Tensor([2.4028, 2.4033, 2.4061, 2.4099, 2.4042, 2.4076, 2.4025, 2.4016, 2.4006]).std()

[ 18, 8, 4, 720, 2880, 224, 218.0, 2.3993, 15, 2.3994, 2.3990, 2.3030, 224000], # 17.6h 14.3G   to evalx8
# 2.3994: minGemma-hidden_layers18-att_heads8-kv_heads4-hidden720-intermediate2880-head_dim224-T1024--2026-09-15-01-36
# 2.3994: minGemma-hidden_layers18-att_heads8-kv_heads4-hidden720-intermediate2880-head_dim224-T1024--2026-09-15-19-31
# 2.3990: minGemma-hidden_layers18-att_heads8-kv_heads4-hidden720-intermediate2880-head_dim224-T1024--2026-09-16-13-25
# 2.3993: minGemma-hidden_layers18-att_heads8-kv_heads4-hidden720-intermediate2880-head_dim224-T1024--2026-09-17-07-19
# 2.3994: minGemma-hidden_layers18-att_heads8-kv_heads4-hidden720-intermediate2880-head_dim224-T1024--2026-09-18-01-13
[ 18, 8, 4, 672, 2688, 224, 196.5, 2.4005, 15, 2.4008, 2.4005, 2.3150, 224000], # 16.8h 13.8G   to evalx8
# 2.4004: minGemma-hidden_layers18-att_heads8-kv_heads4-hidden672-intermediate2688-head_dim224-T1024--2026-09-03-06-00
# 2.4010: minGemma-hidden_layers18-att_heads8-kv_heads4-hidden672-intermediate2688-head_dim224-T1024--2026-09-03-23-07
# 2.4005: minGemma-hidden_layers18-att_heads8-kv_heads4-hidden672-intermediate2688-head_dim224-T1024--2026-09-04-16-13
# 2.4005: minGemma-hidden_layers18-att_heads8-kv_heads4-hidden672-intermediate2688-head_dim224-T1024--2026-09-05-09-20
# 2.4008: minGemma-hidden_layers18-att_heads8-kv_heads4-hidden672-intermediate2688-head_dim224-T1024--2026-09-06-02-27
[ 18, 8, 4, 624, 2496, 192, 167.3, 2.4042, 16, 2.4044, 2.4042, 2.3286, 224000], # 14.9h 12.2G //4

In [2]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  18 # 8 # G28 G18 #blocks
num_attention_heads =10 # 4 # G16 G8
num_key_value_heads = 5 # 4 # G16 G1
hidden_size = num_attention_heads*68 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 208 # 32 # G256 # dim in attention # Doesn't affect time
rms_norm_eps = 1e-1 # 1e-6
rope_theta = 64000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)
        
class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_100M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=24//3; N_step=96000*3 *7//6 //2; print(T * B * N_step / 1000000) # 0.25? B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')
torch.cuda.empty_cache();

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=3, learning_rate=6.0e-4, weight_decay=0.75, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(5000*2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.4048:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0007)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

1376.256
L18 att10 kv_heads5 hidden680 intermediate2720 head_dim208 T1024

1 2.68982421875 tensor(2.4401)

2 2.3578323102678573 tensor(2.4128)

3 2.341597935267857 tensor(2.4052)

4 2.332751953125 tensor(2.4023)

5 2.3326463448660713 tensor(2.4018)

6 2.3291755022321428 tensor(2.4008)

7 2.3308263113839285 tensor(2.4007)

8 2.3301810825892857 tensor(2.4004)

9 2.3315438058035713 tensor(2.4004)

10 2.3349907924107143 tensor(2.3999)

11 2.343886160714286 tensor(2.4004)

12 2.331494419642857 tensor(2.3996)

13 2.3356449497767855 tensor(2.3994)

14 2.3376043526785715 tensor(2.3998)

15 2.3363384486607144 tensor(2.4005)
[ 18, 10, 5, 680, 2720, 208, 210.6, 2.3998, 14, 2.4005, 2.3994, 2.3376, 168000],

In [1]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  18 # 8 # G28 G18 #blocks
num_attention_heads =10 # 4 # G16 G8
num_key_value_heads = 5 # 4 # G16 G1
hidden_size = num_attention_heads*64 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 192 # 32 # G256 # dim in attention # Doesn't affect time
rms_norm_eps = 1e-1 # 1e-6
rope_theta = 64000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)
        
class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_100M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=24//3; N_step=96000*3 *7//6 //2; print(T * B * N_step / 1000000) # 0.25? B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')
torch.cuda.empty_cache();

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=3, learning_rate=6.0e-4, weight_decay=0.75, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(5000*2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.4048:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0007)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

C:\Users\miuralab\AppData\Local\anaconda3\envs\minGemma2\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

1376.256
L18 att10 kv_heads5 hidden640 intermediate2560 head_dim192 T1024

1 2.718295479910714 tensor(2.4530)

2 2.3745945870535716 tensor(2.4215)

3 2.3570200892857143 tensor(2.4131)

4 2.3474564732142857 tensor(2.4093)

5 2.3435242745535714 tensor(2.4072)

6 2.3394510323660715 tensor(2.4049)

7 2.3361844308035713 tensor(2.4040)

8 2.3341485770089285 tensor(2.4027)

9 2.3463663504464285 tensor(2.4027)

10 2.3591905691964286 tensor(2.4028)
[ 18, 10, 5, 640, 2560, 192, 187.1, 2.4027, 9, 2.4028, 2.4027, 2.3464, 168000],

In [38]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  18 # 8 # G28 G18 #blocks
num_attention_heads = 8 # 4 # G16 G8
num_key_value_heads = 4 # 4 # G16 G1
hidden_size = num_attention_heads*90 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 224 # 32 # G256 # dim in attention # Doesn't affect time
rms_norm_eps = 1e-1 # 1e-6
rope_theta = 64000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)
        
class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_100M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=24//4; N_step=96000*4 *7//6 //2; print(T * B * N_step / 1000000) # 0.25? B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')
torch.cuda.empty_cache();

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=4, learning_rate=6.0e-4, weight_decay=0.75, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(5000*2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.4048:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0007)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

1376.256
L18 att8 kv_heads4 hidden720 intermediate2880 head_dim224 T1024

1 2.706748604910714 tensor(2.4395)

2 2.3535284598214288 tensor(2.4119)

3 2.3344926060267857 tensor(2.4053)

4 2.324085239955357 tensor(2.4029)

5 2.3200463169642855 tensor(2.4019)

6 2.315896205357143 tensor(2.4010)

7 2.3130205078125 tensor(2.4012)

8 2.3106064453125 tensor(2.4007)

9 2.3089647042410713 tensor(2.4005)

10 2.3075305524553573 tensor(2.3999)

11 2.3069493582589287 tensor(2.4000)

12 2.303666015625 tensor(2.3994)

13 2.3042081473214284 tensor(2.3994)

14 2.304271484375 tensor(2.3990)

15 2.3030496651785715 tensor(2.3993)

16 2.3051206752232143 tensor(2.3994)
[ 18, 8, 4, 720, 2880, 224, 218.0, 2.3993, 15, 2.3994, 2.3990, 2.3030, 224000],

In [37]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  18 # 8 # G28 G18 #blocks
num_attention_heads = 8 # 4 # G16 G8
num_key_value_heads = 4 # 4 # G16 G1
hidden_size = num_attention_heads*84 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 224 # 32 # G256 # dim in attention # Doesn't affect time
rms_norm_eps = 1e-1 # 1e-6
rope_theta = 64000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)
        
class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_100M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=24//4; N_step=96000*4 *7//6 //2; print(T * B * N_step / 1000000) # 0.25? B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')
torch.cuda.empty_cache();

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=4, learning_rate=6.0e-4, weight_decay=0.75, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(5000*2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.4048:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0007)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

1376.256
L18 att8 kv_heads4 hidden672 intermediate2688 head_dim224 T1024

1 2.6949520089285715 tensor(2.4456)

2 2.364678013392857 tensor(2.4182)

3 2.347833705357143 tensor(2.4102)

4 2.336796595982143 tensor(2.4069)

5 2.3320643136160712 tensor(2.4052)

6 2.3271095145089284 tensor(2.4034)

7 2.3235272042410715 tensor(2.4030)

8 2.321058872767857 tensor(2.4019)

9 2.3193595145089287 tensor(2.4018)

10 2.3180926339285715 tensor(2.4009)

11 2.3172518136160716 tensor(2.4013)

12 2.3153681640625 tensor(2.4004)

13 2.3173388671875 tensor(2.4010)

14 2.3173138950892858 tensor(2.4005)

15 2.3149578683035714 tensor(2.4005)

16 2.316715122767857 tensor(2.4008)
[ 18, 8, 4, 672, 2688, 224, 196.5, 2.4005, 15, 2.4008, 2.4005, 2.3150, 224000],

# L16

In [ ]:
# L16 FORGETTER T1024 Baby100M (default: B24 N56000 lr6e-4 WD0.75) # H10(5): 2.4007 (valx1), H9(3): 2.3973, H8(4): 2.4052

# local best for H10(5): 2.4007 (valx1)
[ 16,10, 5, 680, 2720, 224, 196.2, 2.4048,11, 2.4052, 2.4048, 2.3240, 224000], # 16.1h 14.3G
[ 16,10, 5, 680, 2720, 192, 185.7, 2.4013,18, 2.4019,+2.4007, 2.3230, 224000], # 14.6h 12.7G not saved
[ 16,10, 5, 640, 2560, 224, 179.7, 2.4052,10, 2.4058, 2.4050, 2.3536, 224000], # 15.2h 12.8G
[ 16,10, 5, 600, 2400, 224, 163.9, 2.4099,18, 2.4109, 2.4093, 2.3626, 224000], # 14.8h

# local best for H9(3): 2.3973
[ 16, 9, 3, 756, 3024, 256, 222.2, 2.4009,10, 2.4010, 2.4009, 2.3085, 224000], # 16.5h 14.9G
[+16, 9, 3, 720, 2880, 240, 202.2, 2.3957,18, 2.3969,+2.3957, 2.3133, 224000], # 15.8h 13.3G  minGemma-hidden_layers16-att_heads9-kv_heads3-hidden720-intermediate2880-head_dim240-T1024--2026-07-17-01-31
# valx8: 2.3974 +- 0.0034 # torch.Tensor([2.3957, 2.4053, 2.3962, 2.3954, 2.3946, 2.3980, 2.3985, 2.3985, 2.3943]).std()
[+16, 9, 3, 684, 2736, 224, 183.2, 2.3984,15, 2.3986,+2.3984, 2.3145, 224000], # 15.1h lr6   N96000 13-saved minGemma-hidden_layers16-att_heads9-kv_heads3-hidden684-intermediate2736-head_dim224-T1024--2026-06-04-23-56 # copied (=BASE)
# valx9: 2.3973 +- 0.0030 # torch.Tensor([2.3984, 2.3990, 2.3949, 2.4021, 2.3998, 2.3986, 2.3943, 2.3960, 2.3920,  2.3983]).std()
[ 16, 9, 3, 684, 2736, 224, 183.2, 2.3982,19, "stop",+2.3972, 2.3180,238000 ], # 16.0h lr6  N102000 26-saved minGemma-hidden_layers16-att_heads9-kv_heads3-hidden684-intermediate2736-head_dim224-T1024--2026-05-07-16-15 no criteria prev+0.0007
# valx8: 2.3987 +- 0.0028 # torch.Tensor([2.3972, 2.3974, 2.4016, 2.4015, 2.3982, 2.3989, 2.4006, 2.3926, 2.4006]).std()
[ 16, 9, 3, 612, 2448, 192, 147.9, 2.4015,15, 2.4016, 2.4013, 2.3291, 224000], # 12.7h 12.2G minGemma-hidden_layers16-att_heads9-kv_heads3-hidden612-intermediate2448-head_dim192-T1024--2026-07-25-22-25
### above is newly copied, maybe not evaluated yet???

# local best for H8(4): 2.4052
[ 16, 8, 4, 704, 2816, 224, 191.2, 2.3991, 18, 2.3998, 2.3988, 2.3183, 112000], # 19.4h 21.5G    ### now valx8
# 2.3994: minGemma-hidden_layers16-att_heads8-kv_heads4-hidden704-intermediate2816-head_dim224-T1024--2026-09-04-09-05
# 2.3997: minGemma-hidden_layers16-att_heads8-kv_heads4-hidden704-intermediate2816-head_dim224-T1024--2026-09-05-04-43
# 2.3997: minGemma-hidden_layers16-att_heads8-kv_heads4-hidden704-intermediate2816-head_dim224-T1024--2026-09-06-00-19
# 2.3988: minGemma-hidden_layers16-att_heads8-kv_heads4-hidden704-intermediate2816-head_dim224-T1024--2026-09-06-19-59
# 2.3991: minGemma-hidden_layers16-att_heads8-kv_heads4-hidden704-intermediate2816-head_dim224-T1024--2026-09-07-15-39
# 2.3998: minGemma-hidden_layers16-att_heads8-kv_heads4-hidden704-intermediate2816-head_dim224-T1024--2026-09-08-11-20
[ 16, 8, 4, 672, 2688, 208, 174.3, 2.4031, 15,+2.4031, 2.4032, 2.3249, 112000], # 18.7h 20.9G  minGemma-hidden_layers16-att_heads8-kv_heads4-hidden672-intermediate2688-head_dim208-T1024--2026-07-17-18-26
# valx8: 2.4052 +- 0.0045 # torch.Tensor([2.4031, 2.4121, 2.4024, 2.4063, 2.4104, 2.4086, 2.3979, 2.4027, 2.4034]).std()

In [6]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  16 # 8 # G28 G18 #blocks
num_attention_heads =10 # 4 # G16 G8
num_key_value_heads = 5 # 4 # G16 G1
hidden_size = num_attention_heads*68 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 192 # 32 # G256 # dim in attention # Doesn't affect time
rms_norm_eps = 1e-1 # 1e-6
rope_theta = 64000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)
        
class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_100M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=24//4; N_step=96000*4 *7//6 //2; print(T * B * N_step / 1000000) # 0.25? B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')
torch.cuda.empty_cache();

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=4, learning_rate=6.0e-4, weight_decay=0.75, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(5000*2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.3998:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0007)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

1376.256
L16 att10 kv_heads5 hidden680 intermediate2720 head_dim192 T1024

1 2.72412890625 tensor(2.4423)

2 2.3619098772321427 tensor(2.4160)

3 2.343029017857143 tensor(2.4087)

4 2.3341109095982144 tensor(2.4057)

5 2.332627232142857 tensor(2.4045)

6 2.3294002511160716 tensor(2.4035)

7 2.3271236049107142 tensor(2.4031)

8 2.324764229910714 tensor(2.4024)

9 2.3236642020089286 tensor(2.4022)

10 2.3236922433035714 tensor(2.4011)

11 2.322918387276786 tensor(2.4015)

12 2.3216460658482143 tensor(2.4012)

13 2.321686941964286 tensor(2.4015)

14 2.3221056082589286 tensor(2.4014)

15 2.3213763950892856 tensor(2.4012)

16 2.322878208705357 tensor(2.4018)

17 2.323697265625 tensor(2.4007)

18 2.322975864955357 tensor(2.4013)

19 2.3243530970982142 tensor(2.4019)
[ 16, 10, 5, 680, 2720, 192, 185.7, 2.4013, 18, 2.4019, 2.4007, 2.3230, 224000],

In [1]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  16 # 8 # G28 G18 #blocks
num_attention_heads = 9 # 4 # G16 G8
num_key_value_heads = 3 # 4 # G16 G1
hidden_size = num_attention_heads*80 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 240 # 32 # G256 # dim in attention # Doesn't affect time
rms_norm_eps = 1e-1 # 1e-6
rope_theta = 64000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)
        
class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_100M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=24//4; N_step=96000*4 *7//6 //2; print(T * B * N_step / 1000000) # 0.25? B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')
torch.cuda.empty_cache();

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=4, learning_rate=6.0e-4, weight_decay=0.75, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(5000*2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.4048:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0007)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

C:\Users\miura_lab2\anaconda3\envs\minGemma2\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

1376.256
L16 att9 kv_heads3 hidden720 intermediate2880 head_dim240 T1024

1 2.708310825892857 tensor(2.4421)

2 2.3560337611607145 tensor(2.4143)

3 2.3382659040178573 tensor(2.4061)

4 2.3285294363839286 tensor(2.4025)

5 2.324677734375 tensor(2.4003)

6 2.319123046875 tensor(2.3990)

7 2.316175083705357 tensor(2.3989)

8 2.313705078125 tensor(2.3981)

9 2.312215541294643 tensor(2.3982)

10 2.311673130580357 tensor(2.3973)

11 2.3116993582589287 tensor(2.3977)

12 2.3096111886160715 tensor(2.3973)

13 2.3102720424107144 tensor(2.3970)

14 2.310291015625 tensor(2.3966)

15 2.3100217633928573 tensor(2.3971)

16 2.3120096261160716 tensor(2.3968)

17 2.3139942801339286 tensor(2.3957)

18 2.313263950892857 tensor(2.3966)
back to previous

19 2.313071847098214 tensor(2.3969)
[ 16, 9, 3, 720, 2880, 240, 202.2, 2.3957, 18, 2.3969, 2.3957, 2.3133, 224000],

In [2]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  16 # 8 # G28 G18 #blocks
num_attention_heads = 9 # 4 # G16 G8
num_key_value_heads = 3 # 4 # G16 G1
hidden_size = num_attention_heads*76 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 224 # 32 # G256 # dim in attention # Doesn't affect time
rms_norm_eps = 1e-1 # 1e-6
rope_theta = 64000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)
        
class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_100M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=24//4; N_step=96000*4 *7//6 //2; print(T * B * N_step / 1000000) # 0.25? B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')
torch.cuda.empty_cache();

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=4, learning_rate=6.0e-4, weight_decay=0.75, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(5000*2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.4048:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0007)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

1376.256
L16 att9 kv_heads3 hidden684 intermediate2736 head_dim224 T1024

1 2.6961079799107144 tensor(2.4500)

2 2.36269921875 tensor(2.4173)

3 2.3449115513392855 tensor(2.4084)

4 2.3351068638392856 tensor(2.4046)

5 2.3304884207589285 tensor(2.4024)

6 2.325889927455357 tensor(2.4011)

7 2.322336216517857 tensor(2.4009)

8 2.319759347098214 tensor(2.4003)

9 2.3195821707589284 tensor(2.4000)

10 2.318497628348214 tensor(2.3995)

11 2.3179693080357144 tensor(2.3991)

12 2.315151646205357 tensor(2.3994)

13 2.3158843470982142 tensor(2.3986)

14 2.3156717354910716 tensor(2.3984)

15 2.3144730747767857 tensor(2.3984)

16 2.316421595982143 tensor(2.3986)
[ 16, 9, 3, 684, 2736, 224, 183.2, 2.3984, 15, 2.3986, 2.3984, 2.3145, 224000],

In [1]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  16 # 8 # G28 G18 #blocks
num_attention_heads = 9 # 4 # G16 G8
num_key_value_heads = 3 # 4 # G16 G1
hidden_size = num_attention_heads*76 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 224 # 32 # G256 # dim in attention # Doesn't affect time
rms_norm_eps = 1e-1 # 1e-6
rope_theta = 64000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)
        
class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_100M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=24//4; N_step=102000*4 *7//6 //2; print(T * B * N_step / 1000000) # 0.25? B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')
torch.cuda.empty_cache();

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=4, learning_rate=6.0e-4, weight_decay=0.75, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(5000*2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.4159:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

C:\Users\miura_lab2\anaconda3\envs\minGemma2\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

1462.272
L16 att9 kv_heads3 hidden684 intermediate2736 head_dim224 T1024

1 2.6941945903361346 tensor(2.4446)

2 2.3588883928571427 tensor(2.4179)

3 2.3410711659663868 tensor(2.4085)

4 2.3306034663865547 tensor(2.4043)

5 2.3268358718487394 tensor(2.4024)

6 2.322154149159664 tensor(2.4017)

7 2.3215546218487395 tensor(2.4015)

8 2.3192255777310926 tensor(2.4012)

9 2.318253151260504 tensor(2.4002)

10 2.3172728466386556 tensor(2.4004)

11 2.3151378676470586 tensor(2.3997)

12 2.3164884453781514 tensor(2.3992)

13 2.314514180672269 tensor(2.3989)

14 2.3137429096638655 tensor(2.3978)

15 2.31659375 tensor(2.3986)

16 2.3175081407563027 tensor(2.3980)

17 2.318322478991597 tensor(2.3986)

18 2.322107930672269 tensor(2.3983)

19 2.3180351890756303 tensor(2.3972)

20 2.3179931722689076 tensor(2.3982)

21 2.3200990021008403 tensor(2.3981)

22 2.3218763130252102 tensor(2.3989)

23 2.3206221113445378 tensor(2.3974)

24 2.321090336134454 tensor(2.3983)

25 2.3231664915966386 tensor(2.3980)

26 2.3207975315126053 tensor(2.3976)

27 2.3218193277310926 tensor(2.3980)

28 2.3222996323529412 tensor(2.3979)

KeyboardInterrupt:

In [29]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  16 # 8 # G28 G18 #blocks
num_attention_heads = 8 # 4 # G16 G8
num_key_value_heads = 4 # 4 # G16 G1
hidden_size = num_attention_heads*88 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 224 # 32 # G256 # dim in attention # Doesn't affect time
rms_norm_eps = 1e-1 # 1e-6
rope_theta = 64000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)
        
class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_100M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=24//2; N_step=96000*2 *7//6 //2; print(T * B * N_step / 1000000) # 0.25? B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')
torch.cuda.empty_cache();

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=6.0e-4, weight_decay=0.75, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//1 # Evaluation follows
    for k in range(5000*1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.4048:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0007)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

1376.256
L16 att8 kv_heads4 hidden704 intermediate2816 head_dim224 T1024

1 2.730972377232143 tensor(2.4454)

2 2.362380859375 tensor(2.4175)

3 2.345816964285714 tensor(2.4102)

4 2.335921875 tensor(2.4074)

5 2.3312668805803574 tensor(2.4054)

6 2.3273328683035714 tensor(2.4037)

7 2.3246900111607145 tensor(2.4027)

8 2.322347377232143 tensor(2.4020)

9 2.3213427734375 tensor(2.4017)

10 2.3196854073660713 tensor(2.4006)

11 2.320228515625 tensor(2.4002)

12 2.316655831473214 tensor(2.4000)

13 2.3203755580357144 tensor(2.4002)

14 2.3182085658482143 tensor(2.3994)

15 2.317713169642857 tensor(2.3997)

16 2.3180597098214286 tensor(2.3997)

17 2.3191802455357142 tensor(2.3988)

18 2.318296595982143 tensor(2.3991)

19 2.32136328125 tensor(2.3998)
[ 16, 8, 4, 704, 2816, 224, 191.2, 2.3991, 18, 2.3998, 2.3988, 2.3183, 112000],

In [1]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  16 # 8 # G28 G18 #blocks
num_attention_heads = 8 # 4 # G16 G8
num_key_value_heads = 4 # 4 # G16 G1
hidden_size = num_attention_heads*84 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 208 # 32 # G256 # dim in attention # Doesn't affect time
rms_norm_eps = 1e-1 # 1e-6
rope_theta = 64000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)
        
class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_100M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=24//2; N_step=96000*2 *7//6 //2; print(T * B * N_step / 1000000) # 0.25? B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')
torch.cuda.empty_cache();

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=6.0e-4, weight_decay=0.75, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//1 # Evaluation follows
    for k in range(5000*1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.4048:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0007)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

C:\Users\miura_lab\.conda\envs\minGemma3\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

1376.256
L16 att8 kv_heads4 hidden672 intermediate2688 head_dim208 T1024

1 2.7103962053571427 tensor(2.4488)

2 2.3693102678571427 tensor(2.4192)

3 2.3536710379464285 tensor(2.4129)

4 2.344228515625 tensor(2.4095)

5 2.340490652901786 tensor(2.4076)

6 2.335968470982143 tensor(2.4060)

7 2.332875 tensor(2.4054)

8 2.330576171875 tensor(2.4042)

9 2.3290255301339284 tensor(2.4039)

10 2.3285676618303572 tensor(2.4035)

11 2.3281837332589284 tensor(2.4036)

12 2.3260379464285714 tensor(2.4032)

13 2.3264462890625 tensor(2.4032)

14 2.3264637276785716 tensor(2.4032)

15 2.3248953683035714 tensor(2.4031)

KeyboardInterrupt:

# L12

In [ ]:
# L12 FORGETTER T1024 Baby100M (default: B24 N56000 lr6e-4 WD0.75) # H12(6): x.xxxx

# local best for H12(6): x.xxxx (valx8: x.xxxx)
[ 12, 12, 6, 768, 3072, 256, 208.6, 2.4052, 11, 2.4058, 2.4052, 2.3319, 224000], # 14.9h 13.6G //4
[ 12, 12, 6, 720, 2880, 224, 180.6, 2.4080, 12, 2.4076, 2.4075, 2.3289, 224000], # 13.7h 12.2G //4 stopped
[+12, 12, 6, 672, 2688, 208, 159.3, 2.4048, 15, 2.4052,+2.4043, 2.3352, 168000], # 13.4h 14.9G # cannot recover the saved data, Maybe erase after the better one obtained
# 2.4048 or 2.4048 minGemma-hidden_layers12-att_heads12-kv_heads6-hidden672-intermediate2688-head_dim208-T1024--2026-07-14-06-47
# 2.4048 or 2.4043 minGemma-hidden_layers12-att_heads12-kv_heads6-hidden672-intermediate2688-head_dim208-T1024--2026-07-14-20-27
# 2.4043 or 2.4048 minGemma-hidden_layers12-att_heads12-kv_heads6-hidden672-intermediate2688-head_dim208-T1024--2026-07-15-10-06
[ 12, 12, 6, 624, 2496, 192, 139.3, 2.4089, 21, 2.4088, 2.4086, 2.3490, 168000], # 11.7h 14.4G //3 stopped 2.4083@17th

In [1]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  12 # 8 # G28 G18 #blocks
num_attention_heads =12 # 4 # G16 G8
num_key_value_heads = 6 # 4 # G16 G1
hidden_size = num_attention_heads*64 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 256 # 32 # G256 # dim in attention # Doesn't affect time
rms_norm_eps = 1e-1 # 1e-6
rope_theta = 64000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)
        
class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_100M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=24//4; N_step=96000*4 *7//6 //2; print(T * B * N_step / 1000000) # 0.25? B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')
torch.cuda.empty_cache();

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=4, learning_rate=6.0e-4, weight_decay=0.75, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(5000*2): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.4048:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0007)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

1376.256
L12 att12 kv_heads6 hidden768 intermediate3072 head_dim256 T1024

1 2.7281082589285712 tensor(2.4490)

2 2.362505022321429 tensor(2.4227)

3 2.3460125558035716 tensor(2.4135)

4 2.337095424107143 tensor(2.4101)

5 2.3366223493303573 tensor(2.4086)

6 2.331599051339286 tensor(2.4068)

7 2.330869140625 tensor(2.4066)

8 2.330248744419643 tensor(2.4056)

9 2.3335537109375 tensor(2.4063)
back to previous

10 2.330523856026786 tensor(2.4052)

11 2.331857700892857 tensor(2.4059)
back to previous

12 2.3333318917410715 tensor(2.4058)
[ 12, 12, 6, 768, 3072, 256, 208.6, 2.4052, 11, 2.4058, 2.4052, 2.3319, 224000],

In [1]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  12 # 8 # G28 G18 #blocks
num_attention_heads =12 # 4 # G16 G8
num_key_value_heads = 6 # 4 # G16 G1
hidden_size = num_attention_heads*56 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 208 # 32 # G256 # dim in attention # Doesn't affect time
rms_norm_eps = 1e-1 # 1e-6
rope_theta = 64000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)
        
class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_100M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=24//3; N_step=96000*3 *7//6 //2; print(T * B * N_step / 1000000) # 0.25? B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')
torch.cuda.empty_cache();

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=3, learning_rate=6.0e-4, weight_decay=0.75, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(5000*2): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.4048:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0007)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

1376.256
L12 att12 kv_heads6 hidden672 intermediate2688 head_dim208 T1024

1 2.7186012834821427 tensor(2.4556)

2 2.374333984375 tensor(2.4227)

3 2.359015625 tensor(2.4136)

4 2.351478515625 tensor(2.4100)

5 2.3483507254464286 tensor(2.4082)

6 2.344618582589286 tensor(2.4070)

7 2.3424425223214285 tensor(2.4064)

8 2.3406844308035715 tensor(2.4060)

9 2.3390679408482145 tensor(2.4053)

10 2.3382576729910713 tensor(2.4052)

11 2.338893275669643 tensor(2.4053)

12 2.3356476004464284 tensor(2.4048)

13 2.3363356584821426 tensor(2.4048)

14 2.3366040736607143 tensor(2.4043)

15 2.3351778738839286 tensor(2.4048)

16 2.3377472098214285 tensor(2.4052)
[ 12, 12, 6, 672, 2688, 208, 159.3, 2.4048, 15, 2.4052, 2.4043, 2.3352, 168000],