# Summary of best models for given numbers of layers

In [ ]:
# Each row is the output for a model in the following format. Different lines for different model structures. See the cell below for the excecuted codes.
# print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}, {criteria:.4f}],')
# Example: [16layers, 12(6)heads, hidden-dim=696, inter-layer-dim = 696x4, head-dim=224, #param=218million, val_loss_prev, #epochs, val_loss_current, val_loss_prev_prev, train_loss, Num-steps]

[ 36, 4, 2, 680, 2720, 288, 318.8, 2.9752, 7, 2.9871,+2.9752, 3.2428, 10500], # 2.9772(valx8) minGemma-hidden_layers36-att_heads4-kv_heads2-hidden680-intermediate2720-head_dim288-T1024--2026-07-28-01-46.pth
[ 30, 6, 3, 744, 2976, 256, 339.8, 2.9782, 7, 2.9813,+2.9782, 3.0839, 10500], # 2.9780(valx8) minGemma-hidden_layers30-att_heads6-kv_heads3-hidden744-intermediate2976-head_dim256-T1024--2026-04-18-18-41.pth
[ 24, 7, 1, 616, 2464, 288, 208.5, 2.9765, 7, 2.9839,+2.9765, 2.6495, 10500], # 2.9775(valx8) minGemma-hidden_layers24-att_heads7-kv_heads1-hidden616-intermediate2464-head_dim288-T1024--2026-06-24-17-19.pth
[ 20, 6, 3, 720, 2880, 240, 223.0, 2.9757, 7, 3.0821,+2.9757, 2.8139, 10500], # 2.9775(valx8) minGemma-hidden_layers20-att_heads6-kv_heads3-hidden720-intermediate2880-head_dim240-T1024--2026-07-12-23-01.pth (2nd:2.9767)
[ 18,10, 5, 680, 2720, 240, 222.3, 2.9800, 6, 2.9873,+2.9789, 2.6618, 10500], # 2.9801(valx8) minGemma-hidden_layers18-att_heads10-kv_heads5-hidden680-intermediate2720-head_dim240-T1024--2026-06-25-06-43.pth
[ 16, 8, 4, 736, 2944, 208, 199.9, 2.9779, 7, 2.9853,+2.9779, 2.6630, 10500], # 2.9776(valx8) minGemma-hidden_layers16-att_heads8-kv_heads4-hidden736-intermediate2944-head_dim208-T1024--2026-05-17-22-02.pth
[ 12,15, 5, 660, 2640, 192, 156.8, 2.9836, 6, 2.9899,+2.9827, 2.6713, 10500], # 2.9857(valx8) minGemma-hidden_layers12-att_heads15-kv_heads5-hidden660-intermediate2640-head_dim192-T1024--2026-06-13-20-20.pth

# L36 (Models with 36 Layers)

In [ ]:
# L36 FORGETTER T1024 Baby10M (default: B12 N5250 lr10e-4 WD1.8) # H5(1): 2.9807, H4(2): 2.9772, H3(1): 2.9820   ### Criteria  < 2.9837

# local best for H5(1): 2.9794 (valx8: 2.9807)
[ 36, 5, 1, 800, 3200, 288, 416.5, 2.9868, 5, 3.3465, 2.9868, 3.0845, 5250], # 1.7h 38.5G
[ 36, 5, 1, 800, 3200, 272, 411.0, 2.9845, 7, 3.0883, 2.9845, 2.8727, 5250], # 1.7h 38.2G
[ 36, 5, 1, 800, 3200, 256, 405.5, 2.9843, 6, 2.9928, 2.9843, 3.2564, 5250], # 1.5h
[ 36, 5, 1, 800, 3200, 240, 399.9, 2.9928, 4, 2.9947, 2.9928, 3.3623, 5250], # 1.5h
[ 36, 5, 1, 800, 3200, 224, 394.4, 2.9848, 6, 3.0349, 2.9848, 3.5356, 5250], # 1.5h
[ 36, 5, 1, 800, 3200, 208, 388.9, 2.9982, 4, 2.9987, 2.9982, 3.3859, 5250], # 1.5h
[ 36, 5, 1, 800, 3200, 192, 383.4, 2.9811, 6, 2.9860,+2.9811, 3.2309, 5250], # 1.4h
[ 36, 5, 1, 800, 3200, 176, 377.8, 2.9907, 7, 2.9919, 2.9907, 3.2795, 5250], # 1.4h 36.7G
[ 36, 5, 1, 800, 3200, 160, 372.3, 2.9945, 6, 3.0021, 2.9945, 3.1224, 5250], # 1.3h

[ 36, 5, 1, 760, 3040, 288, 382.6, 2.9848, 5, 3.2036, 2.9848, 3.0373, 5250], # 1.6h
[ 36, 5, 1, 760, 3040, 272, 377.3, 2.9877, 5, 3.1112, 2.9877, 3.5230, 5250], # 1.6h
[ 36, 5, 1, 760, 3040, 256, 372.1, 2.9872, 7, 3.0478, 2.9872, 2.7221, 5250], # 1.4h
[ 36, 5, 1, 760, 3040, 240, 366.8, 2.9881, 4, 3.1267, 2.9881, 3.1103, 5250], # 1.5h
[ 36, 5, 1, 760, 3040, 224, 361.6, 2.9983, 5, 3.0696, 2.9983, 3.1425, 5250], # 1.4h
[ 36, 5, 1, 760, 3040, 208, 356.3, 3.0038, 3, 3.1103, 3.0038, 3.5960, 5250], # 1.4h
[ 36, 5, 1, 760, 3040, 192, 351.1, 2.9905, 6, 2.9947, 2.9905, 3.2470, 5250], # 1.3h 36.1G
[ 36, 5, 1, 760, 3040, 176, 345.8, 2.9929, 5, 3.1574, 2.9929, 3.2057, 5250], # 1.3h
[ 36, 5, 1, 760, 3040, 160, 340.6, 2.9905, 6, 3.1519, 2.9902, 2.7486, 5250], # 1.3h

[ 36, 5, 1, 720, 2880, 288, 350.0, 2.9823, 7, 2.9886,+2.9823, 3.2354, 5250], # 1.6h
[ 36, 5, 1, 720, 2880, 272, 345.0, 2.9844, 6, 3.1528, 2.9844, 3.2736, 5250], # 1.6h
[ 36, 5, 1, 720, 2880, 256, 340.0, 2.9858, 5, 3.0371, 2.9858, 3.2027, 5250], # 1.4h
[ 36, 5, 1, 720, 2880, 240, 335.1, 2.9852, 7, 2.9866, 2.9852, 2.7796, 5250], # 1.4h 35.8G
[ 36, 5, 1, 720, 2880, 224, 330.1, 2.9867, 7, 2.9926, 2.9867, 3.2324, 5250], # 1.4h 35.1G
[ 36, 5, 1, 720, 2880, 208, 325.1, 2.9929, 5, 3.1201, 2.9929, 3.2196, 5250], # 1.4h
[ 36, 5, 1, 720, 2880, 192, 320.1, 2.9831, 5, 3.1295,+2.9828, 2.6851, 5250], # 1.3h
[ 36, 5, 1, 720, 2880, 176, 315.2, 2.9886, 6, 2.9904, 2.9886, 3.2974, 5250], # 1.3h
[ 36, 5, 1, 720, 2880, 160, 310.2, 2.9876, 5, 3.2214, 2.9876, 2.7739, 5250], # 1.2h

[ 36, 5, 1, 680, 2720, 288, 318.8, 2.9922, 4, 3.1259, 2.9922, 3.3368, 5250], # 1.5h
[ 36, 5, 1, 680, 2720, 272, 314.1, 2.9812, 6, 3.0715,+2.9803, 2.7045, 5250], # 1.5h
# valx8: 2.9830 +- 0.0047 # torch.Tensor([2.9803, 2.9770, 2.9810, 2.9852, 2.9835, 2.9839, 2.9810, 2.9809, 2.9939]).std()
[ 36, 5, 1, 680, 2720, 256, 309.4, 2.9875, 6, 3.0885, 2.9875, 3.2908, 5250], # 1.4h 35.5G
[ 36, 5, 1, 680, 2720, 240, 304.7, 2.9831, 6, 2.9869,+2.9831, 3.2820, 5250], # 1.4h
[+36, 5, 1, 680, 2720, 224, 300.0, 2.9817, 6, 2.9888,+2.9804, 2.7221, 5250], # 1.3h  minGemma-hidden_layers36-att_heads5-kv_heads1-hidden680-intermediate2720-head_dim224-T1024--2026-06-20-18-09
# valx8: 2.9807 +- 0.0039 # torch.Tensor([2.9804, 2.9789, 2.9778, 2.9852, 2.9870, 2.9789, 2.9789, 2.9840, 2.9750]).std()
[ 36, 5, 1, 680, 2720, 208, 295.3, 2.9931, 6, 3.0004, 2.9931, 3.2792, 5250], # 1.3h
[ 36, 5, 1, 680, 2720, 192, 290.6, 2.9867, 6, 3.1459, 2.9867, 3.1568, 5250], # 1.2h
[ 36, 5, 1, 680, 2720, 176, 285.9, 2.9953, 5, 3.0562, 2.9953, 2.8896, 5250], # 1.2h
[ 36, 5, 1, 680, 2720, 160, 281.2, 2.9794, 7, 2.9959,+2.9794, 2.9687, 5250], # 1.2h  minGemma-hidden_layers36-att_heads5-kv_heads1-hidden680-intermediate2720-head_dim160-T1024--2026-06-22-15-42
# valx8: 2.9839 +- 0.0028 # torch.Tensor([2.9794, 2.9805, 2.9844, 2.9822, 2.9871, 2.9830, 2.9874, 2.9855, 2.9855]).std()

[ 36, 5, 1, 640, 2560, 288, 289.0, 2.9855, 5, 2.9855, 2.9855, 3.2698, 5250], # 1.5h
[ 36, 5, 1, 640, 2560, 272, 284.6, 2.9861, 6, 2.9928, 2.9845, 2.8133, 5250], # 1.4h 34.6G
[ 36, 5, 1, 640, 2560, 256, 280.1, 2.9885, 6, 2.9944, 2.9875, 2.7260, 5250], # 1.3h 31.5G
[ 36, 5, 1, 640, 2560, 240, 275.7, 2.9822, 6, 2.9952,+2.9815, 2.7591, 5250], # 1.3h 32.2G
[ 36, 5, 1, 640, 2560, 224, 271.3, 2.9882, 7, 3.0030, 2.9882, 2.8621, 5250], # 1.2h
[ 36, 5, 1, 640, 2560, 208, 266.9, 2.9840, 7, 2.9930, 2.9840, 2.6884, 5250], # 1.2h 30.8G
[ 36, 5, 1, 640, 2560, 192, 262.4, 2.9836, 6, 2.9978,+2.9836, 2.7500, 5250], # 1.1h
[ 36, 5, 1, 640, 2560, 176, 258.0, 2.9843, 6, 3.2067, 2.9843, 3.4475, 5250], # 1.1h
[ 36, 5, 1, 640, 2560, 160, 253.6, 2.9851, 6, 3.0003,+2.9835, 2.7571, 5250], # 1.1h

[ 36, 5, 1, 600, 2400, 288, 260.6, 2.9867, 7, 3.2333, 2.9867, 2.6997, 5250], # 1.4h
[ 36, 5, 1, 600, 2400, 272, 256.4, 2.9905, 6, 2.9981, 2.9882, 2.7555, 5250], # 1.4h
[ 36, 5, 1, 600, 2400, 256, 252.3, 2.9909, 7, 2.9940, 2.9909, 2.6778, 5250], # 1.3h
[ 36, 5, 1, 600, 2400, 240, 248.1, 2.9816, 6, 2.9881,+2.9816, 3.4039, 5250], # 1.3h
[ 36, 5, 1, 600, 2400, 224, 244.0, 2.9855, 6, 2.9917, 2.9850, 2.6647, 5250], # 1.2h 30.7G
[ 36, 5, 1, 600, 2400, 208, 239.8, 2.9881, 5, 3.1036, 2.9862, 2.7272, 5250], # 1.2h 30.3G
[ 36, 5, 1, 600, 2400, 192, 235.7, 2.9864, 5, 2.9980, 2.9864, 3.1233, 5250], # 1.1h
[ 36, 5, 1, 600, 2400, 176, 231.5, 2.9906, 6, 3.0587, 2.9881, 2.8791, 5250], # 1.1h 29.5G
[ 36, 5, 1, 600, 2400, 160, 227.4, 2.9856, 6, 3.0760, 2.9856, 2.7240, 5250], # 1.1h

[ 36, 5, 1, 560, 2240, 288, 233.5, 2.9867, 7, 2.9919, 2.9867, 2.6601, 5250], # 1.4h 30.0G
[ 36, 5, 1, 560, 2240, 272, 229.6, 2.9965, 6, 3.0043, 2.9946, 2.6743, 5250], # 1.3h
[ 36, 5, 1, 560, 2240, 256, 225.8, 2.9906, 7, 3.0013, 2.9906, 2.8880, 5250], # 1.2h 29.4G
[ 36, 5, 1, 560, 2240, 240, 221.9, 2.9874, 6, 2.9907, 2.9874, 3.2536, 5250], # 1.2h
[ 36, 5, 1, 560, 2240, 224, 218.0, 2.9911, 6, 2.9999, 2.9911, 2.7265, 5250], # 1.2h
[ 36, 5, 1, 560, 2240, 208, 214.2, 2.9875, 7, 2.9923, 2.9875, 2.6717,10500], # 1.3h
[ 36, 5, 1, 560, 2240, 192, 210.3, 2.9891, 6, 2.9947, 2.9883, 2.7899,10500], # 1.2h
[ 36, 5, 1, 560, 2240, 176, 206.4, 2.9959, 7, 3.0003, 2.9959, 2.7609,10500], # 1.2h
[ 36, 5, 1, 560, 2240, 160, 202.5, 2.9922, 6, 2.9945, 2.9922, 3.2093,10500], # 1.2h


# local best for H4(2): 2.9752 (valx8: 2.9772)
[ 36, 4, 2, 800, 3200, 288, 416.5, 2.9940, 5, 3.1358, 2.9940, 3.4339, 15750], # 2.1h 18.4G
[ 36, 4, 2, 800, 3200, 272, 411.0, 2.9808, 7, 3.3273,+2.9808, 3.2271, 15750], # 2.0h
# valx8: 2.9809 +- 0.0047 # torch.Tensor([2.9808, 2.9860, 2.9814, 2.9843, 2.9823, 2.9864, 2.9784, 2.9763, 2.9719]).std()
[ 36, 4, 2, 800, 3200, 256, 405.5, 2.9803, 6, 2.9880,+2.9803, 3.1152, 15750], # 1.9h
# valx8: 2.9824 +- 0.0025 # torch.Tensor([2.9803, 2.9808, 2.9834, 2.9871, 2.9807, 2.9824, 2.9858, 2.9815, 2.9799]).std()
[ 36, 4, 2, 800, 3200, 240, 399.9, 2.9838, 4, 3.0145, 2.9838, 3.5157, 15750], # 1.9h
[ 36, 4, 2, 800, 3200, 224, 394.4, 2.9858, 6, 2.9976, 2.9858, 3.0212, 15750], # 1.8h
[ 36, 4, 2, 800, 3200, 208, 388.9, 3.0002, 3, 3.1082, 3.0002, 3.2517, 15750], # 1.8h //3
[ 36, 4, 2, 800, 3200, 192, 383.4, 2.9930, 6, 3.0323, 2.9930, 2.8697, 10500], # 1.6h 22.1G //2
[ 36, 4, 2, 800, 3200, 176, 377.8, 2.9866, 6, 3.1102, 2.9866, 3.1513, 10500], # 1.6h
[ 36, 4, 2, 800, 3200, 160, 372.3, 3.0064, 5, 3.0186, 3.0057, 2.9201, 10500], # 1.6h

[ 36, 4, 2, 760, 3040, 288, 382.6, 2.9886, 4, 3.0892, 2.9886, 3.2141, 10500], # 1.8h 22.0G
[ 36, 4, 2, 760, 3040, 272, 377.3, 2.9832, 6, 2.9926,+2.9832, 3.3255, 10500], # 1.8h 22.2G
[ 36, 4, 2, 760, 3040, 256, 372.1, 2.9933, 6, 3.0729, 2.9933, 3.3107, 10500], # 1.6h
[ 36, 4, 2, 760, 3040, 240, 366.8, 2.9829, 6, 2.9904,+2.9829, 3.2545, 10500], # 1.6h 21.9G
[ 36, 4, 2, 760, 3040, 224, 361.6, 2.9841, 5, 3.0056, 2.9838, 2.8026, 10500], # 1.6h 21.9G
[ 36, 4, 2, 760, 3040, 208, 356.3, 2.9951, 4, 3.0112, 2.9951, 3.1339, 10500], # 1.5h
[ 36, 4, 2, 760, 3040, 192, 351.1, 2.9888, 5, 3.0332, 2.9873, 2.8803, 10500], # 1.5h
[ 36, 4, 2, 760, 3040, 176, 345.8, 2.9857, 7, 2.9914, 2.9857, 2.8928, 10500], # 1.5h
[ 36, 4, 2, 760, 3040, 160, 340.6, 3.0165, 3, 3.0288, 3.0165, 3.1657, 10500], # 1.4h 21.2G

[ 36, 4, 2, 720, 2880, 288, 350.0, 2.9874, 4, 3.0505, 2.9874, 3.2604, 10500], # 1.8h 21.6G
[ 36, 4, 2, 720, 2880, 272, 345.0, 2.9851, 7, 2.9916, 2.9851, 2.8334, 10500], # 1.7h 21.4G
[ 36, 4, 2, 720, 2880, 256, 340.0, 2.9918, 5, 3.0614, 2.9918, 3.2175, 10500], # 1.6h
[ 36, 4, 2, 720, 2880, 240, 335.1, 2.9859, 5, 3.0327, 2.9846, 2.7566, 10500], # 1.6h 21.4G
[ 36, 4, 2, 720, 2880, 224, 330.1, 2.9833, 7, 2.9902,+2.9833, 3.2482, 10500], # 1.5h
[ 36, 4, 2, 720, 2880, 208, 325.1, 2.9839, 6, 3.0299, 2.9839, 3.3654, 10500], # 1.5h
[ 36, 4, 2, 720, 2880, 192, 320.1, 2.9920, 5, 3.0362, 2.9920, 3.2292, 10500], # 1.4h
[ 36, 4, 2, 720, 2880, 176, 315.2, 2.9846, 6, 3.0793, 2.9846, 3.2800, 10500], # 1.4h 19.7G
[ 36, 4, 2, 720, 2880, 160, 310.2, 2.9904, 5, 2.9908, 2.9904, 3.1682, 10500], # 1.4h

[+36, 4, 2, 680, 2720, 288, 318.8, 2.9752, 7, 2.9871,+2.9752, 3.2428, 10500], # 1.7h  minGemma-hidden_layers36-att_heads4-kv_heads2-hidden680-intermediate2720-head_dim288-T1024--2026-07-28-01-46
# valx8: 2.9772 +- 0.0035 # torch.Tensor([2.9752, 2.9815, 2.9782, 2.9842, 2.9761, 2.9756, 2.9754, 2.9747, 2.9739]).std()
[ 36, 4, 2, 680, 2720, 272, 314.1, 2.9805, 6, 2.9832,+2.9805, 3.1118, 10500], # 1.7h
# valx8: 2.9846 +- 0.0032 # torch.Tensor([2.9805, 2.9845, 2.9838, 2.9809, 2.9871, 2.9821, 2.9889, 2.9846, 2.9891]).std()
[ 36, 4, 2, 680, 2720, 256, 309.4, 2.9790, 6, 2.9884,+2.9790, 2.9247, 10500], # 1.5h  minGemma-hidden_layers36-att_heads4-kv_heads2-hidden680-intermediate2720-head_dim256-T1024--2026-07-29-07-12
# valx8: 2.9819 +- 0.0048 # torch.Tensor([2.9790, 2.9802, 2.9906, 2.9800, 2.9842, 2.9876, 2.9761, 2.9769, 2.9826]).std()
# (2nd: 2.9793)                                                                       minGemma-hidden_layers36-att_heads4-kv_heads2-hidden680-intermediate2720-head_dim256-T1024--2026-07-29-05-11
# valx8: 2.9819 +- 0.0045 # torch.Tensor([2.9793, 2.9867, 2.9886, 2.9789, 2.9829, 2.9822, 2.9857, 2.9777, 2.9750]).std()
[ 36, 4, 2, 680, 2720, 240, 304.7, 2.9852, 6, 3.1281,+2.9835, 2.7742, 10500], # 1.5h
[ 36, 4, 2, 680, 2720, 224, 300.0, 2.9866, 5, 2.9895, 2.9866, 3.1973, 10500], # 1.5h
[ 36, 4, 2, 680, 2720, 208, 295.3, 2.9907, 7, 3.1108, 2.9907, 2.9554, 10500], # 1.5h
[ 36, 4, 2, 680, 2720, 192, 290.6, 2.9929, 7, 3.1370, 2.9929, 3.2511, 10500], # 1.4h
[ 36, 4, 2, 680, 2720, 176, 285.9, 2.9891, 7, 3.1287, 2.9891, 2.9070, 10500], # 1.4h
[ 36, 4, 2, 680, 2720, 160, 281.2, 2.9897, 7, 3.0160, 2.9897, 3.1678, 10500], # 1.3h

[ 36, 4, 2, 640, 2560, 288, 289.0, 2.9807, 6, 3.1482,+2.9799, 2.7153, 10500], # 1.6h  minGemma-hidden_layers36-att_heads4-kv_heads2-hidden640-intermediate2560-head_dim288-T1024--2026-08-02-09-32
# valx8: 2.9825 +- 0.0061 # torch.Tensor([2.9799, 2.9902, 2.9900, 2.9832, 2.9847, 2.9787, 2.9828, 2.9832, 2.9699]).std()
[ 36, 4, 2, 640, 2560, 272, 284.6, 2.9767, 7, 2.9823,+2.9767, 3.2380, 10500], # 1.5h  minGemma-hidden_layers36-att_heads4-kv_heads2-hidden640-intermediate2560-head_dim272-T1024--2026-08-03-01-38
# valx8: 2.9807 +- 0.0056 # torch.Tensor([2.9767, 2.9797, 2.9754, 2.9841, 2.9899, 2.9805, 2.9843, 2.9844, 2.9717]).std()
[ 36, 4, 2, 640, 2560, 256, 280.1, 2.9781, 7, 2.9875,+2.9781, 3.1316, 10500], # 1.4h  minGemma-hidden_layers36-att_heads4-kv_heads2-hidden640-intermediate2560-head_dim256-T1024--2026-08-03-16-49 
# valx8: 2.9812 +- 0.0034 # torch.Tensor([2.9781, 2.9825, 2.9850, 2.9809, 2.9866, 2.9806, 2.9796, 2.9823, 2.9754]).std()
# (2nd: 2.9792)                                                                       minGemma-hidden_layers36-att_heads4-kv_heads2-hidden640-intermediate2560-head_dim256-T1024--2026-08-03-14-56
# valx8: 2.9806 +- 0.0037 # torch.Tensor([2.9792, 2.9884, 2.9787, 2.9847, 2.9814, 2.9787, 2.9789, 2.9784, 2.9768]).std()
[ 36, 4, 2, 640, 2560, 240, 275.7, 2.9842, 5, 3.1073, 2.9842, 3.0693, 10500], # 1.4h
[ 36, 4, 2, 640, 2560, 224, 271.3, 2.9865, 7, 2.9873, 2.9865, 2.7329, 10500], # 1.4h
[ 36, 4, 2, 640, 2560, 208, 266.9, 2.9826, 6, 3.0486,+2.9826, 2.8972, 10500], # 1.4h
[ 36, 4, 2, 640, 2560, 192, 262.4, 2.9845, 5, 3.1357,+2.9820, 2.8383, 10500], # 1.3h 18.7G
[ 36, 4, 2, 640, 2560, 176, 258.0, 2.9857, 7, 3.0631, 2.9857, 3.3175, 10500], # 1.3h
[ 36, 4, 2, 640, 2560, 160, 253.6, 2.9921, 5, 3.1705, 2.9921, 3.2402, 10500], # 1.2h 18.2G

[ 36, 4, 2, 600, 2400, 288, 260.6, 2.9795, 7, 2.9856,+2.9795, 2.6901, 10500], # 1.6h  minGemma-hidden_layers36-att_heads4-kv_heads2-hidden600-intermediate2400-head_dim288-T1024--2026-08-07-07-54
# valx8: 2.9825 +- 0.0069 # torch.Tensor([2.9795, 2.9880, 2.9857, 2.9789, 2.9972, 2.9830, 2.9772, 2.9784, 2.9748]).std()
[ 36, 4, 2, 600, 2400, 272, 256.4, 2.9877, 6, 3.0779, 2.9877, 3.2366, 10500], # 1.5h 19.0G
[ 36, 4, 2, 600, 2400, 256, 252.3, 2.9912, 6, 2.9972, 2.9905, 2.8401, 10500], # 1.4h
[ 36, 4, 2, 600, 2400, 240, 248.1, 2.9934, 5, 3.1356, 2.9925, 2.7712, 10500], # 1.4h 18.6G

[ 36, 4, 2, 600, 2400, 224, 244.0, 2.9805, 6, 2.9843,+2.9795, 2.9249, 10500], # 1.4h  minGemma-hidden_layers36-att_heads4-kv_heads2-hidden600-intermediate2400-head_dim224-T1024--2026-08-15-02-54
# valx8: 2.9805 +- 0.0033 # torch.Tensor([2.9795, 2.9806, 2.9837, 2.9792, 2.9797, 2.9781, 2.9865, 2.9820, 2.9750]).std()
# (2nd: 2.9805)                                                                       minGemma-hidden_layers36-att_heads4-kv_heads2-hidden600-intermediate2400-head_dim224-T1024--2026-08-15-04-41
# valx8: 2.9834 +- 0.0040 # torch.Tensor([2.9805, 2.9829, 2.9848, 2.9843, 2.9914, 2.9803, 2.9842, 2.9850, 2.9769]).std()
[ 36, 4, 2, 600, 2400, 208, 239.8, 2.9895, 5, 2.9933, 2.9888, 2.7721, 10500], # 1.3h
[ 36, 4, 2, 600, 2400, 192, 235.7, 2.9833,10, 2.9843,+2.9833, 2.7684, 10500], # 1.3h
[ 36, 4, 2, 600, 2400, 176, 231.5, 2.9869, 6, 2.9924, 2.9869, 2.9206, 10500], # 1.3h
[ 36, 4, 2, 600, 2400, 160, 227.4, 2.9881, 6, 3.1318, 2.9881, 2.8416, 10500], # 1.2h

[ 36, 4, 2, 560, 2240, 288, 233.5, 2.9829, 7, 2.9886,+2.9829, 2.7343, 10500], # 1.4h 18.2G
[ 36, 4, 2, 560, 2240, 272, 229.6, 2.9900, 7, 3.1858, 2.9900, 2.6785, 10500], # 1.4h 17.9G
[ 36, 4, 2, 560, 2240, 256, 225.8, 2.9881, 6, 3.0092, 2.9881, 2.8105, 10500], # 1.3h
[ 36, 4, 2, 560, 2240, 240, 221.9, 2.9932, 6, 2.9997, 2.9932, 2.8392, 10500], # 1.3h
[ 36, 4, 2, 560, 2240, 224, 218.0, 2.9912, 5, 2.9914, 2.9898, 2.6913, 10500], # 1.3h
[ 36, 4, 2, 560, 2240, 208, 214.2, 2.9911, 6, 2.9971, 2.9909, 2.6965, 10500], # 1.2h
[ 36, 4, 2, 560, 2240, 192, 210.3, 2.9922, 5, 2.9966, 2.9918, 2.7103, 10500], # 1.2h
[ 36, 4, 2, 560, 2240, 176, 206.4, 2.9920, 6, 3.0014, 2.9914, 2.7035, 10500], # 1.2h
[ 36, 4, 2, 560, 2240, 160, 202.5, 3.0009, 6, 3.0100, 3.0009, 2.9947, 10500], # 1.1h


# local best for H3(1): 2.9797 (valx8: 2.9820)
[ 36, 3, 1, 768, 3072, 288, 357.4, 2.9978, 4, 3.1309, 2.9978, 3.0172, 21000], # 1.3h 14.1G
[ 36, 3, 1, 768, 3072, 272, 353.9, 2.9897, 6, 2.9986, 2.9897, 3.1518, 21000], # 1.3h
[ 36, 3, 1, 768, 3072, 256, 350.3, 2.9890, 5, 2.9951, 2.9890, 3.3501, 21000], # 1.2h
[ 36, 3, 1, 768, 3072, 240, 346.8, 2.9934, 4, 2.9972, 2.9934, 2.9620, 21000], # 1.2h
[ 36, 3, 1, 768, 3072, 224, 343.3, 2.9930, 5, 3.0019, 2.9930, 2.9005, 21000], # 1.1h
[ 36, 3, 1, 768, 3072, 208, 339.7, 2.9968, 5, 3.0039, 2.9968, 3.1819, 21000], # 1.1h
[ 36, 3, 1, 768, 3072, 192, 336.2, 2.9954, 5, 3.0340, 2.9954, 2.9943, 21000], # 1.1h
[ 36, 3, 1, 768, 3072, 176, 332.6, 3.0155, 5, 3.0671, 3.0155, 3.3489, 21000], # 1.1h
[ 36, 3, 1, 768, 3072, 160, 329.1, 2.9987, 6, 3.1231, 2.9987, 3.5268, 21000], # 1.0h

[ 36, 3, 1, 720, 2880, 288, 320.1, 2.9930, 7, 2.9974, 2.9930, 3.2461, 21000], # 1.2h
[ 36, 3, 1, 720, 2880, 272, 316.8, 2.9853, 7, 3.1690, 2.9853, 3.3079, 21000], # 1.2h
[ 36, 3, 1, 720, 2880, 256, 313.5, 2.9842, 7, 3.0008, 2.9842, 2.8784, 21000], # 1.2h
[ 36, 3, 1, 720, 2880, 240, 310.2, 2.9930, 6, 3.1301, 2.9930, 3.2510, 21000], # 1.1h
[ 36, 3, 1, 720, 2880, 224, 306.9, 2.9901, 7, 3.0991, 2.9901, 2.8161, 21000], # 1.1h
[ 36, 3, 1, 720, 2880, 208, 303.6, 2.9954, 6, 3.1920, 2.9954, 2.9093, 21000], # 1.1h 13.2G
[ 36, 3, 1, 720, 2880, 192, 300.2, 3.0007, 4, 3.0814, 3.0007, 3.4406, 21000], # 1.1h
[ 36, 3, 1, 720, 2880, 176, 296.9, 2.9997, 7, 3.1487, 2.9997, 2.8664, 21000], # 1.0h
[ 36, 3, 1, 720, 2880, 160, 293.6, 3.0199, 3, 3.0314, 3.0199, 3.4616, 21000], # 1.0h

[ 36, 3, 1, 672, 2688, 288, 284.9, 2.9864, 7, 3.0032, 2.9864, 3.1547, 21000], # 1.2h 12.5G
[ 36, 3, 1, 672, 2688, 272, 281.8, 2.9854, 5, 2.9882, 2.9854, 2.9739, 21000], # 1.2h 12.4G
[ 36, 3, 1, 672, 2688, 256, 278.7, 2.9993, 5, 3.0054, 2.9993, 3.1356, 21000], # 1.1h
[ 36, 3, 1, 672, 2688, 240, 275.6, 2.9820, 7, 3.0522,+2.9820, 3.2226, 21000], # 1.1h
[ 36, 3, 1, 672, 2688, 224, 272.5, 2.9936, 5, 3.1284, 2.9936, 3.0018, 21000], # 1.1h 12.4G
[ 36, 3, 1, 672, 2688, 208, 269.4, 2.9858, 6, 2.9995, 2.9858, 2.8879, 21000], # 1.1h
[ 36, 3, 1, 672, 2688, 192, 266.3, 2.9840, 7, 3.0866, 2.9840, 2.7607, 21000], # 1.0h 12.4G
[ 36, 3, 1, 672, 2688, 176, 263.2, 2.9946, 7, 3.1252, 2.9946, 2.8257, 21000], # 1.0h
[ 36, 3, 1, 672, 2688, 160, 260.1, 2.9849, 7, 3.0851, 2.9849, 3.4258, 21000], # 1.0h

[ 36, 3, 1, 624, 2496, 288, 251.6, 2.9885, 7, 3.2303, 2.9885, 2.9540, 21000], # 1.1h
[+36, 3, 1, 624, 2496, 272, 248.7, 2.9797, 6, 2.9916,+2.9797, 2.8054, 21000], # 1.1h  minGemma-hidden_layers36-att_heads3-kv_heads1-hidden624-intermediate2496-head_dim272-T1024--2026-08-09-09-41
# valx8: 2.9820 +- 0.0056 # torch.Tensor([2.9797, 2.9880, 2.9824, 2.9821, 2.9890, 2.9786, 2.9886, 2.9748, 2.9745]).std()
[ 36, 3, 1, 624, 2496, 256, 245.8, 2.9799, 6, 2.9841,+2.9799, 3.1643, 21000], # 1.1h  minGemma-hidden_layers36-att_heads3-kv_heads1-hidden624-intermediate2496-head_dim256-T1024--2026-08-09-19-40
# valx8: 2.9821 +- 0.0033 # torch.Tensor([2.9799, 2.9841, 2.9826, 2.9789, 2.9830, 2.9892, 2.9796, 2.9789, 2.9826]).std()
[ 36, 3, 1, 624, 2496, 240, 242.9, 2.9923, 6, 3.0029, 2.9908, 2.8171, 21000], # 1.1h
[ 36, 3, 1, 624, 2496, 224, 240.1, 2.9974, 6, 3.1313, 2.9974, 3.5739, 21000], # 1.0h 11.5G
[ 36, 3, 1, 624, 2496, 208, 237.2, 2.9848, 6, 3.3452, 2.9844, 2.7516, 21000], # 1.0h
[ 36, 3, 1, 624, 2496, 192, 234.3, 2.9887, 7, 3.0141, 2.9887, 2.8371, 21000], # 1.0h
[ 36, 3, 1, 624, 2496, 176, 231.4, 2.9928, 7, 3.0890, 2.9928, 2.8635, 21000], # 1.0h
[ 36, 3, 1, 624, 2496, 160, 228.6, 2.9968, 6, 3.1488, 2.9968, 3.3752, 21000], # 0.9h

[ 36, 3, 1, 576, 2304, 288, 220.3, 2.9830, 7, 2.9878,+2.9830, 2.8091, 21000], # 1.1h
[ 36, 3, 1, 576, 2304, 272, 217.6, 2.9827, 6, 2.9913,+2.9823, 2.6870, 21000], # 1.1h
[ 36, 3, 1, 576, 2304, 256, 215.0, 2.9886, 7, 2.9997, 2.9886, 2.6695, 21000], # 1.0h
[ 36, 3, 1, 576, 2304, 240, 212.3, 2.9889, 5, 2.9917, 2.9883, 2.6960, 21000], # 1.0h
[ 36, 3, 1, 576, 2304, 224, 209.7, 2.9818, 6, 3.0066,+2.9818, 3.1702, 21000], # 1.0h
[ 36, 3, 1, 576, 2304, 208, 207.0, 2.9875, 7, 2.9916, 2.9875, 3.3299, 21000], # 1.0h
[ 36, 3, 1, 576, 2304, 192, 204.4, 2.9963, 4, 3.1193, 2.9963, 3.0065, 21000], # 0.9h
[ 36, 3, 1, 576, 2304, 176, 201.7, 2.9963, 6, 3.0949, 2.9963, 3.1421, 21000], # 0.9h
[ 36, 3, 1, 576, 2304, 160, 199.0, 3.0003, 4, 3.1183, 3.0003, 3.3280, 21000], # 0.9h

In [32]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  36 # 8 # G28 G18 #blocks
num_attention_heads = 5 # 4 # G16 G8
num_key_value_heads = 1 # 4 # G16 G1
hidden_size = num_attention_heads*136 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 224 # 32 # G256 # dim in attention
rms_norm_eps = 1e0 # 1e-6
rope_theta = 80000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//1; N_step=5250*1; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=1, learning_rate=10.0e-4, weight_decay=1.8, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//1 # Evaluation follows
    for k in range(5000*1 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9837:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

64.512
L36 att5 kv_heads1 hidden680 intermediate2720 head_dim224 T1024

1 4.5625625 tensor(3.2496)

2 2.812443824404762 tensor(3.0140)

3 2.8472087053571427 tensor(2.9949)

4 2.717231212797619 tensor(2.9842)

5 2.6980563616071427 tensor(2.9804)

6 2.722095796130952 tensor(2.9817)

7 2.727044456845238 tensor(2.9888)
[ 36, 5, 1, 680, 2720, 224, 300.0, 2.9817, 6, 2.9888, 2.9804, 2.7221, 5250],

In [36]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  36 # 8 # G28 G18 #blocks
num_attention_heads = 5 # 4 # G16 G8
num_key_value_heads = 1 # 4 # G16 G1
hidden_size = num_attention_heads*136 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 160 # 32 # G256 # dim in attention
rms_norm_eps = 1e0 # 1e-6
rope_theta = 80000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//1; N_step=5250*1; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=1, learning_rate=10.0e-4, weight_decay=1.8, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//1 # Evaluation follows
    for k in range(5000*1 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9837:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

64.512
L36 att5 kv_heads1 hidden680 intermediate2720 head_dim160 T1024

1 4.615935267857143 tensor(3.2416)

2 2.8082862723214284 tensor(3.0149)

3 2.7248065476190475 tensor(2.9896)

4 2.714743675595238 tensor(2.9818)

5 3.194021577380952 tensor(3.0841)
back to previous

6 2.739475818452381 tensor(2.9794)

7 2.968667782738095 tensor(3.0221)
back to previous

8 2.8307083333333334 tensor(2.9959)
[ 36, 5, 1, 680, 2720, 160, 281.2, 2.9794, 7, 2.9959, 2.9794, 2.9687, 5250],

In [19]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  36 # 8 # G28 G18 #blocks
num_attention_heads = 4 # 4 # G16 G8
num_key_value_heads = 2 # 4 # G16 G1
hidden_size = num_attention_heads*170 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 288 # 32 # G256 # dim in attention
rms_norm_eps = 1e0 # 1e-6
rope_theta = 80000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//2; N_step=5250*2; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=10.0e-4, weight_decay=1.8, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(5000*2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9837:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

64.512
L36 att4 kv_heads2 hidden680 intermediate2720 head_dim288 T1024

1 4.558604538690476 tensor(3.2300)

2 2.8154771205357143 tensor(3.0115)

3 2.7431223958333333 tensor(2.9872)

4 2.9350158110119047 tensor(2.9834)

5 3.321980282738095 tensor(3.1358)
back to previous

6 2.6903240327380953 tensor(2.9752)

7 3.2428050595238096 tensor(3.1191)
back to previous

8 2.9874142485119046 tensor(2.9871)
[ 36, 4, 2, 680, 2720, 288, 318.8, 2.9752, 7, 2.9871, 2.9752, 3.2428, 10500],

In [21]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  36 # 8 # G28 G18 #blocks
num_attention_heads = 4 # 4 # G16 G8
num_key_value_heads = 2 # 4 # G16 G1
hidden_size = num_attention_heads*170 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 256 # 32 # G256 # dim in attention
rms_norm_eps = 1e0 # 1e-6
rope_theta = 80000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//2; N_step=5250*2; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=10.0e-4, weight_decay=1.8, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(5000*2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9837:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

64.512
L36 att4 kv_heads2 hidden680 intermediate2720 head_dim256 T1024

1 4.6010647321428575 tensor(3.2522)

2 2.9394123883928573 tensor(3.0179)

3 2.998633556547619 tensor(2.9971)

4 2.7692025669642857 tensor(2.9793)

5 2.8014322916666665 tensor(2.9790)

6 2.9246910342261905 tensor(2.9891)
back to previous

7 2.763712425595238 tensor(2.9884)
[ 36, 4, 2, 680, 2720, 256, 309.4, 2.9790, 6, 2.9884, 2.9790, 2.9247, 10500],

In [28]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  36 # 8 # G28 G18 #blocks
num_attention_heads = 4 # 4 # G16 G8
num_key_value_heads = 2 # 4 # G16 G1
hidden_size = num_attention_heads*160 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 288 # 32 # G256 # dim in attention
rms_norm_eps = 1e0 # 1e-6
rope_theta = 80000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//2; N_step=5250*2; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=10.0e-4, weight_decay=1.8, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(5000*2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9837:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

64.512
L36 att4 kv_heads2 hidden640 intermediate2560 head_dim288 T1024

1 4.490627604166667 tensor(3.2063)

2 2.811037388392857 tensor(3.0095)

3 2.800360863095238 tensor(2.9913)

4 2.73206640625 tensor(2.9824)

5 2.6830894717261904 tensor(2.9799)

6 2.71534765625 tensor(2.9807)

7 3.2470907738095236 tensor(3.1482)
[ 36, 4, 2, 640, 2560, 288, 289.0, 2.9807, 6, 3.1482, 2.9799, 2.7153, 10500],

In [29]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  36 # 8 # G28 G18 #blocks
num_attention_heads = 4 # 4 # G16 G8
num_key_value_heads = 2 # 4 # G16 G1
hidden_size = num_attention_heads*160 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 272 # 32 # G256 # dim in attention
rms_norm_eps = 1e0 # 1e-6
rope_theta = 80000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//2; N_step=5250*2; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=10.0e-4, weight_decay=1.8, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(5000*2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9837:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

64.512
L36 att4 kv_heads2 hidden640 intermediate2560 head_dim272 T1024

1 4.523178571428572 tensor(3.2438)

2 2.8138359375 tensor(3.0130)

3 2.716571056547619 tensor(2.9861)

4 2.695174851190476 tensor(2.9805)

5 3.1090610119047617 tensor(3.0519)
back to previous

6 2.994471168154762 tensor(2.9767)

7 3.238005580357143 tensor(3.1333)
back to previous

8 2.7099588913690478 tensor(2.9823)
[ 36, 4, 2, 640, 2560, 272, 284.6, 2.9767, 7, 2.9823, 2.9767, 3.2380, 10500],

In [30]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  36 # 8 # G28 G18 #blocks
num_attention_heads = 4 # 4 # G16 G8
num_key_value_heads = 2 # 4 # G16 G1
hidden_size = num_attention_heads*160 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 256 # 32 # G256 # dim in attention
rms_norm_eps = 1e0 # 1e-6
rope_theta = 80000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//2; N_step=5250*2; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=10.0e-4, weight_decay=1.8, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(5000*2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9837:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

64.512
L36 att4 kv_heads2 hidden640 intermediate2560 head_dim256 T1024

1 4.492000372023809 tensor(3.2258)

2 2.8243768601190475 tensor(3.0143)

3 2.719653831845238 tensor(2.9879)

4 2.7186746651785714 tensor(2.9831)

5 2.6943686755952383 tensor(2.9792)

6 2.678878720238095 tensor(2.9781)

7 3.1315840773809525 tensor(3.0728)
back to previous

8 2.7998852306547617 tensor(2.9875)
[ 36, 4, 2, 640, 2560, 256, 280.1, 2.9781, 7, 2.9875, 2.9781, 3.1316, 10500],

In [37]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  36 # 8 # G28 G18 #blocks
num_attention_heads = 4 # 4 # G16 G8
num_key_value_heads = 2 # 4 # G16 G1
hidden_size = num_attention_heads*150 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 288 # 32 # G256 # dim in attention
rms_norm_eps = 1e0 # 1e-6
rope_theta = 80000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//2; N_step=5250*2; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=10.0e-4, weight_decay=1.8, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(5000*2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9837:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

64.512
L36 att4 kv_heads2 hidden600 intermediate2400 head_dim288 T1024

1 4.478328497023809 tensor(3.2045)

2 2.804287574404762 tensor(3.0063)

3 2.725678943452381 tensor(2.9861)

4 2.7175572916666666 tensor(2.9834)

5 2.872192336309524 tensor(2.9835)

6 2.680510230654762 tensor(2.9795)

7 2.6901197916666666 tensor(2.9872)
back to previous

8 2.6671078869047617 tensor(2.9856)
[ 36, 4, 2, 600, 2400, 288, 260.6, 2.9795, 7, 2.9856, 2.9795, 2.6901, 10500],

In [11]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  36 # 8 # G28 G18 #blocks
num_attention_heads = 4 # 4 # G16 G8
num_key_value_heads = 2 # 4 # G16 G1
hidden_size = num_attention_heads*150 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 224 # 32 # G256 # dim in attention
rms_norm_eps = 1e0 # 1e-6
rope_theta = 80000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//2; N_step=5250*2; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=10.0e-4, weight_decay=1.8, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(5000*2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9837:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

64.512
L36 att4 kv_heads2 hidden600 intermediate2400 head_dim224 T1024

1 4.517818452380952 tensor(3.2526)

2 2.827584077380952 tensor(3.0179)

3 2.9616947544642858 tensor(2.9988)

4 2.7587427455357143 tensor(2.9846)

5 2.6977723214285714 tensor(2.9795)

6 2.9248699776785716 tensor(2.9805)

7 2.7643292410714286 tensor(2.9843)
[ 36, 4, 2, 600, 2400, 224, 244.0, 2.9805, 6, 2.9843, 2.9795, 2.9249, 10500],

In [29]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  36 # 8 # G28 G18 #blocks
num_attention_heads = 3 # 4 # G16 G8
num_key_value_heads = 1 # 4 # G16 G1
hidden_size = num_attention_heads*208 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 272 # 32 # G256 # dim in attention
rms_norm_eps = 1e0 # 1e-6
rope_theta = 80000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//4; N_step=5250*4; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=4, learning_rate=10.0e-4, weight_decay=1.8, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//4 # Evaluation follows
    for k in range(5000*4 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9837:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

64.512
L36 att3 kv_heads1 hidden624 intermediate2496 head_dim272 T1024

1 4.515787202380952 tensor(3.2134)

2 2.8089388020833335 tensor(3.0095)

3 2.7196123511904764 tensor(2.9864)

4 2.812158110119048 tensor(2.9938)
back to previous

5 2.72019140625 tensor(2.9797)

6 2.8053677455357144 tensor(2.9855)
back to previous

7 2.795483072916667 tensor(2.9916)
[ 36, 3, 1, 624, 2496, 272, 248.7, 2.9797, 6, 2.9916, 2.9797, 2.8054, 21000],

In [30]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  36 # 8 # G28 G18 #blocks
num_attention_heads = 3 # 4 # G16 G8
num_key_value_heads = 1 # 4 # G16 G1
hidden_size = num_attention_heads*208 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 256 # 32 # G256 # dim in attention
rms_norm_eps = 1e0 # 1e-6
rope_theta = 80000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//4; N_step=5250*4; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=4, learning_rate=10.0e-4, weight_decay=1.8, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//4 # Evaluation follows
    for k in range(5000*4 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9837:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

64.512
L36 att3 kv_heads1 hidden624 intermediate2496 head_dim256 T1024

1 4.5242406994047615 tensor(3.2207)

2 2.811781063988095 tensor(3.0198)

3 2.7355811011904763 tensor(2.9924)

4 3.325088913690476 tensor(3.1615)
back to previous

5 2.8020595238095236 tensor(2.9799)

6 3.1642712053571427 tensor(3.0647)
back to previous

7 2.6748528645833334 tensor(2.9841)
[ 36, 3, 1, 624, 2496, 256, 245.8, 2.9799, 6, 2.9841, 2.9799, 3.1643, 21000],

# L30

In [ ]:
# L30 FORGETTER T1024 Baby10M (default: B12//2 N5250 lr10e-4 WD1.8) # H6(3): 2.9780, H5(1): 2.9836, H4(2): 2.9790

# local best for H6(3): 2.9769 (valx8: 2.9780)
[ 30, 6, 3, 792, 3168, 288, 389.1, 2.9888, 4, 3.0125, 2.9888, 3.0024, 10500], # 1.0h 22.7G
[+30, 6, 3, 792, 3168, 272, 382.2, 2.9769, 6, 2.9855,+2.9769, 3.0560, 10500], # 0.9h  minGemma-hidden_layers30-att_heads6-kv_heads3-hidden792-intermediate3168-head_dim272-T1024--2026-04-15-03-13
# valx8: 2.9794 +- 0.0030 # torch.Tensor([2.9769, 2.9852, 2.9765, 2.9774, 2.9801, 2.9771, 2.9797, 2.9828, 2.9787]).std()
[ 30, 6, 3, 792, 3168, 256, 375.4, 2.9804, 7, 3.1308,+2.9804, 3.2003, 10500], # 0.9h
# valx8: 2.9868 +- 0.0058 # torch.Tensor([2.9804, 2.9923, 2.9916, 2.9892, 2.9874, 2.9809, 2.9842, 2.9956, 2.9797]).std()
[ 30, 6, 3, 792, 3168, 240, 368.5, 2.9794, 7, 3.0363,+2.9794, 2.6982, 10500], # 0.9h
# valx8: 2.9820 +- 0.0031 # torch.Tensor([2.9794, 2.9810, 2.9844, 2.9813, 2.9821, 2.9814, 2.9891, 2.9802, 2.9793]).std()
[ 30, 6, 3, 792, 3168, 224, 361.7, 2.9858, 6, 3.1267, 2.9858, 2.9084, 10500], # 0.8h
[ 30, 6, 3, 792, 3168, 208, 354.8, 2.9882, 9, 3.1320, 2.9882, 3.1681, 10500], # 0.8h 21.0G
[ 30, 6, 3, 792, 3168, 192, 348.0, 2.9915, 6, 2.9986, 2.9893, 2.7385, 10500], # 0.8h
[ 30, 6, 3, 792, 3168, 176, 341.2, 2.9877, 7, 3.0745, 2.9877, 3.0992, 10500], # 0.8h
[ 30, 6, 3, 792, 3168, 160, 334.3, 2.9854, 6, 2.9955, 2.9854, 3.4775, 10500], # 0.7h

[ 30, 6, 3, 744, 2976, 288, 352.6, 2.9895, 6, 2.9939, 2.9895, 3.2092, 10500], # 0.9h
[ 30, 6, 3, 744, 2976, 272, 346.2, 2.9852, 5, 2.9955, 2.9852, 2.8714, 10500], # 0.9h
[+30, 6, 3, 744, 2976, 256, 339.8, 2.9782, 7, 2.9813,+2.9782, 3.0839, 10500], # 0.8h  minGemma-hidden_layers30-att_heads6-kv_heads3-hidden744-intermediate2976-head_dim256-T1024--2026-04-18-18-41
# valx8: 2.9780 +- 0.0040 # torch.Tensor([2.9782, 2.9751, 2.9827, 2.9829, 2.9714, 2.9798, 2.9788, 2.9800, 2.9734]).std()
# (2nd: 2.9793)                                                                       minGemma-hidden_layers30-att_heads6-kv_heads3-hidden744-intermediate2976-head_dim256-T1024--2026-04-18-17-34
# valx8: 2.9832 +- 0.0042 # torch.Tensor([2.9793, 2.9818, 2.9832, 2.9823, 2.9911, 2.9848, 2.9878, 2.9818, 2.9771]).std()
[ 30, 6, 3, 744, 2976, 240, 333.3, 2.9860, 7, 2.9912, 2.9860, 2.6800, 10500], # 0.8h
[ 30, 6, 3, 744, 2976, 224, 326.9, 2.9833, 9, 3.0101,+2.9833, 3.2593, 10500], # 0.8h
[ 30, 6, 3, 744, 2976, 208, 320.5, 2.9817, 7, 2.9834,+2.9817, 3.2399, 10500], # 0.8h
[ 30, 6, 3, 744, 2976, 192, 314.0, 2.9827, 6, 2.9893,+2.9827, 3.2119, 10500], # 0.7h
[ 30, 6, 3, 744, 2976, 176, 307.6, 2.9850, 6, 3.1020,+2.9833, 2.8330, 10500], # 0.7h
[ 30, 6, 3, 744, 2976, 160, 301.2, 2.9876, 6, 3.1468, 2.9876, 2.8099, 10500], # 0.7h 19.0G

[ 30, 6, 3, 696, 2784, 288, 317.8, 2.9838, 6, 2.9902, 2.9838, 3.1552, 10500], # 0.9h
[ 30, 6, 3, 696, 2784, 272, 311.8, 2.9847,11, 3.1221, 2.9842, 2.8827, 10500], # 0.9h 2.9837
[ 30, 6, 3, 696, 2784, 256, 305.8, 2.9831, 6, 3.1904,+2.9831, 3.2081, 10500], # 0.8h
[ 30, 6, 3, 696, 2784, 240, 299.8, 2.9811,10, 2.9863,+2.9811, 3.1476, 10500], # 0.8h
[ 30, 6, 3, 696, 2784, 224, 293.8, 2.9902, 8, 2.9907, 2.9881, 2.7939, 10500], # 0.8h
[ 30, 6, 3, 696, 2784, 208, 287.8, 2.9824, 6, 3.1299,+2.9800, 2.7686, 10500], # 0.7h
# valx8: 2.9824 +- 0.0057 # torch.Tensor([2.9800, 2.9867, 2.9860, 2.9899, 2.9809, 2.9854, 2.9851, 2.9745, 2.9733]).std()
[ 30, 6, 3, 696, 2784, 192, 281.8, 2.9844, 7, 2.9917, 2.9844, 3.2374, 10500], # 0.7h
[ 30, 6, 3, 696, 2784, 176, 275.7, 2.9889, 7, 2.9929, 2.9889, 3.2209, 10500], # 0.7h
[ 30, 6, 3, 696, 2784, 160, 269.7, 2.9827,10, 3.1143,+2.9826, 2.8187, 10500], # 0.7h

[ 30, 6, 3, 648, 2592, 288, 284.7, 2.9807, 6, 2.9880,+2.9807, 2.9238, 10500], # 0.8h
# valx8: 2.9834 +- 0.0027 # torch.Tensor([2.9807, 2.9818, 2.9839, 2.9845, 2.9844, 2.9826, 2.9823, 2.9896, 2.9811]).std()
[ 30, 6, 3, 648, 2592, 272, 279.1, 2.9874, 6, 3.1295, 2.9874, 3.2163, 10500], # 0.8h
[ 30, 6, 3, 648, 2592, 256, 273.5, 2.9867, 7, 3.1112, 2.9867, 3.1507, 10500], # 0.8h
[ 30, 6, 3, 648, 2592, 240, 267.9, 2.9833, 7, 3.1693,+2.9833, 3.1607, 10500], # 0.7h
[ 30, 6, 3, 648, 2592, 224, 262.3, 2.9870, 6, 2.9887, 2.9870, 2.8094, 10500], # 0.7h
[ 30, 6, 3, 648, 2592, 208, 256.7, 2.9856, 7, 3.2954, 2.9839, 2.7190, 10500], # 0.7h
[ 30, 6, 3, 648, 2592, 192, 251.1, 2.9890, 6, 2.9931, 2.9886, 2.7098, 10500], # 0.7h
[ 30, 6, 3, 648, 2592, 176, 245.5, 2.9864, 7, 2.9892, 2.9864, 3.2883, 10500], # 0.7h
[ 30, 6, 3, 648, 2592, 160, 239.9, 2.9863, 7, 3.1227, 2.9863, 3.2346, 10500], # 0.6h

[ 30, 6, 3, 600, 2400, 288, 253.3, 2.9855, 5, 2.9861, 2.9852, 2.6730, 10500], # 0.8h
[ 30, 6, 3, 600, 2400, 272, 248.1, 2.9840, 6, 2.9892, 2.9840, 3.6154, 10500], # 0.8h
[ 30, 6, 3, 600, 2400, 256, 242.9, 2.9866, 6, 2.9950, 2.9866, 2.6775, 10500], # 0.7h
[ 30, 6, 3, 600, 2400, 240, 237.7, 2.9849, 6, 2.9892, 2.9849, 2.9445, 10500], # 0.7h
[ 30, 6, 3, 600, 2400, 224, 232.5, 2.9835, 6, 2.9885,+2.9835, 2.7063, 10500], # 0.7h
[ 30, 6, 3, 600, 2400, 208, 227.3, 2.9890, 6, 2.9908, 2.9890, 3.1822, 10500], # 0.7h
[ 30, 6, 3, 600, 2400, 192, 222.2, 2.9856, 6, 3.0781, 2.9856, 3.0117, 10500], # 0.6h
[ 30, 6, 3, 600, 2400, 176, 217.0, 2.9946, 4, 2.9952, 2.9923, 2.7009, 10500], # 0.6h
[ 30, 6, 3, 600, 2400, 160, 211.8, 2.9896, 6, 2.9901, 2.9896, 3.2348, 10500], # 0.6h 16.0G

[ 30, 6, 3, 552, 2208, 288, 223.5, 2.9900, 6, 2.9965, 2.9900, 2.8286, 10500], # 0.8h
[ 30, 6, 3, 552, 2208, 272, 218.7, 2.9978, 5, 3.0024, 2.9961, 2.6960, 10500], # 0.7h
[ 30, 6, 3, 552, 2208, 256, 213.9, 2.9804, 6, 3.1317,+2.9804, 2.7181, 10500], # 0.7h
# valx8: 2.9833 +- 0.0043 # torch.Tensor([2.9804, 2.9833, 2.9860, 2.9778, 2.9829, 2.9908, 2.9846, 2.9862, 2.9775]).std()
[ 30, 6, 3, 552, 2208, 240, 209.2, 2.9891, 6, 2.9941, 2.9889, 2.6660, 10500], # 0.7h
[ 30, 6, 3, 552, 2208, 224, 204.4, 2.9962, 6, 3.0006, 2.9952, 2.6862, 10500], # 0.7h
[ 30, 6, 3, 552, 2208, 208, 199.6, 2.9881, 6, 2.9909, 2.9861, 2.6669, 10500], # 0.6h
[ 30, 6, 3, 552, 2208, 192, 194.8, 2.9908, 7, 2.9929, 2.9908, 2.6541, 10500], # 0.6h 16.4G
[ 30, 6, 3, 552, 2208, 176, 190.1, 2.9879, 6, 3.0860, 2.9862, 2.6765, 10500], # 0.6h
[ 30, 6, 3, 552, 2208, 160, 185.3, 2.9926, 7, 2.9947, 2.9926, 2.6658, 10500], # 0.6h


# local best for H5(1): 2.9803 (valx8: 2.9836)
[ 30, 5, 1, 800, 3200, 288, 353.8, 2.9884, 6, 2.9960, 2.9884, 3.0163, 10500], # 0.8h 21.3G
[ 30, 5, 1, 800, 3200, 272, 349.2, 2.9945, 4, 2.9978, 2.9943, 2.7044, 10500], # 0.8h
[ 30, 5, 1, 800, 3200, 256, 344.6, 2.9876, 7, 3.0332, 2.9876, 2.7162, 10500], # 0.8h
[ 30, 5, 1, 800, 3200, 240, 340.0, 2.9978, 6, 3.1302, 2.9978, 3.2162, 10500], # 0.8h
[ 30, 5, 1, 800, 3200, 224, 335.4, 2.9929, 8, 3.0511, 2.9929, 3.2296, 10500], # 0.7h
[ 30, 5, 1, 800, 3200, 208, 330.8, 2.9914, 6, 3.0053, 2.9914, 3.2369, 10500], # 0.7h
[ 30, 5, 1, 800, 3200, 192, 326.2, 3.0174, 3, 3.0310, 3.0174, 3.4067, 10500], # 0.7h
[ 30, 5, 1, 800, 3200, 176, 321.6, 2.9921, 5, 3.2120, 2.9921, 3.3185, 10500], # 0.7h
[ 30, 5, 1, 800, 3200, 160, 317.0, 3.0009, 6, 3.0922, 3.0009, 2.8481, 10500], # 0.7h

[ 30, 5, 1, 760, 3040, 288, 325.2, 2.9868, 6, 3.0615, 2.9868, 2.7798, 10500], # 0.8h
[ 30, 5, 1, 760, 3040, 272, 320.8, 2.9882, 6, 3.1392, 2.9866, 2.9874, 10500], # 0.8h
[ 30, 5, 1, 760, 3040, 256, 316.4, 2.9878, 7, 3.0010, 2.9878, 2.7819, 10500], # 0.8h
[ 30, 5, 1, 760, 3040, 240, 312.0, 2.9881,11, 3.1219, 2.9881, 2.8729, 10500], # 0.8h
[ 30, 5, 1, 760, 3040, 224, 307.7, 2.9805, 7, 2.9977,+2.9805, 2.8926, 10500], # 0.7h
# valx8: 2.9842 +- 0.0051 # torch.Tensor([2.9805, 2.9848, 2.9873, 2.9803, 2.9825, 2.9796, 2.9802, 2.9948, 2.9878]).std()
[ 30, 5, 1, 760, 3040, 208, 303.3, 2.9979, 6, 3.1905, 2.9979, 2.8403, 10500], # 0.7h
[ 30, 5, 1, 760, 3040, 192, 298.9, 2.9873, 7, 3.1264, 2.9873, 3.4043, 10500], # 0.7h
[ 30, 5, 1, 760, 3040, 176, 294.5, 2.9905, 7, 2.9925, 2.9905, 3.0777, 10500], # 0.7h 18.7G
[ 30, 5, 1, 760, 3040, 160, 290.2, 2.9945, 5, 3.0116, 2.9945, 3.1753, 10500], # 0.7h 18.5G

[ 30, 5, 1, 720, 2880, 288, 297.7, 2.9925, 7, 3.4571, 2.9925, 2.9245, 10500], # 0.8h
[ 30, 5, 1, 720, 2880, 272, 293.5, 2.9893, 6, 3.4831, 2.9893, 3.1154, 10500], # 0.8h
[ 30, 5, 1, 720, 2880, 256, 289.4, 2.9877, 6, 3.0285, 2.9870, 2.8112, 10500], # 0.7h 18.7G
[ 30, 5, 1, 720, 2880, 240, 285.3, 2.9882, 6, 2.9883, 2.9882, 3.3262, 10500], # 0.7h
[ 30, 5, 1, 720, 2880, 224, 281.1, 2.9905, 7, 2.9920, 2.9905, 2.9424, 10500], # 0.7h
[ 30, 5, 1, 720, 2880, 208, 277.0, 2.9897,10, 2.9953, 2.9897, 3.2583, 10500], # 0.7h
[ 30, 5, 1, 720, 2880, 192, 272.8, 2.9846, 7, 2.9881, 2.9846, 2.7608, 10500], # 0.6h
[ 30, 5, 1, 720, 2880, 176, 268.7, 2.9816, 7, 2.9823,+2.9816, 2.6981, 10500], # 0.6h
[ 30, 5, 1, 720, 2880, 160, 264.5, 2.9941, 7, 3.0865, 2.9941, 2.7611, 10500], # 0.6h

[ 30, 5, 1, 680, 2720, 288, 271.4, 2.9893, 4, 3.1032, 2.9893, 3.3365, 10500], # 0.8h
[+30, 5, 1, 680, 2720, 272, 267.4, 2.9803,11, 2.9818,+2.9803, 3.1647, 10500], # 0.8h  minGemma-hidden_layers30-att_heads5-kv_heads1-hidden680-intermediate2720-head_dim272-T1024--2026-05-11-11-45
# valx8: 2.9836 +- 0.0028 # torch.Tensor([2.9803, 2.9813, 2.9851, 2.9824, 2.9849, 2.9835, 2.9874, 2.9875, 2.9799]).std()
# (2nd: 2.9806)                                                                       minGemma-hidden_layers30-att_heads5-kv_heads1-hidden680-intermediate2720-head_dim272-T1024--2026-05-11-09-37
# valx8: 2.9845 +- 0.0059 # torch.Tensor([2.9806, 2.9864, 2.9740, 2.9821, 2.9916, 2.9916, 2.9898, 2.9811, 2.9834]).std()
[ 30, 5, 1, 680, 2720, 256, 263.5, 2.9854, 7, 2.9963, 2.9849, 2.6862, 10500], # 0.7h
[ 30, 5, 1, 680, 2720, 240, 259.6, 2.9945, 5, 2.9977, 2.9944, 2.7140, 10500], # 0.7h
[ 30, 5, 1, 680, 2720, 224, 255.7, 2.9816,10, 2.9892,+2.9816, 2.7336, 10500], # 0.7h
[ 30, 5, 1, 680, 2720, 208, 251.8, 2.9865, 6, 2.9874, 2.9865, 3.2550, 10500], # 0.7h
[ 30, 5, 1, 680, 2720, 192, 247.9, 2.9848, 7, 2.9848, 2.9848, 2.8279, 10500], # 0.7h
[ 30, 5, 1, 680, 2720, 176, 243.9, 2.9900, 7, 3.0930, 2.9900, 2.7315, 10500], # 0.6h 17.7G
[ 30, 5, 1, 680, 2720, 160, 240.0, 2.9954, 6, 2.9986, 2.9954, 2.9578, 10500], # 0.6h 17.6G

[ 30, 5, 1, 640, 2560, 288, 246.2, 2.9945, 4, 3.0256, 2.9928, 2.6838, 10500], # 0.7h
[ 30, 5, 1, 640, 2560, 272, 242.5, 2.9838, 7, 2.9840, 2.9838, 2.7223, 10500], # 0.7h
[ 30, 5, 1, 640, 2560, 256, 238.8, 2.9809, 7, 2.9851,+2.9809, 2.7538, 10500], # 0.7h 17.8G
[ 30, 5, 1, 640, 2560, 240, 235.1, 2.9834, 7, 3.0593,+2.9834, 2.8065, 10500], # 0.6h
[ 30, 5, 1, 640, 2560, 224, 231.4, 2.9903, 6, 3.0718, 2.9900, 2.7011, 10500], # 0.6h
[ 30, 5, 1, 640, 2560, 208, 227.8, 2.9911, 7, 2.9941, 2.9911, 3.1811, 10500], # 0.6h
[ 30, 5, 1, 640, 2560, 192, 224.1, 2.9871, 6, 2.9886, 2.9861, 2.8545, 10500], # 0.6h
[ 30, 5, 1, 640, 2560, 176, 220.4, 2.9864, 7, 2.9916, 2.9864, 2.7453, 10500], # 0.6h 16.1G
[ 30, 5, 1, 640, 2560, 160, 216.7, 2.9867, 7, 2.9876, 2.9867, 2.7694, 10500], # 0.6h

[ 30, 5, 1, 600, 2400, 288, 222.2, 2.9836, 7, 2.9942,+2.9836, 2.6686, 10500], # 0.7h
[ 30, 5, 1, 600, 2400, 272, 218.7, 2.9856, 6, 3.1202, 2.9847, 2.7145, 10500], # 0.7h
[ 30, 5, 1, 600, 2400, 256, 215.2, 2.9913, 6, 3.0963, 2.9899, 2.6898, 10500], # 0.7h
[ 30, 5, 1, 600, 2400, 240, 211.8, 2.9857, 7, 2.9888, 2.9857, 2.8057, 10500], # 0.7h
[ 30, 5, 1, 600, 2400, 224, 208.3, 2.9923, 6, 2.9973, 2.9923, 3.4866, 10500], # 0.6h
[ 30, 5, 1, 600, 2400, 208, 204.9, 2.9912, 6, 2.9963, 2.9912, 2.8683, 10500], # 0.6h
[ 30, 5, 1, 600, 2400, 192, 201.4, 2.9966, 6, 2.9996, 2.9966, 2.9620, 10500], # 0.6h
[ 30, 5, 1, 600, 2400, 176, 198.0, 2.9936, 4, 3.0949, 2.9936, 2.8562, 10500], # 0.6h
[ 30, 5, 1, 600, 2400, 160, 194.5, 2.9925, 6, 2.9962, 2.9921, 2.7350, 10500], # 0.6h 15.6G

[ 30, 5, 1, 560, 2240, 288, 199.3, 2.9900, 5, 2.9901, 2.9900, 2.7534, 10500], # 0.7h
[ 30, 5, 1, 560, 2240, 272, 196.1, 2.9891, 5, 3.1124, 2.9891, 2.9521, 10500], # 0.7h
[ 30, 5, 1, 560, 2240, 256, 192.8, 2.9858, 7, 2.9880, 2.9858, 2.6583, 10500], # 0.6h
[ 30, 5, 1, 560, 2240, 240, 189.6, 2.9818,19, 2.9885,+2.9818, 2.6614, 10500], # 0.6h 15.4G
[ 30, 5, 1, 560, 2240, 224, 186.4, 2.9864, 6, 2.9881, 2.9864, 3.1555, 10500], # 0.6h
[ 30, 5, 1, 560, 2240, 208, 183.2, 2.9886, 6, 2.9919, 2.9886, 2.8427, 10500], # 0.6h 15.3G
[ 30, 5, 1, 560, 2240, 192, 179.9, 3.0020, 6, 3.1336, 2.9999, 2.6707, 10500], # 0.6h
[ 30, 5, 1, 560, 2240, 176, 176.7, 2.9890, 7, 2.9913, 2.9890, 2.7090, 10500], # 0.6h
[ 30, 5, 1, 560, 2240, 160, 173.5, 2.9905, 6, 2.9988, 2.9889, 2.7672, 10500], # 0.5h


# local best for H4(2): 2.9770 (valx8: 2.9790)
[ 30, 4, 2, 800, 3200, 288, 353.8, 2.9899, 5, 3.0689, 2.9899, 2.9737, 10500], # 0.8h 20.8G
[ 30, 4, 2, 800, 3200, 272, 349.2, 2.9899, 4, 2.9914, 2.9885, 2.9027, 10500], # 0.8h
[ 30, 4, 2, 800, 3200, 256, 344.6, 2.9939, 5, 3.1466, 2.9939, 3.1710, 10500], # 0.7h
[ 30, 4, 2, 800, 3200, 240, 340.0, 2.9838, 6, 2.9866, 2.9838, 3.2572, 10500], # 0.7h
[ 30, 4, 2, 800, 3200, 224, 335.4, 2.9880, 6, 3.1372, 2.9880, 2.7947, 10500], # 0.7h
[ 30, 4, 2, 800, 3200, 208, 330.8, 2.9928, 4, 3.0447, 2.9928, 3.0402, 10500], # 0.7h
[ 30, 4, 2, 800, 3200, 192, 326.2, 2.9854, 6, 3.0980, 2.9854, 3.1829, 10500], # 0.7h
[ 30, 4, 2, 800, 3200, 176, 321.6, 2.9894, 6, 2.9987, 2.9894, 3.2714, 10500], # 0.7h
[ 30, 4, 2, 800, 3200, 160, 317.0, 2.9971, 4, 3.1873, 2.9971, 3.2907, 10500], # 0.7h

[ 30, 4, 2, 760, 3040, 288, 325.2, 2.9940, 4, 3.1014, 2.9940, 2.9039, 10500], # 0.8h
[ 30, 4, 2, 760, 3040, 272, 320.8, 2.9906, 6, 3.0924, 2.9906, 3.3616, 10500], # 0.8h
[ 30, 4, 2, 760, 3040, 256, 316.4, 2.9855, 6, 2.9966, 2.9855, 2.8517, 10500], # 0.7h
[ 30, 4, 2, 760, 3040, 240, 312.0, 2.9864, 5, 3.1051, 2.9864, 3.3474, 10500], # 0.7h
[ 30, 4, 2, 760, 3040, 224, 307.7, 2.9848, 6, 3.1111, 2.9848, 3.2641, 10500], # 0.7h
[ 30, 4, 2, 760, 3040, 208, 303.3, 2.9873, 9, 2.9917, 2.9873, 2.8241, 10500], # 0.7h
[ 30, 4, 2, 760, 3040, 192, 298.9, 2.9887, 7, 2.9891, 2.9887, 3.1305, 10500], # 0.7h 18.5G
[ 30, 4, 2, 760, 3040, 176, 294.5, 2.9902, 7, 3.0989, 2.9902, 2.7851, 10500], # 0.7h
[ 30, 4, 2, 760, 3040, 160, 290.2, 2.9983, 4, 3.1198, 2.9983, 2.8936, 10500], # 0.6h

[ 30, 4, 2, 720, 2880, 288, 297.7, 2.9779, 7, 2.9876,+2.9779, 3.1781, 10500], # 0.8h  minGemma-hidden_layers30-att_heads4-kv_heads2-hidden720-intermediate2880-head_dim288-T1024--2026-05-26-14-22 2nd(2.9799): minGemma-hidden_layers30-att_heads4-kv_heads2-hidden720-intermediate2880-head_dim288-T1024--2026-05-26-13-20
# valx8: 2.9807 +- 0.0034 # torch.Tensor([2.9779, 2.9799, 2.9770, 2.9812, 2.9780, 2.9856, 2.9840, 2.9850, 2.9775]).std() 1st(2.9779)
# valx8: 2.9826 +- 0.0028 # torch.Tensor([2.9799, 2.9825, 2.9865, 2.9839, 2.9788, 2.9837, 2.9798, 2.9865, 2.9818]).std() 2nd(2.9799)
[ 30, 4, 2, 720, 2880, 272, 293.5, 2.9905, 5, 2.9933, 2.9883, 2.9047, 10500], # 0.7h
[ 30, 4, 2, 720, 2880, 256, 289.4, 2.9895, 8, 3.0363, 2.9895, 3.3156, 10500], # 0.7h
[ 30, 4, 2, 720, 2880, 240, 285.3, 2.9908, 5, 3.1052, 2.9908, 3.3075, 10500], # 0.7h 18.6G
[ 30, 4, 2, 720, 2880, 224, 281.1, 2.9857, 6, 2.9895, 2.9857, 3.1727, 10500], # 0.7h
[ 30, 4, 2, 720, 2880, 208, 277.0, 2.9979, 4, 3.1006, 2.9979, 3.0002, 10500], # 0.7h
[ 30, 4, 2, 720, 2880, 192, 272.8, 2.9850, 6, 3.0252, 2.9850, 2.8602, 10500], # 0.6h
[ 30, 4, 2, 720, 2880, 176, 268.7, 2.9932, 5, 3.1891, 2.9932, 3.1227, 10500], # 0.6h
[ 30, 4, 2, 720, 2880, 160, 264.5, 2.9880, 6, 2.9883, 2.9880, 3.0611, 10500], # 0.6h

[+30, 4, 2, 680, 2720, 288, 271.4, 2.9770, 7, 2.9855,+2.9770, 2.7170, 10500], # 0.8h  minGemma-hidden_layers30-att_heads4-kv_heads2-hidden680-intermediate2720-head_dim288-T1024--2026-05-29-00-37
# valx8: 2.9790 +- 0.0034 # torch.Tensor([2.9770, 2.9841, 2.9762, 2.9813, 2.9751, 2.9807, 2.9835, 2.9757, 2.9774]).std()
[ 30, 4, 2, 680, 2720, 272, 267.4, 2.9802, 7, 2.9824,+2.9802, 3.1584, 10500], # 0.7h
# valx8: 2.9850 +- 0.0054 # torch.Tensor([2.9802, 2.9767, 2.9878, 2.9866, 2.9922, 2.9778, 2.9884, 2.9883, 2.9867]).std()
# (2nd: 2.9804)
# valx8: 2.9822 +- 0.0051 # torch.Tensor([2.9804, 2.9754, 2.9795, 2.9821, 2.9759, 2.9898, 2.9886, 2.9823, 2.9862]).std()
[ 30, 4, 2, 680, 2720, 256, 263.5, 2.9884, 9, 3.0775, 2.9884, 3.1602, 10500], # 0.7h 17.7G
[ 30, 4, 2, 680, 2720, 240, 259.6, 2.9953, 4, 3.0821, 2.9953, 3.2797, 10500], # 0.7h
[ 30, 4, 2, 680, 2720, 224, 255.7, 2.9897,10, 3.1812, 2.9887, 2.7470, 10500], # 0.7h
[ 30, 4, 2, 680, 2720, 208, 251.8, 2.9914, 8, 2.9959, 2.9914, 3.2005, 10500], # 0.7h
[ 30, 4, 2, 680, 2720, 192, 247.9, 2.9927, 6, 2.9953, 2.9927, 3.3222, 10500], # 0.6h
[ 30, 4, 2, 680, 2720, 176, 243.9, 2.9867, 6, 3.1653, 2.9867, 2.8710, 10500], # 0.6h
[ 30, 4, 2, 680, 2720, 160, 240.0, 2.9902, 7, 2.9953, 2.9902, 3.2369, 10500], # 0.6h

[ 30, 4, 2, 640, 2560, 288, 246.2, 2.9882, 7, 2.9920, 2.9882, 3.1228, 10500], # 0.7h
[ 30, 4, 2, 640, 2560, 272, 242.5, 2.9904,10, 3.0355, 2.9904, 3.1951, 10500], # 0.7h
[ 30, 4, 2, 640, 2560, 256, 238.8, 2.9918, 6, 2.9979, 2.9912, 2.6925, 10500], # 0.6h 17.2G
[ 30, 4, 2, 640, 2560, 240, 235.1, 2.9864, 7, 3.1005, 2.9864, 3.2454, 10500], # 0.6h
[ 30, 4, 2, 640, 2560, 224, 231.4, 2.9785, 7, 2.9839,+2.9785, 2.6974, 10500], # 0.6h  minGemma-hidden_layers30-att_heads4-kv_heads2-hidden640-intermediate2560-head_dim224-T1024--2026-06-02-05-14
# valx8: 2.9801 +- 0.0026 # torch.Tensor([2.9785, 2.9808, 2.9792, 2.9813, 2.9754, 2.9793, 2.9850, 2.9820, 2.9795]).std()
[ 30, 4, 2, 640, 2560, 208, 227.8, 2.9912, 7, 3.0589, 2.9912, 2.7021, 10500], # 0.6h
[ 30, 4, 2, 640, 2560, 192, 224.1, 2.9824, 6, 3.0691, 2.9824, 3.0680, 10500], # 0.6h
[ 30, 4, 2, 640, 2560, 176, 220.4, 2.9922, 6, 2.9959, 2.9918, 2.7415, 10500], # 0.6h
[ 30, 4, 2, 640, 2560, 160, 216.7, 2.9891, 7, 2.9967, 2.9891, 2.7413, 10500], # 0.6h

[ 30, 4, 2, 600, 2400, 288, 222.2, 2.9870, 5, 2.9942, 2.9869, 2.7414, 10500], # 0.7h
[ 30, 4, 2, 600, 2400, 272, 218.7, 2.9800, 7, 3.1289,+2.9800, 2.6624, 10500], # 0.7h
# valx8: 2.9808 +- 0.0025 # torch.Tensor([2.9800, 2.9831, 2.9811, 2.9823, 2.9787, 2.9772, 2.9842, 2.9780, 2.9826]).std()
[ 30, 4, 2, 600, 2400, 256, 215.2, 2.9855, 7, 2.9892, 2.9855, 2.6808, 10500], # 0.6h
[ 30, 4, 2, 600, 2400, 240, 211.8, 2.9880, 6, 2.9914, 2.9880, 2.8478, 10500], # 0.6h
[ 30, 4, 2, 600, 2400, 224, 208.3, 2.9942, 7, 2.9973, 2.9942, 2.6799, 10500], # 0.6h 16.7G
[ 30, 4, 2, 600, 2400, 208, 204.9, 2.9857, 6, 2.9895, 2.9857, 3.1886, 10500], # 0.6h
[ 30, 4, 2, 600, 2400, 192, 201.4, 2.9931, 7, 2.9950, 2.9931, 2.6956, 10500], # 0.6h
[ 30, 4, 2, 600, 2400, 176, 198.0, 2.9942, 7, 2.9959, 2.9942, 3.2888, 10500], # 0.6h
[ 30, 4, 2, 600, 2400, 160, 194.5, 2.9915, 6, 3.0014, 2.9915, 3.0218, 10500], # 0.6h

[ 30, 4, 2, 560, 2240, 288, 199.3, 2.9840, 6, 2.9901, 2.9840, 2.6751, 10500], # 0.7h
[ 30, 4, 2, 560, 2240, 272, 196.1, 2.9828, 6, 2.9854,+2.9814, 2.8104, 10500], # 0.6h
[ 30, 4, 2, 560, 2240, 256, 192.8, 2.9920, 6, 2.9954, 2.9920, 2.6682, 10500], # 0.6h
[ 30, 4, 2, 560, 2240, 240, 189.6, 2.9865, 6, 2.9884, 2.9865, 3.0302, 10500], # 0.6h
[ 30, 4, 2, 560, 2240, 224, 186.4, 2.9959, 6, 3.0008, 2.9939, 2.6832, 10500], # 0.6h
[ 30, 4, 2, 560, 2240, 208, 183.2, 2.9916, 6, 3.1062, 2.9916, 2.7439, 10500], # 0.6h
[ 30, 4, 2, 560, 2240, 192, 179.9, 2.9881, 6, 3.1421, 2.9861, 2.7098, 10500], # 0.6h
[ 30, 4, 2, 560, 2240, 176, 176.7, 2.9941, 6, 3.0000, 2.9941, 2.7517, 10500], # 0.5h
[ 30, 4, 2, 560, 2240, 160, 173.5, 2.9902, 7, 2.9964, 2.9902, 2.6901, 10500], # 0.5h

In [2]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  30 # 8 # G28 G18 #blocks
num_attention_heads = 6 # 4 # G16 G8
num_key_value_heads = 3 # 4 # G16 G1
hidden_size = num_attention_heads*132 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 272 # 32 # G256 # dim in attention
rms_norm_eps = 1e0 # 1e-6
rope_theta = 80000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//2; N_step=5250*2; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=10.0e-4, weight_decay=1.8, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(6000*2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9965:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

64.512
L30 att6 kv_heads3 hidden792 intermediate3168 head_dim272 T1024

1 4.786940848214286 tensor(3.2309)

2 2.811957961309524 tensor(3.0062)

3 2.7110719866071427 tensor(2.9833)

4 3.070774181547619 tensor(3.0416)
back to previous

5 2.6826741071428573 tensor(2.9769)

6 3.0560171130952383 tensor(3.0351)
back to previous

7 2.7616767113095237 tensor(2.9855)
[ 30, 6, 3, 792, 3168, 272, 382.2, 2.9769, 6, 2.9855, 2.9769, 3.0560, 10500],

In [12]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  30 # 8 # G28 G18 #blocks
num_attention_heads = 6 # 4 # G16 G8
num_key_value_heads = 3 # 4 # G16 G1
hidden_size = num_attention_heads*124 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 256 # 32 # G256 # dim in attention
rms_norm_eps = 1e0 # 1e-6
rope_theta = 80000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//2; N_step=5250*2; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=10.0e-4, weight_decay=1.8, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(6000*2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9869:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

64.512
L30 att6 kv_heads3 hidden744 intermediate2976 head_dim256 T1024

1 4.701430431547619 tensor(3.2093)

2 2.7932604166666666 tensor(3.0086)

3 2.842166480654762 tensor(2.9890)

4 2.7891235119047617 tensor(2.9851)

5 2.7590863095238096 tensor(2.9793)

6 2.6939330357142857 tensor(2.9782)

7 3.0839166666666666 tensor(3.0840)
back to previous

8 2.717071242559524 tensor(2.9813)
[ 30, 6, 3, 744, 2976, 256, 339.8, 2.9782, 7, 2.9813, 2.9782, 3.0839, 10500],

In [83]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  30 # 8 # G28 G18 #blocks
num_attention_heads = 5 # 4 # G16 G8
num_key_value_heads = 1 # 4 # G16 G1
hidden_size = num_attention_heads*136 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 272 # 32 # G256 # dim in attention
rms_norm_eps = 1e0 # 1e-6
rope_theta = 80000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//2; N_step=5250*2; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=10.0e-4, weight_decay=1.8, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(6000*2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9869:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

64.512
L30 att5 kv_heads1 hidden680 intermediate2720 head_dim272 T1024

1 4.572411830357143 tensor(3.1940)

2 2.7822207961309524 tensor(3.0104)

3 2.8388876488095236 tensor(2.9890)

4 2.710891369047619 tensor(2.9865)

5 2.864393787202381 tensor(2.9851)

6 2.7705997023809523 tensor(2.9827)

7 3.1633545386904762 tensor(3.0810)
back to previous

8 2.6695228794642856 tensor(2.9806)

9 2.7782925967261907 tensor(2.9840)
back to previous

10 2.7248876488095237 tensor(2.9803)

11 3.164703125 tensor(3.1381)
back to previous

12 2.6665848214285712 tensor(2.9818)
[ 30, 5, 1, 680, 2720, 272, 267.4, 2.9803, 11, 2.9818, 2.9803, 3.1647, 10500],

In [136]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  30 # 8 # G28 G18 #blocks
num_attention_heads = 4 # 4 # G16 G8
num_key_value_heads = 2 # 4 # G16 G1
hidden_size = num_attention_heads*180 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 288 # 32 # G256 # dim in attention
rms_norm_eps = 1e0 # 1e-6
rope_theta = 80000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//2; N_step=5250*2; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=10.0e-4, weight_decay=1.8, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(6000*2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9837:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

64.512
L30 att4 kv_heads2 hidden720 intermediate2880 head_dim288 T1024

1 4.63220275297619 tensor(3.2348)

2 2.807221168154762 tensor(3.0156)

3 2.715170386904762 tensor(2.9868)

4 2.7395848214285716 tensor(2.9832)

5 2.7286941964285716 tensor(2.9799)

6 2.677521949404762 tensor(2.9779)

7 3.178104538690476 tensor(3.1303)
back to previous

8 2.841931919642857 tensor(2.9876)
[ 30, 4, 2, 720, 2880, 288, 297.7, 2.9779, 7, 2.9876, 2.9779, 3.1781, 10500],

In [145]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  30 # 8 # G28 G18 #blocks
num_attention_heads = 4 # 4 # G16 G8
num_key_value_heads = 2 # 4 # G16 G1
hidden_size = num_attention_heads*170 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 288 # 32 # G256 # dim in attention
rms_norm_eps = 1e0 # 1e-6
rope_theta = 80000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//2; N_step=5250*2; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=10.0e-4, weight_decay=1.8, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(6000*2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9837:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

64.512
L30 att4 kv_heads2 hidden680 intermediate2720 head_dim288 T1024

1 4.506941592261905 tensor(3.2070)

2 2.8016454613095236 tensor(3.0115)

3 2.7378988095238097 tensor(2.9859)

4 2.8523558407738094 tensor(2.9833)

5 3.173606398809524 tensor(3.0053)
back to previous

6 2.7621143973214286 tensor(2.9770)

7 2.717007068452381 tensor(2.9828)
back to previous

8 2.7883130580357145 tensor(2.9855)
[ 30, 4, 2, 680, 2720, 288, 271.4, 2.9770, 7, 2.9855, 2.9770, 2.7170, 10500],

In [158]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  30 # 8 # G28 G18 #blocks
num_attention_heads = 4 # 4 # G16 G8
num_key_value_heads = 2 # 4 # G16 G1
hidden_size = num_attention_heads*160 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 224 # 32 # G256 # dim in attention
rms_norm_eps = 1e0 # 1e-6
rope_theta = 80000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//2; N_step=5250*2; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=10.0e-4, weight_decay=1.8, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(6000*2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9837:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

64.512
L30 att4 kv_heads2 hidden640 intermediate2560 head_dim224 T1024

1 4.504822544642857 tensor(3.2461)

2 2.820856770833333 tensor(3.0164)

3 2.7206995907738096 tensor(2.9856)

4 2.7430342261904763 tensor(2.9823)

5 2.7444834449404762 tensor(2.9806)

6 2.6770308779761907 tensor(2.9785)

7 2.6974375 tensor(2.9841)
back to previous

8 2.716040736607143 tensor(2.9839)
[ 30, 4, 2, 640, 2560, 224, 231.4, 2.9785, 7, 2.9839, 2.9785, 2.6974, 10500],

# L24

In [ ]:
# L24 FORGETTER T1024 Baby10M (default: B12//2 N5250 lr10e-4 WD1.8) # H7(1): 2.9775, H6(3): 2.9792, H5(1): 2.9802

# local best for H7(1): 2.9765 (valx8: 2.9775)
[ 24, 7, 1, 812, 3248, 288, 320.7, 2.9828, 6, 2.9909, 2.9819, 2.6657, 10500], # 0.8h
[ 24, 7, 1, 812, 3248, 272, 315.7, 2.9852, 5, 2.9858, 2.9846, 2.7030, 10500], # 0.8h 19.8G
[ 24, 7, 1, 812, 3248, 256, 310.7, 2.9781, 7, 2.9852,+2.9781, 2.8370, 10500], # 0.7h  minGemma-hidden_layers24-att_heads7-kv_heads1-hidden812-intermediate3248-head_dim256-T1024--2026-06-08-21-53
# valx8: 2.9796 +- 0.0048 # torch.Tensor([2.9781, 2.9840, 2.9827, 2.9826, 2.9702, 2.9804, 2.9790, 2.9851, 2.9746]).std()
[ 24, 7, 1, 812, 3248, 240, 305.7, 2.9907, 7, 2.9963, 2.9907, 3.1782, 10500], # 0.7h
[ 24, 7, 1, 812, 3248, 224, 300.8, 2.9869, 7, 2.9930, 2.9869, 2.8331, 10500], # 0.7h
[ 24, 7, 1, 812, 3248, 208, 295.8, 2.9900, 7, 2.9954, 2.9900, 2.8087, 10500], # 0.6h
[ 24, 7, 1, 812, 3248, 192, 290.8, 2.9974, 6, 3.0030, 2.9974, 3.0244, 10500], # 0.6h
[ 24, 7, 1, 812, 3248, 176, 285.8, 2.9894, 6, 2.9993, 2.9894, 3.2409, 10500], # 0.6h
[ 24, 7, 1, 812, 3248, 160, 280.8, 2.9912, 7, 3.4038, 2.9912, 2.9040, 10500], # 0.6h

[ 24, 7, 1, 784, 3136, 288, 303.3, 2.9834, 7, 2.9888,+2.9834, 2.6930, 10500], # 0.8h
[ 24, 7, 1, 784, 3136, 272, 298.5, 2.9886, 6, 2.9945, 2.9878, 2.6950, 10500], # 0.7h
[ 24, 7, 1, 784, 3136, 256, 293.7, 2.9853, 6, 2.9936, 2.9853, 2.7592, 10500], # 0.7h
[ 24, 7, 1, 784, 3136, 240, 288.9, 2.9964, 5, 2.9996, 2.9948, 2.8840, 10500], # 0.7h
[ 24, 7, 1, 784, 3136, 224, 284.1, 2.9864, 6, 3.0942, 2.9852, 2.7105, 10500], # 0.6h
[ 24, 7, 1, 784, 3136, 208, 279.2, 2.9927, 6, 2.9976, 2.9904, 2.7536, 10500], # 0.6h
[ 24, 7, 1, 784, 3136, 192, 274.4, 2.9910, 7, 2.9977, 2.9910, 2.6642, 10500], # 0.6h 17.6G
[ 24, 7, 1, 784, 3136, 176, 269.6, 2.9892, 6, 2.9942, 2.9892, 3.2353, 10500], # 0.6h 17.4G
[ 24, 7, 1, 784, 3136, 160, 264.8, 2.9935, 7, 2.9968, 2.9935, 2.8405, 10500], # 0.6h

[ 24, 7, 1, 756, 3024, 288, 286.4, 2.9915, 7, 2.9967, 2.9915, 2.7048, 10500], # 0.7h
[ 24, 7, 1, 756, 3024, 272, 281.8, 2.9800, 7, 3.0960,+2.9800, 2.7211, 10500], # 0.7h
# valx8: 2.9831 +- 0.0064 # torch.Tensor([2.9800, 2.9770, 2.9942, 2.9893, 2.9848, 2.9875, 2.9776, 2.9829, 2.9749]).std()
[ 24, 7, 1, 756, 3024, 256, 277.1, 2.9885, 7, 3.0580, 2.9885, 3.2164, 10500], # 0.7h
[ 24, 7, 1, 756, 3024, 240, 272.5, 2.9881, 6, 2.9969, 2.9876, 2.6936, 10500], # 0.6h
[ 24, 7, 1, 756, 3024, 224, 267.8, 2.9827, 7, 2.9882,+2.9827, 2.7690, 10500], # 0.6h
[ 24, 7, 1, 756, 3024, 208, 263.2, 2.9905, 6, 3.1249, 2.9905, 3.1727, 10500], # 0.6h
[ 24, 7, 1, 756, 3024, 192, 258.5, 2.9884, 6, 2.9934, 2.9884, 2.8135, 10500], # 0.6h
[ 24, 7, 1, 756, 3024, 176, 253.9, 2.9847, 6, 3.1003, 2.9847, 3.2485, 10500], # 0.6h
[ 24, 7, 1, 756, 3024, 160, 249.2, 2.9914, 6, 3.1596, 2.9914, 3.1689, 10500], # 0.6h

[ 24, 7, 1, 728, 2912, 288, 269.9, 2.9866, 6, 2.9944, 2.9863, 2.6702, 10500], # 0.7h
[ 24, 7, 1, 728, 2912, 272, 265.5, 2.9872, 6, 3.0650, 2.9872, 2.7986, 10500], # 0.7h
[ 24, 7, 1, 728, 2912, 256, 261.0, 2.9887, 7, 2.9938, 2.9887, 2.6597, 10500], # 0.7h
[ 24, 7, 1, 728, 2912, 240, 256.5, 2.9955, 7, 2.9999, 2.9955, 2.6692, 10500], # 0.7h
[ 24, 7, 1, 728, 2912, 224, 252.0, 2.9857, 7, 2.9992, 2.9857, 3.2856, 10500], # 0.6h
[ 24, 7, 1, 728, 2912, 208, 247.6, 2.9917, 7, 2.9966, 2.9896, 2.7093, 10500], # 0.6h
[ 24, 7, 1, 728, 2912, 192, 243.1, 2.9889, 6, 2.9947, 2.9871, 2.7644, 10500], # 0.6h
[ 24, 7, 1, 728, 2912, 176, 238.6, 2.9914, 6, 3.0052, 2.9914, 3.3870, 10500], # 0.6h
[ 24, 7, 1, 728, 2912, 160, 234.1, 2.9881, 6, 2.9926, 2.9881, 3.0057, 10500], # 0.6h

[ 24, 7, 1, 700, 2800, 288, 253.9, 2.9840, 6, 2.9972,+2.9816, 2.7403, 10500], # 0.7h
[ 24, 7, 1, 700, 2800, 272, 249.6, 2.9924, 6, 3.0001, 2.9909, 2.6555, 10500], # 0.7h
[ 24, 7, 1, 700, 2800, 256, 245.3, 2.9890, 7, 3.0789, 2.9890, 2.8345, 10500], # 0.6h
[ 24, 7, 1, 700, 2800, 240, 241.0, 2.9953, 6, 2.9989, 2.9929, 2.8260, 10500], # 0.6h 17.1G
[ 24, 7, 1, 700, 2800, 224, 236.7, 2.9915, 6, 2.9952, 2.9915, 3.2574, 10500], # 0.6h
[ 24, 7, 1, 700, 2800, 208, 232.4, 2.9913, 7, 2.9946, 2.9913, 2.7303, 10500], # 0.6h
[ 24, 7, 1, 700, 2800, 192, 228.1, 2.9914, 4, 3.0447, 2.9892, 3.0150, 10500], # 0.6h 16.7G
[ 24, 7, 1, 700, 2800, 176, 223.8, 2.9882, 7, 3.1671, 2.9882, 2.7160, 10500], # 0.5h
[ 24, 7, 1, 700, 2800, 160, 219.5, 2.9839, 6, 2.9892,+2.9824, 2.6722, 10500], # 0.5h

[ 24, 7, 1, 672, 2688, 288, 238.3, 2.9913, 5, 3.0112, 2.9913, 2.9962, 10500], # 0.7h
[ 24, 7, 1, 672, 2688, 272, 234.2, 2.9836, 6, 2.9912,+2.9831, 2.6619, 10500], # 0.7h
[ 24, 7, 1, 672, 2688, 256, 230.1, 2.9871, 6, 2.9925, 2.9857, 2.6609, 10500], # 0.6h
[ 24, 7, 1, 672, 2688, 240, 225.9, 2.9917, 7, 3.0015, 2.9917, 2.6548, 10500], # 0.6h
[ 24, 7, 1, 672, 2688, 224, 221.8, 2.9807, 6, 2.9852,+2.9803, 2.7317, 10500], # 0.6h
# valx8: 2.9825 +- 0.0056 # torch.Tensor([2.9803, 2.9837, 2.9836, 2.9817, 2.9814, 2.9879, 2.9797, 2.9920, 2.9718]).std()
[ 24, 7, 1, 672, 2688, 208, 217.7, 2.9860, 6, 3.0582, 2.9860, 2.6649, 10500], # 0.6h
[ 24, 7, 1, 672, 2688, 192, 213.6, 2.9884, 6, 3.1959, 2.9866, 2.6838, 10500], # 0.5h
[ 24, 7, 1, 672, 2688, 176, 209.4, 2.9852, 6, 2.9918, 2.9852, 2.6850, 10500], # 0.5h
[ 24, 7, 1, 672, 2688, 160, 205.3, 2.9847, 7, 2.9887, 2.9847, 2.7264, 10500], # 0.5h

[ 24, 7, 1, 644, 2576, 288, 223.2, 2.9825, 7, 2.9872,+2.9825, 2.6604, 10500], # 0.7h
[ 24, 7, 1, 644, 2576, 272, 219.2, 2.9942, 7, 3.0022, 2.9942, 2.6483, 10500], # 0.7h 16.8G
[ 24, 7, 1, 644, 2576, 256, 215.3, 2.9885, 7, 2.9923, 2.9885, 2.6930, 10500], # 0.6h
[ 24, 7, 1, 644, 2576, 240, 211.3, 2.9789, 6, 2.9851,+2.9776, 2.8391, 10500], # 0.6h  minGemma-hidden_layers24-att_heads7-kv_heads1-hidden644-intermediate2576-head_dim240-T1024--2026-06-23-07-10 2nd(2.9789): minGemma-hidden_layers24-att_heads7-kv_heads1-hidden644-intermediate2576-head_dim240-T1024--2026-06-23-07-59
# valx8: 2.9829 +- 0.0042 # torch.Tensor([2.9776, 2.9752, 2.9876, 2.9824, 2.9856, 2.9856, 2.9855, 2.9853, 2.9809]).std() # 1st(2.9776)
# valx8: 2.9837 +- 0.0045 # torch.Tensor([2.9789, 2.9842, 2.9882, 2.9884, 2.9873, 2.9881, 2.9775, 2.9787, 2.9818]).std() # 2nd(2.9789)
[ 24, 7, 1, 644, 2576, 224, 207.4, 2.9877, 6, 2.9926, 2.9861, 2.6781, 10500], # 0.6h 16.3G
[ 24, 7, 1, 644, 2576, 208, 203.4, 2.9990, 5, 3.0025, 2.9987, 2.6733, 10500], # 0.6h 15.3G
[ 24, 7, 1, 644, 2576, 192, 199.5, 2.9855, 6, 2.9922, 2.9855, 3.2613, 10500], # 0.5h 15.0G
[ 24, 7, 1, 644, 2576, 176, 195.5, 2.9938, 7, 3.0010, 2.9938, 2.6743, 10500], # 0.5h
[ 24, 7, 1, 644, 2576, 160, 191.5, 2.9871, 7, 2.9919, 2.9871, 2.7842, 10500], # 0.5h 14.9G

[+24, 7, 1, 616, 2464, 288, 208.5, 2.9765, 7, 2.9839,+2.9765, 2.6495, 10500], # 0.7h  minGemma-hidden_layers24-att_heads7-kv_heads1-hidden616-intermediate2464-head_dim288-T1024--2026-06-24-17-19
# valx8: 2.9775 +- 0.0044 # torch.Tensor([2.9765, 2.9760, 2.9709, 2.9775, 2.9815, 2.9735, 2.9747, 2.9844, 2.9821]).std()
# (2nd: 2.9780)                                                                       minGemma-hidden_layers24-att_heads7-kv_heads1-hidden616-intermediate2464-head_dim288-T1024--2026-06-24-16-26
# valx8: 2.9800 +- 0.0049 # torch.Tensor([2.9780, 2.9732, 2.9863, 2.9752, 2.9763, 2.9858, 2.9786, 2.9857, 2.9805]).std()
[ 24, 7, 1, 616, 2464, 272, 204.7, 2.9927, 6, 2.9997, 2.9927, 2.7067, 10500], # 0.7h
[ 24, 7, 1, 616, 2464, 256, 201.0, 2.9881, 7, 2.9955, 2.9881, 2.7051, 10500], # 0.6h
[ 24, 7, 1, 616, 2464, 240, 197.2, 2.9907, 7, 2.9978, 2.9907, 2.6715, 10500], # 0.6h
[ 24, 7, 1, 616, 2464, 224, 193.4, 2.9864, 6, 2.9938, 2.9862, 2.6595, 10500], # 0.6h
[ 24, 7, 1, 616, 2464, 208, 189.6, 2.9850, 6, 2.9932, 2.9848, 2.6594, 10500], # 0.6h
[ 24, 7, 1, 616, 2464, 192, 185.8, 2.9960, 7, 2.9995, 2.9960, 2.6663, 10500], # 0.5h
[ 24, 7, 1, 616, 2464, 176, 182.0, 2.9920, 5, 3.0420, 2.9920, 2.8183, 10500], # 0.5h
[ 24, 7, 1, 616, 2464, 160, 178.3, 2.9824, 7, 2.9872,+2.9824, 3.1997, 10500], # 0.5h 14.4G

[ 24, 7, 1, 588, 2352, 288, 194.3, 2.9999, 6, 3.0089, 2.9993, 2.6644, 10500], # 0.6h
[ 24, 7, 1, 588, 2352, 272, 190.7, 2.9909, 7, 2.9976, 2.9909, 2.6524, 10500], # 0.6h
[ 24, 7, 1, 588, 2352, 256, 187.1, 2.9893, 7, 2.9949, 2.9893, 2.6618, 10500], # 0.6h
[ 24, 7, 1, 588, 2352, 240, 183.5, 2.9849, 6, 2.9956,+2.9833, 2.6638, 10500], # 0.6h
[ 24, 7, 1, 588, 2352, 224, 179.9, 2.9950, 6, 3.0035, 2.9939, 2.6614, 10500], # 0.5h
[ 24, 7, 1, 588, 2352, 208, 176.2, 2.9884, 7, 2.9961, 2.9884, 2.6444, 10500], # 0.5h
[ 24, 7, 1, 588, 2352, 192, 172.6, 2.9902, 6, 2.9993, 2.9884, 2.6617, 10500], # 0.5h
[ 24, 7, 1, 588, 2352, 176, 169.0, 2.9948, 6, 3.0024, 2.9940, 2.6832, 10500], # 0.5h
[ 24, 7, 1, 588, 2352, 160, 165.4, 2.9958, 6, 3.0049, 2.9948, 2.6609, 10500], # 0.5h

[ 24, 7, 1, 560, 2240, 288, 180.5, 2.9926, 6, 2.9998, 2.9909, 2.6991, 10500], # 0.6h
[ 24, 7, 1, 560, 2240, 272, 177.1, 2.9968, 5, 2.9975, 2.9968, 2.6728, 10500], # 0.6h
[ 24, 7, 1, 560, 2240, 256, 173.7, 2.9953, 5, 2.9973, 2.9942, 2.7029, 10500], # 0.6h
[ 24, 7, 1, 560, 2240, 240, 170.2, 2.9988, 5, 3.0015, 2.9983, 2.6889, 10500], # 0.5h
[ 24, 7, 1, 560, 2240, 224, 166.8, 2.9951, 6, 2.9973, 2.9932, 3.0786, 10500], # 0.5h 14.6G
[ 24, 7, 1, 560, 2240, 208, 163.3, 2.9893, 6, 2.9981, 2.9881, 2.6629, 10500], # 0.5h
[ 24, 7, 1, 560, 2240, 192, 159.9, 2.9981, 6, 3.0017, 2.9958, 2.6646, 10500], # 0.5h
[ 24, 7, 1, 560, 2240, 176, 156.5, 2.9858, 6, 2.9904, 2.9858, 2.8501, 10500], # 0.5h
[ 24, 7, 1, 560, 2240, 160, 153.0, 2.9974, 6, 3.0089, 2.9951, 2.6822, 10500], # 0.5h


# local best for H6(3): 2.9761 (valx8: 2.9792)
[ 24, 6, 3, 792, 3168, 288, 319.2, 2.9857, 7, 2.9910, 2.9857, 3.2584, 10500], # 0.8h
[ 24, 6, 3, 792, 3168, 272, 313.7, 2.9827, 7, 3.2364,+2.9827, 2.7631, 10500], # 0.8h
[ 24, 6, 3, 792, 3168, 256, 308.3, 2.9829, 6, 3.1270,+2.9829, 3.1045, 10500], # 0.7h
[ 24, 6, 3, 792, 3168, 240, 302.8, 2.9863, 6, 3.0419, 2.9854, 2.7481, 10500], # 0.7h 18.0G
[ 24, 6, 3, 792, 3168, 224, 297.3, 2.9792, 7, 3.0927,+2.9792, 3.1057, 10500], # 0.7h  minGemma-hidden_layers24-att_heads6-kv_heads3-hidden792-intermediate3168-head_dim224-T1024--2026-07-02-02-16
# valx8: 2.9802 +- 0.0043 # torch.Tensor([2.9792, 2.9774, 2.9822, 2.9767, 2.9807, 2.9831, 2.9753, 2.9892, 2.9776]).std()
[ 24, 6, 3, 792, 3168, 208, 291.8, 2.9815, 7, 2.9887,+2.9815, 2.6975, 10500], # 0.7h
[ 24, 6, 3, 792, 3168, 192, 286.4, 2.9818, 7, 3.3770,+2.9818, 2.7686, 10500], # 0.6h
[ 24, 6, 3, 792, 3168, 176, 280.9, 2.9808, 6, 3.0205,+2.9808, 3.1623, 10500], # 0.6h
# valx8: 2.9852 +- 0.0067 # torch.Tensor([2.9808, 2.9809, 2.9925, 2.9811, 2.9985, 2.9882, 2.9805, 2.9857, 2.9783]).std()
[ 24, 6, 3, 792, 3168, 160, 275.4, 2.9883, 7, 2.9913, 2.9883, 2.7180, 10500], # 0.6h

[ 24, 6, 3, 768, 3072, 288, 304.2, 2.9831, 6, 2.9881,+2.9831, 2.9777, 10500], # 0.7h
[ 24, 6, 3, 768, 3072, 272, 298.9, 2.9885, 6, 2.9916, 2.9871, 2.7003, 10500], # 0.7h
[ 24, 6, 3, 768, 3072, 256, 293.6, 2.9794, 6, 3.0219,+2.9794, 2.8211, 10500], # 0.6h
# valx8: 2.9824 +- 0.0038 # torch.Tensor([2.9794, 2.9838, 2.9848, 2.9813, 2.9877, 2.9836, 2.9857, 2.9801, 2.9752]).std()
[ 24, 6, 3, 768, 3072, 240, 288.3, 2.9789, 6, 2.9855,+2.9789, 2.8508, 10500], # 0.6h  minGemma-hidden_layers24-att_heads6-kv_heads3-hidden768-intermediate3072-head_dim240-T1024--2026-08-03-12-37
# valx8: 2.9811 +- 0.0032 # torch.Tensor([2.9789, 2.9833, 2.9801, 2.9799, 2.9822, 2.9879, 2.9812, 2.9793, 2.9769]).std()
[ 24, 6, 3, 768, 3072, 224, 283.0, 2.9856, 7, 3.0092,+2.9833, 2.6810, 10500], # 0.6h
[ 24, 6, 3, 768, 3072, 208, 277.7, 2.9816, 6, 3.1385,+2.9811, 2.7116, 10500], # 0.6h
[ 24, 6, 3, 768, 3072, 192, 272.4, 2.9840, 6, 2.9893,+2.9832, 2.6761, 10500], # 0.6h
[ 24, 6, 3, 768, 3072, 176, 267.1, 2.9826, 7, 2.9867,+2.9826, 3.1764, 10500], # 0.6h
[ 24, 6, 3, 768, 3072, 160, 261.8, 2.9837, 7, 2.9937, 2.9837, 2.6687, 10500], # 0.5h

[ 24, 6, 3, 744, 2976, 288, 289.6, 2.9782, 7, 2.9834,+2.9782, 3.3390, 10500], # 0.7h  minGemma-hidden_layers24-att_heads6-kv_heads3-hidden744-intermediate2976-head_dim288-T1024--2026-07-03-12-36
# valx8: 2.9803 +- 0.0036 # torch.Tensor([2.9782, 2.9783, 2.9799, 2.9821, 2.9748, 2.9767, 2.9855, 2.9836, 2.9832]).std()
# (2nd: 2.9783)                                                                       minGemma-hidden_layers24-att_heads6-kv_heads3-hidden744-intermediate2976-head_dim288-T1024--2026-07-03-11-38
# valx8: 2.9813 +- 0.0048 # torch.Tensor([2.9783, 2.9824, 2.9828, 2.9829, 2.9754, 2.9734, 2.9858, 2.9883, 2.9827]).std()
[ 24, 6, 3, 744, 2976, 272, 284.4, 2.9797, 7, 2.9919,+2.9797, 3.0965, 10500], # 0.7h
# valx8: 2.9824 +- 0.0027 # torch.Tensor([2.9797, 2.9804, 2.9840, 2.9818, 2.9857, 2.9821, 2.9784, 2.9825, 2.9866]).std()
# (2nd: 2.9801)
# valx8: 2.9827 +- 0.0066 # torch.Tensor([2.9801, 2.9886, 2.9824, 2.9975, 2.9759, 2.9812, 2.9778, 2.9825, 2.9785]).std()
[ 24, 6, 3, 744, 2976, 256, 279.3, 2.9831, 6, 3.1689,+2.9807, 2.7857, 10500], # 0.7h
# valx8: 2.9854 +- 0.0062 # torch.Tensor([2.9807, 2.9941, 2.9845, 2.9887, 2.9880, 2.9847, 2.9786, 2.9934, 2.9762]).std()
[ 24, 6, 3, 744, 2976, 240, 274.1, 2.9839, 6, 3.2026,+2.9821, 2.7365, 10500], # 0.7h
[ 24, 6, 3, 744, 2976, 224, 269.0, 2.9809, 7, 3.0886,+2.9809, 3.0068, 10500], # 0.6h
# valx8: 2.9817 +- 0.0029 # torch.Tensor([2.9809, 2.9802, 2.9881, 2.9819, 2.9799, 2.9844, 2.9801, 2.9810, 2.9786]).std()
[ 24, 6, 3, 744, 2976, 208, 263.9, 2.9830, 7, 3.0200,+2.9830, 3.1978, 10500], # 0.6h 2.9821@4th
[ 24, 6, 3, 744, 2976, 192, 258.7, 2.9840, 7, 2.9975, 2.9840, 2.9480, 10500], # 0.6h
[ 24, 6, 3, 744, 2976, 176, 253.6, 2.9807, 6, 2.9870,+2.9803, 2.6906, 10500], # 0.6h
# valx8: 2.9842 +- 0.0028 # torch.Tensor([2.9803, 2.9883, 2.9803, 2.9858, 2.9861, 2.9857, 2.9825, 2.9830, 2.9855]).std()
# (2nd: 2.9807)
# valx8: 2.9811 +- 0.0051 # torch.Tensor([2.9807, 2.9855, 2.9821, 2.9794, 2.9717, 2.9758, 2.9839, 2.9885, 2.9826]).std()
[ 24, 6, 3, 744, 2976, 160, 248.4, 2.9874, 7, 3.1367, 2.9874, 2.7934, 10500], # 0.6h 16.8G

[ 24, 6, 3, 720, 2880, 288, 275.3, 2.9782, 7, 2.9870,+2.9782, 2.6538, 10500], # 0.7h  minGemma-hidden_layers24-att_heads6-kv_heads3-hidden720-intermediate2880-head_dim288-T1024--2026-08-02-00-15
# valx8: 2.9806 +- 0.0041 # torch.Tensor([2.9782, 2.9836, 2.9763, 2.9843, 2.9852, 2.9783, 2.9828, 2.9829, 2.9735]).std()
[ 24, 6, 3, 720, 2880, 272, 270.3, 2.9863, 6, 2.9932, 2.9843, 2.7704, 10500], # 0.7h
[ 24, 6, 3, 720, 2880, 256, 265.3, 2.9836, 6, 3.0980,+2.9833, 2.6764, 10500], # 0.6h
[ 24, 6, 3, 720, 2880, 240, 260.3, 2.9917, 6, 3.0569, 2.9900, 2.6865, 10500], # 0.6h
[ 24, 6, 3, 720, 2880, 224, 255.3, 2.9816, 7, 3.0534,+2.9816, 2.7041, 10500], # 0.6h
[ 24, 6, 3, 720, 2880, 208, 250.4, 2.9849, 6, 2.9956, 2.9849, 3.1543, 10500], # 0.6h
[ 24, 6, 3, 720, 2880, 192, 245.4, 2.9948, 5, 3.0361, 2.9939, 2.6880, 10500], # 0.6h
[ 24, 6, 3, 720, 2880, 176, 240.4, 2.9850, 6, 2.9900, 2.9844, 2.8278, 10500], # 0.5h
[ 24, 6, 3, 720, 2880, 160, 235.4, 2.9871, 6, 2.9966, 2.9871, 3.1716, 10500], # 0.5h

[ 24, 6, 3, 696, 2784, 288, 261.3, 2.9841, 6, 2.9926, 2.9841, 3.1467, 10500], # 0.7h 17.2G
[ 24, 6, 3, 696, 2784, 272, 256.5, 2.9810, 6, 2.9874,+2.9810, 3.2293, 10500], # 0.7h
[ 24, 6, 3, 696, 2784, 256, 251.6, 2.9910, 7, 2.9969, 2.9910, 2.6934, 10500], # 0.6h 17.0G
[ 24, 6, 3, 696, 2784, 240, 246.8, 2.9838, 7, 2.9924, 2.9838, 2.6867, 10500], # 0.6h 16.9G
[ 24, 6, 3, 696, 2784, 224, 242.0, 2.9858, 6, 3.1523, 2.9846, 2.7481, 10500], # 0.6h
[ 24, 6, 3, 696, 2784, 208, 237.2, 2.9824, 7, 2.9857,+2.9824, 3.1704, 10500], # 0.6h
[ 24, 6, 3, 696, 2784, 192, 232.4, 2.9810, 7, 2.9863,+2.9810, 2.6749, 10500], # 0.6h
[ 24, 6, 3, 696, 2784, 176, 227.6, 2.9841, 6, 2.9917,+2.9836, 2.6770, 10500], # 0.6h
[ 24, 6, 3, 696, 2784, 160, 222.8, 2.9789, 7, 2.9859,+2.9789, 2.6677, 10500], # 0.5h
# valx8: 2.9833 +- 0.0038 # torch.Tensor([2.9789, 2.9814, 2.9879, 2.9869, 2.9824, 2.9851, 2.9882, 2.9806, 2.9787]).std()

[ 24, 6, 3, 672, 2688, 288, 247.6, 2.9838, 6, 2.9912,+2.9817, 2.6703, 10500], # 0.7h
[ 24, 6, 3, 672, 2688, 272, 243.0, 2.9800, 6, 2.9864,+2.9800, 2.8415, 10500], # 0.6h
# valx8: 2.9837 +- 0.0022 # torch.Tensor([2.9800, 2.9831, 2.9843, 2.9869, 2.9848, 2.9836, 2.9843, 2.9856, 2.9806]).std()
[ 24, 6, 3, 672, 2688, 256, 238.3, 2.9785, 6, 3.0952,+2.9785, 3.4285, 10500], # 0.6h  minGemma-hidden_layers24-att_heads6-kv_heads3-hidden672-intermediate2688-head_dim256-T1024--2026-07-30-07-20
# valx8: 2.9825 +- 0.0055 # torch.Tensor([2.9785, 2.9811, 2.9934, 2.9836, 2.9839, 2.9819, 2.9804, 2.9859, 2.9734]).std()
[+24, 6, 3, 672, 2688, 240, 233.7, 2.9761, 6, 2.9828,+2.9761, 3.0100, 10500], # 0.6h  minGemma-hidden_layers24-att_heads6-kv_heads3-hidden672-intermediate2688-head_dim240-T1024--2026-07-30-01-41
# valx8: 2.9792 +- 0.0024 # torch.Tensor([2.9761, 2.9804, 2.9828, 2.9815, 2.9794, 2.9768, 2.9789, 2.9803, 2.9764]).std()
[ 24, 6, 3, 672, 2688, 224, 229.0, 2.9859, 7, 2.9893, 2.9859, 2.7070, 10500], # 0.6h
[ 24, 6, 3, 672, 2688, 208, 224.4, 2.9828, 7, 2.9867,+2.9828, 2.6692, 10500], # 0.6h
[ 24, 6, 3, 672, 2688, 192, 219.7, 2.9850, 6, 2.9883,+2.9833, 2.6785, 10500], # 0.5h
[ 24, 6, 3, 672, 2688, 176, 215.1, 2.9882, 7, 2.9946, 2.9882, 3.1146, 10500], # 0.5h
[ 24, 6, 3, 672, 2688, 160, 210.5, 2.9892, 6, 3.0109, 2.9879, 2.8628, 10500], # 0.5h

[ 24, 6, 3, 648, 2592, 288, 234.3, 2.9867, 6, 2.9932, 2.9848, 2.7206, 10500], # 0.7h
[ 24, 6, 3, 648, 2592, 272, 229.8, 2.9879, 6, 2.9958, 2.9879, 2.7589, 10500], # 0.7h 16.6G
[ 24, 6, 3, 648, 2592, 256, 225.3, 2.9803, 7, 2.9838,+2.9803, 2.6616, 10500], # 0.6h
# valx8: 2.9820 +- 0.0031 # torch.Tensor([2.9803, 2.9788, 2.9836, 2.9804, 2.9798, 2.9859, 2.9855, 2.9857, 2.9783]).std()
[ 24, 6, 3, 648, 2592, 240, 220.9, 2.9846, 6, 2.9913, 2.9843, 2.6719, 10500], # 0.6h
[ 24, 6, 3, 648, 2592, 224, 216.4, 2.9837, 6, 3.1166,+2.9835, 2.7533, 10500], # 0.6h
[ 24, 6, 3, 648, 2592, 208, 211.9, 2.9804, 7, 2.9879,+2.9804, 2.6605, 10500], # 0.6h
# valx8: 2.9848 +- 0.0044 # torch.Tensor([2.9804, 2.9856, 2.9891, 2.9886, 2.9782, 2.9850, 2.9916, 2.9823, 2.9823]).std()
[ 24, 6, 3, 648, 2592, 192, 207.4, 2.9876, 5, 3.1102, 2.9876, 2.8510, 10500], # 0.5h
[ 24, 6, 3, 648, 2592, 176, 202.9, 2.9822, 7, 2.9874,+2.9822, 2.9139, 10500], # 0.5h
[ 24, 6, 3, 648, 2592, 160, 198.5, 2.9967, 7, 3.0277, 2.9967, 2.6879, 10500], # 0.5h

[ 24, 6, 3, 624, 2496, 288, 221.3, 2.9914, 5, 2.9929, 2.9906, 2.6897, 10500], # 0.6h
[ 24, 6, 3, 624, 2496, 272, 217.0, 2.9878, 6, 2.9932, 2.9862, 2.6659, 10500], # 0.6h 16.2G
[ 24, 6, 3, 624, 2496, 256, 212.7, 2.9786, 6, 2.9839,+2.9786, 2.7399, 10500], # 0.6h   minGemma-hidden_layers24-att_heads6-kv_heads3-hidden624-intermediate2496-head_dim256-T1024--2026-07-28-05-00
# valx8: 2.9822 +- 0.0024 # torch.Tensor([2.9786, 2.9819, 2.9827, 2.9852, 2.9813, 2.9820, 2.9806, 2.9866, 2.9806]).std()
[ 24, 6, 3, 624, 2496, 240, 208.4, 2.9957, 6, 3.0035, 2.9957, 2.7298, 10500], # 0.6h
[ 24, 6, 3, 624, 2496, 224, 204.0, 2.9911, 6, 3.1510, 2.9898, 2.7170, 10500], # 0.5h
[ 24, 6, 3, 624, 2496, 208, 199.7, 2.9866, 6, 2.9946, 2.9856, 2.6772, 10500], # 0.5h
[ 24, 6, 3, 624, 2496, 192, 195.4, 2.9868, 7, 2.9950, 2.9868, 2.6587, 10500], # 0.5h
[ 24, 6, 3, 624, 2496, 176, 191.1, 2.9865, 5, 3.0691, 2.9862, 2.7353, 10500], # 0.5h
[ 24, 6, 3, 624, 2496, 160, 186.8, 2.9904, 7, 2.9923, 2.9881, 2.6731, 10500], # 0.5h

[ 24, 6, 3, 600, 2400, 288, 208.6, 2.9827, 7, 2.9886,+2.9827, 2.6715, 10500], # 0.7h
[ 24, 6, 3, 600, 2400, 272, 204.5, 2.9813, 7, 2.9861,+2.9813, 2.6591, 10500], # 0.6h
[ 24, 6, 3, 600, 2400, 256, 200.3, 2.9791, 7, 2.9851,+2.9791, 2.6624, 10500], # 0.6h  minGemma-hidden_layers24-att_heads6-kv_heads3-hidden600-intermediate2400-head_dim256-T1024--2026-07-11-04-13
# valx8: 2.9800 +- 0.0058 # torch.Tensor([2.9791, 2.9880, 2.9741, 2.9751, 2.9869, 2.9750, 2.9772, 2.9877, 2.9771]).std()
[ 24, 6, 3, 600, 2400, 240, 196.2, 2.9841, 6, 2.9904,+2.9830, 2.6649, 10500], # 0.6h
[ 24, 6, 3, 600, 2400, 224, 192.1, 2.9927, 7, 2.9976, 2.9927, 2.6705, 10500], # 0.6h
[ 24, 6, 3, 600, 2400, 208, 187.9, 2.9834, 7, 2.9919,+2.9834, 2.7148, 10500], # 0.6h
[ 24, 6, 3, 600, 2400, 192, 183.8, 2.9904, 7, 2.9979, 2.9904, 2.7728, 10500], # 0.5h
[ 24, 6, 3, 600, 2400, 176, 179.6, 2.9879, 6, 2.9961, 2.9879, 2.7079, 10500], # 0.5h
[ 24, 6, 3, 600, 2400, 160, 175.5, 2.9857, 6, 2.9933, 2.9841, 2.7020, 10500], # 0.5h

[ 24, 6, 3, 576, 2304, 288, 196.3, 2.9926, 5, 2.9959, 2.9920, 2.6778, 10500], # 0.6h 14.6G
[ 24, 6, 3, 576, 2304, 272, 192.3, 2.9871, 6, 2.9974, 2.9861, 2.6716, 10500], # 0.6h
[ 24, 6, 3, 576, 2304, 256, 188.4, 2.9888, 6, 2.9984, 2.9888, 2.7943, 10500], # 0.5h
[ 24, 6, 3, 576, 2304, 240, 184.4, 2.9819, 6, 2.9909,+2.9813, 2.6706, 10500], # 0.5h
[ 24, 6, 3, 576, 2304, 224, 180.4, 2.9866, 6, 2.9938, 2.9866, 2.6687, 10500], # 0.5h
[ 24, 6, 3, 576, 2304, 208, 176.4, 2.9831, 7, 2.9889,+2.9831, 2.6830, 10500], # 0.5h
[ 24, 6, 3, 576, 2304, 192, 172.4, 2.9809, 6, 2.9876,+2.9805, 2.6776, 10500], # 0.5h
# valx8: 2.9830 +- 0.0044 # torch.Tensor([2.9805, 2.9842, 2.9847, 2.9923, 2.9830, 2.9827, 2.9776, 2.9843, 2.9776]).std()
[ 24, 6, 3, 576, 2304, 176, 168.4, 2.9883, 6, 2.9958, 2.9879, 2.6708, 10500], # 0.5h
[ 24, 6, 3, 576, 2304, 160, 164.5, 2.9874, 6, 2.9946, 2.9849, 2.7615, 10500], # 0.4h


# local best for H5(1): 2.9788 (valx8: 2.9802)
[ 24, 5, 1, 760, 3040, 288, 267.8, 2.9862, 6, 2.9965, 2.9847, 2.6894, 10500], # 0.7h 17.2G
[ 24, 5, 1, 760, 3040, 272, 264.3, 2.9831, 6, 3.0428,+2.9831, 3.1756, 10500], # 0.7h
[ 24, 5, 1, 760, 3040, 256, 260.8, 2.9914, 5, 3.0181, 2.9914, 3.0500, 10500], # 0.6h
[ 24, 5, 1, 760, 3040, 240, 257.3, 2.9853, 7, 3.1562, 2.9853, 2.6798, 10500], # 0.6h 17.0G
[ 24, 5, 1, 760, 3040, 224, 253.8, 2.9931, 5, 2.9936, 2.9917, 2.7589, 10500], # 0.6h 16.8G
[ 24, 5, 1, 760, 3040, 208, 250.3, 2.9923, 6, 3.1719, 2.9903, 2.7154, 10500], # 0.6h 16.7G
[ 24, 5, 1, 760, 3040, 192, 246.8, 2.9932, 7, 3.0025, 2.9932, 2.6983, 10500], # 0.6h
[ 24, 5, 1, 760, 3040, 176, 243.3, 2.9887, 7, 3.0906, 2.9887, 2.7736, 10500], # 0.6h
[ 24, 5, 1, 760, 3040, 160, 239.8, 2.9996, 5, 3.1388, 2.9979, 2.9879, 10500], # 0.5h 16.5G

[ 24, 5, 1, 720, 2880, 288, 245.4, 2.9826, 7, 2.9907,+2.9826, 3.3049, 10500], # 0.6h
[ 24, 5, 1, 720, 2880, 272, 242.1, 2.9963, 4, 3.0379, 2.9962, 2.8126, 10500], # 0.6h
[ 24, 5, 1, 720, 2880, 256, 238.8, 2.9927, 7, 3.1604, 2.9927, 2.8102, 10500], # 0.6h 16.6G
[ 24, 5, 1, 720, 2880, 240, 235.4, 2.9855, 6, 2.9925, 2.9855, 3.1269, 10500], # 0.6h 16.6G
[ 24, 5, 1, 720, 2880, 224, 232.1, 2.9815, 7, 2.9890,+2.9815, 2.6933, 10500], # 0.6h 16.5G
[ 24, 5, 1, 720, 2880, 208, 228.8, 2.9909, 6, 2.9979, 2.9909, 3.1683, 10500], # 0.5h
[ 24, 5, 1, 720, 2880, 192, 225.5, 2.9840, 7, 2.9902, 2.9840, 2.6921, 10500], # 0.5h
[ 24, 5, 1, 720, 2880, 176, 222.2, 2.9852, 6, 2.9984,+2.9836, 2.7262, 10500], # 0.5h 16.1G
[ 24, 5, 1, 720, 2880, 160, 218.9, 3.0040, 4, 3.1067, 3.0040, 2.9946, 10500], # 0.5h

[ 24, 5, 1, 680, 2720, 288, 223.9, 2.9864, 6, 3.0001, 2.9864, 3.0332, 10500], # 0.6h
[ 24, 5, 1, 680, 2720, 272, 220.8, 2.9930, 7, 3.0022, 2.9930, 2.7756, 10500], # 0.6h 16.2G
[ 24, 5, 1, 680, 2720, 256, 217.7, 2.9914, 6, 2.9931, 2.9905, 2.9184, 10500], # 0.6h 16.2G
[ 24, 5, 1, 680, 2720, 240, 214.5, 2.9869, 7, 2.9938, 2.9869, 3.1399, 10500], # 0.6h
[ 24, 5, 1, 680, 2720, 224, 211.4, 2.9907, 5, 2.9956, 2.9907, 3.1703, 10500], # 0.6h
[ 24, 5, 1, 680, 2720, 208, 208.3, 2.9910, 6, 2.9966, 2.9910, 2.8700, 10500], # 0.5h
[ 24, 5, 1, 680, 2720, 192, 205.1, 2.9897, 6, 3.0020, 2.9897, 2.9696, 10500], # 0.5h 15.7G
[ 24, 5, 1, 680, 2720, 176, 202.0, 2.9850, 7, 3.1169, 2.9850, 2.7578, 10500], # 0.5h
[ 24, 5, 1, 680, 2720, 160, 198.9, 2.9897, 6, 3.0887, 2.9885, 2.7121, 10500], # 0.5h

[ 24, 5, 1, 640, 2560, 288, 203.4, 2.9822, 7, 2.9896,+2.9822, 2.6553, 10500], # 0.6h
[+24, 5, 1, 640, 2560, 272, 200.4, 2.9788, 7, 2.9833,+2.9788, 2.7560, 10500], # 0.6h  minGemma-hidden_layers24-att_heads5-kv_heads1-hidden640-intermediate2560-head_dim272-T1024--2026-07-19-17-26
# valx8: 2.9802 +- 0.0027 # torch.Tensor([2.9788, 2.9810, 2.9795, 2.9818, 2.9834, 2.9848, 2.9777, 2.9781, 2.9769]).std()
[ 24, 5, 1, 640, 2560, 256, 197.5, 2.9825, 6, 2.9889,+2.9823, 2.7556, 10500], # 0.5h
[ 24, 5, 1, 640, 2560, 240, 194.5, 2.9860, 6, 2.9926, 2.9860, 3.1517, 10500], # 0.5h
[ 24, 5, 1, 640, 2560, 224, 191.6, 2.9845, 6, 2.9900,+2.9823, 2.6855, 10500], # 0.5h
[ 24, 5, 1, 640, 2560, 208, 188.6, 2.9884, 6, 2.9943, 2.9861, 2.7039, 10500], # 0.5h
[ 24, 5, 1, 640, 2560, 192, 185.7, 3.0004, 5, 3.0005, 2.9990, 2.6865, 10500], # 0.5h 14.2G
[ 24, 5, 1, 640, 2560, 176, 182.7, 2.9842, 7, 2.9932, 2.9842, 2.6561, 10500], # 0.5h
[ 24, 5, 1, 640, 2560, 160, 179.8, 2.9953, 7, 2.9999, 2.9953, 2.6811, 10500], # 0.5h

[ 24, 5, 1, 600, 2400, 288, 183.8, 2.9824, 7, 2.9877,+2.9824, 2.6672, 10500], # 0.6h 14.5G
[ 24, 5, 1, 600, 2400, 272, 181.0, 2.9908, 5, 2.9920, 2.9908, 3.0769, 10500], # 0.6h
[ 24, 5, 1, 600, 2400, 256, 178.2, 2.9935, 5, 2.9990, 2.9935, 3.1917, 10500], # 0.5h
[ 24, 5, 1, 600, 2400, 240, 175.5, 2.9898, 6, 2.9952, 2.9896, 2.7224, 10500], # 0.5h
[ 24, 5, 1, 600, 2400, 224, 172.7, 2.9893, 6, 2.9980, 2.9893, 3.2068, 10500], # 0.5h
[ 24, 5, 1, 600, 2400, 208, 169.9, 2.9867, 6, 2.9928, 2.9854, 2.6737, 10500], # 0.5h 14.1G
[ 24, 5, 1, 600, 2400, 192, 167.2, 2.9844, 7, 2.9903, 2.9844, 2.6944, 10500], # 0.5h
[ 24, 5, 1, 600, 2400, 176, 164.4, 2.9795, 6, 3.1032,+2.9795, 3.2620, 10500], # 0.5h  minGemma-hidden_layers24-att_heads5-kv_heads1-hidden600-intermediate2400-head_dim176-T1024--2026-07-22-20-37
# valx8: 2.9808 +- 0.0026 # torch.Tensor([2.9795, 2.9751, 2.9823, 2.9833, 2.9798, 2.9818, 2.9818, 2.9837, 2.9801]).std()
[ 24, 5, 1, 600, 2400, 160, 161.6, 2.9857, 7, 2.9919, 2.9857, 2.7406, 10500], # 0.5h

[ 24, 5, 1, 560, 2240, 288, 165.1, 2.9928, 6, 2.9999, 2.9909, 2.6694, 10500], # 0.5h
[ 24, 5, 1, 560, 2240, 272, 162.5, 2.9899, 6, 3.0001, 2.9887, 2.6631, 10500], # 0.5h
[ 24, 5, 1, 560, 2240, 256, 159.9, 2.9868, 6, 2.9941, 2.9868, 2.6689, 10500], # 0.5h 13.5G
[ 24, 5, 1, 560, 2240, 240, 157.3, 2.9904, 7, 2.9977, 2.9904, 2.6639, 10500], # 0.5h
[ 24, 5, 1, 560, 2240, 224, 154.7, 2.9883, 6, 2.9942, 2.9873, 2.6735, 10500], # 0.5h
[ 24, 5, 1, 560, 2240, 208, 152.2, 2.9928, 6, 3.0000, 2.9916, 2.7420, 10500], # 0.5h
[ 24, 5, 1, 560, 2240, 192, 149.6, 2.9900, 6, 2.9962, 2.9900, 2.6831, 10500], # 0.4h
[ 24, 5, 1, 560, 2240, 176, 147.0, 3.0013, 6, 3.0097, 3.0011, 2.6760, 10500], # 0.4h 13.4G
[ 24, 5, 1, 560, 2240, 160, 144.4, 2.9948, 6, 3.1747, 2.9944, 2.7912, 10500], # 0.4h

In [183]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  24 # 8 # G28 G18 #blocks
num_attention_heads = 7 # 4 # G16 G8
num_key_value_heads = 1 # 4 # G16 G1
hidden_size = num_attention_heads*116 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 256 # 32 # G256 # dim in attention
rms_norm_eps = 1e0 # 1e-6
rope_theta = 80000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//2; N_step=5250*2; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=10.0e-4, weight_decay=1.8, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(5000*2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9837:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

64.512
L24 att7 kv_heads1 hidden812 intermediate3248 head_dim256 T1024

1 4.715565104166667 tensor(3.1541)

2 2.834967075892857 tensor(3.0047)

3 2.803708705357143 tensor(2.9892)

4 2.9470543154761906 tensor(3.0063)
back to previous

5 2.8548102678571428 tensor(2.9853)

6 2.8259968377976192 tensor(2.9781)

7 2.8370403645833333 tensor(2.9963)
back to previous

8 2.6812291666666668 tensor(2.9852)
[ 24, 7, 1, 812, 3248, 256, 310.7, 2.9781, 7, 2.9852, 2.9781, 2.8370, 10500],

In [238]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  24 # 8 # G28 G18 #blocks
num_attention_heads = 7 # 4 # G16 G8
num_key_value_heads = 1 # 4 # G16 G1
hidden_size = num_attention_heads*92 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 240 # 32 # G256 # dim in attention
rms_norm_eps = 1e0 # 1e-6
rope_theta = 80000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//2; N_step=5250*2; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=10.0e-4, weight_decay=1.8, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(5000*2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9837:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

64.512
L24 att7 kv_heads1 hidden644 intermediate2576 head_dim240 T1024

1 4.531771205357143 tensor(3.2337)

2 2.8078238467261905 tensor(3.0167)

3 2.7235699404761906 tensor(2.9893)

4 2.6930987723214286 tensor(2.9834)

5 2.8428404017857143 tensor(2.9776)

6 2.839091145833333 tensor(2.9789)

7 2.6671307663690476 tensor(2.9851)
[ 24, 7, 1, 644, 2576, 240, 211.3, 2.9789, 6, 2.9851, 2.9776, 2.8391, 10500],

In [244]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  24 # 8 # G28 G18 #blocks
num_attention_heads = 7 # 4 # G16 G8
num_key_value_heads = 1 # 4 # G16 G1
hidden_size = num_attention_heads*88 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 288 # 32 # G256 # dim in attention
rms_norm_eps = 1e0 # 1e-6
rope_theta = 80000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//2; N_step=5250*2; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=10.0e-4, weight_decay=1.8, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(5000*2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9837:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

64.512
L24 att7 kv_heads1 hidden616 intermediate2464 head_dim288 T1024

1 4.512943080357143 tensor(3.2515)

2 2.8218645833333333 tensor(3.0244)

3 2.7125825892857143 tensor(2.9905)

4 2.6852198660714284 tensor(2.9822)

5 2.6690504092261906 tensor(2.9780)

6 2.660184337797619 tensor(2.9765)

7 2.6495174851190475 tensor(2.9844)
back to previous

8 2.654231398809524 tensor(2.9839)
[ 24, 7, 1, 616, 2464, 288, 208.5, 2.9765, 7, 2.9839, 2.9765, 2.6495, 10500],

In [275]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  24 # 8 # G28 G18 #blocks
num_attention_heads = 6 # 4 # G16 G8
num_key_value_heads = 3 # 4 # G16 G1
hidden_size = num_attention_heads*132 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 224 # 32 # G256 # dim in attention
rms_norm_eps = 1e0 # 1e-6
rope_theta = 80000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//2; N_step=5250*2; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=10.0e-4, weight_decay=1.8, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(5000*2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9837:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

64.512
L24 att6 kv_heads3 hidden792 intermediate3168 head_dim224 T1024

1 4.790052083333333 tensor(3.1684)

2 2.7860712425595238 tensor(3.0063)

3 2.8108846726190477 tensor(2.9910)

4 2.7308792782738096 tensor(2.9862)

5 2.6914090401785713 tensor(2.9809)

6 2.6716264880952383 tensor(2.9792)

7 3.10570703125 tensor(3.0933)
back to previous

8 3.1524676339285715 tensor(3.0927)
[ 24, 6, 3, 792, 3168, 224, 297.3, 2.9792, 7, 3.0927, 2.9792, 3.1057, 10500],

In [80]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  24 # 8 # G28 G18 #blocks
num_attention_heads = 6 # 4 # G16 G8
num_key_value_heads = 3 # 4 # G16 G1
hidden_size = num_attention_heads*128 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 240 # 32 # G256 # dim in attention
rms_norm_eps = 1e0 # 1e-6
rope_theta = 80000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//2; N_step=5250*2; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=10.0e-4, weight_decay=1.8, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(5000*2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9837:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

64.512
L24 att6 kv_heads3 hidden768 intermediate3072 head_dim240 T1024

1 4.697032366071428 tensor(3.1942)

2 2.790424293154762 tensor(3.0086)

3 3.055189918154762 tensor(3.0311)
back to previous

4 2.713780319940476 tensor(2.9890)

5 2.690801525297619 tensor(2.9789)

6 2.8508067336309524 tensor(2.9844)
back to previous

7 2.7043348214285716 tensor(2.9855)
[ 24, 6, 3, 768, 3072, 240, 288.3, 2.9789, 6, 2.9855, 2.9789, 2.8508, 10500],

In [280]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  24 # 8 # G28 G18 #blocks
num_attention_heads = 6 # 4 # G16 G8
num_key_value_heads = 3 # 4 # G16 G1
hidden_size = num_attention_heads*124 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 288 # 32 # G256 # dim in attention
rms_norm_eps = 1e0 # 1e-6
rope_theta = 80000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//2; N_step=5250*2; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=10.0e-4, weight_decay=1.8, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(5000*2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9837:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

64.512
L24 att6 kv_heads3 hidden744 intermediate2976 head_dim288 T1024

1 4.619083333333333 tensor(3.1759)

2 2.784838355654762 tensor(3.0055)

3 2.7089603794642856 tensor(2.9866)

4 2.7026242559523808 tensor(2.9806)

5 2.686528087797619 tensor(2.9783)

6 2.671006324404762 tensor(2.9782)

7 3.338979910714286 tensor(3.2118)
back to previous

8 2.6598370535714286 tensor(2.9834)
[ 24, 6, 3, 744, 2976, 288, 289.6, 2.9782, 7, 2.9834, 2.9782, 3.3390, 10500],

In [74]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  24 # 8 # G28 G18 #blocks
num_attention_heads = 6 # 4 # G16 G8
num_key_value_heads = 3 # 4 # G16 G1
hidden_size = num_attention_heads*120 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 288 # 32 # G256 # dim in attention
rms_norm_eps = 1e0 # 1e-6
rope_theta = 80000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//2; N_step=5250*2; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=10.0e-4, weight_decay=1.8, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(5000*2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9837:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

64.512
L24 att6 kv_heads3 hidden720 intermediate2880 head_dim288 T1024

1 4.692092633928572 tensor(3.1876)

2 2.797539992559524 tensor(3.0043)

3 2.702375744047619 tensor(2.9859)

4 2.7068764880952383 tensor(2.9814)

5 3.0059603794642857 tensor(3.0254)
back to previous

6 2.6820321800595237 tensor(2.9782)

7 2.6538363095238093 tensor(2.9860)
back to previous

8 2.7136512276785716 tensor(2.9870)
[ 24, 6, 3, 720, 2880, 288, 275.3, 2.9782, 7, 2.9870, 2.9782, 2.6538, 10500],

In [63]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  24 # 8 # G28 G18 #blocks
num_attention_heads = 6 # 4 # G16 G8
num_key_value_heads = 3 # 4 # G16 G1
hidden_size = num_attention_heads*112 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 256 # 32 # G256 # dim in attention
rms_norm_eps = 1e0 # 1e-6
rope_theta = 80000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//2; N_step=5250*2; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=10.0e-4, weight_decay=1.8, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(5000*2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9837:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

64.512
L24 att6 kv_heads3 hidden672 intermediate2688 head_dim256 T1024

1 4.622747023809524 tensor(3.2290)

2 2.8037832961309523 tensor(3.0152)

3 2.715727864583333 tensor(2.9900)

4 2.688521019345238 tensor(2.9809)

5 2.9081941964285716 tensor(2.9785)

6 3.4284572172619048 tensor(3.3062)
back to previous

7 3.140238467261905 tensor(3.0952)
[ 24, 6, 3, 672, 2688, 256, 238.3, 2.9785, 6, 3.0952, 2.9785, 3.4285, 10500],

In [62]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  24 # 8 # G28 G18 #blocks
num_attention_heads = 6 # 4 # G16 G8
num_key_value_heads = 3 # 4 # G16 G1
hidden_size = num_attention_heads*112 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 240 # 32 # G256 # dim in attention
rms_norm_eps = 1e0 # 1e-6
rope_theta = 80000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//2; N_step=5250*2; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=10.0e-4, weight_decay=1.8, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(5000*2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9837:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

64.512
L24 att6 kv_heads3 hidden672 intermediate2688 head_dim240 T1024

1 4.590160342261905 tensor(3.2579)

2 2.814350632440476 tensor(3.0130)

3 2.7155360863095237 tensor(2.9886)

4 2.6909825148809525 tensor(2.9809)

5 2.688620907738095 tensor(2.9761)

6 3.009963169642857 tensor(3.0377)
back to previous

7 2.6707470238095237 tensor(2.9828)
[ 24, 6, 3, 672, 2688, 240, 233.7, 2.9761, 6, 2.9828, 2.9761, 3.0100, 10500],

In [54]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  24 # 8 # G28 G18 #blocks
num_attention_heads = 6 # 4 # G16 G8
num_key_value_heads = 3 # 4 # G16 G1
hidden_size = num_attention_heads*104 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 256 # 32 # G256 # dim in attention
rms_norm_eps = 1e0 # 1e-6
rope_theta = 80000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//2; N_step=5250*2; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=10.0e-4, weight_decay=1.8, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(5000*2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9837:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

64.512
L24 att6 kv_heads3 hidden624 intermediate2496 head_dim256 T1024

1 4.5999300595238095 tensor(3.2687)

2 2.8303238467261904 tensor(3.0193)

3 2.7329827008928573 tensor(2.9900)

4 2.757167224702381 tensor(2.9835)

5 2.6836566220238094 tensor(2.9786)

6 2.73988671875 tensor(2.9813)
back to previous

7 2.698894345238095 tensor(2.9839)
[ 24, 6, 3, 624, 2496, 256, 212.7, 2.9786, 6, 2.9839, 2.9786, 2.7399, 10500],

In [309]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  24 # 8 # G28 G18 #blocks
num_attention_heads = 6 # 4 # G16 G8
num_key_value_heads = 3 # 4 # G16 G1
hidden_size = num_attention_heads*100 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 256 # 32 # G256 # dim in attention
rms_norm_eps = 1e0 # 1e-6
rope_theta = 80000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//2; N_step=5250*2; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=10.0e-4, weight_decay=1.8, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(5000*2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9837:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

64.512
L24 att6 kv_heads3 hidden600 intermediate2400 head_dim256 T1024

1 4.483826264880952 tensor(3.2396)

2 2.82007421875 tensor(3.0250)

3 2.723245163690476 tensor(2.9934)

4 2.708154947916667 tensor(2.9845)

5 2.6889940476190475 tensor(2.9808)

6 2.6781365327380953 tensor(2.9791)

7 2.6624313616071427 tensor(2.9858)
back to previous

8 2.6683755580357142 tensor(2.9851)
[ 24, 6, 3, 600, 2400, 256, 200.3, 2.9791, 7, 2.9851, 2.9791, 2.6624, 10500],

In [13]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  24 # 8 # G28 G18 #blocks
num_attention_heads = 5 # 4 # G16 G8
num_key_value_heads = 1 # 4 # G16 G1
hidden_size = num_attention_heads*128 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 272 # 32 # G256 # dim in attention
rms_norm_eps = 1e0 # 1e-6
rope_theta = 80000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//2; N_step=5250*2; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=10.0e-4, weight_decay=1.8, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(5000*2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9837:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

64.512
L24 att5 kv_heads1 hidden640 intermediate2560 head_dim272 T1024

1 4.451273809523809 tensor(3.2263)

2 2.8007100074404763 tensor(3.0130)

3 2.710435825892857 tensor(2.9899)

4 2.734375558035714 tensor(2.9838)

5 3.0822838541666666 tensor(3.0205)
back to previous

6 2.680788318452381 tensor(2.9788)

7 2.755954427083333 tensor(2.9876)
back to previous

8 2.7143470982142857 tensor(2.9833)
[ 24, 5, 1, 640, 2560, 272, 200.4, 2.9788, 7, 2.9833, 2.9788, 2.7560, 10500],

In [28]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  24 # 8 # G28 G18 #blocks
num_attention_heads = 5 # 4 # G16 G8
num_key_value_heads = 1 # 4 # G16 G1
hidden_size = num_attention_heads*120 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 176 # 32 # G256 # dim in attention
rms_norm_eps = 1e0 # 1e-6
rope_theta = 80000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//2; N_step=5250*2; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=10.0e-4, weight_decay=1.8, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(5000*2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9837:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

64.512
L24 att5 kv_heads1 hidden600 intermediate2400 head_dim176 T1024

1 4.582751488095238 tensor(3.2642)

2 2.8279051339285712 tensor(3.0257)

3 2.744186569940476 tensor(2.9932)

4 2.7116729910714286 tensor(2.9836)

5 2.7055885416666667 tensor(2.9795)

6 3.262033110119048 tensor(3.1331)
back to previous

7 3.191913318452381 tensor(3.1032)
[ 24, 5, 1, 600, 2400, 176, 164.4, 2.9795, 6, 3.1032, 2.9795, 3.2620, 10500],

# L20

In [ ]:
# L20 FORGETTER T1024 Baby10M (default: B12//2 N5250 lr10e-4 WD1.8) # H9(3): 2.9815, H8(4): 2.9807, H6(3): 2.9775, H7(1)&H5(1): worse than H6(3) (2.9917@env1V1old)

# local best for H9(3): 2.9777 (valx8: 2.9815)
[ 20, 9, 3, 792, 3168, 288, 300.0, 2.9899, 7, 2.9925, 2.9899, 2.6534, 10500], # 1.5h 17.4G
[ 20, 9, 3, 792, 3168, 272, 293.9, 2.9895, 7, 2.9917, 2.9895, 2.6561, 10500], # 1.5h
[ 20, 9, 3, 792, 3168, 256, 287.8, 2.9833, 7, 2.9845,+2.9833, 2.6509, 10500], # 1.4h
[ 20, 9, 3, 792, 3168, 240, 281.8, 2.9919, 4, 2.9923, 2.9919, 2.6778, 10500], # 1.4h
[ 20, 9, 3, 792, 3168, 224, 275.7, 2.9955, 8, 2.9973, 2.9933, 2.6640, 10500], # 1.3h
[ 20, 9, 3, 792, 3168, 208, 269.6, 2.9834, 6, 2.9868,+2.9834, 2.7628, 10500], # 1.3h
[ 20, 9, 3, 792, 3168, 192, 263.5, 2.9914, 6, 2.9962, 2.9913, 2.6920, 10500], # 1.2h
[ 20, 9, 3, 792, 3168, 176, 257.4, 2.9854, 7, 3.1507, 2.9852, 2.6924, 10500], # 1.2h 16.2G
[ 20, 9, 3, 792, 3168, 160, 251.3, 2.9864, 6, 2.9896, 2.9860, 2.6737, 10500], # 1.2h

[ 20, 9, 3, 756, 3024, 288, 279.8, 2.9839, 6, 2.9902, 2.9839, 2.6689, 10500], # 1.4h
[ 20, 9, 3, 756, 3024, 272, 274.0, 2.9870, 7, 2.9898, 2.9870, 2.6499, 10500], # 1.4h
[ 20, 9, 3, 756, 3024, 256, 268.2, 2.9867, 6, 2.9897, 2.9865, 2.6689, 10500], # 1.3h
[ 20, 9, 3, 756, 3024, 240, 262.4, 2.9881, 7, 2.9890, 2.9881, 2.6493, 10500], # 1.3h
[ 20, 9, 3, 756, 3024, 224, 256.6, 2.9821, 7, 2.9897,+2.9821, 2.6626, 10500], # 1.2h
[+20, 9, 3, 756, 3024, 208, 250.8, 2.9777, 9, 2.9813,+2.9777, 2.7850, 10500], # 1.2h  minGemma-hidden_layers20-att_heads9-kv_heads3-hidden756-intermediate3024-head_dim208-T1024--2026-04-30-02-29
# 2.9828 +- 0.0046 # torch.Tensor([2.9845, 2.9856, 2.9875, 2.9876, 2.9768, 2.9848, 2.9788, 2.9767]).std()
# (2nd: 2.9813)                                                                       minGemma-hidden_layers20-att_heads9-kv_heads3-hidden756-intermediate3024-head_dim208-T1024--2026-04-30-05-47
# 2.9815 +- 0.0049 # torch.Tensor([2.9823, 2.9866, 2.9771, 2.9849, 2.9881, 2.9788, 2.9801, 2.9741]).std()
[ 20, 9, 3, 756, 3024, 192, 245.0, 2.9903,11, 2.9906, 2.9882, 2.7060, 10500], # 1.1h
[ 20, 9, 3, 756, 3024, 176, 239.2, 2.9850,10, 2.9872, 2.9846, 2.6697, 10500], # 1.1h
[ 20, 9, 3, 756, 3024, 160, 233.4, 2.9918, 7, 3.1128, 2.9918, 3.1725, 10500], # 1.1h

[ 20, 9, 3, 720, 2880, 288, 260.3, 2.9897, 6, 3.1111, 2.9884, 2.6916, 10500], # 1.4h 16.7G
[ 20, 9, 3, 720, 2880, 272, 254.8, 2.9852, 6, 2.9890, 2.9841, 2.6613, 10500], # 1.4h
[ 20, 9, 3, 720, 2880, 256, 249.2, 2.9923, 6, 2.9979, 2.9920, 2.6690, 10500], # 1.2h
[ 20, 9, 3, 720, 2880, 240, 243.7, 2.9833, 7, 2.9869,+2.9833, 2.6535, 10500], # 1.2h
[ 20, 9, 3, 720, 2880, 224, 238.2, 2.9812, 7, 2.9838,+2.9812, 2.6542, 10500], # 1.2h
[ 20, 9, 3, 720, 2880, 208, 232.6, 2.9839, 6, 2.9870, 2.9839, 2.8156, 10500], # 1.2h
[ 20, 9, 3, 720, 2880, 192, 227.1, 2.9925, 7, 2.9941, 2.9925, 2.6516, 10500], # 1.1h
[ 20, 9, 3, 720, 2880, 176, 221.6, 2.9864, 7, 2.9911, 2.9864, 3.1533, 10500], # 1.1h
[ 20, 9, 3, 720, 2880, 160, 216.1, 2.9865, 6, 2.9884, 2.9865, 3.1203, 10500], # 1.0h

[ 20, 9, 3, 684, 2736, 288, 241.4, 2.9902, 4, 2.9908, 2.9886, 2.6895, 10500], # 1.4h
[ 20, 9, 3, 684, 2736, 272, 236.1, 2.9864, 6, 2.9885, 2.9862, 2.6633, 10500], # 1.3h 16.2G
[ 20, 9, 3, 684, 2736, 256, 230.9, 2.9872, 6, 2.9904, 2.9871, 2.6700, 10500], # 1.2h 16.0G
[ 20, 9, 3, 684, 2736, 240, 225.6, 2.9873, 6, 2.9886, 2.9863, 2.6839, 10500], # 1.2h 15.9G
[ 20, 9, 3, 684, 2736, 224, 220.4, 2.9859, 7, 2.9870, 2.9859, 2.6552, 10500], # 1.2h
[ 20, 9, 3, 684, 2736, 208, 215.1, 2.9837, 7, 2.9862, 2.9837, 2.6610, 10500], # 1.1h
[ 20, 9, 3, 684, 2736, 192, 209.8, 2.9909, 6, 2.9962, 2.9904, 2.7059, 10500], # 1.1h
[ 20, 9, 3, 684, 2736, 176, 204.6, 2.9841, 7, 2.9861, 2.9841, 2.6769, 10500], # 1.1h
[ 20, 9, 3, 684, 2736, 160, 199.3, 2.9855, 6, 2.9885, 2.9845, 2.7733, 10500], # 1.0h

[ 20, 9, 3, 648, 2592, 288, 223.1, 2.9829, 6, 2.9902,+2.9819, 2.6635, 10500], # 1.3h
[ 20, 9, 3, 648, 2592, 272, 218.1, 2.9973, 6, 3.0026, 2.9964, 2.6663, 10500], # 1.3h
[ 20, 9, 3, 648, 2592, 256, 213.1, 2.9867, 6, 2.9926, 2.9867, 2.6612, 10500], # 1.2h
[ 20, 9, 3, 648, 2592, 240, 208.1, 2.9881, 7, 2.9907, 2.9881, 2.6516, 10500], # 1.2h
[ 20, 9, 3, 648, 2592, 224, 203.2, 2.9850, 6, 2.9884, 2.9847, 2.6675, 10500], # 1.1h 14.3G
[ 20, 9, 3, 648, 2592, 208, 198.2, 2.9942, 5, 2.9948, 2.9937, 2.6874, 10500], # 1.1h
[ 20, 9, 3, 648, 2592, 192, 193.2, 2.9859, 6, 2.9914, 2.9859, 3.1850, 10500], # 1.0h
[ 20, 9, 3, 648, 2592, 176, 188.2, 2.9822, 6, 2.9866,+2.9822, 3.2338, 10500], # 1.0h
[ 20, 9, 3, 648, 2592, 160, 183.3, 2.9858, 7, 3.1563, 2.9858, 2.6637, 10500], # 1.0h

[ 20, 9, 3, 612, 2448, 288, 205.4, 2.9869, 6, 2.9926, 2.9869, 2.6663, 10500], # 1.3h 14.6G
[ 20, 9, 3, 612, 2448, 272, 200.7, 2.9872, 6, 2.9900, 2.9868, 2.6717, 10500], # 1.2h
[ 20, 9, 3, 612, 2448, 256, 196.0, 2.9876, 6, 2.9938, 2.9865, 2.6706, 10500], # 1.1h
[ 20, 9, 3, 612, 2448, 240, 191.3, 2.9860, 7, 2.9882, 2.9860, 2.6555, 10500], # 1.1h 14.0G
[ 20, 9, 3, 612, 2448, 224, 186.6, 2.9943, 6, 2.9983, 2.9943, 3.1298, 10500], # 1.1h
[ 20, 9, 3, 612, 2448, 208, 181.9, 2.9889,10, 2.9891, 2.9880, 2.6644, 10500], # 1.0h
[ 20, 9, 3, 612, 2448, 192, 177.2, 2.9921, 6, 2.9975, 2.9911, 2.6695, 10500], # 1.0h 13.5G
[ 20, 9, 3, 612, 2448, 176, 172.5, 2.9917, 6, 2.9959, 2.9902, 2.6663, 10500], # 0.9h
[ 20, 9, 3, 612, 2448, 160, 167.8, 2.9932, 6, 2.9972, 2.9923, 2.6711, 10500], # 0.9h

[ 20, 9, 3, 576, 2304, 288, 188.3, 2.9994, 6, 3.0051, 2.9977, 2.6690, 10500], # 1.2h 14.1G
[ 20, 9, 3, 576, 2304, 272, 183.9, 2.9904, 7, 2.9933, 2.9904, 2.6543, 10500], # 1.2h
[ 20, 9, 3, 576, 2304, 256, 179.5, 2.9948, 7, 2.9985, 2.9948, 2.6566, 10500], # 1.1h 13.7G
[ 20, 9, 3, 576, 2304, 240, 175.1, 2.9953, 6, 3.0023, 2.9940, 2.6647, 10500], # 1.1h
[ 20, 9, 3, 576, 2304, 224, 170.6, 2.9836, 7, 2.9870,+2.9836, 2.6710, 10500], # 1.0h
[ 20, 9, 3, 576, 2304, 208, 166.2, 2.9914, 7, 2.9939, 2.9914, 2.6660, 10500], # 1.0h
[ 20, 9, 3, 576, 2304, 192, 161.8, 2.9904, 7, 2.9928, 2.9904, 2.6634, 10500], # 0.9h
[ 20, 9, 3, 576, 2304, 176, 157.4, 2.9906, 6, 2.9951, 2.9905, 2.6677, 10500], # 0.9h
[ 20, 9, 3, 576, 2304, 160, 152.9, 2.9901, 6, 2.9940, 2.9893, 2.6705, 10500], # 0.9h


# local best for H8(4): 2.9778 (valx8: 2.9807)
[ 20, 8, 4, 800, 3200, 288, 304.6, 2.9838, 6, 2.9975, 2.9838, 3.1105, 10500], # 1.5h 18.2G
[ 20, 8, 4, 800, 3200, 272, 298.4, 2.9840, 7, 2.9925, 2.9840, 2.6961, 10500], # 1.5h
[ 20, 8, 4, 800, 3200, 256, 292.3, 2.9848, 6, 2.9911, 2.9848, 2.6837, 10500], # 1.4h
[ 20, 8, 4, 800, 3200, 240, 286.1, 2.9824, 7, 2.9900,+2.9824, 2.6761, 10500], # 1.3h 16.8G
[ 20, 8, 4, 800, 3200, 224, 280.0, 2.9811, 7, 2.9878,+2.9811, 2.6651, 10500], # 1.3h
[ 20, 8, 4, 800, 3200, 208, 273.9, 2.9863, 6, 2.9910, 2.9863, 3.1446, 10500], # 1.3h
[ 20, 8, 4, 800, 3200, 192, 267.7, 2.9813, 7, 2.9877,+2.9813, 2.6932, 10500], # 1.2h
[ 20, 8, 4, 800, 3200, 176, 261.6, 2.9851, 6, 2.9914, 2.9849, 2.6706, 10500], # 1.2h 16.4G
[ 20, 8, 4, 800, 3200, 160, 255.4, 2.9861, 7, 2.9893, 2.9861, 2.7154, 10500], # 1.1h

[ 20, 8, 4, 768, 3072, 288, 286.5, 2.9843, 6, 2.9908, 2.9843, 2.7001, 10500], # 1.4h
[ 20, 8, 4, 768, 3072, 272, 280.6, 2.9846, 6, 2.9910, 2.9845, 2.6649, 10500], # 1.4h
[ 20, 8, 4, 768, 3072, 256, 274.7, 2.9832, 6, 2.9891,+2.9828, 2.6730, 10500], # 1.2h
[ 20, 8, 4, 768, 3072, 240, 268.8, 2.9865, 6, 3.0092, 2.9849, 2.6732, 10500], # 1.2h
[ 20, 8, 4, 768, 3072, 224, 262.9, 2.9850, 6, 2.9902, 2.9845, 2.6662, 10500], # 1.2h
[ 20, 8, 4, 768, 3072, 208, 257.0, 2.9854, 6, 2.9925, 2.9840, 2.6721, 10500], # 1.2h 16.2G
[ 20, 8, 4, 768, 3072, 192, 251.1, 2.9822, 6, 2.9963,+2.9822, 3.1737, 10500], # 1.1h
[ 20, 8, 4, 768, 3072, 176, 245.2, 2.9896, 7, 2.9967, 2.9896, 2.6803, 10500], # 1.1h
[ 20, 8, 4, 768, 3072, 160, 239.3, 2.9855, 7, 2.9900, 2.9855, 2.6982, 10500], # 1.0h

[ 20, 8, 4, 736, 2944, 288, 268.9, 2.9850, 6, 3.1089,+2.9834, 2.7069, 10500], # 1.4h
[ 20, 8, 4, 736, 2944, 272, 263.3, 2.9871, 6, 2.9925, 2.9868, 2.6705, 10500], # 1.3h
[ 20, 8, 4, 736, 2944, 256, 257.6, 2.9841, 7, 2.9925, 2.9841, 3.1808, 10500], # 1.2h
[ 20, 8, 4, 736, 2944, 240, 251.9, 2.9806, 6, 2.9850,+2.9792, 2.6701, 10500], # 1.2h
# valx8: 2.9818 +- 0.0053 # torch.Tensor([2.9792, 2.9807, 2.9852, 2.9835, 2.9734, 2.9900, 2.9880, 2.9797, 2.9768]).std()
[ 20, 8, 4, 736, 2944, 224, 246.3, 2.9841, 6, 2.9902, 2.9841, 2.6718, 10500], # 1.2h 16.3G
[ 20, 8, 4, 736, 2944, 208, 240.6, 2.9833, 6, 2.9881,+2.9826, 2.6682, 10500], # 1.1h
[ 20, 8, 4, 736, 2944, 192, 235.0, 2.9884, 7, 2.9922, 2.9884, 2.7241, 10500], # 1.1h
[ 20, 8, 4, 736, 2944, 176, 229.3, 2.9932, 5, 3.1196, 2.9925, 2.6977, 10500], # 1.1h
[ 20, 8, 4, 736, 2944, 160, 223.7, 2.9873, 6, 2.9938, 2.9863, 2.6812, 10500], # 1.0h

[ 20, 8, 4, 704, 2816, 288, 251.8, 2.9830, 6, 2.9892,+2.9821, 2.6685, 10500], # 1.3h
[ 20, 8, 4, 704, 2816, 272, 246.4, 2.9810, 6, 3.0357,+2.9810, 3.1248, 10500], # 1.3h
[ 20, 8, 4, 704, 2816, 256, 241.0, 2.9844, 6, 2.9930, 2.9844, 2.7045, 10500], # 1.2h 16.1G
[ 20, 8, 4, 704, 2816, 240, 235.6, 2.9829, 7, 2.9874,+2.9829, 2.6738, 10500], # 1.2h
[ 20, 8, 4, 704, 2816, 224, 230.2, 2.9835, 6, 2.9876,+2.9823, 2.7687, 10500], # 1.2h
[ 20, 8, 4, 704, 2816, 208, 224.8, 2.9839, 6, 2.9897,+2.9835, 2.6687, 10500], # 1.1h
[ 20, 8, 4, 704, 2816, 192, 219.4, 2.9869, 7, 2.9898, 2.9869, 3.2800, 10500], # 1.1h
[ 20, 8, 4, 704, 2816, 176, 214.0, 2.9855, 7, 2.9918, 2.9855, 2.6571, 10500], # 1.1h
[ 20, 8, 4, 704, 2816, 160, 208.6, 2.9875, 6, 2.9937, 2.9873, 2.7003, 10500], # 1.0h

[ 20, 8, 4, 672, 2688, 288, 235.2, 2.9877, 6, 2.9957, 2.9865, 2.6661, 10500], # 1.3h
[+20, 8, 4, 672, 2688, 272, 230.0, 2.9804, 7, 2.9865,+2.9804, 2.9959, 10500], # 1.3h  minGemma-hidden_layers20-att_heads8-kv_heads4-hidden672-intermediate2688-head_dim272-T1024--2026-06-13-00-02
# valx8: 2.9807 +- 0.0045 # torch.Tensor([2.9804, 2.9755, 2.9821, 2.9888, 2.9738, 2.9789, 2.9831, 2.9843, 2.9796]).std()
[ 20, 8, 4, 672, 2688, 256, 224.9, 2.9828, 5, 2.9831,+2.9818, 2.6997, 10500], # 1.2h
[ 20, 8, 4, 672, 2688, 240, 219.7, 2.9907, 6, 2.9994, 2.9887, 2.6668, 10500], # 1.2h
[ 20, 8, 4, 672, 2688, 224, 214.6, 2.9856, 6, 2.9900, 2.9851, 2.6698, 10500], # 1.1h
[ 20, 8, 4, 672, 2688, 208, 209.4, 2.9802, 6, 2.9894,+2.9787, 2.6678, 10500], # 1.1h  minGemma-hidden_layers20-att_heads8-kv_heads4-hidden672-intermediate2688-head_dim208-T1024--2026-06-14-17-30
# valx8: 2.9815 +- 0.0042 # torch.Tensor([2.9787, 2.9850, 2.9840, 2.9725, 2.9833, 2.9849, 2.9848, 2.9810, 2.9791]).std()
[ 20, 8, 4, 672, 2688, 192, 204.2, 2.9831, 7, 2.9927,+2.9831, 2.6896, 10500], # 1.0h
[ 20, 8, 4, 672, 2688, 176, 199.1, 2.9821, 7, 2.9865,+2.9821, 2.6649, 10500], # 1.0h
[ 20, 8, 4, 672, 2688, 160, 193.9, 2.9800, 7, 2.9858,+2.9800, 2.6749, 10500], # 1.0h
# valx8: 2.9817 +- 0.0061 # torch.Tensor([2.9800, 2.9770, 2.9919, 2.9758, 2.9771, 2.9780, 2.9844, 2.9913, 2.9800]).std()
[ 20, 8, 4, 640, 2560, 288, 219.1, 2.9842, 6, 2.9907,+2.9831, 2.6783, 10500], # 1.3h
[ 20, 8, 4, 640, 2560, 272, 214.2, 2.9872, 6, 2.9934, 2.9871, 2.6735, 10500], # 1.2h
[ 20, 8, 4, 640, 2560, 256, 209.3, 2.9887, 6, 2.9954, 2.9882, 2.6668, 10500], # 1.1h
[ 20, 8, 4, 640, 2560, 240, 204.3, 2.9878, 6, 2.9963, 2.9871, 2.6664, 10500], # 1.1h
[ 20, 8, 4, 640, 2560, 224, 199.4, 2.9825, 7, 2.9871,+2.9825, 2.6654, 10500], # 1.1h
[ 20, 8, 4, 640, 2560, 208, 194.5, 2.9840, 6, 2.9879,+2.9817, 2.6666, 10500], # 1.0h 13.6G
[ 20, 8, 4, 640, 2560, 192, 189.6, 2.9894, 7, 2.9957, 2.9894, 2.6565, 10500], # 1.0h
[ 20, 8, 4, 640, 2560, 176, 184.7, 2.9871, 6, 2.9935, 2.9849, 2.6872, 10500], # 1.0h 13.5G
[ 20, 8, 4, 640, 2560, 160, 179.8, 2.9899, 6, 2.9983, 2.9897, 2.6738, 10500], # 0.9h

[ 20, 8, 4, 608, 2432, 288, 203.5, 2.9789, 6, 2.9865,+2.9778, 2.6715, 10500], # 1.3h  minGemma-hidden_layers20-att_heads8-kv_heads4-hidden608-intermediate2432-head_dim288-T1024--2026-06-20-09-34
# valx8: 2.9815 +- 0.0049 # torch.Tensor([2.9778, 2.9877, 2.9801, 2.9880, 2.9777, 2.9864, 2.9768, 2.9759, 2.9832]).std()
# (2nd: 2.9789)                                                                       minGemma-hidden_layers20-att_heads8-kv_heads4-hidden608-intermediate2432-head_dim288-T1024--2026-06-20-11-12
# valx8: 2.9824 +- 0.0050 # torch.Tensor([2.9789, 2.9908, 2.9820, 2.9770, 2.9817, 2.9871, 2.9858, 2.9835, 2.9752]).std()
[ 20, 8, 4, 608, 2432, 272, 198.8, 2.9893, 6, 2.9963, 2.9883, 2.6732, 10500], # 1.2h 15.2G
[ 20, 8, 4, 608, 2432, 256, 194.1, 2.9891, 6, 2.9953, 2.9869, 2.7008, 10500], # 1.1h
[ 20, 8, 4, 608, 2432, 240, 189.5, 2.9888, 6, 2.9950, 2.9876, 2.6748, 10500], # 1.1h
[ 20, 8, 4, 608, 2432, 224, 184.8, 2.9890, 6, 2.9952, 2.9875, 2.6831, 10500], # 1.1h
[ 20, 8, 4, 608, 2432, 208, 180.1, 2.9912, 6, 2.9974, 2.9894, 2.6704, 10500], # 1.0h
[ 20, 8, 4, 608, 2432, 192, 175.4, 2.9815, 7, 2.9857,+2.9815, 2.6698, 10500], # 1.0h 13.2G
[ 20, 8, 4, 608, 2432, 176, 170.8, 2.9918, 7, 3.0002, 2.9918, 2.6636, 10500], # 1.0h 13.1G
[ 20, 8, 4, 608, 2432, 160, 166.1, 2.9906, 7, 2.9958, 2.9906, 2.6688, 10500], # 0.9h 13.1G

[ 20, 8, 4, 576, 2304, 288, 188.3, 2.9901, 6, 2.9980, 2.9890, 2.6772, 10500], # 1.2h
[ 20, 8, 4, 576, 2304, 272, 183.9, 2.9821, 7, 2.9864,+2.9821, 2.6646, 10500], # 1.2h 13.8G
[ 20, 8, 4, 576, 2304, 256, 179.5, 2.9929, 6, 2.9981, 2.9907, 2.6765, 10500], # 1.1h
[ 20, 8, 4, 576, 2304, 240, 175.1, 2.9844, 7, 2.9934, 2.9844, 3.3484, 10500], # 1.0h
[ 20, 8, 4, 576, 2304, 224, 170.6, 2.9891, 6, 2.9957, 2.9873, 2.6740, 10500], # 1.0h 13.3G
[ 20, 8, 4, 576, 2304, 208, 166.2, 2.9823, 7, 2.9882,+2.9823, 2.6610, 10500], # 1.0h 13.1G
[ 20, 8, 4, 576, 2304, 192, 161.8, 2.9942, 5, 2.9958, 2.9939, 2.6775, 10500], # 0.9h
[ 20, 8, 4, 576, 2304, 176, 157.4, 2.9903, 6, 2.9991, 2.9886, 2.6798, 10500], # 0.9h
[ 20, 8, 4, 576, 2304, 160, 152.9, 2.9861, 6, 2.9933, 2.9855, 2.6802, 10500], # 0.9h 12.8G


# local best for H6(3): 2.9757 (valx8: 2.9775)
[ 20, 6, 3, 792, 3168, 288, 272.6, 2.9845, 7, 2.9911, 2.9845, 2.7592, 10500], # 1.3h
[ 20, 6, 3, 792, 3168, 272, 268.1, 2.9865, 7, 2.9931, 2.9865, 2.6676, 10500], # 1.3h
[ 20, 6, 3, 792, 3168, 256, 263.5, 2.9817, 6, 2.9915,+2.9808, 2.6905, 10500], # 1.2h
# valx8: 2.9819 +- 0.0024 # torch.Tensor([2.9808, 2.9818, 2.9855, 2.9814, 2.9794, 2.9797, 2.9794, 2.9837, 2.9854]).std()
[ 20, 6, 3, 792, 3168, 240, 259.0, 2.9815, 6, 2.9878,+2.9815, 3.2089, 10500], # 1.2h
[ 20, 6, 3, 792, 3168, 224, 254.4, 2.9889, 6, 3.0381, 2.9875, 2.7809, 10500], # 1.1h 16.3G
[ 20, 6, 3, 792, 3168, 208, 249.8, 2.9860, 7, 2.9940, 2.9860, 2.7751, 10500], # 1.1h
[ 20, 6, 3, 792, 3168, 192, 245.3, 2.9897, 6, 2.9932, 2.9897, 3.2720, 10500], # 1.1h
[ 20, 6, 3, 792, 3168, 176, 240.7, 2.9846, 7, 3.0339, 2.9846, 2.6713, 10500], # 1.1h
[ 20, 6, 3, 792, 3168, 160, 236.1, 2.9900, 7, 3.0036, 2.9900, 2.8267, 10500], # 1.0h 15.7G

[ 20, 6, 3, 768, 3072, 288, 260.0, 2.9844, 5, 2.9857, 2.9840, 2.7606, 10500], # 1.2h
[ 20, 6, 3, 768, 3072, 272, 255.5, 2.9851, 9, 2.9854, 2.9851, 3.1231, 10500], # 1.2h
[ 20, 6, 3, 768, 3072, 256, 251.1, 2.9860, 6, 2.9899, 2.9854, 2.6759, 10500], # 1.1h
[ 20, 6, 3, 768, 3072, 240, 246.7, 2.9930, 6, 3.0011, 2.9930, 2.8347, 10500], # 1.1h
[ 20, 6, 3, 768, 3072, 224, 242.3, 2.9848, 6, 2.9910, 2.9844, 2.6746, 10500], # 1.1h
[ 20, 6, 3, 768, 3072, 208, 237.8, 2.9853, 6, 3.0897, 2.9843, 2.6729, 10500], # 1.0h
[ 20, 6, 3, 768, 3072, 192, 233.4, 2.9911, 7, 2.9949, 2.9911, 2.7143, 10500], # 1.0h
[ 20, 6, 3, 768, 3072, 176, 229.0, 2.9928, 6, 2.9979, 2.9910, 2.7660, 10500], # 1.0h
[ 20, 6, 3, 768, 3072, 160, 224.6, 2.9895, 7, 2.9934, 2.9895, 2.7960, 10500], # 0.9h 15.4G

[ 20, 6, 3, 744, 2976, 288, 247.5, 2.9801, 7, 2.9867,+2.9801, 2.6711, 10500], # 1.2h
# valx8: 2.9820 +- 0.0063 # torch.Tensor([2.9801, 2.9819, 2.9888, 2.9785, 2.9767, 2.9883, 2.9708, 2.9895, 2.9837]).std()
[ 20, 6, 3, 744, 2976, 272, 243.3, 2.9850, 6, 2.9926, 2.9846, 2.6763, 10500], # 1.2h
[ 20, 6, 3, 744, 2976, 256, 239.0, 2.9852, 6, 2.9921, 2.9852, 2.7115, 10500], # 1.1h
[ 20, 6, 3, 744, 2976, 240, 234.7, 2.9880, 6, 2.9944, 2.9862, 2.7494, 10500], # 1.1h
[ 20, 6, 3, 744, 2976, 224, 230.4, 2.9859, 7, 2.9920, 2.9859, 2.6594, 10500], # 1.1h
[ 20, 6, 3, 744, 2976, 208, 226.1, 2.9865, 6, 2.9943, 2.9859, 2.6788, 10500], # 1.0h
[ 20, 6, 3, 744, 2976, 192, 221.8, 2.9897, 7, 2.9946, 2.9897, 2.7476, 10500], # 1.0h
[ 20, 6, 3, 744, 2976, 176, 217.5, 2.9813, 6, 3.0758,+2.9813, 2.7086, 10500], # 1.0h
[ 20, 6, 3, 744, 2976, 160, 213.3, 2.9916, 7, 3.2065, 2.9916, 2.6810, 10500], # 0.9h 14.1G

[ 20, 6, 3, 720, 2880, 288, 235.4, 2.9794, 7, 2.9864,+2.9794, 2.7092, 10500], # 1.2h  minGemma-hidden_layers20-att_heads6-kv_heads3-hidden720-intermediate2880-head_dim288-T1024--2026-07-10-05-51
# valx8: 2.9788 +- 0.0032 # torch.Tensor([2.9794, 2.9796, 2.9808, 2.9761, 2.9802, 2.9777, 2.9836, 2.9793, 2.9723]).std()
[ 20, 6, 3, 720, 2880, 272, 231.3, 2.9791, 6, 2.9860,+2.9791, 2.8622, 10500], # 1.2h
# valx8: 2.9827 +- 0.0039 # torch.Tensor([2.9791, 2.9766, 2.9876, 2.9820, 2.9841, 2.9789, 2.9839, 2.9876, 2.9843]).std()
[ 20, 6, 3, 720, 2880, 256, 227.1, 2.9849, 6, 2.9892, 2.9847, 2.6753, 10500], # 1.1h
[+20, 6, 3, 720, 2880, 240, 223.0, 2.9757, 7, 3.0821,+2.9757, 2.8139, 10500], # 1.1h  minGemma-hidden_layers20-att_heads6-kv_heads3-hidden720-intermediate2880-head_dim240-T1024--2026-07-13-00-26
# valx8: 2.9799 +- 0.0074 # torch.Tensor([2.9757, 2.9726, 2.9974, 2.9762, 2.9794, 2.9772, 2.9749, 2.9820, 2.9835]).std()
# (2nd: 2.9767)                                                                       minGemma-hidden_layers20-att_heads6-kv_heads3-hidden720-intermediate2880-head_dim240-T1024--2026-07-12-23-01
# valx8: 2.9775 +- 0.0045 # torch.Tensor([2.9767, 2.9854, 2.9769, 2.9782, 2.9745, 2.9823, 2.9790, 2.9737, 2.9706]).std()
[ 20, 6, 3, 720, 2880, 224, 218.8, 2.9880, 7, 2.9930, 2.9880, 2.8070, 10500], # 1.0h
[ 20, 6, 3, 720, 2880, 208, 214.7, 2.9819, 6, 3.1306,+2.9816, 2.6850, 10500], # 1.0h
[ 20, 6, 3, 720, 2880, 192, 210.5, 2.9879, 6, 2.9941, 2.9865, 2.6992, 10500], # 1.0h
[ 20, 6, 3, 720, 2880, 176, 206.4, 2.9847, 7, 2.9918, 2.9847, 2.8732, 10500], # 0.9h 14.8G
[ 20, 6, 3, 720, 2880, 160, 202.2, 2.9876, 7, 3.0014, 2.9876, 3.0548, 10500], # 0.9h

[ 20, 6, 3, 696, 2784, 288, 223.6, 2.9838, 6, 2.9980, 2.9838, 2.6953, 10500], # 1.2h 15.4G
[ 20, 6, 3, 696, 2784, 272, 219.5, 2.9818, 6, 2.9891,+2.9818, 2.6806, 10500], # 1.1h
[ 20, 6, 3, 696, 2784, 256, 215.5, 2.9848, 7, 2.9875, 2.9848, 2.6645, 10500], # 1.1h
[ 20, 6, 3, 696, 2784, 240, 211.5, 2.9851, 6, 2.9932, 2.9842, 2.6818, 10500], # 1.0h 15.2G
[ 20, 6, 3, 696, 2784, 224, 207.5, 2.9832, 6, 2.9917,+2.9818, 2.6709, 10500], # 1.0h
[ 20, 6, 3, 696, 2784, 208, 203.5, 2.9824, 7, 2.9860,+2.9824, 2.6644, 10500], # 1.0h 14.9G
[ 20, 6, 3, 696, 2784, 192, 199.5, 2.9831, 6, 2.9870,+2.9831, 3.1322, 10500], # 0.9h
[ 20, 6, 3, 696, 2784, 176, 195.5, 2.9822, 6, 2.9898,+2.9820, 2.7209, 10500], # 0.9h
[ 20, 6, 3, 696, 2784, 160, 191.5, 2.9910, 7, 2.9977, 2.9910, 2.7496, 10500], # 0.9h 13.7G

[ 20, 6, 3, 672, 2688, 288, 212.0, 2.9858, 7, 2.9924, 2.9858, 2.6588, 10500], # 1.1h
[ 20, 6, 3, 672, 2688, 272, 208.1, 2.9839, 6, 2.9910, 2.9839, 3.1750, 10500], # 1.1h 15.0G
[ 20, 6, 3, 672, 2688, 256, 204.2, 2.9816, 7, 2.9889,+2.9816, 2.6587, 10500], # 1.0h
[ 20, 6, 3, 672, 2688, 240, 200.4, 2.9880, 7, 2.9978, 2.9880, 2.6635, 10500], # 1.0h 15.0G
[ 20, 6, 3, 672, 2688, 224, 196.5, 2.9848, 6, 2.9911, 2.9844, 2.6828, 10500], # 1.0h 13.7G
[ 20, 6, 3, 672, 2688, 208, 192.6, 2.9881, 6, 2.9961, 2.9880, 2.6916, 10500], # 1.0h 13.8G
[ 20, 6, 3, 672, 2688, 192, 188.8, 2.9851, 7, 2.9882, 2.9851, 2.6659, 10500], # 0.9h
[ 20, 6, 3, 672, 2688, 176, 184.9, 2.9930, 6, 2.9990, 2.9918, 2.8389, 10500], # 0.9h
[ 20, 6, 3, 672, 2688, 160, 181.0, 2.9849, 7, 2.9878, 2.9849, 2.6873, 10500], # 0.9h 13.2G

[ 20, 6, 3, 648, 2592, 288, 200.7, 2.9818, 7, 2.9890,+2.9818, 2.6699, 10500], # 1.1h
[ 20, 6, 3, 648, 2592, 272, 196.9, 2.9861, 6, 3.1006, 2.9856, 2.6828, 10500], # 1.1h
[ 20, 6, 3, 648, 2592, 256, 193.2, 2.9837, 7, 2.9891,+2.9837, 2.6686, 10500], # 1.0h 13.9G
[ 20, 6, 3, 648, 2592, 240, 189.5, 2.9913, 7, 2.9976, 2.9913, 2.6799, 10500], # 1.0h
[ 20, 6, 3, 648, 2592, 224, 185.7, 2.9912, 7, 2.9971, 2.9912, 2.6646, 10500], # 1.0h 13.6G
[ 20, 6, 3, 648, 2592, 208, 182.0, 2.9867, 6, 2.9954, 2.9859, 2.6774, 10500], # 1.0h
[ 20, 6, 3, 648, 2592, 192, 178.3, 2.9830, 6, 2.9889,+2.9828, 2.6937, 10500], # 0.9h
[ 20, 6, 3, 648, 2592, 176, 174.5, 2.9848, 6, 2.9912, 2.9842, 2.6752, 10500], # 0.9h
[ 20, 6, 3, 648, 2592, 160, 170.8, 2.9834, 6, 2.9923,+2.9833, 2.6809, 10500], # 0.9h

[ 20, 6, 3, 624, 2496, 288, 189.6, 2.9855, 6, 2.9960, 2.9855, 2.6722, 10500], # 1.1h 13.7G
[ 20, 6, 3, 624, 2496, 272, 186.1, 2.9893, 6, 2.9971, 2.9886, 2.6732, 10500], # 1.1h
[ 20, 6, 3, 624, 2496, 256, 182.5, 2.9875, 6, 2.9959, 2.9875, 2.6847, 10500], # 1.0h
[ 20, 6, 3, 624, 2496, 240, 178.9, 2.9844, 7, 2.9898, 2.9844, 2.6624, 15750], # 0.8h
[ 20, 6, 3, 624, 2496, 224, 175.3, 2.9842, 6, 2.9900, 2.9842, 3.1957, 15750], # 0.8h
[ 20, 6, 3, 624, 2496, 208, 171.7, 2.9808, 6, 2.9904,+2.9800, 2.6750, 15750], # 0.7h
# valx8: 2.9843 +- 0.0050 # torch.Tensor([2.9800, 2.9851, 2.9860, 2.9903, 2.9934, 2.9834, 2.9801, 2.9809, 2.9791]).std()
[ 20, 6, 3, 624, 2496, 192, 168.1, 2.9864, 6, 2.9960, 2.9863, 2.6868, 15750], # 0.7h
[ 20, 6, 3, 624, 2496, 176, 164.5, 2.9816, 6, 2.9882,+2.9808, 2.6809, 15750], # 0.7h
# valx8: 2.9810 +- 0.0043 # torch.Tensor([2.9808, 2.9885, 2.9865, 2.9818, 2.9808, 2.9790, 2.9772, 2.9798, 2.9746]).std()
[ 20, 6, 3, 624, 2496, 160, 160.9, 2.9839, 6, 3.1313,+2.9833, 2.7044, 15750], # 0.7h

[ 20, 6, 3, 600, 2400, 288, 178.9, 2.9778, 6, 2.9853,+2.9778, 2.8796, 15750], # 0.9h  minGemma-hidden_layers20-att_heads6-kv_heads3-hidden600-intermediate2400-head_dim288-T1024--2026-08-09-20-14
# valx8: 2.9798 +- 0.0034 # torch.Tensor([2.9778, 2.9806, 2.9827, 2.9843, 2.9800, 2.9837, 2.9778, 2.9781, 2.9735]).std()
# (1st: 2.9778)                                                                       minGemma-hidden_layers20-att_heads6-kv_heads3-hidden600-intermediate2400-head_dim288-T1024--2026-08-09-19-05
# valx8: 2.9802 +- 0.0035 # torch.Tensor([2.9778, 2.9768, 2.9780, 2.9834, 2.9860, 2.9816, 2.9788, 2.9835, 2.9760]).std()
# (3rd: 2.9799)                                                                       minGemma-hidden_layers20-att_heads6-kv_heads3-hidden600-intermediate2400-head_dim288-T1024--2026-08-09-17-56
# valx8: 2.9848 +- 0.0042 # torch.Tensor([2.9799, 2.9821, 2.9908, 2.9903, 2.9807, 2.9851, 2.9869, 2.9870, 2.9808]).std()
[ 20, 6, 3, 600, 2400, 272, 175.4, 2.9874, 6, 2.9926, 2.9863, 2.6805, 15750], # 0.9h
[ 20, 6, 3, 600, 2400, 256, 172.0, 2.9922, 6, 3.0004, 2.9922, 3.1674, 15750], # 0.8h
[ 20, 6, 3, 600, 2400, 240, 168.5, 2.9896, 6, 3.0003, 2.9887, 2.6737, 15750], # 0.8h 9.5G
[ 20, 6, 3, 600, 2400, 224, 165.1, 2.9878, 6, 2.9964, 2.9878, 2.6727, 15750], # 0.7h
[ 20, 6, 3, 600, 2400, 208, 161.6, 2.9813, 6, 2.9894,+2.9810, 2.6767, 15750], # 0.7h
# valx8: 2.9820 +- 0.0037 # torch.Tensor([2.9810, 2.9859, 2.9801, 2.9813, 2.9858, 2.9785, 2.9812, 2.9878, 2.9767]).std()
[ 20, 6, 3, 600, 2400, 192, 158.2, 2.9885, 6, 2.9950, 2.9882, 2.6946, 15750], # 0.7h
[ 20, 6, 3, 600, 2400, 176, 154.7, 2.9816, 7, 2.9868,+2.9816, 2.6755, 15750], # 0.7h
[ 20, 6, 3, 600, 2400, 160, 151.2, 2.9957, 5, 3.0240, 2.9954, 2.8382, 15750], # 0.7h

[ 20, 6, 3, 576, 2304, 288, 168.4, 2.9769, 7, 2.9838,+2.9769, 2.6648, 15750], # 0.8h  minGemma-hidden_layers20-att_heads6-kv_heads3-hidden576-intermediate2304-head_dim288-T1024--2026-08-12-11-26
# valx8: 2.9818 +- 0.0046 # torch.Tensor([2.9769, 2.9816, 2.9874, 2.9840, 2.9788, 2.9800, 2.9890, 2.9837, 2.9751]).std()
# (2nd:2.9778)                                                                        minGemma-hidden_layers20-att_heads6-kv_heads3-hidden576-intermediate2304-head_dim288-T1024--2026-08-12-10-20
# valx8: 2.9795 +- 0.0077 # torch.Tensor([2.9778, 2.9734, 2.9794, 2.9839, 2.9877, 2.9781, 2.9804, 2.9905, 2.9647]).std()
[ 20, 6, 3, 576, 2304, 272, 165.1, 2.9885, 7, 2.9927, 2.9885, 2.6687, 15750], # 0.8h
[ 20, 6, 3, 576, 2304, 256, 161.8, 2.9835, 6, 2.9883,+2.9821, 2.6822, 15750], # 0.8h
[ 20, 6, 3, 576, 2304, 240, 158.5, 2.9888, 6, 2.9973, 2.9868, 2.6760, 15750], # 0.7h
[ 20, 6, 3, 576, 2304, 224, 155.2, 2.9904, 7, 2.9974, 2.9904, 2.6663, 15750], # 0.7h
[ 20, 6, 3, 576, 2304, 208, 151.8, 2.9944, 6, 3.0033, 2.9925, 2.6770, 15750], # 0.7h
[ 20, 6, 3, 576, 2304, 192, 148.5, 2.9847, 7, 2.9900, 2.9847, 2.6701, 15750], # 0.7h
[ 20, 6, 3, 576, 2304, 176, 145.2, 2.9833, 7, 2.9888,+2.9833, 2.6660, 15750], # 0.6h
[ 20, 6, 3, 576, 2304, 160, 141.9, 2.9830, 7, 2.9882,+2.9830, 2.6711, 15750], # 0.6h

In [15]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  20 # 8 # G28 G18 #blocks
num_attention_heads = 9 # 4 # G16 G8
num_key_value_heads = 3 # 4 # G16 G1
hidden_size = num_attention_heads*84 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 208 # 32 # G256 # dim in attention
rms_norm_eps = 1e0 # 1e-6
rope_theta = 80000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//2; N_step=5250*2; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=10.0e-4, weight_decay=1.8, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(6000*2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9869:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

64.512
L20 att9 kv_heads3 hidden756 intermediate3024 head_dim208 T1024

1 4.685666294642857 tensor(3.2430)

2 2.8011586681547618 tensor(3.0186)

3 2.710798549107143 tensor(2.9937)

4 2.688841331845238 tensor(2.9880)

5 2.678466145833333 tensor(2.9839)

6 2.6664724702380953 tensor(2.9823)

7 3.051190662202381 tensor(3.0651)
back to previous

8 2.8717563244047617 tensor(2.9777)

9 2.785032924107143 tensor(2.9831)
back to previous

10 2.6689927455357143 tensor(2.9813)
[ 20, 9, 3, 756, 3024, 208, 250.8, 2.9777, 9, 2.9813, 2.9777, 2.7850, 10500],

In [1]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  20 # 8 # G28 G18 #blocks
num_attention_heads = 8 # 4 # G16 G8
num_key_value_heads = 4 # 4 # G16 G1
hidden_size = num_attention_heads*84 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 272 # 32 # G256 # dim in attention
rms_norm_eps = 1e0 # 1e-6
rope_theta = 80000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//2; N_step=5250*2; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=10.0e-4, weight_decay=1.8, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(5000*2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9837:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

C:\Users\miuralab\AppData\Local\anaconda3\envs\minGemma2\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

64.512
L20 att8 kv_heads4 hidden672 intermediate2688 head_dim272 T1024

1 4.523113467261905 tensor(3.2285)

2 2.809137276785714 tensor(3.0161)

3 2.7175308779761904 tensor(2.9920)

4 2.6943182663690477 tensor(2.9845)

5 2.68010546875 tensor(2.9811)

6 2.671140438988095 tensor(2.9804)

7 2.995867745535714 tensor(3.0440)
back to previous

8 2.6644012276785713 tensor(2.9865)
[ 20, 8, 4, 672, 2688, 272, 230.0, 2.9804, 7, 2.9865, 2.9804, 2.9959, 10500],

In [5]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  20 # 8 # G28 G18 #blocks
num_attention_heads = 8 # 4 # G16 G8
num_key_value_heads = 4 # 4 # G16 G1
hidden_size = num_attention_heads*84 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 208 # 32 # G256 # dim in attention
rms_norm_eps = 1e0 # 1e-6
rope_theta = 80000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//2; N_step=5250*2; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=10.0e-4, weight_decay=1.8, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(5000*2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9837:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

64.512
L20 att8 kv_heads4 hidden672 intermediate2688 head_dim208 T1024

1 4.586488095238095 tensor(3.2211)

2 2.7932323288690477 tensor(3.0095)

3 2.714044642857143 tensor(2.9866)

4 2.6929361979166666 tensor(2.9819)

5 2.6759925595238094 tensor(2.9787)

6 2.667802269345238 tensor(2.9802)

7 2.70963671875 tensor(2.9894)
[ 20, 8, 4, 672, 2688, 208, 209.4, 2.9802, 6, 2.9894, 2.9787, 2.6678, 10500],

In [18]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  20 # 8 # G28 G18 #blocks
num_attention_heads = 8 # 4 # G16 G8
num_key_value_heads = 4 # 4 # G16 G1
hidden_size = num_attention_heads*76 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 288 # 32 # G256 # dim in attention
rms_norm_eps = 1e0 # 1e-6
rope_theta = 80000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//2; N_step=5250*2; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=10.0e-4, weight_decay=1.8, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(5000*2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9837:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

64.512
L20 att8 kv_heads4 hidden608 intermediate2432 head_dim288 T1024

1 4.5250412946428575 tensor(3.2251)

2 2.8244086681547618 tensor(3.0137)

3 2.7855831473214288 tensor(2.9883)

4 2.6991932663690474 tensor(2.9799)

5 2.6810120907738093 tensor(2.9778)

6 2.671499441964286 tensor(2.9789)

7 2.6608794642857143 tensor(2.9865)
[ 20, 8, 4, 608, 2432, 288, 203.5, 2.9789, 6, 2.9865, 2.9778, 2.6715, 10500],

In [63]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  20 # 8 # G28 G18 #blocks
num_attention_heads = 6 # 4 # G16 G8
num_key_value_heads = 3 # 4 # G16 G1
hidden_size = num_attention_heads*120 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 288 # 32 # G256 # dim in attention
rms_norm_eps = 1e0 # 1e-6
rope_theta = 80000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//2; N_step=5250*2; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=10.0e-4, weight_decay=1.8, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(5000*2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9837:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

64.512
L20 att6 kv_heads3 hidden720 intermediate2880 head_dim288 T1024

1 4.5807265625 tensor(3.2179)

2 2.8170824032738095 tensor(3.0108)

3 2.743357700892857 tensor(2.9874)

4 2.7239002976190476 tensor(2.9827)

5 2.703143973214286 tensor(2.9800)

6 2.7161443452380953 tensor(2.9794)

7 2.7092418154761906 tensor(2.9867)
back to previous

8 2.6911274181547618 tensor(2.9864)
[ 20, 6, 3, 720, 2880, 288, 235.4, 2.9794, 7, 2.9864, 2.9794, 2.7092, 10500],

In [1]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  20 # 8 # G28 G18 #blocks
num_attention_heads = 6 # 4 # G16 G8
num_key_value_heads = 3 # 4 # G16 G1
hidden_size = num_attention_heads*120 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 240 # 32 # G256 # dim in attention
rms_norm_eps = 1e0 # 1e-6
rope_theta = 80000.0 # scale freq is small for S-model. 1000 might work too # G10000.0
# 696/116 672/112 648/108 624/104 600/100 576/96
def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//2; N_step=5250*2; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=10.0e-4, weight_decay=1.8, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(5000*2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9837:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

C:\Users\miuralab\AppData\Local\anaconda3\envs\minGemma2\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

64.512
L20 att6 kv_heads3 hidden720 intermediate2880 head_dim240 T1024

1 4.688765997023809 tensor(3.1869)

2 2.788927455357143 tensor(3.0081)

3 3.1194315476190475 tensor(3.0164)
back to previous

4 2.71578515625 tensor(2.9859)

5 2.693170572916667 tensor(2.9767)

6 2.681688430059524 tensor(2.9757)

7 2.813913318452381 tensor(2.9856)
back to previous

8 3.1258683035714285 tensor(3.0821)
[ 20, 6, 3, 720, 2880, 240, 223.0, 2.9757, 7, 3.0821, 2.9757, 2.8139, 10500],

In [18]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  20 # 8 # G28 G18 #blocks
num_attention_heads = 6 # 4 # G16 G8
num_key_value_heads = 3 # 4 # G16 G1
hidden_size = num_attention_heads*100 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 288 # 32 # G256 # dim in attention
rms_norm_eps = 1e0 # 1e-6
rope_theta = 80000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//3; N_step=5250*3; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=3, learning_rate=10.0e-4, weight_decay=1.8, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//3 # Evaluation follows
    for k in range(5000*3 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9837:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

64.512
L20 att6 kv_heads3 hidden600 intermediate2400 head_dim288 T1024

1 4.425101934523809 tensor(3.2254)

2 2.8293145461309526 tensor(3.0188)

3 2.7400362723214284 tensor(2.9890)

4 2.7233377976190476 tensor(2.9799)

5 2.711218191964286 tensor(2.9778)

6 2.8796378348214287 tensor(2.9778)

7 2.6913515625 tensor(2.9853)
[ 20, 6, 3, 600, 2400, 288, 178.9, 2.9778, 6, 2.9853, 2.9778, 2.8796, 15750],

In [27]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  20 # 8 # G28 G18 #blocks
num_attention_heads = 6 # 4 # G16 G8
num_key_value_heads = 3 # 4 # G16 G1
hidden_size = num_attention_heads*96 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 288 # 32 # G256 # dim in attention
rms_norm_eps = 1e0 # 1e-6
rope_theta = 80000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//3; N_step=5250*3; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=3, learning_rate=10.0e-4, weight_decay=1.8, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//3 # Evaluation follows
    for k in range(5000*3 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9837:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

64.512
L20 att6 kv_heads3 hidden576 intermediate2304 head_dim288 T1024

1 4.466599330357143 tensor(3.2349)

2 2.834606212797619 tensor(3.0223)

3 2.7307873883928573 tensor(2.9909)

4 2.70380859375 tensor(2.9806)

5 2.685762648809524 tensor(2.9778)

6 2.6775745907738093 tensor(2.9769)

7 2.6647892485119047 tensor(2.9833)
back to previous

8 2.667967447916667 tensor(2.9838)
[ 20, 6, 3, 576, 2304, 288, 168.4, 2.9769, 7, 2.9838, 2.9769, 2.6648, 15750],

# L18

In [ ]:
# L18 FORGETTER T1024 Baby10M (default: x4 B12 N5250 lr10e-4 WD1.8) # H10(5): 2.9801, H9(3): 2.9813, H8(4): 2.9812, H7(1): 2.9809, H6(3): 2.9846

# local best for H10(5): 2.9797 (valx8: 2.9801)
[ 18,10, 5, 800, 3200, 288, 303.0, 2.9812, 6, 2.9905,+2.9800, 2.6679, 10500], # 1.5h
# valx8: 2.9813 +- 0.0022 # torch.Tensor([2.9800, 2.9794, 2.9791, 2.9810, 2.9822, 2.9848, 2.9845, 2.9789, 2.9821]).std()
[ 18,10, 5, 800, 3200, 272, 296.1, 2.9878, 6, 3.0974, 2.9863, 2.6736, 10500], # 1.5h
[ 18,10, 5, 800, 3200, 256, 289.2, 2.9849, 6, 2.9925, 2.9842, 2.6713, 10500], # 1.4h
[ 18,10, 5, 800, 3200, 240, 282.3, 2.9827, 6, 2.9895,+2.9824, 2.6678, 10500], # 1.4h
[ 18,10, 5, 800, 3200, 224, 275.4, 2.9808, 7, 2.9892,+2.9808, 2.6578, 10500], # 1.3h
# valx8: 2.9832 +- 0.0047 # torch.Tensor([2.9808, 2.9814, 2.9885, 2.9791, 2.9920, 2.9848, 2.9796, 2.9845, 2.9780]).std()
[ 18,10, 5, 800, 3200, 208, 268.5, 2.9840, 6, 2.9904,+2.9836, 2.6774, 10500], # 1.3h
[ 18,10, 5, 800, 3200, 192, 261.5, 2.9847, 7, 2.9926, 2.9847, 2.7213, 10500], # 1.2h
[ 18,10, 5, 800, 3200, 176, 254.6, 2.9884, 6, 2.9934, 2.9883, 2.6932, 10500], # 1.2h
[ 18,10, 5, 800, 3200, 160, 247.7, 2.9883, 6, 2.9944, 2.9872, 2.6775, 10500], # 1.1h

[ 18,10, 5, 760, 3040, 288, 281.3, 2.9862, 6, 2.9951, 2.9860, 2.6625, 10500], # 1.4h
[ 18,10, 5, 760, 3040, 272, 274.7, 2.9865, 6, 2.9940, 2.9865, 3.0626, 10500], # 1.4h 16.3G
[ 18,10, 5, 760, 3040, 256, 268.2, 2.9904, 6, 2.9953, 2.9883, 2.6667, 10500], # 1.3h
[ 18,10, 5, 760, 3040, 240, 261.6, 2.9874, 6, 2.9922, 2.9849, 2.7970, 10500], # 1.3h 16.1G
[ 18,10, 5, 760, 3040, 224, 255.0, 2.9912, 6, 2.9966, 2.9910, 2.6769, 10500], # 1.2h
[ 18,10, 5, 760, 3040, 208, 248.5, 2.9838, 7, 2.9896, 2.9838, 2.6669, 10500], # 1.2h
[ 18,10, 5, 760, 3040, 192, 241.9, 2.9797, 6, 2.9859,+2.9797, 3.0923, 10500], # 1.1h
# valx8: 2.9812 +- 0.0035 # torch.Tensor([2.9797, 2.9755, 2.9847, 2.9790, 2.9867, 2.9786, 2.9814, 2.9838, 2.9810]).std()
[ 18,10, 5, 760, 3040, 176, 235.3, 2.9851, 6, 3.1031, 2.9841, 2.6773, 10500], # 1.1h
[ 18,10, 5, 760, 3040, 160, 228.8, 2.9819, 7, 2.9877,+2.9819, 2.6814, 10500], # 1.0h 15.2G

[ 18,10, 5, 720, 2880, 288, 260.3, 2.9877, 6, 2.9959, 2.9877, 2.8025, 10500], # 1.4h 16.2G
[ 18,10, 5, 720, 2880, 272, 254.1, 2.9855, 6, 2.9905,+2.9835, 2.6663, 10500], # 1.4h
[ 18,10, 5, 720, 2880, 256, 247.8, 2.9837, 6, 2.9909,+2.9837, 2.6828, 10500], # 1.3h
[ 18,10, 5, 720, 2880, 240, 241.6, 2.9922, 7, 2.9963, 2.9922, 2.6606, 10500], # 1.2h 15.7G
[ 18,10, 5, 720, 2880, 224, 235.4, 2.9900, 6, 2.9962, 2.9900, 2.7578, 10500], # 1.2h
[ 18,10, 5, 720, 2880, 208, 229.2, 2.9838, 6, 2.9903, 2.9838, 2.7791, 10500], # 1.2h
[ 18,10, 5, 720, 2880, 192, 223.0, 2.9859, 6, 2.9910, 2.9856, 2.6692, 10500], # 1.1h
[ 18,10, 5, 720, 2880, 176, 216.7, 2.9875, 6, 2.9936, 2.9864, 2.6759, 10500], # 1.1h 15.1G
[ 18,10, 5, 720, 2880, 160, 210.5, 2.9861, 7, 2.9921, 2.9861, 2.6649, 10500], # 1.0h

[ 18,10, 5, 680, 2720, 288, 239.9, 2.9896, 6, 2.9977, 2.9884, 2.6671, 10500], # 1.4h 15.8G
[ 18,10, 5, 680, 2720, 272, 234.1, 2.9813, 6, 2.9896,+2.9798, 2.6641, 10500], # 1.4h 15.6G
# valx8: 2.9821 +- 0.0029 # torch.Tensor([2.9798, 2.9799, 2.9827, 2.9792, 2.9874, 2.9852, 2.9831, 2.9790, 2.9823]).std()
[ 18,10, 5, 680, 2720, 256, 228.2, 2.9839, 6, 2.9906,+2.9821, 2.6681, 10500], # 1.2h 15.5G
[+18,10, 5, 680, 2720, 240, 222.3, 2.9800, 6, 2.9873,+2.9789, 2.6618, 10500], # 1.2h  minGemma-hidden_layers18-att_heads10-kv_heads5-hidden680-intermediate2720-head_dim240-T1024--2026-06-25-06-43
# valx8: 2.9801 +- 0.0044 # torch.Tensor([2.9789, 2.9865, 2.9731, 2.9771, 2.9774, 2.9828, 2.9779, 2.9822, 2.9854]).std()
# (2nd: 2.9800)                                                                       minGemma-hidden_layers18-att_heads10-kv_heads5-hidden680-intermediate2720-head_dim240-T1024--2026-06-25-08-19
# valx8: 2.9831 +- 0.0041 # torch.Tensor([2.9800, 2.9853, 2.9856, 2.9865, 2.9824, 2.9878, 2.9858, 2.9783, 2.9763]).std()
[ 18,10, 5, 680, 2720, 224, 216.4, 2.9932, 6, 2.9999, 2.9920, 2.6646, 10500], # 1.2h 15.2G
[ 18,10, 5, 680, 2720, 208, 210.6, 2.9840, 6, 2.9930,+2.9825, 2.6734, 10500], # 1.1h
[ 18,10, 5, 680, 2720, 192, 204.7, 2.9913, 6, 2.9961, 2.9890, 2.7295, 10500], # 1.1h 13.7G
[ 18,10, 5, 680, 2720, 176, 198.8, 2.9914, 6, 2.9993, 2.9913, 2.6709, 10500], # 1.1h
[ 18,10, 5, 680, 2720, 160, 192.9, 2.9863, 6, 2.9909, 2.9839, 2.6862, 10500], # 1.0h

[ 18,10, 5, 640, 2560, 288, 220.3, 2.9865, 7, 2.9939, 2.9865, 2.6746, 10500], # 1.3h
[ 18,10, 5, 640, 2560, 272, 214.8, 2.9840, 6, 2.9935,+2.9820, 2.6726, 10500], # 1.3h
[ 18,10, 5, 640, 2560, 256, 209.2, 2.9889, 6, 2.9978, 2.9870, 2.6708, 10500], # 1.1h
[ 18,10, 5, 640, 2560, 240, 203.7, 2.9890, 6, 2.9961, 2.9885, 2.6723, 10500], # 1.1h
[ 18,10, 5, 640, 2560, 224, 198.2, 2.9901, 6, 2.9990, 2.9901, 2.6736, 10500], # 1.1h 13.7G
[ 18,10, 5, 640, 2560, 208, 192.7, 2.9836, 7, 2.9897,+2.9836, 2.6625, 10500], # 1.1h
[ 18,10, 5, 640, 2560, 192, 187.1, 2.9846, 6, 2.9913,+2.9836, 2.6710, 10500], # 1.0h 13.4G
[ 18,10, 5, 640, 2560, 176, 181.6, 2.9843, 6, 2.9925,+2.9831, 2.6741, 10500], # 1.0h
[ 18,10, 5, 640, 2560, 160, 176.1, 2.9827, 7, 2.9909,+2.9827, 2.6632, 10500], # 0.9h

[ 18,10, 5, 600, 2400, 288, 201.3, 2.9815, 7, 2.9882,+2.9815, 2.6628, 10500], # 1.3h 14.2G
[ 18,10, 5, 600, 2400, 272, 196.2, 2.9854, 6, 2.9928, 2.9839, 2.6789, 10500], # 1.3h
[ 18,10, 5, 600, 2400, 256, 191.0, 2.9886, 6, 2.9950, 2.9869, 2.6682, 10500], # 1.1h
[ 18,10, 5, 600, 2400, 240, 185.8, 2.9830, 7, 2.9908,+2.9830, 2.6621, 10500], # 1.1h
[ 18,10, 5, 600, 2400, 224, 180.6, 2.9825, 6, 2.9886,+2.9804, 2.6772, 10500], # 1.1h 13.5G
# valx8: 2.9818 +- 0.0051 # torch.Tensor([2.9804, 2.9826, 2.9698, 2.9857, 2.9823, 2.9800, 2.9869, 2.9832, 2.9853]).std()
[ 18,10, 5, 600, 2400, 208, 175.4, 2.9860, 6, 2.9943, 2.9854, 2.6763, 10500], # 1.1h
[ 18,10, 5, 600, 2400, 192, 170.2, 2.9901, 6, 2.9975, 2.9881, 2.6736, 10500], # 1.0h
[ 18,10, 5, 600, 2400, 176, 165.1, 2.9832, 6, 2.9925,+2.9827, 2.6764, 10500], # 1.0h
[ 18,10, 5, 600, 2400, 160, 159.9, 2.9878, 6, 2.9949, 2.9861, 2.6892, 10500], # 0.9h


# local best for H9(3): 2.9772 (valx8: 2.9813)
[ 18, 9, 3, 792, 3168, 288, 274.0, 2.9843, 6, 2.9902,+2.9836, 2.6704, 10500], # 1.4h 16.4G
[ 18, 9, 3, 792, 3168, 272, 268.5, 2.9913, 6, 3.0595, 2.9913, 3.2983, 10500], # 1.4h 16.3G
[ 18, 9, 3, 792, 3168, 256, 263.0, 2.9859, 6, 2.9920, 2.9851, 2.7429, 10500], # 1.2h
[ 18, 9, 3, 792, 3168, 240, 257.6, 2.9862, 7, 2.9912, 2.9862, 3.0110, 10500], # 1.2h 16.0G
[ 18, 9, 3, 792, 3168, 224, 252.1, 2.9863, 6, 2.9923, 2.9849, 2.6914, 10500], # 1.2h
[ 18, 9, 3, 792, 3168, 208, 246.6, 2.9921, 7, 2.9975, 2.9921, 2.6707, 10500], # 1.2h
[ 18, 9, 3, 792, 3168, 192, 241.1, 2.9815, 6, 2.9874,+2.9800, 2.6739, 10500], # 1.1h
# valx8: 2.9832 +- 0.0026 # torch.Tensor([2.9800, 2.9868, 2.9805, 2.9796, 2.9828, 2.9847, 2.9844, 2.9859, 2.9837]).std()
[ 18, 9, 3, 792, 3168, 176, 235.7, 2.9860, 6, 3.1181, 2.9855, 2.7044, 10500], # 1.1h
[ 18, 9, 3, 792, 3168, 160, 230.2, 2.9841, 6, 2.9897,+2.9831, 2.7122, 10500], # 1.1h

[+18, 9, 3, 756, 3024, 288, 255.7, 2.9824, 6, 2.9904,+2.9804, 2.6809, 10500], # 1.3h (erased) minGemma-hidden_layers18-att_heads9-kv_heads3-hidden756-intermediate3024-head_dim288-T1024--2026-05-18-10-52
# valx8: 2.9813 +- 0.0051 # torch.Tensor([2.9804, 2.9765, 2.9756, 2.9886, 2.9874, 2.9833, 2.9765, 2.9861, 2.9774]).std()
[ 18, 9, 3, 756, 3024, 272, 250.4, 2.9878, 7, 2.9937, 2.9878, 2.7380, 10500], # 1.3h
[ 18, 9, 3, 756, 3024, 256, 245.2, 2.9869, 7, 2.9930, 2.9869, 2.6743, 10500], # 1.1h
[ 18, 9, 3, 756, 3024, 240, 240.0, 2.9865, 6, 2.9916, 2.9847, 2.6734, 10500], # 1.2h
[ 18, 9, 3, 756, 3024, 224, 234.8, 2.9846, 7, 2.9903, 2.9846, 2.6926, 10500], # 1.1h 15.5G
[ 18, 9, 3, 756, 3024, 208, 229.5, 2.9772, 6, 2.9852,+2.9772, 2.7156, 10500], # 1.1h  minGemma-hidden_layers18-att_heads9-kv_heads3-hidden756-intermediate3024-head_dim208-T1024--2026-05-20-21-49
# valx8: 2.9814 +- 0.0038 # torch.Tensor([2.9772, 2.9837, 2.9819, 2.9868, 2.9838, 2.9813, 2.9816, 2.9739, 2.9824]).std()
[ 18, 9, 3, 756, 3024, 192, 224.3, 2.9849, 7, 2.9900, 2.9849, 2.6720, 10500], # 1.0h
[ 18, 9, 3, 756, 3024, 176, 219.1, 2.9863, 6, 2.9925, 2.9858, 2.6954, 10500], # 1.0h 15.0G
[ 18, 9, 3, 756, 3024, 160, 213.9, 2.9838, 6, 2.9900,+2.9822, 2.6786, 10500], # 1.0h

[ 18, 9, 3, 720, 2880, 288, 237.9, 2.9828, 6, 2.9916,+2.9815, 2.6696, 10500], # 1.3h 15.8G
[ 18, 9, 3, 720, 2880, 272, 232.9, 2.9930, 6, 2.9994, 2.9912, 2.6696, 10500], # 1.3h
[ 18, 9, 3, 720, 2880, 256, 227.9, 2.9890, 6, 2.9961, 2.9872, 2.6752, 10500], # 1.1h
[ 18, 9, 3, 720, 2880, 240, 223.0, 2.9888, 6, 2.9940, 2.9886, 2.6778, 10500], # 1.1h
[ 18, 9, 3, 720, 2880, 224, 218.0, 2.9853, 6, 2.9888, 2.9838, 2.6942, 10500], # 1.1h
[ 18, 9, 3, 720, 2880, 208, 213.0, 2.9847, 7, 2.9915, 2.9847, 2.6601, 10500], # 1.1h
[ 18, 9, 3, 720, 2880, 192, 208.0, 2.9861, 7, 2.9914, 2.9861, 2.6571, 10500], # 1.0h
[ 18, 9, 3, 720, 2880, 176, 203.0, 2.9852, 6, 2.9923, 2.9844, 2.7111, 10500], # 1.0h 13.7G
[ 18, 9, 3, 720, 2880, 160, 198.1, 2.9913, 7, 2.9968, 2.9913, 2.6585, 10500], # 0.9h

[ 18, 9, 3, 684, 2736, 288, 220.7, 2.9850, 6, 2.9927, 2.9850, 2.6918, 10500], # 1.2h
[ 18, 9, 3, 684, 2736, 272, 215.9, 2.9897, 6, 2.9982, 2.9882, 2.6705, 10500], # 1.2h
[ 18, 9, 3, 684, 2736, 256, 211.2, 2.9836, 7, 2.9885,+2.9836, 2.6593, 10500], # 1.1h 15.3G
[ 18, 9, 3, 684, 2736, 240, 206.5, 2.9826, 7, 2.9898,+2.9826, 2.6612, 10500], # 1.1h
[ 18, 9, 3, 684, 2736, 224, 201.8, 2.9855, 6, 2.9923, 2.9843, 2.6732, 10500], # 1.0h
[ 18, 9, 3, 684, 2736, 208, 197.0, 2.9816, 7, 3.2665,+2.9816, 2.6588, 10500], # 1.0h
[ 18, 9, 3, 684, 2736, 192, 192.3, 2.9823, 7, 2.9858,+2.9823, 2.6615, 10500], # 1.0h
[ 18, 9, 3, 684, 2736, 176, 187.6, 2.9851, 7, 2.9922, 2.9851, 2.6547, 10500], # 0.9h
[ 18, 9, 3, 684, 2736, 160, 182.8, 2.9831, 7, 3.1226,+2.9831, 2.6589, 10500], # 0.9h

[ 18, 9, 3, 648, 2592, 288, 204.0, 2.9843, 6, 2.9912,+2.9835, 2.6717, 10500], # 1.2h
[ 18, 9, 3, 648, 2592, 272, 199.5, 2.9886, 6, 2.9944, 2.9880, 2.6704, 10500], # 1.2h
[ 18, 9, 3, 648, 2592, 256, 195.1, 2.9923, 6, 3.0002, 2.9901, 2.6642, 10500], # 1.1h
[ 18, 9, 3, 648, 2592, 240, 190.6, 2.9840, 6, 2.9902,+2.9834, 2.6660, 10500], # 1.1h
[ 18, 9, 3, 648, 2592, 224, 186.1, 2.9911, 6, 3.0023, 2.9911, 2.6611, 10500], # 1.0h
[ 18, 9, 3, 648, 2592, 208, 181.6, 2.9845, 7, 2.9887, 2.9845, 2.6522, 10500], # 1.0h    
[ 18, 9, 3, 648, 2592, 192, 177.1, 2.9938, 7, 2.9998, 2.9938, 2.6604, 10500], # 0.9h
[ 18, 9, 3, 648, 2592, 176, 172.7, 2.9874, 7, 2.9924, 2.9874, 2.6645, 10500], # 0.9h
[ 18, 9, 3, 648, 2592, 160, 168.2, 2.9928, 5, 3.0451, 2.9928, 2.8799, 10500], # 0.9h

[ 18, 9, 3, 612, 2448, 288, 187.9, 2.9912, 6, 2.9986, 2.9889, 2.6798, 10500], # 1.1h
[ 18, 9, 3, 612, 2448, 272, 183.7, 2.9816, 6, 2.9878,+2.9816, 2.6724, 10500], # 1.1h
[ 18, 9, 3, 612, 2448, 256, 179.5, 2.9904, 7, 2.9942, 2.9904, 2.6648, 10500], # 1.0h
[ 18, 9, 3, 612, 2448, 240, 175.2, 2.9827, 6, 2.9879,+2.9815, 2.6741, 10500], # 1.0h
[ 18, 9, 3, 612, 2448, 224, 171.0, 2.9895, 6, 2.9957, 2.9879, 2.6736, 10500], # 1.0h 13.2G
[ 18, 9, 3, 612, 2448, 208, 166.8, 2.9949, 6, 3.0019, 2.9942, 2.6753, 10500], # 0.9h
[ 18, 9, 3, 612, 2448, 192, 162.5, 2.9918, 7, 3.0035, 2.9918, 2.6942, 10500], # 0.9h
[ 18, 9, 3, 612, 2448, 176, 158.3, 3.0004, 6, 3.0095, 2.9991, 2.6727, 10500], # 0.9h
[ 18, 9, 3, 612, 2448, 160, 154.1, 2.9914, 7, 2.9978, 2.9914, 2.6610, 10500], # 0.8h

[ 18, 9, 3, 576, 2304, 288, 172.4, 2.9890, 6, 2.9963, 2.9878, 2.6730, 10500], # 1.1h
[ 18, 9, 3, 576, 2304, 272, 168.4, 2.9865, 7, 2.9933, 2.9865, 2.6596, 10500], # 1.1h
[ 18, 9, 3, 576, 2304, 256, 164.4, 2.9885, 6, 2.9967, 2.9876, 2.6735, 10500], # 1.0h
[ 18, 9, 3, 576, 2304, 240, 160.4, 2.9826, 6, 2.9898,+2.9821, 2.6748, 10500], # 1.0h
[ 18, 9, 3, 576, 2304, 224, 156.5, 2.9968, 6, 3.0036, 2.9948, 2.6791, 10500], # 0.9h 12.9G
[ 18, 9, 3, 576, 2304, 208, 152.5, 2.9918, 6, 2.9999, 2.9918, 2.6737, 10500], # 0.9h
[ 18, 9, 3, 576, 2304, 192, 148.5, 2.9884, 6, 2.9951, 2.9876, 2.6750, 10500], # 0.8h
[ 18, 9, 3, 576, 2304, 176, 144.5, 2.9835, 7, 2.9900,+2.9835, 2.6571, 10500], # 0.8h
[ 18, 9, 3, 576, 2304, 160, 140.5, 2.9908, 7, 2.9989, 2.9908, 2.6650, 10500], # 0.8h


# local best for H8(4): 2.9786 (valx8: 2.9812)
[ 18, 8, 4, 800, 3200, 288, 278.1, 2.9853, 7, 2.9915, 2.9853, 2.6695, 15750], # 1.1h 12.5G
[ 18, 8, 4, 800, 3200, 272, 272.6, 2.9861, 6, 2.9919, 2.9857, 2.6758, 15750], # 1.0h
[ 18, 8, 4, 800, 3200, 256, 267.1, 2.9862, 7, 3.0997, 2.9862, 2.6701, 15750], # 1.0h
[ 18, 8, 4, 800, 3200, 240, 261.5, 2.9852, 7, 2.9922, 2.9852, 2.6582, 15750], # 0.9h
[ 18, 8, 4, 800, 3200, 224, 256.0, 2.9881, 6, 2.9936, 2.9872, 2.6754, 15750], # 0.9h
[ 18, 8, 4, 800, 3200, 208, 250.5, 2.9879, 7, 2.9924, 2.9879, 2.6794, 15750], # 0.9h
[ 18, 8, 4, 800, 3200, 192, 245.0, 2.9864, 6, 2.9904, 2.9846, 2.6821, 15750], # 0.8h
[ 18, 8, 4, 800, 3200, 176, 239.4, 2.9828, 6, 2.9888,+2.9828, 2.7885, 15750], # 0.8h
[ 18, 8, 4, 800, 3200, 160, 233.9, 2.9884, 7, 2.9942, 2.9884, 3.3150, 15750], # 0.8h

[ 18, 8, 4, 768, 3072, 288, 261.7, 2.9858, 6, 2.9897, 2.9850, 2.6752, 15750], # 1.0h
[ 18, 8, 4, 768, 3072, 272, 256.4, 2.9796, 6, 2.9869,+2.9793, 2.6745, 15750], # 1.0h
# valx8: 2.9819 +- 0.0035 # torch.Tensor([2.9793, 2.9815, 2.9857, 2.9792, 2.9824, 2.9847, 2.9861, 2.9828, 2.9753]).std()
# (2nd: 2.9796)
# valx8: 2.9827 +- 0.0049 # torch.Tensor([2.9796, 2.9822, 2.9791, 2.9866, 2.9845, 2.9798, 2.9867, 2.9909, 2.9752]).std()
[ 18, 8, 4, 768, 3072, 256, 251.1, 2.9882, 6, 2.9935, 2.9876, 2.6996, 15750], # 0.9h
[ 18, 8, 4, 768, 3072, 240, 245.8, 2.9870, 7, 2.9926, 2.9870, 2.6623, 15750], # 0.9h
[ 18, 8, 4, 768, 3072, 224, 240.5, 2.9853, 6, 2.9907, 2.9850, 2.6741, 15750], # 0.9h
[ 18, 8, 4, 768, 3072, 208, 235.2, 2.9896, 6, 2.9961, 2.9889, 2.7215, 15750], # 0.8h 11.0G
[ 18, 8, 4, 768, 3072, 192, 229.9, 2.9901, 5, 3.1371, 2.9901, 3.0174, 15750], # 0.8h
[ 18, 8, 4, 768, 3072, 176, 224.5, 2.9878, 7, 2.9953, 2.9878, 2.7572, 15750], # 0.8h
[+18, 8, 4, 768, 3072, 160, 219.2, 2.9805, 7, 2.9851,+2.9805, 3.1170, 15750], # 0.7h  minGemma-hidden_layers18-att_heads8-kv_heads4-hidden768-intermediate3072-head_dim160-T1024--2026-07-12-16-24
# valx8: 2.9812 +- 0.0037 # torch.Tensor([2.9805, 2.9865, 2.9778, 2.9837, 2.9773, 2.9806, 2.9866, 2.9816, 2.9766]).std()

[ 18, 8, 4, 736, 2944, 288, 245.7, 2.9812, 7, 2.9887,+2.9812, 2.6812, 15750], # 1.0h
[ 18, 8, 4, 736, 2944, 272, 240.6, 2.9838, 7, 2.9890, 2.9838, 2.6553, 15750], # 1.0h
[ 18, 8, 4, 736, 2944, 256, 235.5, 2.9835, 6, 2.9897,+2.9824, 2.6685, 15750], # 0.9h
[ 18, 8, 4, 736, 2944, 240, 230.5, 2.9861, 6, 2.9927, 2.9850, 2.6770, 15750], # 0.9h
[ 18, 8, 4, 736, 2944, 224, 225.4, 2.9827, 6, 2.9906,+2.9827, 3.1386, 15750], # 0.8h
[ 18, 8, 4, 736, 2944, 208, 220.3, 2.9830, 7, 2.9873,+2.9830, 2.6586, 15750], # 0.8h
[ 18, 8, 4, 736, 2944, 192, 215.2, 2.9851, 7, 2.9908, 2.9851, 2.6589, 15750], # 0.8h
[ 18, 8, 4, 736, 2944, 176, 210.1, 2.9847, 6, 2.9913, 2.9838, 2.6782, 15750], # 0.7h 10.6G
[ 18, 8, 4, 736, 2944, 160, 205.0, 2.9859, 7, 2.9916, 2.9859, 2.7146, 15750], # 0.7h

[ 18, 8, 4, 704, 2816, 288, 230.2, 2.9874, 5, 2.9878, 2.9851, 2.7505, 15750], # 1.0h
[ 18, 8, 4, 704, 2816, 272, 225.3, 2.9840, 6, 2.9895, 2.9839, 2.6774, 15750], # 0.9h
[ 18, 8, 4, 704, 2816, 256, 220.4, 2.9885, 6, 2.9961, 2.9881, 2.6780, 15750], # 0.9h
[ 18, 8, 4, 704, 2816, 240, 215.6, 2.9809, 7, 2.9878,+2.9809, 2.6633, 15750], # 0.8h
# valx8: 2.9846 +- 0.0040 # torch.Tensor([2.9809, 2.9869, 2.9888, 2.9880, 2.9849, 2.9801, 2.9881, 2.9860, 2.9779]).std()
[ 18, 8, 4, 704, 2816, 224, 210.7, 2.9836, 6, 2.9904,+2.9822, 2.6737, 15750], # 0.8h 10.7G
[ 18, 8, 4, 704, 2816, 208, 205.8, 2.9821, 6, 2.9892,+2.9819, 2.6824, 15750], # 0.8h
[ 18, 8, 4, 704, 2816, 192, 201.0, 2.9887, 6, 2.9941, 2.9882, 2.6758, 15750], # 0.7h
[ 18, 8, 4, 704, 2816, 176, 196.1, 2.9826, 6, 2.9873,+2.9813, 2.6692, 15750], # 0.7h 10.4G
[ 18, 8, 4, 704, 2816, 160, 191.2, 2.9837, 6, 2.9887,+2.9823, 2.6982, 15750], # 0.7h

[ 18, 8, 4, 672, 2688, 288, 215.1, 2.9839, 7, 2.9870, 2.9839, 2.6617, 15750], # 1.0h
[ 18, 8, 4, 672, 2688, 272, 210.4, 2.9854, 6, 2.9950, 2.9854, 2.7166, 15750], # 0.9h
[ 18, 8, 4, 672, 2688, 256, 205.8, 2.9818, 7, 2.9874,+2.9818, 2.6633, 15750], # 0.8h
[ 18, 8, 4, 672, 2688, 240, 201.1, 2.9831, 6, 2.9898,+2.9824, 2.6733, 15750], # 0.8h
[ 18, 8, 4, 672, 2688, 224, 196.5, 2.9877, 5, 2.9888, 2.9872, 2.6817, 15750], # 0.8h
[ 18, 8, 4, 672, 2688, 208, 191.8, 2.9905, 7, 2.9958, 2.9905, 2.6689, 15750], # 0.8h
[ 18, 8, 4, 672, 2688, 192, 187.2, 2.9877, 6, 2.9919, 2.9852, 2.9224, 15750], # 0.7h
[ 18, 8, 4, 672, 2688, 176, 182.5, 2.9867, 6, 2.9913, 2.9849, 2.7198, 15750], # 0.7h
[ 18, 8, 4, 672, 2688, 160, 177.9, 2.9856, 6, 2.9908, 2.9854, 2.6738, 15750], # 0.7h

[ 18, 8, 4, 640, 2560, 288, 200.4, 2.9866, 6, 2.9919, 2.9844, 2.7103, 15750], # 0.9h
[ 18, 8, 4, 640, 2560, 272, 196.0, 2.9821, 6, 2.9901,+2.9821, 2.6742, 15750], # 0.9h
[ 18, 8, 4, 640, 2560, 256, 191.5, 2.9853, 6, 2.9917, 2.9845, 2.6939, 15750], # 0.8h
[ 18, 8, 4, 640, 2560, 240, 187.1, 2.9867, 6, 2.9970, 2.9867, 2.6711, 15750], # 0.8h
[ 18, 8, 4, 640, 2560, 224, 182.7, 2.9898, 6, 2.9965, 2.9895, 2.6662, 15750], # 0.8h
[ 18, 8, 4, 640, 2560, 208, 178.3, 2.9852, 6, 2.9893,+2.9830, 2.6789, 15750], # 0.7h 9.4G
[ 18, 8, 4, 640, 2560, 192, 173.8, 2.9904, 6, 2.9982, 2.9899, 2.6687, 15750], # 0.7h
[ 18, 8, 4, 640, 2560, 176, 169.4, 2.9899, 6, 2.9970, 2.9888, 2.6779, 15750], # 0.7h
[ 18, 8, 4, 640, 2560, 160, 165.0, 2.9879, 6, 2.9964, 2.9877, 2.6771, 15750], # 0.7h

[ 18, 8, 4, 608, 2432, 288, 186.2, 2.9872, 7, 2.9939, 2.9872, 2.6613, 15750], # 0.9h
[ 18, 8, 4, 608, 2432, 272, 182.0, 2.9890, 6, 2.9970, 2.9872, 2.6715, 15750], # 0.9h
[ 18, 8, 4, 608, 2432, 256, 177.8, 2.9843, 6, 2.9889, 2.9838, 2.6822, 15750], # 0.8h 9.5G
[ 18, 8, 4, 608, 2432, 240, 173.6, 2.9900, 7, 2.9980, 2.9900, 2.6671, 15750], # 0.8h
[ 18, 8, 4, 608, 2432, 224, 169.4, 2.9786, 6, 2.9866,+2.9786, 2.6773, 15750], # 0.7h  minGemma-hidden_layers18-att_heads8-kv_heads4-hidden608-intermediate2432-head_dim224-T1024--2026-06-29-06-00
# valx8: 2.9814 +- 0.0036 # torch.Tensor([2.9786, 2.9760, 2.9867, 2.9809, 2.9828, 2.9827, 2.9780, 2.9861, 2.9812]).std()
[ 18, 8, 4, 608, 2432, 208, 165.2, 2.9903, 6, 2.9985, 2.9898, 2.6708, 15750], # 0.7h 9.2G
[ 18, 8, 4, 608, 2432, 192, 161.0, 2.9897, 7, 2.9938, 2.9897, 2.6594, 15750], # 0.7h
[ 18, 8, 4, 608, 2432, 176, 156.8, 2.9848, 6, 2.9906, 2.9838, 2.6808, 15750], # 0.7h
[ 18, 8, 4, 608, 2432, 160, 152.5, 2.9836, 7, 3.0788, 2.9836, 2.6821, 15750], # 0.6h

[ 18, 8, 4, 576, 2304, 288, 172.4, 2.9884, 6, 2.9960, 2.9881, 2.6729, 15750], # 0.9h
[ 18, 8, 4, 576, 2304, 272, 168.4, 2.9904, 6, 3.0006, 2.9889, 2.6731, 15750], # 0.8h? 9.4G
[ 18, 8, 4, 576, 2304, 256, 164.4, 2.9875, 6, 2.9947, 2.9855, 2.6781, 15750], # 0.8h
[ 18, 8, 4, 576, 2304, 240, 160.4, 2.9888, 6, 2.9981, 2.9875, 2.6734, 15750], # 0.7h
[ 18, 8, 4, 576, 2304, 224, 156.5, 2.9902, 7, 2.9971, 2.9902, 2.6648, 15750], # 0.7h
[ 18, 8, 4, 576, 2304, 208, 152.5, 2.9846, 6, 2.9915,+2.9830, 2.6788, 15750], # 0.7h
[ 18, 8, 4, 576, 2304, 192, 148.5, 2.9851, 6, 2.9923, 2.9840, 2.6722, 15750], # 0.7h
[ 18, 8, 4, 576, 2304, 176, 144.5, 2.9913, 6, 2.9978, 2.9890, 2.6747, 15750], # 0.6h
[ 18, 8, 4, 576, 2304, 160, 140.5, 2.9899, 7, 2.9958, 2.9899, 2.6633, 15750], # 0.6h


# local best for H7(1): 2.9811 (valx8: 2.9809)
[ 18, 7, 1, 784, 3136, 288, 237.4, 2.9909, 7, 2.9956, 2.9909, 2.7377, 15750], # 0.9h
[ 18, 7, 1, 784, 3136, 272, 233.7, 2.9914, 6, 2.9997, 2.9911, 2.7152, 15750], # 0.8h
[ 18, 7, 1, 784, 3136, 256, 230.1, 2.9942, 6, 3.1198, 2.9922, 2.6717, 15750], # 0.8h 11.8G
[ 18, 7, 1, 784, 3136, 240, 226.5, 2.9961, 6, 3.4737, 2.9961, 3.3764, 15750], # 0.8h
[ 18, 7, 1, 784, 3136, 224, 222.9, 2.9879, 7, 2.9934, 2.9879, 2.6937, 15750], # 0.7h
[ 18, 7, 1, 784, 3136, 208, 219.3, 2.9949, 7, 3.0001, 2.9949, 2.6747, 15750], # 0.7h
[ 18, 7, 1, 784, 3136, 192, 215.7, 2.9918, 7, 2.9970, 2.9918, 2.6832, 15750], # 0.7h
[ 18, 7, 1, 784, 3136, 176, 212.1, 2.9929, 6, 2.9987, 2.9926, 2.7974, 15750], # 0.7h
[ 18, 7, 1, 784, 3136, 160, 208.4, 2.9925, 7, 2.9966, 2.9925, 2.6799, 15750], # 0.7h

[ 18, 7, 1, 742, 2968, 288, 217.9, 2.9936, 7, 3.0021, 2.9936, 2.8451, 15750], # 0.8h 11.6G
[ 18, 7, 1, 742, 2968, 272, 214.5, 2.9892, 7, 2.9947, 2.9892, 2.6817, 15750], # 0.8h
[ 18, 7, 1, 742, 2968, 256, 211.1, 2.9939, 6, 3.0019, 2.9920, 2.7021, 15750], # 0.7h
[ 18, 7, 1, 742, 2968, 240, 207.6, 2.9916, 5, 3.1633, 2.9916, 3.1671, 15750], # 0.7h
[ 18, 7, 1, 742, 2968, 224, 204.2, 2.9879, 7, 2.9958, 2.9879, 3.0161, 15750], # 0.7h
[ 18, 7, 1, 742, 2968, 208, 200.8, 3.0013, 6, 3.0089, 3.0000, 2.6768, 15750], # 0.7h
[ 18, 7, 1, 742, 2968, 192, 197.4, 2.9857, 7, 2.9913, 2.9857, 2.6717, 15750], # 0.7h
[ 18, 7, 1, 742, 2968, 176, 194.0, 2.9922, 7, 2.9967, 2.9922, 2.9141, 15750], # 0.7h 10.4G
[ 18, 7, 1, 742, 2968, 160, 190.6, 2.9927, 6, 2.9997, 2.9908, 2.6655, 15750], # 0.6h

[ 18, 7, 1, 700, 2800, 288, 199.2, 2.9918, 6, 2.9978, 2.9918, 2.6661, 15750], # 0.8h
[ 18, 7, 1, 700, 2800, 272, 196.0, 2.9901, 7, 2.9959, 2.9901, 2.6591, 15750], # 0.8h
[ 18, 7, 1, 700, 2800, 256, 192.8, 2.9927, 7, 2.9957, 2.9927, 2.6575, 15750], # 0.7h
[ 18, 7, 1, 700, 2800, 240, 189.5, 2.9954, 7, 3.2278, 2.9954, 3.2504, 15750], # 0.7h
[ 18, 7, 1, 700, 2800, 224, 186.3, 2.9934, 6, 2.9993, 2.9916, 2.7839, 15750], # 0.7h
[ 18, 7, 1, 700, 2800, 208, 183.1, 2.9933, 6, 3.0039, 2.9918, 2.6671, 15750], # 0.7h 10.2G
[ 18, 7, 1, 700, 2800, 192, 179.9, 2.9925, 7, 2.9994, 2.9925, 2.6603, 15750], # 0.6h
[ 18, 7, 1, 700, 2800, 176, 176.6, 2.9910, 7, 2.9949, 2.9910, 2.6964, 15750], # 0.6h
[ 18, 7, 1, 700, 2800, 160, 173.4, 2.9961, 6, 3.0036, 2.9944, 2.6665, 15750], # 0.6h

[ 18, 7, 1, 658, 2632, 288, 181.3, 2.9955, 6, 3.0017, 2.9945, 2.6612, 15750], # 0.8h
[ 18, 7, 1, 658, 2632, 272, 178.3, 2.9892, 6, 2.9983, 2.9871, 2.6969, 15750], # 0.8h
[ 18, 7, 1, 658, 2632, 256, 175.2, 2.9901, 7, 3.1114, 2.9901, 2.6702, 15750], # 0.7h
[ 18, 7, 1, 658, 2632, 240, 172.2, 2.9856, 7, 2.9877, 2.9856, 2.6821, 15750], # 0.7h 10.2G
[ 18, 7, 1, 658, 2632, 224, 169.2, 2.9870, 7, 2.9961, 2.9870, 2.6761, 15750], # 0.7h
[ 18, 7, 1, 658, 2632, 208, 166.1, 2.9852, 6, 2.9906,+2.9833, 2.7059, 15750], # 0.6h 10.0G
[ 18, 7, 1, 658, 2632, 192, 163.1, 2.9950, 6, 3.0029, 2.9926, 2.6681, 15750], # 0.6h
[ 18, 7, 1, 658, 2632, 176, 160.1, 2.9873, 7, 2.9958, 2.9873, 2.6614, 15750], # 0.6h 9.9G
[ 18, 7, 1, 658, 2632, 160, 157.0, 2.9882, 6, 2.9943, 2.9878, 2.6747, 15750], # 0.6h

[ 18, 7, 1, 616, 2464, 288, 164.1, 2.9907, 7, 2.9982, 2.9907, 2.6628, 15750], # 0.7h
[ 18, 7, 1, 616, 2464, 272, 161.3, 2.9944, 6, 3.0001, 2.9939, 2.6743, 15750], # 0.7h 10.0G
[ 18, 7, 1, 616, 2464, 256, 158.5, 2.9982, 6, 3.0072, 2.9958, 2.6674, 15750], # 0.7h
[ 18, 7, 1, 616, 2464, 240, 155.6, 2.9861, 6, 2.9918, 2.9859, 2.6715, 15750], # 0.6h 9.8G
[ 18, 7, 1, 616, 2464, 224, 152.8, 2.9825, 6, 2.9871,+2.9825, 2.7048, 15750], # 0.6h 9.8G
[+18, 7, 1, 616, 2464, 208, 149.9, 2.9825, 6, 2.9895,+2.9811, 2.6692, 15750], # 0.6h  minGemma-hidden_layers18-att_heads7-kv_heads1-hidden616-intermediate2464-head_dim208-T1024--2026-07-18-00-42
# valx8: 2.9809 +- 0.0061 # torch.Tensor([2.9811, 2.9827, 2.9846, 2.9859, 2.9890, 2.9810, 2.9727, 2.9807, 2.9700]).std()
[ 18, 7, 1, 616, 2464, 192, 147.1, 2.9904, 7, 2.9951, 2.9904, 2.6647, 15750], # 0.6h
[ 18, 7, 1, 616, 2464, 176, 144.3, 2.9907, 7, 2.9963, 2.9907, 2.6660, 15750], # 0.6h
[ 18, 7, 1, 616, 2464, 160, 141.4, 2.9972, 6, 3.0032, 2.9955, 2.7181, 15750], # 0.5h 9.5G

[ 18, 7, 1, 574, 2296, 288, 147.7, 2.9964, 6, 3.0053, 2.9961, 2.6715, 15750], # 0.7h
[ 18, 7, 1, 574, 2296, 272, 145.1, 2.9986, 6, 3.0050, 2.9965, 2.6778, 15750], # 0.7h
[ 18, 7, 1, 574, 2296, 256, 142.4, 2.9947, 6, 3.0029, 2.9940, 2.6775, 15750], # 0.6h 9.8G
[ 18, 7, 1, 574, 2296, 240, 139.8, 2.9938, 6, 3.0027, 2.9930, 2.6822, 15750], # 0.6h 
[ 18, 7, 1, 574, 2296, 224, 137.2, 2.9879, 7, 2.9940, 2.9879, 2.6598, 15750], # 0.6h
[ 18, 7, 1, 574, 2296, 208, 134.5, 2.9907, 7, 2.9960, 2.9907, 2.6679, 15750], # 0.6h
[ 18, 7, 1, 574, 2296, 192, 131.9, 2.9944, 5, 2.9945, 2.9942, 2.6998, 15750], # 0.5h
[ 18, 7, 1, 574, 2296, 176, 129.2, 2.9900, 7, 2.9957, 2.9900, 2.6620, 15750], # 0.5h
[ 18, 7, 1, 574, 2296, 160, 126.6, 2.9888, 7, 2.9934, 2.9888, 2.6637, 15750], # 0.5h


# local best for H6(3): 2.9807 (valx8: 2.9846)
[ 18, 6, 3, 768, 3072, 288, 237.8, 2.9878, 7, 2.9933, 2.9878, 2.6642, 15750], # 0.9h 11.1G
[ 18, 6, 3, 768, 3072, 272, 233.8, 2.9887, 6, 2.9947, 2.9869, 2.6789, 15750], # 0.9h 11.0G
[ 18, 6, 3, 768, 3072, 256, 229.9, 2.9850, 7, 2.9916, 2.9850, 2.6655, 15750], # 0.8h
[ 18, 6, 3, 768, 3072, 240, 225.9, 2.9853, 7, 2.9893, 2.9853, 2.6715, 15750], # 0.8h
[ 18, 6, 3, 768, 3072, 224, 221.9, 2.9838, 7, 2.9902, 2.9838, 2.6646, 15750], # 0.8h
[ 18, 6, 3, 768, 3072, 208, 217.9, 2.9895, 5, 3.0584, 2.9895, 3.1697, 15750], # 0.8h
[ 18, 6, 3, 768, 3072, 192, 213.9, 2.9939, 6, 3.1173, 2.9922, 2.7470, 15750], # 0.7h 10.6G
[ 18, 6, 3, 768, 3072, 176, 209.9, 2.9903, 6, 2.9944, 2.9903, 3.1871, 15750], # 0.7h
[ 18, 6, 3, 768, 3072, 160, 206.0, 2.9947, 7, 3.0086, 2.9947, 3.1998, 15750], # 0.7h

[ 18, 6, 3, 720, 2880, 288, 215.5, 2.9923, 7, 2.9956, 2.9923, 2.6680, 15750], # 0.9h
[ 18, 6, 3, 720, 2880, 272, 211.8, 2.9890, 6, 2.9928, 2.9879, 2.6746, 15750], # 0.9h
[ 18, 6, 3, 720, 2880, 256, 208.0, 2.9860, 6, 2.9928, 2.9860, 2.6758, 15750], # 0.8h
[ 18, 6, 3, 720, 2880, 240, 204.3, 2.9855, 7, 2.9934, 2.9855, 2.6622, 15750], # 0.8h
[ 18, 6, 3, 720, 2880, 224, 200.6, 2.9940, 7, 2.9976, 2.9940, 2.6689, 15750], # 0.7h 10.5G
[ 18, 6, 3, 720, 2880, 208, 196.8, 2.9878, 6, 2.9942, 2.9872, 2.6783, 15750], # 0.7h
[ 18, 6, 3, 720, 2880, 192, 193.1, 2.9853, 6, 3.1053, 2.9853, 3.2821, 15750], # 0.7h
[ 18, 6, 3, 720, 2880, 176, 189.4, 2.9914, 7, 2.9945, 2.9914, 2.6727, 15750], # 0.7h 9.5G
[ 18, 6, 3, 720, 2880, 160, 185.6, 2.9885, 6, 2.9960, 2.9870, 2.7409, 15750], # 0.7h

[ 18, 6, 3, 672, 2688, 288, 194.2, 2.9895, 7, 2.9955, 2.9895, 2.6773, 15750], # 0.8h
[ 18, 6, 3, 672, 2688, 272, 190.7, 2.9860, 6, 2.9861, 2.9860, 2.9303, 15750], # 0.8h
[ 18, 6, 3, 672, 2688, 256, 187.2, 2.9857, 7, 2.9904, 2.9857, 2.6690, 15750], # 0.8h 9.6G
[ 18, 6, 3, 672, 2688, 240, 183.7, 2.9864, 6, 2.9920, 2.9841, 2.6709, 15750], # 0.7h
[+18, 6, 3, 672, 2688, 224, 180.2, 2.9807, 7, 2.9837,+2.9807, 2.6715, 15750], # 0.7h  minGemma-hidden_layers18-att_heads6-kv_heads3-hidden672-intermediate2688-head_dim224-T1024--2026-07-21-20-19
# valx8: 2.9846 +- 0.0043 # torch.Tensor([2.9807, 2.9880, 2.9891, 2.9814, 2.9874, 2.9898, 2.9857, 2.9788, 2.9803]).std()
[ 18, 6, 3, 672, 2688, 208, 176.7, 2.9908, 6, 2.9963, 2.9891, 2.6748, 15750], # 0.7h 9.4G
[ 18, 6, 3, 672, 2688, 192, 173.3, 2.9920, 6, 2.9949, 2.9900, 2.7081, 15750], # 0.7h
[ 18, 6, 3, 672, 2688, 176, 169.8, 2.9909, 5, 2.9910, 2.9909, 3.1342, 15750], # 0.6h
[ 18, 6, 3, 672, 2688, 160, 166.3, 2.9970, 7, 3.0024, 2.9970, 3.1756, 15750], # 0.6h 9.1G

[ 18, 6, 3, 624, 2496, 288, 173.8, 2.9900, 6, 2.9973, 2.9896, 2.8991, 15750], # 0.8h
[ 18, 6, 3, 624, 2496, 272, 170.6, 2.9898, 5, 2.9914, 2.9883, 2.7256, 15750], # 0.8h
[ 18, 6, 3, 624, 2496, 256, 167.3, 2.9834, 6, 2.9901,+2.9830, 2.6754, 15750], # 0.7h
[ 18, 6, 3, 624, 2496, 240, 164.1, 2.9876, 7, 2.9942, 2.9876, 2.6681, 15750], # 0.7h
[ 18, 6, 3, 624, 2496, 224, 160.9, 2.9845, 6, 2.9917, 2.9845, 2.7383, 15750], # 0.7h
[ 18, 6, 3, 624, 2496, 208, 157.6, 2.9964, 6, 3.0018, 2.9960, 2.6948, 15750], # 0.7h
[ 18, 6, 3, 624, 2496, 192, 154.4, 2.9886, 7, 2.9947, 2.9886, 2.6740, 15750], # 0.6h 8.9G
[ 18, 6, 3, 624, 2496, 176, 151.2, 2.9949, 6, 3.0018, 2.9943, 2.6852, 15750], # 0.6h
[ 18, 6, 3, 624, 2496, 160, 147.9, 2.9912, 6, 2.9979, 2.9895, 2.6799, 15750], # 0.6h

[ 18, 6, 3, 576, 2304, 288, 154.5, 2.9850, 6, 2.9926,+2.9841, 2.6816, 15750], # 0.8h
[ 18, 6, 3, 576, 2304, 272, 151.5, 2.9901, 7, 2.9974, 2.9901, 2.6705, 15750], # 0.7h 9.0G
[ 18, 6, 3, 576, 2304, 256, 148.5, 2.9870, 6, 2.9939, 2.9853, 2.6820, 15750], # 0.7h
[ 18, 6, 3, 576, 2304, 240, 145.5, 2.9853, 7, 2.9899, 2.9853, 2.6708, 15750], # 0.7h
[ 18, 6, 3, 576, 2304, 224, 142.5, 2.9918, 7, 2.9989, 2.9918, 2.6954, 15750], # 0.6h 8.8G
[ 18, 6, 3, 576, 2304, 208, 139.5, 2.9869, 7, 2.9917, 2.9869, 2.6706, 15750], # 0.6h
[ 18, 6, 3, 576, 2304, 192, 136.6, 2.9899, 6, 2.9982, 2.9887, 2.6778, 15750], # 0.6h
[ 18, 6, 3, 576, 2304, 176, 133.6, 2.9935, 7, 2.9999, 2.9935, 2.6664, 15750], # 0.6h 7.8G
[ 18, 6, 3, 576, 2304, 160, 130.6, 2.9875, 7, 2.9946, 2.9875, 2.6695, 15750], # 0.6h

In [94]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  18 # 8 # G28 G18 #blocks
num_attention_heads =10 # 4 # G16 G8
num_key_value_heads = 5 # 4 # G16 G1
hidden_size = num_attention_heads*68 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 240 # 32 # G256 # dim in attention
rms_norm_eps = 1e0 # 1e-6
rope_theta = 80000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//2; N_step=5250*2; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=10.0e-4, weight_decay=1.8, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(5000*2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9837:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

64.512
L18 att10 kv_heads5 hidden680 intermediate2720 head_dim240 T1024

1 4.563516369047619 tensor(3.1910)

2 2.7863848586309525 tensor(3.0054)

3 2.703696242559524 tensor(2.9849)

4 2.6843723958333334 tensor(2.9809)

5 2.670903831845238 tensor(2.9789)

6 2.6618433779761905 tensor(2.9800)

7 2.6480745907738097 tensor(2.9873)
[ 18, 10, 5, 680, 2720, 240, 222.3, 2.9800, 6, 2.9873, 2.9789, 2.6618, 10500],

In [15]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  18 # 8 # G28 G18 #blocks
num_attention_heads = 9 # 4 # G16 G8
num_key_value_heads = 3 # 4 # G16 G1
hidden_size = num_attention_heads*84 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 208 # 32 # G256 # dim in attention
rms_norm_eps = 1e0 # 1e-6
rope_theta = 80000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//2; N_step=5250*2; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=10.0e-4, weight_decay=1.8, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(5000*2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9837:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

64.512
L18 att9 kv_heads3 hidden756 intermediate3024 head_dim208 T1024

1 4.570540922619047 tensor(3.1879)

2 2.7789222470238095 tensor(3.0079)

3 2.7050217633928573 tensor(2.9881)

4 2.6874737723214284 tensor(2.9812)

5 2.6792215401785713 tensor(2.9772)

6 2.715617931547619 tensor(2.9807)
back to previous

7 2.69893359375 tensor(2.9852)
[ 18, 9, 3, 756, 3024, 208, 229.5, 2.9772, 6, 2.9852, 2.9772, 2.7156, 10500],

In [281]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  18 # 8 # G28 G18 #blocks
num_attention_heads = 8 # 4 # G16 G8
num_key_value_heads = 4 # 4 # G16 G1
hidden_size = num_attention_heads*96 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 160 # 32 # G256 # dim in attention
rms_norm_eps = 1e0 # 1e-6
rope_theta = 80000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//3; N_step=5250*3; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=3, learning_rate=10.0e-4, weight_decay=1.8, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//3 # Evaluation follows
    for k in range(5000*3 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9837:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

64.512
L18 att8 kv_heads4 hidden768 intermediate3072 head_dim160 T1024

1 4.959919270833334 tensor(3.1935)

2 2.790693266369048 tensor(3.0082)

3 2.7422682291666667 tensor(2.9894)

4 3.1519918154761903 tensor(3.0836)
back to previous

5 2.7020448288690475 tensor(2.9815)

6 2.6996568080357144 tensor(2.9805)

7 3.1169795386904764 tensor(3.0012)
back to previous

8 2.673951636904762 tensor(2.9851)
[ 18, 8, 4, 768, 3072, 160, 219.2, 2.9805, 7, 2.9851, 2.9805, 3.1170, 15750],

In [240]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  18 # 8 # G28 G18 #blocks
num_attention_heads = 8 # 4 # G16 G8
num_key_value_heads = 4 # 4 # G16 G1
hidden_size = num_attention_heads*76 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 224 # 32 # G256 # dim in attention
rms_norm_eps = 1e0 # 1e-6
rope_theta = 80000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//3; N_step=5250*3; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=3, learning_rate=10.0e-4, weight_decay=1.8, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//3 # Evaluation follows
    for k in range(5000*3 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9837:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

64.512
L18 att8 kv_heads4 hidden608 intermediate2432 head_dim224 T1024

1 4.552543154761905 tensor(3.2443)

2 2.8187708333333332 tensor(3.0200)

3 2.718820870535714 tensor(2.9902)

4 2.696526413690476 tensor(2.9832)

5 2.682045386904762 tensor(2.9786)

6 2.6772745535714284 tensor(2.9812)
back to previous

7 2.6692088913690477 tensor(2.9866)
[ 18, 8, 4, 608, 2432, 224, 169.4, 2.9786, 6, 2.9866, 2.9786, 2.6773, 15750],

In [9]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  18 # 8 # G28 G18 #blocks
num_attention_heads = 7 # 4 # G16 G8
num_key_value_heads = 1 # 4 # G16 G1
hidden_size = num_attention_heads*88 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 208 # 32 # G256 # dim in attention
rms_norm_eps = 1e0 # 1e-6
rope_theta = 80000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//3; N_step=5250*3; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=3, learning_rate=10.0e-4, weight_decay=1.8, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//3 # Evaluation follows
    for k in range(5000*3 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9837:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

64.512
L18 att7 kv_heads1 hidden616 intermediate2464 head_dim208 T1024

1 4.586116071428571 tensor(3.2113)

2 2.7942261904761905 tensor(3.0150)

3 2.7086670386904763 tensor(2.9884)

4 2.6916175595238094 tensor(2.9817)

5 2.679869605654762 tensor(2.9811)

6 2.669198288690476 tensor(2.9825)

7 2.6572025669642856 tensor(2.9895)
[ 18, 7, 1, 616, 2464, 208, 149.9, 2.9825, 6, 2.9895, 2.9811, 2.6692, 15750],

In [312]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  18 # 8 # G28 G18 #blocks
num_attention_heads = 6 # 4 # G16 G8
num_key_value_heads = 3 # 4 # G16 G1
hidden_size = num_attention_heads*112 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 224 # 32 # G256 # dim in attention
rms_norm_eps = 1e0 # 1e-6
rope_theta = 80000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//3; N_step=5250*3; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=3, learning_rate=10.0e-4, weight_decay=1.8, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//3 # Evaluation follows
    for k in range(5000*3 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9837:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

64.512
L18 att6 kv_heads3 hidden672 intermediate2688 head_dim224 T1024

1 4.597893601190476 tensor(3.2532)

2 2.8111212797619047 tensor(3.0216)

3 3.079685825892857 tensor(3.0407)
back to previous

4 2.7243318452380954 tensor(2.9928)

5 2.697084449404762 tensor(2.9831)

6 2.6851897321428573 tensor(2.9807)

7 2.6715193452380954 tensor(2.9853)
back to previous

8 2.6754254092261904 tensor(2.9837)
[ 18, 6, 3, 672, 2688, 224, 180.2, 2.9807, 7, 2.9837, 2.9807, 2.6715, 15750],

# L16

In [ ]:
# L16 FORGETTER T1024 Baby10M (default: B12 x4 N5250 lr10e-4 WD1.8) # H11(1): 2.9854(valx1), H10(5): 2.9819, H9(3): 2.9806(env1), H8(4): 2.9776, H7(1): 2.9830

# local best for H11(1): 2.9854
[ 16,11, 1, 792, 3168, 288, 248.0, 2.9870, 7, 2.9927, 2.9870, 2.6488, 15750], # 1.0h
[ 16,11, 1, 792, 3168, 272, 243.1, 2.9961, 4, 2.9964, 2.9959, 2.6883, 15750], # 0.9h
[ 16,11, 1, 792, 3168, 256, 238.2, 2.9876, 7, 2.9948, 2.9876, 2.6441, 10500], # 0.8h 15.4G
[ 16,11, 1, 792, 3168, 240, 233.4, 2.9923, 7, 2.9977, 2.9923, 2.6488, 10500], # 0.8h
[ 16,11, 1, 792, 3168, 224, 228.5, 2.9958, 6, 3.0029, 2.9958, 2.7269, 10500], # 0.8h
[ 16,11, 1, 792, 3168, 208, 223.6, 2.9975, 7, 3.1314, 2.9975, 2.6785, 10500], # 0.8h 15.1G
[ 16,11, 1, 792, 3168, 192, 218.8, 3.0017, 6, 3.0092, 2.9998, 2.6614, 10500], # 0.7h
[ 16,11, 1, 792, 3168, 176, 213.9, 2.9965, 7, 3.0035, 2.9965, 2.7586, 10500], # 0.7h
[ 16,11, 1, 792, 3168, 160, 209.0, 2.9973, 7, 3.0039, 2.9973, 2.6545, 10500], # 0.7h

[+16,11, 1, 748, 2992, 288, 227.9, 2.9877, 5, 2.9881,+2.9854, 2.6633, 15750], # 0.9h  not saved
[ 16,11, 1, 748, 2992, 272, 223.3, 2.9987, 6, 3.0032, 2.9973, 2.7131, 15750], # 0.9h
[ 16,11, 1, 748, 2992, 256, 218.7, 2.9989, 6, 3.0052, 2.9981, 2.6584, 10500], # 0.8h
[ 16,11, 1, 748, 2992, 240, 214.1, 2.9958, 6, 3.0042, 2.9958, 2.6618, 10500], # 0.8h
[ 16,11, 1, 748, 2992, 224, 209.5, 2.9941, 5, 2.9955, 2.9937, 2.6659, 10500], # 0.7h 15.0G
[ 16,11, 1, 748, 2992, 208, 204.9, 2.9878, 7, 2.9941, 2.9878, 2.6574, 10500], # 0.7h 14.7G
[ 16,11, 1, 748, 2992, 192, 200.3, 2.9865, 7, 2.9918, 2.9865, 2.7376, 10500], # 0.7h
[ 16,11, 1, 748, 2992, 176, 195.7, 2.9986, 6, 3.0062, 2.9986, 3.1567, 10500], # 0.7h 13.3G
[ 16,11, 1, 748, 2992, 160, 191.1, 2.9922, 6, 2.9981, 2.9921, 2.6841, 10500], # 0.6h 13.2G

[ 16,11, 1, 704, 2816, 288, 208.5, 2.9903, 7, 3.0773, 2.9903, 3.0779, 15750], # 0.9h 11.6G
[ 16,11, 1, 704, 2816, 272, 204.2, 2.9934, 5, 2.9944, 2.9933, 2.8062, 15750], # 0.9h
[ 16,11, 1, 704, 2816, 256, 199.9, 3.0025, 6, 3.0119, 3.0025, 2.6825, 10500], # 0.7h
[ 16,11, 1, 704, 2816, 240, 195.5, 2.9905, 6, 2.9993, 2.9890, 2.6936, 10500], # 0.7h 13.5G
[ 16,11, 1, 704, 2816, 224, 191.2, 2.9947, 6, 3.0018, 2.9927, 2.6636, 10500], # 0.7h
[ 16,11, 1, 704, 2816, 208, 186.9, 2.9919, 7, 2.9963, 2.9919, 2.6494, 10500], # 0.7h
[ 16,11, 1, 704, 2816, 192, 182.6, 2.9965, 7, 3.0016, 2.9965, 2.6491, 10500], # 0.6h
[ 16,11, 1, 704, 2816, 176, 178.2, 2.9966, 7, 3.0025, 2.9966, 2.6509, 10500], # 0.6h
[ 16,11, 1, 704, 2816, 160, 173.9, 2.9945, 7, 3.0001, 2.9945, 2.6510, 10500], # 0.6h 13.0G

[ 16,11, 1, 660, 2640, 288, 189.9, 2.9957, 7, 3.0011, 2.9957, 2.6539, 10500], # 0.8h
[ 16,11, 1, 660, 2640, 272, 185.9, 2.9944, 6, 3.0022, 2.9941, 2.6830, 10500], # 0.8h 13.7G
[ 16,11, 1, 660, 2640, 256, 181.8, 2.9928, 6, 3.0039, 2.9928, 2.6611, 10500], # 0.7h
[ 16,11, 1, 660, 2640, 240, 177.7, 2.9934, 6, 2.9995, 2.9925, 2.6683, 10500], # 0.7h
[ 16,11, 1, 660, 2640, 224, 173.7, 2.9898, 7, 2.9948, 2.9898, 2.6814, 10500], # 0.7h 13.1G
[ 16,11, 1, 660, 2640, 208, 169.6, 2.9856, 7, 2.9932,+2.9856, 2.6467, 10500], # 0.7h
[ 16,11, 1, 660, 2640, 192, 165.6, 2.9896, 7, 2.9956, 2.9896, 2.6463, 10500], # 0.6h
[ 16,11, 1, 660, 2640, 176, 161.5, 2.9899, 7, 2.9962, 2.9899, 2.6483, 10500], # 0.6h
[ 16,11, 1, 660, 2640, 160, 157.5, 2.9992, 6, 3.0046, 2.9971, 2.7261, 10500], # 0.6h 12.5G

[ 16,11, 1, 616, 2464, 288, 172.0, 2.9882, 7, 2.9919, 2.9882, 2.7666, 10500], # 0.8h 13.3G
[ 16,11, 1, 616, 2464, 272, 168.3, 2.9936, 6, 2.9992, 2.9936, 2.8476, 10500], # 0.8h 13.2G
[ 16,11, 1, 616, 2464, 256, 164.5, 2.9986, 5, 3.0001, 2.9983, 2.6722, 10500], # 0.7h
[ 16,11, 1, 616, 2464, 240, 160.7, 2.9861, 6, 2.9937,+2.9860, 2.6627, 10500], # 0.7h
[ 16,11, 1, 616, 2464, 224, 156.9, 2.9966, 6, 3.0050, 2.9941, 2.6621, 10500], # 0.7h
[ 16,11, 1, 616, 2464, 208, 153.1, 2.9932, 6, 3.0011, 2.9930, 2.6626, 10500], # 0.6h
[ 16,11, 1, 616, 2464, 192, 149.3, 3.0032, 6, 3.0129, 3.0032, 2.6607, 10500], # 0.6h
[ 16,11, 1, 616, 2464, 176, 145.6, 2.9931, 7, 2.9990, 2.9931, 2.6490, 10500], # 0.6h
[ 16,11, 1, 616, 2464, 160, 141.8, 2.9909, 6, 2.9995, 2.9894, 2.6709, 10500], # 0.5h

[ 16,11, 1, 572, 2288, 288, 154.9, 2.9940, 7, 2.9996, 2.9940, 2.6579, 10500], # 0.8h
[ 16,11, 1, 572, 2288, 272, 151.4, 3.0035, 6, 3.0122, 3.0016, 2.6672, 10500], # 0.7h
[ 16,11, 1, 572, 2288, 256, 147.9, 2.9956, 6, 3.0004, 2.9951, 2.6708, 10500], # 0.7h
[ 16,11, 1, 572, 2288, 240, 144.4, 2.9965, 6, 3.0042, 2.9957, 2.6758, 10500], # 0.7h
[ 16,11, 1, 572, 2288, 224, 140.9, 2.9910, 6, 2.9976, 2.9895, 2.6998, 10500], # 0.6h 12.5G
[ 16,11, 1, 572, 2288, 208, 137.4, 2.9948, 6, 3.0015, 2.9931, 2.6697, 10500], # 0.6h
[ 16,11, 1, 572, 2288, 192, 133.8, 2.9922, 6, 2.9983, 2.9922, 2.6701, 10500], # 0.6h
[ 16,11, 1, 572, 2288, 176, 130.3, 2.9949, 6, 3.0035, 2.9947, 2.6672, 10500], # 0.6h
[ 16,11, 1, 572, 2288, 160, 126.8, 2.9935, 7, 3.0007, 2.9935, 2.6561, 10500], # 0.5h


# local best for H10(5): 2.9798 (valx8: 2.9819)
[ 16,10, 5, 800, 3200, 288, 273.8, 2.9829, 6, 2.9886,+2.9819, 2.6727, 10500], # 1.0h
[ 16,10, 5, 800, 3200, 272, 267.7, 2.9876, 7, 2.9929, 2.9876, 2.6620, 10500], # 0.9h 15.6G
[ 16,10, 5, 800, 3200, 256, 261.5, 2.9892, 6, 2.9969, 2.9882, 2.7276, 10500], # 0.9h 15.4G
[ 16,10, 5, 800, 3200, 240, 255.4, 2.9843, 6, 2.9909,+2.9831, 2.7033, 10500], # 0.8h
[ 16,10, 5, 800, 3200, 224, 249.2, 2.9882, 7, 3.2949, 2.9882, 2.6593, 10500], # 0.8h
[ 16,10, 5, 800, 3200, 208, 243.1, 2.9818, 7, 2.9882,+2.9818, 2.6626, 10500], # 0.8h
[ 16,10, 5, 800, 3200, 192, 237.0, 2.9869, 6, 2.9931, 2.9865, 2.6713, 10500], # 0.7h
[ 16,10, 5, 800, 3200, 176, 230.8, 2.9881, 7, 2.9925, 2.9881, 2.6810, 10500], # 0.7h
[ 16,10, 5, 800, 3200, 160, 224.7, 2.9870, 6, 2.9957, 2.9864, 2.6812, 10500], # 0.7h

[ 16,10, 5, 760, 3040, 288, 254.3, 2.9871, 6, 2.9958, 2.9871, 2.6611, 10500], # 0.9h
[ 16,10, 5, 760, 3040, 272, 248.5, 2.9868, 6, 2.9929, 2.9844, 2.6684, 10500], # 0.9h
[ 16,10, 5, 760, 3040, 256, 242.6, 2.9888, 6, 2.9948, 2.9872, 2.6696, 10500], # 0.8h
[ 16,10, 5, 760, 3040, 240, 236.8, 2.9885, 6, 2.9922, 2.9869, 2.6759, 10500], # 0.8h
[ 16,10, 5, 760, 3040, 224, 230.9, 2.9866, 6, 2.9968, 2.9866, 3.0398, 10500], # 0.8h
[ 16,10, 5, 760, 3040, 208, 225.1, 2.9895, 6, 2.9971, 2.9874, 2.7023, 10500], # 0.7h
[ 16,10, 5, 760, 3040, 192, 219.3, 2.9879, 7, 2.9943, 2.9879, 3.2401, 10500], # 0.7h 2.9859
[ 16,10, 5, 760, 3040, 176, 213.4, 2.9830, 7, 2.9885,+2.9830, 2.6582, 10500], # 0.7h
[ 16,10, 5, 760, 3040, 160, 207.6, 2.9862, 6, 2.9944, 2.9841, 2.6752, 10500], # 0.6h

[ 16,10, 5, 720, 2880, 288, 235.4, 2.9854, 6, 3.1600, 2.9854, 2.7022, 10500], # 0.9h
[ 16,10, 5, 720, 2880, 272, 229.8, 2.9861, 6, 2.9915, 2.9838, 2.6881, 10500], # 0.9h
[ 16,10, 5, 720, 2880, 256, 224.3, 2.9810, 5, 2.9827,+2.9798, 2.6789, 10500], # 0.8h
# valx8: 2.9830 +- 0.0054 # torch.Tensor([2.9798, 2.9890, 2.9764, 2.9926, 2.9822, 2.9853, 2.9763, 2.9835, 2.9819]).std()
[ 16,10, 5, 720, 2880, 240, 218.8, 2.9926, 6, 3.0010, 2.9905, 2.6675, 10500], # 0.8h
[ 16,10, 5, 720, 2880, 224, 213.3, 2.9924, 6, 2.9989, 2.9906, 2.6694, 10500], # 0.7h
[ 16,10, 5, 720, 2880, 208, 207.7, 2.9919, 7, 2.9983, 2.9919, 2.6653, 10500], # 0.7h 14.4G
[ 16,10, 5, 720, 2880, 192, 202.2, 2.9862, 7, 2.9915, 2.9862, 2.6603, 10500], # 0.7h
[ 16,10, 5, 720, 2880, 176, 196.7, 2.9860, 7, 2.9924, 2.9860, 2.6784, 10500], # 0.7h
[ 16,10, 5, 720, 2880, 160, 191.1, 2.9856, 7, 2.9916, 2.9856, 2.7105, 10500], # 0.6h 12.8G

[ 16,10, 5, 680, 2720, 288, 217.1, 2.9839, 7, 2.9918, 2.9839, 2.6550, 10500], # 0.9h
[ 16,10, 5, 680, 2720, 272, 211.9, 2.9803, 7, 2.9868,+2.9803, 2.6556, 10500], # 0.8h
# valx8: 2.9836 +- 0.0033 # torch.Tensor([2.9803, 2.9827, 2.9815, 2.9819, 2.9846, 2.9828, 2.9810, 2.9865, 2.9909]).std()
[ 16,10, 5, 680, 2720, 256, 206.6, 2.9913, 6, 3.0006, 2.9901, 2.6746, 10500], # 0.8h 14.4G
[ 16,10, 5, 680, 2720, 240, 201.4, 2.9814, 7, 2.9891,+2.9814, 2.8148, 10500], # 0.7h
[ 16,10, 5, 680, 2720, 224, 196.2, 2.9882, 6, 2.9970, 2.9882, 2.6693, 10500], # 0.7h
[ 16,10, 5, 680, 2720, 208, 191.0, 2.9809, 6, 2.9865,+2.9807, 2.6741, 10500], # 0.7h
[ 16,10, 5, 680, 2720, 192, 185.7, 2.9855, 6, 2.9944, 2.9855, 2.6689, 10500], # 0.7h
[ 16,10, 5, 680, 2720, 176, 180.5, 2.9892, 7, 2.9949, 2.9892, 2.6632, 10500], # 0.6h
[ 16,10, 5, 680, 2720, 160, 175.3, 2.9889, 7, 2.9993, 2.9889, 2.6645, 10500], # 0.6h

[ 16,10, 5, 640, 2560, 288, 199.4, 2.9901, 5, 2.9931, 2.9893, 2.6824, 10500], # 0.8h
[ 16,10, 5, 640, 2560, 272, 194.5, 2.9809, 6, 2.9889,+2.9805, 2.6774, 10500], # 0.8h
# valx8: 2.9856 +- 0.0043 # torch.Tensor([2.9805, 2.9877, 2.9846, 2.9878, 2.9947, 2.9808, 2.9856, 2.9862, 2.9829]).std()
[ 16,10, 5, 640, 2560, 256, 189.6, 2.9935, 6, 3.0023, 2.9920, 2.6712, 10500], # 0.7h
[+16,10, 5, 640, 2560, 240, 184.6, 2.9800, 7, 2.9850,+2.9800, 2.6632, 10500], # 0.7h  minGemma-hidden_layers16-att_heads10-kv_heads5-hidden640-intermediate2560-head_dim240-T1024--2026-05-04-13-14
# valx8: 2.9819 +- 0.0059 # torch.Tensor([2.9800, 2.9897, 2.9826, 2.9740, 2.9786, 2.9904, 2.9840, 2.9740, 2.9837]).std()
[ 16,10, 5, 640, 2560, 224, 179.7, 2.9849, 6, 2.9901, 2.9835, 2.6770, 10500], # 0.7h
[ 16,10, 5, 640, 2560, 208, 174.8, 2.9840, 6, 2.9922,+2.9832, 2.6681, 10500], # 0.7h
[ 16,10, 5, 640, 2560, 192, 169.9, 2.9916, 6, 2.9982, 2.9898, 2.6749, 10500], # 0.6h
[ 16,10, 5, 640, 2560, 176, 165.0, 2.9846, 6, 2.9925, 2.9844, 2.6698, 10500], # 0.6h
[ 16,10, 5, 640, 2560, 160, 160.1, 2.9848, 6, 2.9911, 2.9845, 2.6793, 10500], # 0.6h

[ 16,10, 5, 600, 2400, 288, 182.3, 2.9908, 6, 2.9984, 2.9893, 2.6755, 10500], # 0.8h
[ 16,10, 5, 600, 2400, 272, 177.7, 2.9918, 6, 2.9985, 2.9900, 2.6748, 10500], # 0.8h
[ 16,10, 5, 600, 2400, 256, 173.1, 2.9939, 6, 3.0014, 2.9921, 2.6711, 10500], # 0.7h
[ 16,10, 5, 600, 2400, 240, 168.5, 2.9986, 6, 3.0077, 2.9968, 2.6726, 10500], # 0.7h
[ 16,10, 5, 600, 2400, 224, 163.9, 2.9877, 7, 2.9940, 2.9877, 2.6549, 10500], # 0.7h
[ 16,10, 5, 600, 2400, 208, 159.3, 2.9942, 6, 3.0026, 2.9927, 2.6714, 10500], # 0.6h
[ 16,10, 5, 600, 2400, 192, 154.7, 2.9932, 6, 3.0006, 2.9911, 2.6768, 10500], # 0.6h 12.2G
[ 16,10, 5, 600, 2400, 176, 150.1, 2.9857, 6, 2.9936, 2.9846, 2.6751, 10500], # 0.6h
[ 16,10, 5, 600, 2400, 160, 145.5, 2.9841, 7, 2.9919, 2.9841, 2.6687, 10500], # 0.5h

[ 16,10, 5, 560, 2240, 288, 165.9, 2.9893, 6, 2.9979, 2.9885, 2.6837, 10500], # 0.8h 12.7G
[ 16,10, 5, 560, 2240, 272, 161.6, 2.9911, 6, 2.9989, 2.9903, 2.6784, 10500], # 0.8h
[ 16,10, 5, 560, 2240, 256, 157.3, 2.9855, 6, 2.9917, 2.9848, 2.6780, 10500], # 0.7h
[ 16,10, 5, 560, 2240, 240, 153.0, 2.9938, 6, 3.0025, 2.9914, 2.6775, 10500], # 0.7h
[ 16,10, 5, 560, 2240, 224, 148.7, 2.9867, 6, 2.9942, 2.9856, 2.6805, 10500], # 0.6h
[ 16,10, 5, 560, 2240, 208, 144.4, 2.9928, 6, 2.9994, 2.9928, 2.6788, 10500], # 0.6h
[ 16,10, 5, 560, 2240, 192, 140.1, 2.9856, 6, 3.0782, 2.9856, 2.6873, 10500], # 0.6h
[ 16,10, 5, 560, 2240, 176, 135.8, 2.9948, 6, 3.0031, 2.9930, 2.6753, 10500], # 0.5h
[ 16,10, 5, 560, 2240, 160, 131.5, 2.9887, 6, 2.9919, 2.9887, 2.6855, 10500], # 0.5h


# local best for H9(3): 2.9804 (valx8: 2.9806) (env1, N6000, lr18e-4, WD1.2, rms1e-1, rope32000 <- default: env2, N5250, lr10e-4, WD1.8, rms1e0, rope80000)
[ 16, 9, 3, 756, 3024, 288, 231.5, 2.9970, 8, 3.1287, 2.9968, 2.8100, 12000], # 1.8h 15.5G
[ 16, 9, 3, 756, 3024, 272, 226.8, 2.9900,14, 2.9901, 2.9899, 2.8040, 12000], # 1.7h 15.5G
[ 16, 9, 3, 756, 3024, 256, 222.2, 2.9852,14, 2.9856, 2.9849, 2.7687, 12000], # 1.6h
[ 16, 9, 3, 756, 3024, 240, 217.5, 2.9869,14, 2.9916, 2.9864, 2.7717, 12000], # 1.5h
[ 16, 9, 3, 756, 3024, 224, 212.9, 2.9836,11, 2.9843, 2.9836, 2.7763, 12000], # 1.5h
[ 16, 9, 3, 756, 3024, 208, 208.2, 2.9938, 8, 3.0490, 2.9938, 3.2820, 12000], # 1.4h 15.3G
[ 16, 9, 3, 756, 3024, 192, 203.6, 2.9967, 8, 2.9995, 2.9967, 3.5544, 12000], # 1.4h
[ 16, 9, 3, 756, 3024, 176, 199.0, 2.9985, 6, 3.1084, 2.9985, 3.2917, 12000], # 1.3h
[ 16, 9, 3, 756, 3024, 160, 194.3, 2.9879,11, 2.9880, 2.9872, 2.7743, 12000], # 1.3h

[ 16, 9, 3, 720, 2880, 288, 215.5, 2.9923,11, 2.9957, 2.9922, 2.8008, 12000], # 1.7h 15.4G
[ 16, 9, 3, 720, 2880, 272, 211.0, 2.9998, 5, 3.0070, 2.9998, 3.0017, 12000], # 1.7h
[ 16, 9, 3, 720, 2880, 256, 206.6, 2.9919, 9, 2.9962, 2.9919, 2.8901, 12000], # 1.5h 15.4G
[ 16, 9, 3, 720, 2880, 240, 202.2, 2.9911,11, 3.0000, 2.9911, 2.8279, 12000],
[ 16, 9, 3, 720, 2880, 224, 197.8, 2.9869,11, 2.9920, 2.9869, 2.7862, 12000],
[ 16, 9, 3, 720, 2880, 208, 193.4, 2.9972, 6, 3.2005, 2.9972, 3.1042, 12000], # 1.4h
[+16, 9, 3, 720, 2880, 192, 188.9, 2.9804,17, 2.9818,+2.9804, 2.7902, 12000], #  minGemma-hidden_layers16-att_heads9-kv_heads3-hidden720-intermediate2880-head_dim192-T1024--2026-04-06-02-35.pth
# valx8: 2.9806 +- 0.0021 # torch.Tensor([2.9804, 2.9777, 2.9823, 2.9826, 2.9820, 2.9820, 2.9772, 2.9788, 2.9823]).std()
[ 16, 9, 3, 720, 2880, 176, 184.5, 2.9859,16, 2.9888, 2.9838, 2.8029, 12000],
[ 16, 9, 3, 720, 2880, 160, 180.1, 2.9903,11, 2.9905, 2.9885, 2.7897, 12000], # 1.2h

[ 16, 9, 3, 684, 2736, 288, 200.0, 2.9920,11, 3.0159, 2.9920, 3.1817, 12000], # 1.7h 14.0G
[ 16, 9, 3, 684, 2736, 272, 195.8, 2.9935, 8, 2.9952, 2.9935, 2.8583, 12000], # 1.7h
[ 16, 9, 3, 684, 2736, 256, 191.6, 2.9859,11, 2.9889, 2.9859, 2.7974, 12000],
[ 16, 9, 3, 684, 2736, 240, 187.4, 2.9994, 5, 2.9994, 2.9991, 2.8260, 12000],
[ 16, 9, 3, 684, 2736, 224, 183.2, 2.9874,11, 2.9902, 2.9874, 2.9914, 12000],
[ 16, 9, 3, 684, 2736, 208, 179.0, 2.9815,17, 2.9842,+2.9815, 2.8878, 12000],
[ 16, 9, 3, 684, 2736, 192, 174.8, 2.9968, 5, 3.0016, 2.9968, 3.0108, 12000],
[ 16, 9, 3, 684, 2736, 176, 170.6, 2.9841,11, 2.9852, 2.9841, 2.7805, 12000],
[ 16, 9, 3, 684, 2736, 160, 166.4, 2.9875,16, 2.9932, 2.9875, 3.1555, 12000], # 1.2h

[ 16, 9, 3, 648, 2592, 288, 185.0, 2.9911,11, 2.9950, 2.9892, 2.8065, 12000], # 1.7h
[ 16, 9, 3, 648, 2592, 272, 181.0, 2.9935, 9, 3.0765, 2.9932, 2.8273, 12000], # 1.6h
[ 16, 9, 3, 648, 2592, 256, 177.0, 2.9836,14, 2.9852,+2.9832, 2.7903, 12000],
[ 16, 9, 3, 648, 2592, 240, 173.0, 3.0001, 8, 3.0008, 3.0001, 3.4046, 12000],
[ 16, 9, 3, 648, 2592, 224, 169.0, 2.9887,11, 2.9911, 2.9887, 2.8671, 12000],
[ 16, 9, 3, 648, 2592, 208, 165.1, 2.9852,17, 2.9877, 2.9852, 2.7851, 12000],
[ 16, 9, 3, 648, 2592, 192, 161.1, 2.9847, 9, 3.1220, 2.9841, 2.7793, 12000],
[ 16, 9, 3, 648, 2592, 176, 157.1, 2.9889, 9, 3.1854, 2.9889, 2.8238, 12000],
[ 16, 9, 3, 648, 2592, 160, 153.1, 2.9828,11, 2.9869,+2.9828, 2.7804, 12000], # 1.2h 12.9G

[ 16, 9, 3, 612, 2448, 288, 170.5, 2.9887,11, 2.9899, 2.9887, 2.7986, 12000], # 1.6h 13.4G
[ 16, 9, 3, 612, 2448, 272, 166.7, 2.9885,15, 2.9912, 2.9866, 2.8035, 12000], # 1.6h
[ 16, 9, 3, 612, 2448, 256, 162.9, 3.0022, 6, 3.0038, 3.0009, 2.8697, 12000], # 1.4h 13.4G
[ 16, 9, 3, 612, 2448, 240, 159.2, 2.9920, 9, 2.9937, 2.9918, 2.8407, 12000], # 1.4h
[ 16, 9, 3, 612, 2448, 224, 155.4, 2.9883,11, 2.9910, 2.9883, 2.7931, 12000], # 1.3h
[ 16, 9, 3, 612, 2448, 208, 151.7, 2.9889,11, 2.9917, 2.9889, 2.7898, 12000], # 1.3h
[ 16, 9, 3, 612, 2448, 192, 147.9, 2.9892,11, 2.9900, 2.9892, 2.7885, 12000], # 1.2h
[ 16, 9, 3, 612, 2448, 176, 144.1, 2.9886,11, 2.9894, 2.9886, 2.9165, 12000], # 1.2h
[ 16, 9, 3, 612, 2448, 160, 140.4, 2.9831,11, 2.9874,+2.9831, 2.7924, 12000], # 1.2h

[ 16, 9, 3, 576, 2304, 288, 156.5, 2.9859,15, 3.0492, 2.9859, 2.8138, 12000], # 1.6h
[ 16, 9, 3, 576, 2304, 272, 152.9, 2.9899,11, 2.9922, 2.9899, 2.7845, 12000], # 1.5h
[ 16, 9, 3, 576, 2304, 256, 149.4, 2.9856,11, 3.0343, 2.9856, 2.7839, 12000], # 1.4h
[ 16, 9, 3, 576, 2304, 240, 145.8, 2.9893,11, 2.9917, 2.9893, 2.8170, 12000], # 1.3h
[ 16, 9, 3, 576, 2304, 224, 142.3, 2.9901,11, 2.9933, 2.9901, 2.7867, 12000], # 1.3h
[ 16, 9, 3, 576, 2304, 208, 138.8, 2.9929,10, 2.9940, 2.9929, 3.2192, 12000], # 1.2h
[ 16, 9, 3, 576, 2304, 192, 135.2, 2.9863,17, 2.9878, 2.9863, 2.7744, 12000], # 1.2h
[ 16, 9, 3, 576, 2304, 176, 131.7, 2.9919,11, 2.9927, 2.9919, 2.8165, 12000], # 1.1h
[ 16, 9, 3, 576, 2304, 160, 128.1, 2.9846,11, 2.9868, 2.9846, 2.7670, 12000], # 1.1h 12.4G


# local best for H8(4): 2.9779 (valx8: 2.9776)
[ 16, 8, 4, 800, 3200, 288, 251.7, 2.9827, 7, 2.9865,+2.9827, 2.6579, 10500], # 0.8h
[ 16, 8, 4, 800, 3200, 272, 246.8, 2.9840, 7, 2.9920, 2.9840, 3.1493, 10500], # 0.8h
[ 16, 8, 4, 800, 3200, 256, 241.9, 2.9894, 7, 2.9940, 2.9894, 2.6752, 10500], # 0.8h
[ 16, 8, 4, 800, 3200, 240, 237.0, 2.9862, 6, 2.9907, 2.9851, 2.6771, 10500], # 0.7h
[ 16, 8, 4, 800, 3200, 224, 232.0, 2.9869, 6, 3.1187, 2.9869, 3.1229, 10500], # 0.7h
[ 16, 8, 4, 800, 3200, 208, 227.1, 2.9863, 7, 2.9907, 2.9863, 2.6631, 10500], # 0.7h
[ 16, 8, 4, 800, 3200, 192, 222.2, 2.9857, 7, 2.9898, 2.9857, 2.6739, 10500], # 0.7h
[ 16, 8, 4, 800, 3200, 176, 217.3, 2.9892, 6, 2.9941, 2.9890, 2.6793, 10500], # 0.6h
[ 16, 8, 4, 800, 3200, 160, 212.4, 2.9874, 7, 2.9910, 2.9874, 2.6679, 10500], # 0.6h

[ 16, 8, 4, 768, 3072, 288, 236.9, 2.9821, 7, 2.9889,+2.9821, 2.6617, 10500], # 0.8h
[ 16, 8, 4, 768, 3072, 272, 232.2, 2.9874, 6, 2.9953, 2.9862, 2.7148, 10500], # 0.8h
[ 16, 8, 4, 768, 3072, 256, 227.5, 2.9979, 6, 3.0032, 2.9979, 2.6854, 10500], # 0.7h
[ 16, 8, 4, 768, 3072, 240, 222.8, 2.9876, 7, 2.9921, 2.9876, 2.6843, 10500], # 0.7h 14.5G
[ 16, 8, 4, 768, 3072, 224, 218.0, 2.9908, 7, 2.9982, 2.9908, 2.8666, 10500], # 0.7h
[ 16, 8, 4, 768, 3072, 208, 213.3, 2.9841, 7, 2.9916, 2.9841, 2.6860, 10500], # 0.7h
[ 16, 8, 4, 768, 3072, 192, 208.6, 2.9905, 7, 3.1509, 2.9905, 2.6620, 10500], # 0.6h
[ 16, 8, 4, 768, 3072, 176, 203.9, 2.9894, 6, 2.9963, 2.9894, 2.8748, 10500], # 0.6h 14.0G
[ 16, 8, 4, 768, 3072, 160, 199.2, 2.9908, 7, 3.1560, 2.9908, 2.6964, 10500], # 0.6h

[ 16, 8, 4, 736, 2944, 288, 222.5, 2.9860, 6, 2.9925, 2.9850, 2.6961, 10500], # 0.8h
[ 16, 8, 4, 736, 2944, 272, 218.0, 2.9849, 6, 2.9930, 2.9844, 2.6707, 10500], # 0.8h
[ 16, 8, 4, 736, 2944, 256, 213.5, 2.9919, 7, 2.9982, 2.9919, 2.6641, 10500], # 0.7h
[ 16, 8, 4, 736, 2944, 240, 209.0, 2.9894, 7, 2.9976, 2.9894, 2.6640, 10500], # 0.7h
[ 16, 8, 4, 736, 2944, 224, 204.4, 2.9892, 7, 2.9952, 2.9892, 2.6647, 10500], # 0.7h
[+16, 8, 4, 736, 2944, 208, 199.9, 2.9779, 7, 2.9853,+2.9779, 2.6630, 10500], # 0.6h  minGemma-hidden_layers16-att_heads8-kv_heads4-hidden736-intermediate2944-head_dim208-T1024--2026-05-17-22-02
# valx8: 2.9776 +- 0.0029 # torch.Tensor([2.9779, 2.9723, 2.9769, 2.9801, 2.9757, 2.9788, 2.9811, 2.9752, 2.9807]).std()
# (2nd: 2.9789)                                                                       minGemma-hidden_layers16-att_heads8-kv_heads4-hidden736-intermediate2944-head_dim208-T1024--2026-05-17-21-09
# valx8: 2.9790 +- 0.0023 # torch.Tensor([2.9789, 2.9819, 2.9815, 2.9787, 2.9810, 2.9774, 2.9795, 2.9778, 2.9744]).std()
[ 16, 8, 4, 736, 2944, 192, 195.4, 2.9876, 7, 2.9939, 2.9876, 2.6962, 10500], # 0.6h
[ 16, 8, 4, 736, 2944, 176, 190.9, 2.9914, 7, 2.9971, 2.9914, 2.6680, 10500], # 0.6h
[ 16, 8, 4, 736, 2944, 160, 186.3, 2.9858, 6, 3.1180, 2.9854, 2.6772, 10500], # 0.6h 12.6G

[ 16, 8, 4, 704, 2816, 288, 208.5, 2.9836, 7, 2.9894,+2.9836, 2.6599, 10500], # 0.8h
[ 16, 8, 4, 704, 2816, 272, 204.2, 2.9801, 7, 3.0552,+2.9801, 2.7126, 10500], # 0.7h
# valx8: 2.9833 +- 0.0046 # torch.Tensor([2.9801, 2.9775, 2.9861, 2.9873, 2.9856, 2.9762, 2.9824, 2.9899, 2.9844]).std()
# (2nd: 2.9802)
# valx8: 2.9816 +- 0.0035 # torch.Tensor([2.9802, 2.9840, 2.9859, 2.9821, 2.9793, 2.9860, 2.9831, 2.9767, 2.9769]).std()
[ 16, 8, 4, 704, 2816, 256, 199.9, 2.9851, 6, 2.9915, 2.9841, 2.7063, 10500], # 0.7h
[ 16, 8, 4, 704, 2816, 240, 195.5, 2.9865, 6, 2.9900, 2.9850, 2.6747, 10500], # 0.7h
[ 16, 8, 4, 704, 2816, 224, 191.2, 2.9890, 6, 2.9967, 2.9885, 2.7109, 10500], # 0.6h
[ 16, 8, 4, 704, 2816, 208, 186.9, 2.9877, 6, 3.1265, 2.9872, 2.6804, 10500], # 0.6h
[ 16, 8, 4, 704, 2816, 192, 182.6, 2.9935, 6, 3.0005, 2.9919, 2.6848, 10500], # 0.6h 12.6G
[ 16, 8, 4, 704, 2816, 176, 178.2, 2.9892, 6, 2.9955, 2.9887, 2.6771, 10500], # 0.6h
[ 16, 8, 4, 704, 2816, 160, 173.9, 2.9843, 7, 2.9900, 2.9843, 2.6693, 10500], # 0.5h

[ 16, 8, 4, 672, 2688, 288, 194.9, 2.9902, 5, 2.9918, 2.9881, 2.6746, 10500], # 0.7h
[ 16, 8, 4, 672, 2688, 272, 190.8, 2.9889, 6, 2.9962, 2.9867, 2.6960, 10500], # 0.7h 12.9G
[ 16, 8, 4, 672, 2688, 256, 186.7, 2.9876, 6, 2.9924, 2.9871, 2.6790, 10500], # 0.7h
[ 16, 8, 4, 672, 2688, 240, 182.5, 2.9865, 5, 2.9868, 2.9858, 2.6819, 10500], # 0.6h
[ 16, 8, 4, 672, 2688, 224, 178.4, 2.9807, 6, 2.9864,+2.9804, 2.6815, 10500], # 0.6h
# valx8: 2.9819 +- 0.0044 # torch.Tensor([2.9804, 2.9790, 2.9870, 2.9721, 2.9848, 2.9845, 2.9838, 2.9820, 2.9837]).std()
[ 16, 8, 4, 672, 2688, 208, 174.3, 2.9860, 6, 2.9925, 2.9860, 2.6808, 10500], # 0.6h
[ 16, 8, 4, 672, 2688, 192, 170.1, 2.9860, 7, 2.9918, 2.9860, 2.6658, 10500], # 0.6h
[ 16, 8, 4, 672, 2688, 176, 166.0, 2.9956, 7, 3.0008, 2.9956, 2.6745, 10500], # 0.5h
[ 16, 8, 4, 672, 2688, 160, 161.9, 2.9902, 6, 2.9963, 2.9893, 2.6894, 10500], # 0.5h

[ 16, 8, 4, 640, 2560, 288, 181.7, 2.9847, 6, 2.9906, 2.9841, 2.6744, 10500], # 0.7h
[ 16, 8, 4, 640, 2560, 272, 177.8, 2.9847, 6, 2.9953,+2.9836, 2.6914, 10500], # 0.7h
[ 16, 8, 4, 640, 2560, 256, 173.8, 2.9927, 6, 3.0004, 2.9927, 2.6950, 10500], # 0.6h
[ 16, 8, 4, 640, 2560, 240, 169.9, 2.9836, 7, 2.9881,+2.9836, 2.6617, 10500], # 0.6h
[ 16, 8, 4, 640, 2560, 224, 166.0, 2.9881, 7, 2.9951, 2.9881, 2.6709, 10500], # 0.6h
[ 16, 8, 4, 640, 2560, 208, 162.0, 2.9848, 6, 2.9919, 2.9839, 2.6764, 10500], # 0.6h
[ 16, 8, 4, 640, 2560, 192, 158.1, 2.9843, 7, 2.9892, 2.9843, 2.6649, 10500], # 0.5h
[ 16, 8, 4, 640, 2560, 176, 154.2, 2.9876, 6, 2.9959, 2.9866, 2.6768, 10500], # 0.5h
[ 16, 8, 4, 640, 2560, 160, 150.2, 2.9959, 6, 3.0026, 2.9949, 2.6809, 10500], # 0.5h

[ 16, 8, 4, 608, 2432, 288, 168.9, 2.9920, 6, 2.9992, 2.9903, 2.6769, 10500], # 0.7h
[ 16, 8, 4, 608, 2432, 272, 165.1, 2.9913, 6, 2.9976, 2.9897, 2.6777, 10500], # 0.7h
[ 16, 8, 4, 608, 2432, 256, 161.4, 2.9829, 7, 2.9904,+2.9829, 2.6755, 10500], # 0.6h
[ 16, 8, 4, 608, 2432, 240, 157.7, 2.9962, 6, 3.0044, 2.9945, 2.6805, 10500], # 0.6h
[ 16, 8, 4, 608, 2432, 224, 153.9, 2.9868, 6, 2.9933, 2.9864, 2.6786, 10500], # 0.6h
[ 16, 8, 4, 608, 2432, 208, 150.2, 2.9827, 7, 2.9889,+2.9827, 2.6838, 10500], # 0.6h
[ 16, 8, 4, 608, 2432, 192, 146.5, 2.9927, 6, 2.9981, 2.9920, 2.6775, 10500], # 0.5h
[ 16, 8, 4, 608, 2432, 176, 142.7, 2.9892, 7, 2.9926, 2.9892, 2.6732, 10500], # 0.5h
[ 16, 8, 4, 608, 2432, 160, 139.0, 2.9871, 7, 2.9917, 2.9871, 2.6688, 10500], # 0.5h

[ 16, 8, 4, 576, 2304, 288, 156.5, 2.9980, 5, 2.9999, 2.9980, 2.6862, 10500], # 0.7h
[ 16, 8, 4, 576, 2304, 272, 152.9, 2.9853, 7, 2.9903, 2.9853, 2.6693, 10500], # 0.7h
[ 16, 8, 4, 576, 2304, 256, 149.4, 2.9983, 6, 3.0067, 2.9972, 2.6779, 10500], # 0.6h 12.0G
[ 16, 8, 4, 576, 2304, 240, 145.8, 2.9927, 6, 2.9992, 2.9927, 2.6786, 10500], # 0.6h
[ 16, 8, 4, 576, 2304, 224, 142.3, 2.9886, 6, 2.9965, 2.9864, 2.6781, 10500], # 0.6h
[ 16, 8, 4, 576, 2304, 208, 138.8, 2.9926, 7, 3.0008, 2.9926, 2.6642, 10500], # 0.5h
[ 16, 8, 4, 576, 2304, 192, 135.2, 2.9853, 6, 2.9920, 2.9839, 2.6777, 10500], # 0.5h
[ 16, 8, 4, 576, 2304, 176, 131.7, 2.9921, 6, 3.0010, 2.9913, 2.6810, 10500], # 0.5h 11.5G
[ 16, 8, 4, 576, 2304, 160, 128.1, 2.9963, 6, 3.0028, 2.9963, 2.6791, 10500], # 0.5h


# local best for H7(1): 2.9815 (valx8: 2.9830)
[ 16, 7, 1, 784, 3136, 288, 215.4, 2.9866, 7, 2.9924, 2.9866, 2.8077, 10500], # 0.7h
[ 16, 7, 1, 784, 3136, 272, 212.1, 2.9872, 7, 2.9928, 2.9872, 2.6543, 10500], # 0.7h
[ 16, 7, 1, 784, 3136, 256, 208.9, 2.9904, 6, 2.9990, 2.9889, 2.6880, 10500], # 0.7h
[ 16, 7, 1, 784, 3136, 240, 205.7, 2.9893, 7, 2.9975, 2.9893, 2.6785, 10500], # 0.7h
[ 16, 7, 1, 784, 3136, 224, 202.5, 2.9927, 7, 2.9996, 2.9927, 2.6748, 10500], # 0.6h
[ 16, 7, 1, 784, 3136, 208, 199.3, 2.9912, 6, 2.9965, 2.9908, 2.6754, 10500], # 0.6h
[ 16, 7, 1, 784, 3136, 192, 196.1, 2.9929, 6, 3.0002, 2.9925, 2.7191, 10500], # 0.6h
[ 16, 7, 1, 784, 3136, 176, 192.9, 2.9977, 5, 3.1625, 2.9977, 3.1696, 10500], # 0.6h
[ 16, 7, 1, 784, 3136, 160, 189.7, 2.9853, 7, 2.9902, 2.9853, 2.6779, 10500], # 0.6h

[ 16, 7, 1, 756, 3024, 288, 203.6, 2.9927, 6, 3.0026, 2.9914, 2.6676, 10500], # 0.7h 14.7G
[ 16, 7, 1, 756, 3024, 272, 200.5, 2.9958, 6, 3.0013, 2.9938, 2.6878, 10500], # 0.7h
[ 16, 7, 1, 756, 3024, 256, 197.4, 2.9873, 6, 2.9985, 2.9869, 2.6720, 10500], # 0.6h
[ 16, 7, 1, 756, 3024, 240, 194.3, 2.9895, 6, 2.9921, 2.9895, 3.0442, 10500], # 0.6h
[ 16, 7, 1, 756, 3024, 224, 191.2, 2.9902, 6, 2.9948, 2.9902, 2.7470, 10500], # 0.6h
[ 16, 7, 1, 756, 3024, 208, 188.1, 2.9946, 7, 2.9982, 2.9946, 3.1171, 10500], # 0.6h
[ 16, 7, 1, 756, 3024, 192, 185.0, 2.9957, 7, 2.9986, 2.9957, 2.7029, 10500], # 0.6h
[ 16, 7, 1, 756, 3024, 176, 181.9, 2.9919, 7, 2.9955, 2.9919, 2.6672, 10500], # 0.6h
[ 16, 7, 1, 756, 3024, 160, 178.8, 2.9918, 7, 2.9990, 2.9918, 2.6818, 10500], # 0.6h

[ 16, 7, 1, 728, 2912, 288, 192.1, 2.9945, 5, 2.9947, 2.9942, 2.7067, 10500], # 0.7h
[ 16, 7, 1, 728, 2912, 272, 189.2, 2.9867, 6, 2.9913, 2.9863, 2.6760, 10500], # 0.7h
[ 16, 7, 1, 728, 2912, 256, 186.2, 2.9858, 6, 2.9944, 2.9840, 2.6632, 10500], # 0.6h
[ 16, 7, 1, 728, 2912, 240, 183.2, 2.9958, 6, 3.0003, 2.9940, 2.7613, 10500], # 0.6h
[ 16, 7, 1, 728, 2912, 224, 180.2, 2.9946, 7, 2.9989, 2.9946, 3.0527, 10500], # 0.6h
[ 16, 7, 1, 728, 2912, 208, 177.2, 2.9940, 6, 2.9968, 2.9940, 3.1221, 10500], # 0.6h
[ 16, 7, 1, 728, 2912, 192, 174.3, 2.9986, 7, 3.0041, 2.9986, 3.1857, 10500], # 0.6h
[ 16, 7, 1, 728, 2912, 176, 171.3, 2.9959, 6, 3.0013, 2.9944, 2.7102, 10500], # 0.5h
[ 16, 7, 1, 728, 2912, 160, 168.3, 3.0004, 6, 3.0511, 3.0003, 2.7218, 10500], # 0.5h 12.3G

[ 16, 7, 1, 700, 2800, 288, 181.0, 2.9924, 6, 2.9996, 2.9923, 2.6639, 10500], # 0.7h
[ 16, 7, 1, 700, 2800, 272, 178.1, 2.9901, 7, 3.1531, 2.9901, 2.6614, 10500], # 0.7h
[ 16, 7, 1, 700, 2800, 256, 175.3, 2.9871, 7, 2.9931, 2.9871, 2.6789, 10500], # 0.6h
[ 16, 7, 1, 700, 2800, 240, 172.4, 2.9995, 6, 3.0077, 2.9982, 2.6666, 10500], # 0.6h
[ 16, 7, 1, 700, 2800, 224, 169.5, 2.9937, 7, 2.9988, 2.9937, 2.6620, 10500], # 0.6h
[ 16, 7, 1, 700, 2800, 208, 166.7, 2.9863, 7, 2.9898, 2.9863, 2.7197, 10500], # 0.6h
[ 16, 7, 1, 700, 2800, 192, 163.8, 2.9963, 7, 2.9996, 2.9963, 2.6808, 10500], # 0.5h
[ 16, 7, 1, 700, 2800, 176, 160.9, 2.9929, 7, 2.9999, 2.9929, 2.8046, 10500], # 0.5h
[ 16, 7, 1, 700, 2800, 160, 158.1, 2.9926, 6, 2.9960, 2.9916, 2.7320, 10500], # 0.5h

[ 16, 7, 1, 672, 2688, 288, 170.1, 2.9879, 6, 2.9947, 2.9863, 2.6718, 10500], # 0.7h 12.7G
[ 16, 7, 1, 672, 2688, 272, 167.4, 2.9956, 6, 3.0042, 2.9956, 2.6671, 10500], # 0.6h
[ 16, 7, 1, 672, 2688, 256, 164.6, 2.9912, 6, 2.9980, 2.9912, 3.1579, 10500], # 0.6h
[ 16, 7, 1, 672, 2688, 240, 161.9, 2.9888, 7, 2.9958, 2.9888, 3.1354, 10500], # 0.6h
[ 16, 7, 1, 672, 2688, 224, 159.1, 2.9908, 6, 2.9979, 2.9892, 2.6634, 10500], # 0.6h
[ 16, 7, 1, 672, 2688, 208, 156.4, 2.9996, 6, 3.0072, 2.9996, 2.6767, 10500], # 0.5h
[ 16, 7, 1, 672, 2688, 192, 153.6, 3.0003, 7, 3.0070, 3.0003, 2.6705, 10500], # 0.5h
[ 16, 7, 1, 672, 2688, 176, 150.9, 2.9899, 7, 2.9955, 2.9899, 2.6621, 10500], # 0.5h
[ 16, 7, 1, 672, 2688, 160, 148.1, 3.0044, 6, 3.0099, 3.0036, 2.6796, 10500], # 0.5h

[ 16, 7, 1, 644, 2576, 288, 159.6, 2.9975, 6, 3.0057, 2.9960, 2.6628, 10500], # 0.7h
[ 16, 7, 1, 644, 2576, 272, 157.0, 2.9928, 6, 3.0018, 2.9924, 2.6741, 10500], # 0.6h
[ 16, 7, 1, 644, 2576, 256, 154.3, 2.9893, 7, 3.0732, 2.9893, 2.6684, 10500], # 0.6h
[ 16, 7, 1, 644, 2576, 240, 151.7, 2.9943, 6, 3.0023, 2.9942, 2.6689, 10500], # 0.6h
[ 16, 7, 1, 644, 2576, 224, 149.0, 3.0005, 7, 3.0063, 3.0005, 2.7346, 10500], # 0.6h
[ 16, 7, 1, 644, 2576, 208, 146.4, 2.9894, 7, 2.9982, 2.9894, 2.6551, 10500], # 0.5h
[ 16, 7, 1, 644, 2576, 192, 143.8, 2.9870, 6, 2.9921, 2.9857, 2.7076, 10500], # 0.5h
[ 16, 7, 1, 644, 2576, 176, 141.1, 2.9947, 7, 2.9992, 2.9947, 2.6640, 10500], # 0.5h
[ 16, 7, 1, 644, 2576, 160, 138.5, 2.9966, 6, 3.0093, 2.9959, 2.6842, 10500], # 0.5h 12.0G

[ 16, 7, 1, 616, 2464, 288, 149.3, 2.9963, 7, 3.0007, 2.9963, 2.6882, 10500], # 0.6h
[ 16, 7, 1, 616, 2464, 272, 146.8, 2.9952, 6, 3.0033, 2.9952, 2.6781, 10500], # 0.6h
[ 16, 7, 1, 616, 2464, 256, 144.3, 2.9847, 7, 2.9908, 2.9847, 2.6621, 10500], # 0.6h
[ 16, 7, 1, 616, 2464, 240, 141.8, 2.9830, 7, 2.9895,+2.9830, 2.6621, 10500], # 0.5h
[ 16, 7, 1, 616, 2464, 224, 139.2, 2.9851, 7, 2.9913, 2.9851, 2.6613, 10500], # 0.5h
[ 16, 7, 1, 616, 2464, 208, 136.7, 2.9943, 6, 2.9985, 2.9943, 3.1248, 10500], # 0.5h
[ 16, 7, 1, 616, 2464, 192, 134.2, 2.9890, 7, 2.9944, 2.9890, 2.6661, 10500], # 0.5h
[ 16, 7, 1, 616, 2464, 176, 131.7, 2.9962, 6, 2.9997, 2.9951, 2.7385, 10500], # 0.5h
[ 16, 7, 1, 616, 2464, 160, 129.2, 2.9973, 6, 3.0039, 2.9969, 2.6729, 10500], # 0.5h

[+16, 7, 1, 588, 2352, 288, 139.4, 2.9815, 6, 2.9882,+2.9815, 2.8066, 10500], # 0.6h  minGemma-hidden_layers16-att_heads7-kv_heads1-hidden588-intermediate2352-head_dim288-T1024--2026-06-14-21-12
# valx8: 2.9830 +- 0.0057 # torch.Tensor([2.9815, 2.9923, 2.9827, 2.9824, 2.9854, 2.9867, 2.9744, 2.9863, 2.9751]).std()
[ 16, 7, 1, 588, 2352, 272, 137.0, 2.9933, 6, 3.0716, 2.9929, 2.6781, 10500], # 0.6h
[ 16, 7, 1, 588, 2352, 256, 134.6, 2.9905, 6, 2.9972, 2.9900, 2.6864, 10500], # 0.5h
[ 16, 7, 1, 588, 2352, 240, 132.2, 2.9980, 7, 3.0036, 2.9980, 2.6843, 10500], # 0.5h
[ 16, 7, 1, 588, 2352, 224, 129.8, 2.9934, 7, 3.0000, 2.9934, 2.6687, 10500], # 0.5h 11.9G
[ 16, 7, 1, 588, 2352, 208, 127.3, 2.9943, 7, 2.9993, 2.9943, 2.6644, 10500], # 0.5h
[ 16, 7, 1, 588, 2352, 192, 124.9, 3.0015, 6, 3.0071, 3.0010, 2.6804, 10500], # 0.5h
[ 16, 7, 1, 588, 2352, 176, 122.5, 2.9972, 6, 3.0028, 2.9957, 2.6765, 10500], # 0.5h 11.6G
[ 16, 7, 1, 588, 2352, 160, 120.1, 2.9951, 6, 3.0020, 2.9942, 2.6768, 10500], # 0.4h

[ 16, 7, 1, 560, 2240, 288, 129.7, 2.9903, 7, 2.9982, 2.9903, 2.8466, 10500], # 0.6h
[ 16, 7, 1, 560, 2240, 272, 127.4, 2.9887, 7, 2.9915, 2.9887, 2.7777, 10500], # 0.6h
[ 16, 7, 1, 560, 2240, 256, 125.2, 3.0008, 6, 3.0062, 2.9988, 2.6846, 10500], # 0.5h
[ 16, 7, 1, 560, 2240, 240, 122.9, 2.9939, 6, 3.0012, 2.9939, 2.6824, 10500], # 0.5h
[ 16, 7, 1, 560, 2240, 224, 120.6, 2.9915, 7, 2.9982, 2.9915, 2.6704, 10500], # 0.5h
[ 16, 7, 1, 560, 2240, 208, 118.3, 3.0004, 6, 3.0082, 2.9986, 2.6757, 10500], # 0.5h
[ 16, 7, 1, 560, 2240, 192, 116.0, 3.0018, 6, 3.0105, 3.0014, 2.6818, 10500], # 0.4h
[ 16, 7, 1, 560, 2240, 176, 113.7, 2.9898, 7, 2.9942, 2.9898, 2.6734, 10500], # 0.4h
[ 16, 7, 1, 560, 2240, 160, 111.4, 2.9967, 6, 3.0032, 2.9950, 2.6904, 10500], # 0.4h

In [40]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  16 # 8 # G28 G18 #blocks
num_attention_heads =11 # 4 # G16 G8
num_key_value_heads = 1 # 4 # G16 G1
hidden_size = num_attention_heads*68 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 288 # 32 # G256 # dim in attention
rms_norm_eps = 1e0 # 1e-6
rope_theta = 80000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//3; N_step=5250*3; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=3, learning_rate=10.0e-4, weight_decay=1.8, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//3 # Evaluation follows
    for k in range(5000*3 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9837:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

64.512
L16 att11 kv_heads1 hidden748 intermediate2992 head_dim288 T1024

1 4.5944162946428575 tensor(3.1933)

2 2.777079613095238 tensor(3.0052)

3 2.695141927083333 tensor(2.9909)

4 2.7919190848214286 tensor(2.9854)

5 2.6633324032738095 tensor(2.9877)

6 2.6510511532738095 tensor(2.9881)
[ 16, 11, 1, 748, 2992, 288, 227.9, 2.9877, 5, 2.9881, 2.9854, 2.6633, 15750],

In [39]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  16 # 8 # G28 G18 #blocks
num_attention_heads =10 # 4 # G16 G8
num_key_value_heads = 5 # 4 # G16 G1
hidden_size = num_attention_heads*64 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 240 # 32 # G256 # dim in attention
rms_norm_eps = 1e0 # 1e-6
rope_theta = 80000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//2; N_step=5250*2; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=10.0e-4, weight_decay=1.8, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(5000*2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9869:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

64.512
L16 att10 kv_heads5 hidden640 intermediate2560 head_dim240 T1024

1 4.697887648809524 tensor(3.2082)

2 2.804531063988095 tensor(3.0130)

3 2.7154895833333335 tensor(2.9892)

4 2.6972924107142857 tensor(2.9819)

5 2.6826188616071427 tensor(2.9814)

6 2.6766497395833335 tensor(2.9800)

7 2.6632494419642856 tensor(2.9857)
back to previous

8 2.667351004464286 tensor(2.9850)
[ 16, 10, 5, 640, 2560, 240, 184.6, 2.9800, 7, 2.9850, 2.9800, 2.6632, 10500],

In [30]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  16 # 8 # G28 G18 #blocks
num_attention_heads = 9 # 4 # G16 G8
num_key_value_heads = 3 # 4 # G16 G1
hidden_size = num_attention_heads*80 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 192 # 32 # G256 # dim in attention
rms_norm_eps = 1e-1 # 1e-6
rope_theta = 32000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//2; N_step=6000*2; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=18.0e-4, weight_decay=1.2, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(6000*2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9974:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

73.728
L16 att9 kv_heads3 hidden720 intermediate2880 head_dim192 T1024

1 4.254903645833333 tensor(3.1054)

2 2.84466015625 tensor(3.0208)

3 2.813270833333333 tensor(3.0052)

4 2.8400074869791667 tensor(2.9965)

5 2.815620442708333 tensor(2.9930)

6 2.7784440104166666 tensor(2.9896)

7 2.800552734375 tensor(2.9868)

8 2.7975380859375 tensor(2.9856)

9 2.835871419270833 tensor(2.9913)
back to previous

10 2.7953645833333334 tensor(2.9836)

11 2.7770582682291667 tensor(2.9841)

12 2.7720319010416667 tensor(2.9827)

13 2.785425455729167 tensor(2.9824)

14 2.7777229817708333 tensor(2.9823)

15 2.773117838541667 tensor(2.9820)

16 2.7880315755208334 tensor(2.9804)

17 2.790234375 tensor(2.9843)
back to previous

18 2.7801686197916666 tensor(2.9818)
[ 16, 9, 3, 720, 2880, 192, 188.9, 2.9804, 17, 2.9818, 2.9804, 2.7902, 12000],

In [86]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  16 # 8 # G28 G18 #blocks
num_attention_heads = 8 # 4 # G16 G8
num_key_value_heads = 4 # 4 # G16 G1
hidden_size = num_attention_heads*92 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 208 # 32 # G256 # dim in attention
rms_norm_eps = 1e0 # 1e-6
rope_theta = 80000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//2; N_step=5250*2; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=10.0e-4, weight_decay=1.8, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(5000*2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9837:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

64.512
L16 att8 kv_heads4 hidden736 intermediate2944 head_dim208 T1024

1 4.7644568452380955 tensor(3.1824)

2 2.7903759300595237 tensor(3.0138)

3 2.712397507440476 tensor(2.9899)

4 2.6951925223214284 tensor(2.9824)

5 2.681426711309524 tensor(2.9789)

6 2.6733716517857142 tensor(2.9779)

7 2.6630115327380954 tensor(2.9843)
back to previous

8 2.6664918154761903 tensor(2.9853)
[ 16, 8, 4, 736, 2944, 208, 199.9, 2.9779, 7, 2.9853, 2.9779, 2.6630, 10500],

In [198]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  16 # 8 # G28 G18 #blocks
num_attention_heads = 7 # 4 # G16 G8
num_key_value_heads = 1 # 4 # G16 G1
hidden_size = num_attention_heads*84 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 288 # 32 # G256 # dim in attention
rms_norm_eps = 1e0 # 1e-6
rope_theta = 80000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//2; N_step=5250*2; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=10.0e-4, weight_decay=1.8, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(5000*2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9837:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

64.512
L16 att7 kv_heads1 hidden588 intermediate2352 head_dim288 T1024

1 4.399291666666667 tensor(3.2312)

2 2.803073474702381 tensor(3.0195)

3 2.713617745535714 tensor(2.9918)

4 2.694447916666667 tensor(2.9843)

5 2.6832286086309525 tensor(2.9815)

6 2.8065911458333335 tensor(2.9870)
back to previous

7 2.667179501488095 tensor(2.9882)
[ 16, 7, 1, 588, 2352, 288, 139.4, 2.9815, 6, 2.9882, 2.9815, 2.8066, 10500],

# L12

In [ ]:
# L12 Forgetter env2 (default: B12//2 N5250 lr10e-4 WD1.8) # H15(5): 2.9857, H14(7): 2.9864, H12(6): 2.9889, H10(5): 2.9889, H9(3)@env1: 2.9861

# local best for H15(5): 2.9827 (valx8: 2.9857)
[ 12, 15, 5, 780, 3120, 288, 234.7, 2.9897, 6, 2.9972, 2.9897, 2.6806, 10500], # 1.0h
[ 12, 15, 5, 780, 3120, 272, 228.8, 2.9893, 7, 2.9961, 2.9893, 2.6566, 10500], # 1.0h
[ 12, 15, 5, 780, 3120, 256, 222.8, 2.9890, 7, 2.9956, 2.9890, 2.6518, 10500], # 0.9h 13.7G
[ 12, 15, 5, 780, 3120, 240, 216.8, 2.9854, 6, 2.9927, 2.9854, 2.6616, 10500], # 0.9h
[ 12, 15, 5, 780, 3120, 224, 210.8, 2.9913, 6, 2.9965, 2.9901, 2.6628, 10500], # 0.8h
[ 12, 15, 5, 780, 3120, 208, 204.8, 2.9871, 6, 2.9945, 2.9863, 2.6756, 10500], # 0.8h
[ 12, 15, 5, 780, 3120, 192, 198.8, 2.9997, 6, 3.0029, 2.9984, 2.6703, 10500], # 0.8h
[ 12, 15, 5, 780, 3120, 176, 192.8, 2.9885, 6, 2.9951, 2.9869, 2.6712, 10500], # 0.7h
[ 12, 15, 5, 780, 3120, 160, 186.8, 2.9909, 6, 2.9972, 2.9897, 2.6842, 10500], # 0.7h

[ 12, 15, 5, 750, 3000, 288, 222.5, 2.9863, 6, 2.9925, 2.9855, 2.6839, 10500], # 1.0h
[ 12, 15, 5, 750, 3000, 272, 216.7, 2.9888, 6, 2.9943, 2.9867, 2.6754, 10500], # 1.0h
[ 12, 15, 5, 750, 3000, 256, 211.0, 2.9906, 6, 2.9957, 2.9887, 2.6721, 10500], # 0.9h 13.5G
[ 12, 15, 5, 750, 3000, 240, 205.2, 2.9927, 6, 2.9978, 2.9908, 2.6801, 10500], # 0.8h 13.4G
[ 12, 15, 5, 750, 3000, 224, 199.4, 2.9898, 6, 2.9972, 2.9875, 2.6670, 10500], # 0.8h
[ 12, 15, 5, 750, 3000, 208, 193.7, 2.9913, 7, 2.9961, 2.9913, 2.6577, 10500], # 0.8h 12.0G
[ 12, 15, 5, 750, 3000, 192, 187.9, 2.9902, 6, 2.9960, 2.9902, 2.6776, 10500], # 0.7h
[ 12, 15, 5, 750, 3000, 176, 182.2, 2.9945, 6, 3.1210, 2.9921, 2.7300, 10500], # 0.7h
[ 12, 15, 5, 750, 3000, 160, 176.4, 2.9909, 7, 2.9966, 2.9909, 2.6575, 10500], # 0.7h

[ 12, 15, 5, 720, 2880, 288, 210.5, 2.9909, 7, 2.9960, 2.9909, 2.6618, 10500], # 0.9h
[ 12, 15, 5, 720, 2880, 272, 204.9, 2.9892, 6, 2.9984, 2.9888, 2.6700, 10500], # 0.9h
[ 12, 15, 5, 720, 2880, 256, 199.4, 2.9945, 6, 3.0018, 2.9924, 2.6693, 10500], # 0.8h
[ 12, 15, 5, 720, 2880, 240, 193.9, 2.9993, 6, 3.0058, 2.9973, 2.6661, 10500], # 0.8h 12.1G
[ 12, 15, 5, 720, 2880, 224, 188.3, 2.9922, 6, 3.0005, 2.9908, 2.6746, 10500], # 0.8h
[ 12, 15, 5, 720, 2880, 208, 182.8, 2.9906, 6, 2.9989, 2.9905, 2.6657, 10500], # 0.7h
[ 12, 15, 5, 720, 2880, 192, 177.3, 2.9952, 7, 3.0022, 2.9952, 2.6542, 10500], # 0.7h
[ 12, 15, 5, 720, 2880, 176, 171.8, 2.9952, 6, 3.0036, 2.9951, 2.6680, 10500], # 0.7h
[ 12, 15, 5, 720, 2880, 160, 166.2, 2.9972, 6, 3.0047, 2.9972, 2.6665, 10500], # 0.6h

[ 12, 15, 5, 690, 2760, 288, 198.7, 2.9867, 6, 2.9954, 2.9855, 2.6715, 10500], # 0.9h 12.3G
[ 12, 15, 5, 690, 2760, 272, 193.4, 2.9962, 5, 2.9985, 2.9961, 2.6712, 10500], # 0.9h
[ 12, 15, 5, 690, 2760, 256, 188.1, 2.9940, 6, 3.0020, 2.9921, 2.6703, 10500], # 0.8h
[ 12, 15, 5, 690, 2760, 240, 182.8, 2.9860, 7, 2.9927, 2.9860, 2.6608, 10500], # 0.8h
[ 12, 15, 5, 690, 2760, 224, 177.5, 2.9908, 6, 2.9981, 2.9884, 2.6697, 10500], # 0.8h
[ 12, 15, 5, 690, 2760, 208, 172.2, 2.9952, 6, 3.0015, 2.9947, 2.6723, 10500], # 0.7h
[ 12, 15, 5, 690, 2760, 192, 166.9, 2.9924, 7, 2.9989, 2.9924, 2.6538, 10500], # 0.7h
[ 12, 15, 5, 690, 2760, 176, 161.6, 2.9860, 6, 2.9928, 2.9859, 2.6714, 10500], # 0.7h 11.2G
[ 12, 15, 5, 690, 2760, 160, 156.3, 2.9910, 7, 2.9978, 2.9910, 2.6572, 10500], # 0.6h

[ 12, 15, 5, 660, 2640, 288, 187.2, 2.9912, 6, 3.0003, 2.9892, 2.6696, 10500], # 0.9h 12.1G
[ 12, 15, 5, 660, 2640, 272, 182.2, 2.9950, 6, 3.0035, 2.9931, 2.6667, 10500], # 0.9h
[ 12, 15, 5, 660, 2640, 256, 177.1, 2.9884, 7, 2.9970, 2.9884, 2.6554, 10500], # 0.8h
[ 12, 15, 5, 660, 2640, 240, 172.0, 2.9877, 6, 2.9950, 2.9860, 2.6697, 10500], # 0.8h
[ 12, 15, 5, 660, 2640, 224, 166.9, 2.9982, 6, 3.0063, 2.9970, 2.6723, 10500], # 0.8h
[ 12, 15, 5, 660, 2640, 208, 161.9, 2.9918, 6, 2.9999, 2.9914, 2.6674, 10500], # 0.6h
[+12, 15, 5, 660, 2640, 192, 156.8, 2.9836, 6, 2.9899,+2.9827, 2.6713, 10500], # 0.7h  minGemma-hidden_layers12-att_heads15-kv_heads5-hidden660-intermediate2640-head_dim192-T1024--2026-06-13-20-20
# valx8: 2.9857 +- 0.0040 # torch.Tensor([2.9827, 2.9910, 2.9836, 2.9939, 2.9849, 2.9828, 2.9831, 2.9852, 2.9843]).std()
[ 12, 15, 5, 660, 2640, 176, 151.7, 2.9876, 6, 2.9957, 2.9872, 2.6693, 10500], # 0.7h
[ 12, 15, 5, 660, 2640, 160, 146.7, 2.9958, 6, 3.0037, 2.9958, 2.6733, 10500], # 0.6h

[ 12, 15, 5, 630, 2520, 288, 176.0, 2.9923, 7, 2.9991, 2.9923, 2.6638, 10500], # 0.9h
[ 12, 15, 5, 630, 2520, 272, 171.2, 2.9918, 6, 2.9967, 2.9895, 2.6764, 10500], # 0.9h 11.8G
[ 12, 15, 5, 630, 2520, 256, 166.3, 2.9845, 7, 2.9895, 2.9845, 2.6794, 10500], # 0.8h
[ 12, 15, 5, 630, 2520, 240, 161.5, 2.9868, 7, 2.9916, 2.9868, 2.6604, 10500], # 0.8h
[ 12, 15, 5, 630, 2520, 224, 156.6, 2.9925, 6, 2.9989, 2.9909, 2.6755, 10500], # 0.7h
[ 12, 15, 5, 630, 2520, 208, 151.8, 2.9872, 6, 2.9927, 2.9864, 2.6742, 10500], # 0.7h
[ 12, 15, 5, 630, 2520, 192, 147.0, 2.9958, 6, 3.0028, 2.9949, 2.6742, 10500], # 0.7h
[ 12, 15, 5, 630, 2520, 176, 142.1, 2.9923, 6, 2.9989, 2.9907, 2.6692, 10500], # 0.6h
[ 12, 15, 5, 630, 2520, 160, 137.3, 2.9962, 6, 3.0047, 2.9939, 2.6751, 10500], # 0.6h

[ 12, 15, 5, 600, 2400, 288, 165.0, 2.9948, 6, 3.0015, 2.9926, 2.6791, 10500], # 0.9h
[ 12, 15, 5, 600, 2400, 272, 160.4, 2.9945, 6, 3.0034, 2.9932, 2.6728, 10500], # 0.9h
[ 12, 15, 5, 600, 2400, 256, 155.8, 2.9973, 6, 3.0036, 2.9968, 2.6772, 10500], # 0.8h
[ 12, 15, 5, 600, 2400, 240, 151.2, 2.9944, 6, 2.9996, 2.9926, 2.6799, 10500], # 0.8h
[ 12, 15, 5, 600, 2400, 224, 146.6, 2.9896, 6, 2.9979, 2.9883, 2.6759, 10500], # 0.7h
[ 12, 15, 5, 600, 2400, 208, 142.0, 2.9907, 6, 2.9978, 2.9900, 2.6730, 10500], # 0.7h 11.0G
[ 12, 15, 5, 600, 2400, 192, 137.4, 2.9863, 7, 2.9936, 2.9863, 2.6662, 10500], # 0.6h
[ 12, 15, 5, 600, 2400, 176, 132.8, 2.9909, 7, 2.9988, 2.9909, 2.6612, 10500], # 0.6h
[ 12, 15, 5, 600, 2400, 160, 128.2, 2.9936, 7, 2.9999, 2.9936, 2.6621, 10500], # 0.6h

[ 12, 15, 5, 570, 2280, 288, 154.3, 2.9877, 7, 2.9919, 2.9877, 2.7018, 10500], # 0.9h
[ 12, 15, 5, 570, 2280, 272, 149.9, 2.9944, 7, 2.9985, 2.9944, 2.6695, 10500], # 0.9h
[ 12, 15, 5, 570, 2280, 256, 145.5, 2.9972, 6, 3.0040, 2.9972, 2.6786, 10500], # 0.8h
[ 12, 15, 5, 570, 2280, 240, 141.2, 2.9951, 7, 3.0029, 2.9951, 2.6734, 10500], # 0.7h
[ 12, 15, 5, 570, 2280, 224, 136.8, 2.9902, 6, 2.9964, 2.9890, 2.6842, 10500], # 0.7h 11.0G
[ 12, 15, 5, 570, 2280, 208, 132.4, 2.9922, 7, 2.9988, 2.9922, 2.6674, 10500], # 0.7h
[ 12, 15, 5, 570, 2280, 192, 128.0, 2.9905, 7, 2.9970, 2.9905, 2.6703, 10500], # 0.6h
[ 12, 15, 5, 570, 2280, 176, 123.7, 2.9968, 6, 3.0022, 2.9950, 2.6801, 10500], # 0.6h
[ 12, 15, 5, 570, 2280, 160, 119.3, 2.9927, 7, 2.9991, 2.9927, 2.6685, 10500], # 0.6h 10.3G


# local best for H14(7): 2.9832 (valx8: 2.9864)
[ 12, 14, 7, 784, 3136, 288, 241.8, 2.9888, 7, 2.9912, 2.9888, 2.6637, 10500], # 1.0h
[ 12, 14, 7, 784, 3136, 272, 235.5, 2.9918, 7, 2.9938, 2.9918, 2.6624, 10500], # 1.0h
[ 12, 14, 7, 784, 3136, 256, 229.2, 2.9934, 7, 2.9947, 2.9934, 2.6875, 10500], # 0.9h
[ 12, 14, 7, 784, 3136, 240, 222.8, 2.9947,10, 2.9949, 2.9938, 2.6616, 10500], # 0.9h
[ 12, 14, 7, 784, 3136, 224, 216.5, 2.9946, 6, 2.9987, 2.9944, 2.6703, 10500], # 0.8h
[ 12, 14, 7, 784, 3136, 208, 210.2, 2.9956, 6, 2.9982, 2.9944, 2.6746, 10500], # 0.8h
[ 12, 14, 7, 784, 3136, 192, 203.9, 2.9877, 7, 2.9896, 2.9877, 2.6591, 10500], # 0.7h
[ 12, 14, 7, 784, 3136, 176, 197.6, 2.9920, 6, 2.9965, 2.9915, 2.6688, 10500], # 0.7h
[ 12, 14, 7, 784, 3136, 160, 191.2, 2.9957, 6, 2.9984, 2.9957, 2.7097, 10500], # 0.7h

[ 12, 14, 7, 728, 2912, 288, 218.7, 2.9897, 6, 2.9957, 2.9888, 2.6717, 10500], # 1.0h
[ 12, 14, 7, 728, 2912, 272, 212.8, 2.9970, 7, 2.9988, 2.9970, 2.6596, 10500], # 0.9h
[ 12, 14, 7, 728, 2912, 256, 206.9, 2.9898, 7, 2.9908, 2.9898, 2.6596, 10500], # 0.8h
[ 12, 14, 7, 728, 2912, 240, 201.1, 2.9915, 6, 2.9962, 2.9909, 2.6719, 10500], # 0.8h
[ 12, 14, 7, 728, 2912, 224, 195.2, 2.9898, 6, 2.9944, 2.9894, 2.6752, 10500], # 0.8h
[ 12, 14, 7, 728, 2912, 208, 189.3, 2.9938, 6, 2.9980, 2.9928, 2.6707, 10500], # 0.8h
[ 12, 14, 7, 728, 2912, 192, 183.4, 2.9931, 6, 2.9983, 2.9931, 2.6799, 10500], # 0.7h 11.5G
[ 12, 14, 7, 728, 2912, 176, 177.6, 2.9910, 6, 2.9943, 2.9907, 2.6744, 10500], # 0.7h
[ 12, 14, 7, 728, 2912, 160, 171.7, 2.9860, 7, 2.9888, 2.9860, 2.6609, 10500], # 0.6h

[ 12, 14, 7, 672, 2688, 288, 196.4, 2.9916, 6, 2.9969, 2.9913, 2.6797, 10500], # 0.9h
[ 12, 14, 7, 672, 2688, 272, 191.0, 2.9865, 7, 2.9888, 2.9865, 2.6921, 10500], # 0.9h 11.9G
[ 12, 14, 7, 672, 2688, 256, 185.6, 2.9923, 6, 2.9995, 2.9921, 2.6733, 10500], # 0.8h
[ 12, 14, 7, 672, 2688, 240, 180.2, 2.9945, 7, 2.9969, 2.9945, 2.6616, 10500], # 0.8h
[ 12, 14, 7, 672, 2688, 224, 174.8, 2.9922, 7, 2.9941, 2.9922, 2.6705, 10500], # 0.7h 11.5G
[ 12, 14, 7, 672, 2688, 208, 169.3, 2.9936, 6, 2.9976, 2.9916, 2.6685, 10500], # 0.7h
[ 12, 14, 7, 672, 2688, 192, 163.9, 2.9944, 6, 2.9991, 2.9937, 2.6746, 10500], # 0.7h
[ 12, 14, 7, 672, 2688, 176, 158.5, 2.9879, 6, 2.9916, 2.9878, 2.6696, 10500], # 0.6h
[ 12, 14, 7, 672, 2688, 160, 153.1, 2.9996, 6, 3.0036, 2.9978, 2.6686, 10500], # 0.6h

[ 12, 14, 7, 616, 2464, 288, 175.1, 2.9875, 7, 2.9904, 2.9875, 2.6702, 10500], # 0.9h
[ 12, 14, 7, 616, 2464, 272, 170.1, 2.9963, 6, 3.0030, 2.9944, 2.6705, 10500], # 0.9h
[ 12, 14, 7, 616, 2464, 256, 165.2, 2.9956, 6, 3.0011, 2.9939, 2.6763, 10500], # 0.8h
[ 12, 14, 7, 616, 2464, 240, 160.2, 2.9866, 6, 2.9909,+2.9859, 2.6714, 10500], # 0.8h
[ 12, 14, 7, 616, 2464, 224, 155.2, 2.9862, 7, 2.9900,+2.9862, 2.6671, 10500], # 0.7h
[ 12, 14, 7, 616, 2464, 208, 150.3, 2.9919, 6, 2.9959, 2.9901, 2.6725, 10500], # 0.7h
[ 12, 14, 7, 616, 2464, 192, 145.3, 2.9887, 7, 2.9903, 2.9887, 2.6722, 10500], # 0.6h
[+12, 14, 7, 616, 2464, 176, 140.3, 2.9832, 7, 2.9843,+2.9832, 2.6731, 10500], # 0.6h  minGemma-hidden_layers12-att_heads14-kv_heads7-hidden616-intermediate2464-head_dim176-T1024--2026-05-23-12-52
# valx8: 2.9864 +- 0.0058 # torch.Tensor([2.9832, 2.9811, 2.9896, 2.9890, 2.9965, 2.9836, 2.9919, 2.9778, 2.9849]).std()
[ 12, 14, 7, 616, 2464, 160, 135.4, 2.9874, 7, 2.9900, 2.9874, 2.6648, 10500], # 0.6h

[ 12, 14, 7, 560, 2240, 288, 154.7, 2.9892, 7, 2.9914, 2.9892, 2.6728, 10500], # 0.9h
[ 12, 14, 7, 560, 2240, 272, 150.1, 2.9854, 7, 2.9873,+2.9854, 2.6786, 10500], # 0.8h 
[ 12, 14, 7, 560, 2240, 256, 145.6, 2.9959, 7, 2.9962, 2.9937, 2.6748, 10500], # 0.8h
[ 12, 14, 7, 560, 2240, 240, 141.1, 2.9920, 7, 2.9926, 2.9920, 2.6728, 10500], # 0.7h
[ 12, 14, 7, 560, 2240, 224, 136.6, 2.9862, 7, 2.9881,+2.9862, 2.6829, 10500], # 0.7h
[ 12, 14, 7, 560, 2240, 208, 132.1, 2.9926, 6, 2.9974, 2.9917, 2.6784, 10500], # 0.7h
[ 12, 14, 7, 560, 2240, 192, 127.6, 2.9953, 6, 2.9992, 2.9950, 2.6854, 10500], # 0.6h
[ 12, 14, 7, 560, 2240, 176, 123.1, 2.9912, 6, 2.9959, 2.9902, 2.6895, 10500], # 0.6h
[ 12, 14, 7, 560, 2240, 160, 118.5, 2.9941, 7, 2.9975, 2.9941, 2.6799, 10500], # 0.6h


# local best for H12(6): 2.9841 (valx8: 2.9889)
[ 12, 12, 6, 816, 3264, 288, 238.5, 2.9952, 6, 2.9992, 2.9949, 2.6728, 10500], # 0.9h
[ 12, 12, 6, 816, 3264, 272, 232.9, 2.9918, 9, 2.9930, 2.9915, 2.6628, 10500], # 0.9h
[ 12, 12, 6, 816, 3264, 256, 227.2, 2.9911, 6, 2.9939, 2.9909, 2.6696, 10500], # 0.8h
[ 12, 12, 6, 816, 3264, 240, 221.6, 2.9983, 7, 2.9993, 2.9983, 2.6684, 10500], # 0.8h
[ 12, 12, 6, 816, 3264, 224, 216.0, 2.9886, 6, 2.9903, 2.9870, 2.6720, 10500], # 0.7h
[ 12, 12, 6, 816, 3264, 208, 210.3, 2.9937, 6, 2.9990, 2.9931, 2.6666, 10500], # 0.7h 13.0G
[ 12, 12, 6, 816, 3264, 192, 204.7, 2.9911, 7, 2.9938, 2.9911, 2.6666, 10500], # 0.7h 12.9G
[ 12, 12, 6, 816, 3264, 176, 199.0, 2.9895,10, 2.9905, 2.9881, 2.6648, 10500], # 0.7h
[ 12, 12, 6, 816, 3264, 160, 193.4, 2.9953, 7, 2.9956, 2.9953, 2.6677, 10500], # 0.6h 11.5G

[ 12, 12, 6, 768, 3072, 288, 219.2, 2.9875, 7, 2.9903, 2.9875, 2.6683, 10500], # 0.8h
[ 12, 12, 6, 768, 3072, 272, 213.9, 2.9928, 7, 2.9931, 2.9928, 2.6671, 10500], # 0.8h
[ 12, 12, 6, 768, 3072, 256, 208.6, 2.9933, 6, 2.9981, 2.9933, 2.6935, 10500], # 0.7h
[ 12, 12, 6, 768, 3072, 240, 203.3, 2.9921, 6, 2.9946, 2.9910, 2.6697, 10500], # 0.7h
[ 12, 12, 6, 768, 3072, 224, 198.0, 2.9972, 6, 3.0025, 2.9965, 2.6866, 10500], # 0.7h
[ 12, 12, 6, 768, 3072, 208, 192.6, 2.9949, 6, 2.9989, 2.9936, 2.6689, 10500], # 0.7h
[ 12, 12, 6, 768, 3072, 192, 187.3, 2.9891, 7, 2.9911, 2.9891, 2.6607, 10500], # 0.6h
[ 12, 12, 6, 768, 3072, 176, 182.0, 2.9942, 7, 2.9976, 2.9942, 2.6618, 10500], # 0.6h
[ 12, 12, 6, 768, 3072, 160, 176.7, 2.9895, 7, 2.9917, 2.9895, 2.6606, 10500], # 0.6h

[ 12, 12, 6, 720, 2880, 288, 200.5, 2.9994, 6, 3.0043, 2.9971, 2.6656, 10500], # 0.8h 12.0G
[ 12, 12, 6, 720, 2880, 272, 195.5, 2.9945, 6, 2.9991, 2.9927, 2.6745, 10500], # 0.8h
[ 12, 12, 6, 720, 2880, 256, 190.6, 2.9930, 7, 2.9958, 2.9930, 2.6611, 10500], # 0.7h 11.7G
[ 12, 12, 6, 720, 2880, 240, 185.6, 2.9903, 7, 2.9931, 2.9903, 2.6608, 10500], # 0.7h
[ 12, 12, 6, 720, 2880, 224, 180.6, 2.9845, 6, 2.9876,+2.9845, 2.7111, 10500], # 0.7h
[ 12, 12, 6, 720, 2880, 208, 175.6, 2.9920, 6, 2.9966, 2.9907, 2.6729, 10500], # 0.6h
[ 12, 12, 6, 720, 2880, 192, 170.7, 2.9974, 6, 3.0018, 2.9961, 2.6731, 10500], # 0.6h
[ 12, 12, 6, 720, 2880, 176, 165.7, 2.9890, 7, 3.1005, 2.9890, 2.6726, 10500], # 0.6h
[ 12, 12, 6, 720, 2880, 160, 160.7, 2.9970, 7, 2.9979, 2.9970, 2.6709, 10500], # 0.6h

[ 12, 12, 6, 672, 2688, 288, 182.5, 2.9955, 6, 3.0008, 2.9942, 2.6745, 10500], # 0.8h
[ 12, 12, 6, 672, 2688, 272, 177.9, 2.9935, 7, 2.9948, 2.9935, 2.6640, 10500], # 0.8h
[ 12, 12, 6, 672, 2688, 256, 173.2, 2.9925, 6, 2.9971, 2.9902, 2.6775, 10500], # 0.7h
[ 12, 12, 6, 672, 2688, 240, 168.6, 2.9944, 6, 2.9990, 2.9938, 2.6755, 10500], # 0.7h
[ 12, 12, 6, 672, 2688, 224, 163.9, 2.9919, 6, 2.9966, 2.9905, 2.6776, 10500], # 0.6h 11.2G
[ 12, 12, 6, 672, 2688, 208, 159.3, 2.9886, 7, 2.9913, 2.9886, 2.6652, 10500], # 0.6h
[ 12, 12, 6, 672, 2688, 192, 154.6, 2.9900, 9, 2.9920, 2.9891, 2.6711, 10500], # 0.6h
[ 12, 12, 6, 672, 2688, 176, 150.0, 2.9920, 6, 2.9940, 2.9919, 2.6791, 10500], # 0.6h
[ 12, 12, 6, 672, 2688, 160, 145.3, 2.9945, 7, 2.9982, 2.9945, 2.6646, 10500], # 0.5h

[ 12, 12, 6, 624, 2496, 288, 165.1, 2.9949, 7, 2.9976, 2.9949, 2.6659, 10500], # 0.8h
[ 12, 12, 6, 624, 2496, 272, 160.8, 2.9947, 6, 2.9981, 2.9938, 2.6841, 10500], # 0.7h
[ 12, 12, 6, 624, 2496, 256, 156.5, 2.9917, 6, 2.9938, 2.9909, 2.6810, 10500], # 0.7h
[ 12, 12, 6, 624, 2496, 240, 152.2, 2.9943, 6, 2.9975, 2.9940, 2.6811, 10500], # 0.7h
[ 12, 12, 6, 624, 2496, 224, 147.9, 2.9942, 7, 2.9980, 2.9942, 2.6674, 10500], # 0.6h
[ 12, 12, 6, 624, 2496, 208, 143.6, 2.9927, 7, 2.9964, 2.9927, 2.6623, 10500], # 0.6h
[ 12, 12, 6, 624, 2496, 192, 139.3, 2.9933,11, 2.9958, 2.9921, 2.6719, 10500], # 0.6h
[ 12, 12, 6, 624, 2496, 176, 135.0, 2.9928, 6, 2.9979, 2.9924, 2.6786, 10500], # 0.5h
[+12, 12, 6, 624, 2496, 160, 130.6, 2.9841, 7, 2.9882,+2.9841, 2.6718, 10500], # 0.5h  minGemma-hidden_layers12-att_heads12-kv_heads6-hidden624-intermediate2496-head_dim160-T1024--2026-04-28-20-05
# valx8: 2.9889 +- 0.0039 # torch.Tensor([2.9841, 2.9851, 2.9956, 2.9898, 2.9918, 2.9874, 2.9930, 2.9867, 2.9863]).std()
[ 12, 12, 6, 624, 2496, 144, 126.3, 2.9925, 6, 2.9982, 2.9923, 2.6766, 10500], # 0.5h 10.3G

[ 12, 12, 6, 576, 2304, 288, 148.5, 2.9901, 7, 2.9924, 2.9901, 2.6819, 10500], # 0.7h
[ 12, 12, 6, 576, 2304, 272, 144.5, 2.9933, 7, 2.9938, 2.9933, 2.6801, 10500], # 0.7h
[ 12, 12, 6, 576, 2304, 256, 140.5, 2.9869, 7, 2.9893, 2.9869, 2.6951, 10500], # 0.6h 10.9G
[ 12, 12, 6, 576, 2304, 240, 136.5, 2.9947, 7, 2.9965, 2.9947, 2.6778, 10500], # 0.6h
[ 12, 12, 6, 576, 2304, 224, 132.5, 2.9909, 7, 2.9937, 2.9909, 2.6767, 10500], # 0.6h 10.6G
[ 12, 12, 6, 576, 2304, 208, 128.6, 2.9911, 7, 2.9921, 2.9911, 2.6730, 10500], # 0.6h
[ 12, 12, 6, 576, 2304, 192, 124.6, 2.9978, 6, 3.0009, 2.9970, 2.6859, 10500], # 0.5h
[ 12, 12, 6, 576, 2304, 176, 120.6, 2.9927, 7, 2.9949, 2.9927, 2.6705, 10500], # 0.5h
[ 12, 12, 6, 576, 2304, 160, 116.6, 2.9885, 7, 2.9917, 2.9885, 2.6738, 10500], # 0.5h


# local best for H10(5): 2.9851 (valx8: 2.9889)
[ 12, 10, 5, 800, 3200, 288, 215.4, 2.9952, 6, 2.9986, 2.9946, 2.6703, 10500], # 0.8h
[ 12, 10, 5, 800, 3200, 272, 210.8, 2.9911, 6, 2.9969, 2.9894, 2.6734, 10500], # 0.8h
[ 12, 10, 5, 800, 3200, 256, 206.2, 2.9952, 6, 2.9992, 2.9946, 2.6760, 10500], # 0.7h 13.0G
[ 12, 10, 5, 800, 3200, 240, 201.6, 2.9946, 6, 2.9977, 2.9923, 2.6882, 10500], # 0.7h
[ 12, 10, 5, 800, 3200, 224, 197.0, 2.9915, 7, 2.9939, 2.9915, 2.6629, 10500], # 0.7h
[ 12, 10, 5, 800, 3200, 208, 192.4, 2.9936,10, 2.9954, 2.9930, 2.6663, 10500], # 0.7h
[ 12, 10, 5, 800, 3200, 192, 187.8, 2.9887, 7, 2.9907, 2.9887, 2.6583, 10500], # 0.6h
[ 12, 10, 5, 800, 3200, 176, 183.2, 2.9872, 6, 2.9875, 2.9872, 2.9242, 10500], # 0.6h
[ 12, 10, 5, 800, 3200, 160, 178.6, 2.9924, 6, 2.9935, 2.9912, 2.7406, 10500], # 0.6h

[ 12, 10, 5, 760, 3040, 288, 200.3, 2.9906, 6, 2.9956, 2.9901, 2.6733, 10500], # 0.8h
[ 12, 10, 5, 760, 3040, 272, 195.9, 2.9903, 7, 2.9932, 2.9903, 2.6628, 10500], # 0.8h
[ 12, 10, 5, 760, 3040, 256, 191.5, 3.0003, 6, 3.0032, 3.0001, 2.6743, 10500], # 0.7h
[ 12, 10, 5, 760, 3040, 240, 187.1, 2.9960, 7, 2.9968, 2.9939, 2.6632, 10500], # 0.7h
[ 12, 10, 5, 760, 3040, 224, 182.8, 2.9902, 7, 2.9918, 2.9902, 2.6660, 10500], # 0.7h
[ 12, 10, 5, 760, 3040, 208, 178.4, 2.9921, 7, 2.9946, 2.9921, 2.7849, 10500], # 0.6h
[ 12, 10, 5, 760, 3040, 192, 174.0, 2.9983, 6, 3.0013, 2.9973, 2.6765, 10500], # 0.6h
[ 12, 10, 5, 760, 3040, 176, 169.6, 2.9884, 7, 2.9904, 2.9884, 2.6702, 10500], # 0.6h
[ 12, 10, 5, 760, 3040, 160, 165.2, 2.9879,11, 2.9910, 2.9879, 2.6803, 10500], # 0.5h

[ 12, 10, 5, 720, 2880, 288, 185.6, 2.9937, 6, 2.9976, 2.9931, 2.6695, 10500], # 0.7h 11.6G
[ 12, 10, 5, 720, 2880, 272, 181.4, 2.9945, 7, 2.9983, 2.9945, 2.6650, 10500], # 0.7h
[ 12, 10, 5, 720, 2880, 256, 177.3, 2.9953, 6, 2.9993, 2.9943, 2.6760, 10500], # 0.7h
[ 12, 10, 5, 720, 2880, 240, 173.1, 2.9890, 7, 2.9925, 2.9890, 2.6729, 10500], # 0.7h
[ 12, 10, 5, 720, 2880, 224, 169.0, 2.9925, 6, 2.9947, 2.9901, 2.7324, 10500], # 0.6h
[ 12, 10, 5, 720, 2880, 208, 164.8, 2.9889, 7, 2.9902, 2.9889, 2.6678, 10500], # 0.6h
[ 12, 10, 5, 720, 2880, 192, 160.7, 2.9924, 7, 2.9943, 2.9924, 2.6765, 10500], # 0.6h
[ 12, 10, 5, 720, 2880, 176, 156.5, 2.9929, 7, 2.9957, 2.9929, 2.6701, 10500], # 0.5h
[ 12, 10, 5, 720, 2880, 160, 152.4, 2.9919, 7, 2.9928, 2.9899, 2.6906, 10500], # 0.5h

[ 12, 10, 5, 680, 2720, 288, 171.4, 2.9930, 6, 2.9976, 2.9918, 2.6866, 10500], # 0.7h
[ 12, 10, 5, 680, 2720, 272, 167.4, 2.9932, 7, 2.9955, 2.9932, 2.6628, 10500], # 0.7h
[ 12, 10, 5, 680, 2720, 256, 163.5, 2.9927, 6, 2.9981, 2.9923, 2.6785, 10500], # 0.7h
[ 12, 10, 5, 680, 2720, 240, 159.6, 2.9944, 6, 2.9972, 2.9943, 2.6775, 10500], # 0.6h
[ 12, 10, 5, 680, 2720, 224, 155.7, 2.9851, 7, 2.9880,+2.9851, 2.6760, 10500], # 0.6h not saved
[ 12, 10, 5, 680, 2720, 208, 151.8, 2.9925, 7, 2.9959, 2.9925, 2.6682, 10500], # 0.6h
[ 12, 10, 5, 680, 2720, 192, 147.9, 2.9957, 7, 2.9980, 2.9957, 2.6623, 10500], # 0.6h
[ 12, 10, 5, 680, 2720, 176, 143.9, 2.9944, 7, 2.9974, 2.9944, 2.6687, 10500], # 0.5h
[ 12, 10, 5, 680, 2720, 160, 140.0, 2.9927, 6, 2.9935, 2.9915, 2.7577, 10500], # 0.5h

[ 12, 10, 5, 640, 2560, 288, 157.6, 2.9866, 6, 2.9918, 2.9865, 2.6828, 10500], # 0.7h
[ 12, 10, 5, 640, 2560, 272, 153.9, 2.9887, 6, 2.9914, 2.9880, 2.6814, 10500], # 0.7h
[ 12, 10, 5, 640, 2560, 256, 150.2, 2.9912, 9, 2.9922, 2.9910, 2.6740, 10500], # 0.6h
[ 12, 10, 5, 640, 2560, 240, 146.5, 2.9863, 6, 2.9883, 2.9862, 2.6779, 10500], # 0.6h 10.8G
[ 12, 10, 5, 640, 2560, 224, 142.8, 2.9886, 6, 2.9919, 2.9881, 2.6841, 10500], # 0.6h
[ 12, 10, 5, 640, 2560, 208, 139.2, 2.9931, 6, 2.9975, 2.9920, 2.6766, 10500], # 0.6h
[ 12, 10, 5, 640, 2560, 192, 135.5, 2.9903, 7, 2.9908, 2.9903, 2.6739, 10500], # 0.5h
[ 12, 10, 5, 640, 2560, 176, 131.8, 2.9970,14, 2.9977, 2.9966, 2.6680, 10500], # 0.5h 10.3G
[ 12, 10, 5, 640, 2560, 160, 128.1, 2.9961, 7, 2.9997, 2.9961, 2.6766, 10500], # 0.5h

[ 12, 10, 5, 600, 2400, 288, 144.3, 2.9908, 7, 2.9915, 2.9908, 2.6971, 10500], # 0.7h
[ 12, 10, 5, 600, 2400, 272, 140.8, 2.9955, 7, 2.9978, 2.9955, 2.6735, 10500], # 0.7h 10.8G
[ 12, 10, 5, 600, 2400, 256, 137.4, 2.9890, 7, 2.9923, 2.9890, 2.6678, 10500], # 0.6h
[ 12, 10, 5, 600, 2400, 240, 133.9, 2.9913, 6, 2.9941, 2.9904, 2.6984, 10500], # 0.6h
[ 12, 10, 5, 600, 2400, 224, 130.5, 2.9897, 7, 2.9909, 2.9897, 2.6788, 10500], # 0.6h
[ 12, 10, 5, 600, 2400, 208, 127.0, 3.0007, 7, 3.0023, 3.0007, 2.6737, 10500], # 0.6h
[ 12, 10, 5, 600, 2400, 192, 123.5, 2.9883, 7, 2.9920, 2.9883, 2.6770, 10500], # 0.5h
[ 12, 10, 5, 600, 2400, 176, 120.1, 2.9941, 7, 2.9974, 2.9941, 2.6749, 10500], # 0.5h
[ 12, 10, 5, 600, 2400, 160, 116.6, 2.9944,11, 2.9968, 2.9936, 2.6743, 10500], # 0.5h
[ 12, 10, 5, 560, 2240, 288, 131.4, 2.9901, 6, 2.9938, 2.9900, 2.6919, 10500], # 0.7h
[+12, 10, 5, 560, 2240, 272, 128.2, 2.9867, 6, 2.9898,+2.9862, 2.6921, 10500], # 0.7h minGemma-hidden_layers12-att_heads10-kv_heads5-hidden560-intermediate2240-head_dim272-T1024--2026-05-18-06-59
# valx8: 2.9889 +- 0.0046 # torch.Tensor([2.9862, 2.9917, 2.9835, 2.9941, 2.9964, 2.9913, 2.9879, 2.9842, 2.9852]).std()
[ 12, 10, 5, 560, 2240, 256, 125.0, 2.9900, 7, 2.9917, 2.9900, 2.6767, 10500], # 0.6h
[ 12, 10, 5, 560, 2240, 240, 121.8, 2.9934, 6, 2.9979, 2.9931, 2.6953, 10500], # 0.6h
[ 12, 10, 5, 560, 2240, 224, 118.5, 2.9923, 7, 2.9939, 2.9923, 2.6874, 10500], # 0.6h
[ 12, 10, 5, 560, 2240, 208, 115.3, 2.9914, 7, 2.9920, 2.9914, 2.6829, 10500], # 0.5h
[ 12, 10, 5, 560, 2240, 192, 112.1, 2.9946, 6, 2.9968, 2.9939, 2.6904, 10500], # 0.5h
[ 12, 10, 5, 560, 2240, 176, 108.9, 2.9960, 6, 2.9993, 2.9953, 2.6912, 10500], # 0.5h 9.9G
[ 12, 10, 5, 560, 2240, 160, 105.6, 2.9880, 7, 2.9881, 2.9880, 2.6790, 10500], # 0.4h


# local best for H9(3): 2.9837 (valx8: 2.9861) (env1, N6000 lr18e-4, WD1.2, rms1e-1, rope32000 <- default: env2, N5250, lr10e-4, WD1.8, rms1e0, rope80000)
[ 12, 9, 3, 756, 3024, 256, 176.1, 2.9970, 11, 2.9971, 2.9947, 2.8118, 12000], # 1.0h
[ 12, 9, 3, 756, 3024, 240, 172.7, 2.9897, 11, 3.0416, 2.9897, 2.8038, 12000], # 1.0h
[ 12, 9, 3, 756, 3024, 224, 169.2, 2.9919, 11, 2.9931, 2.9911, 2.7774, 12000], # 0.9h
[ 12, 9, 3, 756, 3024, 208, 165.7, 2.9913, 17, 2.9917, 2.9913, 2.7981, 12000], # 0.9h
[ 12, 9, 3, 756, 3024, 192, 162.2, 2.9901, 11, 2.9906,+2.9883, 2.7948, 12000], # 0.8h
[ 12, 9, 3, 756, 3024, 176, 158.7, 2.9915,  9, 3.1950, 2.9900, 2.8267, 12000], # 0.8h

[ 12, 9, 3, 720, 2880, 272, 167.3, 3.0008,  9, 3.0222, 3.0000, 2.8328, 12000], # 1.1h
[ 12, 9, 3, 720, 2880, 256, 164.0, 2.9916, 10, 2.9916, 2.9916, 2.8217,  13000],# 1.1h
[ 12, 9, 3, 720, 2880, 256, 164.0, 2.9876, 20, 2.9909,+2.9876, 2.8357,  12500],# 1.0h 12.4G
[ 12, 9, 3, 720, 2880, 256, 164.0, 2.9868, 16, 2.9924,+2.9867, 2.8198, 12000], # 1.0h
[ 12, 9, 3, 720, 2880, 256, 164.0, 2.9926, 20, 2.9944, 2.9919, 2.8193,  11500],# 0.9h 12.4G
[ 12, 9, 3, 720, 2880, 240, 160.7, 2.9912,  8, 2.9913, 2.9912, 2.9643, 12000], # 0.9h
[ 12, 9, 3, 720, 2880, 224, 157.4, 2.9991, 10, 3.0094, 2.9975, 2.8121,  12500],# 0.9h 12.2G
[ 12, 9, 3, 720, 2880, 224, 157.4, 2.9850, 11, 2.9900,+2.9850, 2.7858, 12000], # 0.9h
[ 12, 9, 3, 720, 2880, 224, 157.4, 2.9894, 22, 2.9906, 2.9894, 2.8056,  11500],# 0.9h
[ 12, 9, 3, 720, 2880, 208, 154.1, 3.0028,  9, 3.0044, 3.0024, 2.8139, 12000], # 0.9h
[ 12, 9, 3, 720, 2880, 192, 150.7, 2.9919, 16, 2.9942, 2.9907, 2.8302, 12000], # 0.8h
[ 12, 9, 3, 720, 2880, 176, 147.4, 2.9940, 11, 2.9954, 2.9919, 2.7991, 12000], # 0.8h

[ 12, 9, 3, 684, 2736, 256, 152.3, 3.0045,  5, 3.0892, 3.0045, 3.1495, 12000], # 0.9h
[ 12, 9, 3, 684, 2736, 240, 149.1, 3.0003, 11, 3.0030, 3.0003, 2.8473, 12000], # 0.9h
[ 12, 9, 3, 684, 2736, 224, 146.0, 2.9909, 11, 2.9915, 2.9909, 2.8134, 12000], # 0.9h
[ 12, 9, 3, 684, 2736, 208, 142.8, 2.9937,  6, 2.9937, 2.9937, 2.9110, 12000], # 0.9h
[ 12, 9, 3, 684, 2736, 192, 139.7, 2.9854, 17, 2.9881,+2.9854, 2.7869,  12500],# 0.8h
[ 12, 9, 3, 684, 2736, 192, 139.7, 2.9867, 11, 2.9881,+2.9867, 2.7925, 12000], # 0.8h
[ 12, 9, 3, 684, 2736, 192, 139.7, 2.9953, 11, 3.0452, 2.9953, 2.7940,  11500],# 0.8h 11.9G
[ 12, 9, 3, 684, 2736, 176, 136.5, 2.9929, 17, 3.0100, 2.9908, 2.7860, 12000], # 0.8h

[ 12, 9, 3, 648, 2592, 256, 140.9, 2.9901, 11, 2.9924, 2.9901, 2.8175, 12000], # 0.9h
[ 12, 9, 3, 648, 2592, 240, 137.9, 2.9886, 10, 2.9888,+2.9886, 2.8041,  12500],# 1.0h 11.9G
[ 12, 9, 3, 648, 2592, 240, 137.9, 2.9885, 11, 3.0356,+2.9870, 2.7893, 12000], # 0.9h
[ 12, 9, 3, 648, 2592, 240, 137.9, 2.9884, 11, 2.9896,+2.9884, 2.7912,  11500],# 0.9h
[ 12, 9, 3, 648, 2592, 224, 134.9, 2.9916, 16, 2.9942, 2.9914, 2.8156, 12000], # 0.9h
[ 12, 9, 3, 648, 2592, 208, 131.9, 2.9917, 11, 2.9938, 2.9917, 2.8113, 12000], # 0.8h 11.6G
[ 12, 9, 3, 648, 2592, 192, 129.0, 2.9892, 11, 2.9917, 2.9892, 2.7850, 12000], # 0.8h
[+12, 9, 3, 648, 2592, 176, 126.0, 2.9855, 17, 2.9873,+2.9847, 2.7824,  12500],# 0.8h  minGemma-hidden_layers12-att_heads9-kv_heads3-hidden648-intermediate2592-head_dim176-T1024--2026-04-19-20-20.pth (2.9837@14th)
# valx8: 2.9861 +- 0.0048 # torch.Tensor([2.9847, 2.9971, 2.9818, 2.9888, 2.9824, 2.9846, 2.9861, 2.9871, 2.9819]).std()
[ 12, 9, 3, 648, 2592, 176, 126.0, 2.9865, 17, 2.9895,+2.9865, 2.8236, 12000], # 0.8h
[ 12, 9, 3, 648, 2592, 176, 126.0, 2.9899, 14, 2.9917, 2.9899, 2.8223,  11500],# 0.7h
[ 12, 9, 3, 648, 2592, 160, 123.0, 2.9902, 11, 2.9916, 2.9902, 2.7929, 12000], # 0.7h

[ 12, 9, 3, 612, 2448, 256, 129.9, 2.9927, 11, 3.0010, 2.9927, 2.8189, 12000], # 0.9h
[ 12, 9, 3, 612, 2448, 240, 127.1, 2.9896, 16, 2.9936, 2.9896, 2.8287, 12000], # 0.9h
[ 12, 9, 3, 612, 2448, 224, 124.3, 2.9915, 11, 2.9928, 2.9915, 2.8029, 12000], # 0.8h
[ 12, 9, 3, 612, 2448, 208, 121.4, 2.9895, 11, 2.9914, 2.9895, 2.7807, 12000], # 0.8h
[ 12, 9, 3, 612, 2448, 192, 118.6, 2.9988, 10, 3.0019, 2.9988, 2.8282,  12500],# 0.8h 11.4G
[ 12, 9, 3, 612, 2448, 192, 118.6, 2.9870, 14, 2.9873,+2.9869, 2.7808, 12000], # 0.8h
[ 12, 9, 3, 612, 2448, 192, 118.6, 2.9886, 15, 2.9886, 2.9886, 2.7890,  11500],# 0.7h
[ 12, 9, 3, 612, 2448, 176, 115.8, 2.9961, 14, 2.9978, 2.9960, 2.7859, 12000], # 0.7h

[ 12, 9, 3, 576, 2304, 256, 119.3, 2.9925, 16, 2.9950, 2.9916, 2.8274, 12000], # 0.9h
[ 12, 9, 3, 576, 2304, 240, 116.6, 2.9943, 11, 2.9970, 2.9943, 2.7858, 12000], # 0.9h 11.5G
[ 12, 9, 3, 576, 2304, 224, 114.0, 3.0001, 13, 3.0007, 3.0001, 3.3941, 12000], # 0.8h 2.9998@10th
[ 12, 9, 3, 576, 2304, 208, 111.3, 2.9914, 16, 2.9956, 2.9910, 2.8122, 12000], # 0.8h 11.3G
[ 12, 9, 3, 576, 2304, 192, 108.7, 2.9971, 11, 2.9972, 2.9958, 2.7771, 12000], # 0.7h
[ 12, 9, 3, 576, 2304, 176, 106.0, 2.9891, 17, 2.9916,+2.9891, 2.7804, 12000], # 0.7h
[ 12, 9, 3, 576, 2304, 160, 103.3, 2.9911, 11, 2.9925, 2.9911, 2.7825, 12000], # 0.7h

In [193]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  12 # 8 # G28 G18 #blocks
num_attention_heads =15 # 4 # G16 G8
num_key_value_heads = 5 # 4 # G16 G1
hidden_size = num_attention_heads*44 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 192 # 32 # G256 # dim in attention
rms_norm_eps = 1e0 # 1e-6
rope_theta = 80000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//2; N_step=5250*2; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=10.0e-4, weight_decay=1.8, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(5000*2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9837:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

64.512
L12 att15 kv_heads5 hidden660 intermediate2640 head_dim192 T1024

1 4.556558035714286 tensor(3.2232)

2 2.7974745163690478 tensor(3.0166)

3 2.713362723214286 tensor(2.9923)

4 2.6937806919642857 tensor(2.9862)

5 2.678925967261905 tensor(2.9827)

6 2.6713125 tensor(2.9836)

7 2.660122581845238 tensor(2.9899)
[ 12, 15, 5, 660, 2640, 192, 156.8, 2.9836, 6, 2.9899, 2.9827, 2.6713, 10500],

In [129]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  12 # 8 # G28 G18 #blocks
num_attention_heads =14 # 4 # G16 G8
num_key_value_heads = 7 # 4 # G16 G1
hidden_size = num_attention_heads*44 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 176 # 32 # G256 # dim in attention
rms_norm_eps = 1e0 # 1e-6
rope_theta = 80000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//2; N_step=5250*2; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=10.0e-4, weight_decay=1.8, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(6000*2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9837:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

64.512
L12 att14 kv_heads7 hidden616 intermediate2464 head_dim176 T1024

1 4.605668526785714 tensor(3.2258)

2 2.8131927083333332 tensor(3.0305)

3 2.7272578125 tensor(2.9970)

4 2.7044661458333334 tensor(2.9897)

5 2.695087239583333 tensor(2.9835)

6 2.6831995907738095 tensor(2.9832)

7 2.6731263020833333 tensor(2.9871)
back to previous

8 2.678938802083333 tensor(2.9843)
[ 12, 14, 7, 616, 2464, 176, 140.3, 2.9832, 7, 2.9843, 2.9832, 2.6731, 10500],

In [45]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  12 # 8 # G28 G18 #blocks
num_attention_heads =12 # 4 # G16 G8
num_key_value_heads = 6 # 4 # G16 G1
hidden_size = num_attention_heads*52 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 160 # 32 # G256 # dim in attention
rms_norm_eps = 1e0 # 1e-6
rope_theta = 80000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//2; N_step=5250*2; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=10.0e-4, weight_decay=1.8, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(6000*2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9871:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

64.512
L12 att12 kv_heads6 hidden624 intermediate2496 head_dim160 T1024

1 4.662549851190477 tensor(3.2272)

2 2.8078675595238094 tensor(3.0265)

3 2.7257609747023808 tensor(2.9966)

4 2.7017440476190475 tensor(2.9900)

5 2.6903848586309524 tensor(2.9867)

6 2.6764246651785712 tensor(2.9841)

7 2.6717855282738094 tensor(2.9908)
back to previous

8 2.671871837797619 tensor(2.9882)
[ 12, 12, 6, 624, 2496, 160, 130.6, 2.9841, 7, 2.9882, 2.9841, 2.6718, 10500],

In [111]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  12 # 8 # G28 G18 #blocks
num_attention_heads =10 # 4 # G16 G8
num_key_value_heads = 5 # 4 # G16 G1
hidden_size = num_attention_heads*56 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 272 # 32 # G256 # dim in attention
rms_norm_eps = 1e0 # 1e-6
rope_theta = 80000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//2; N_step=5250*2; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=10.0e-4, weight_decay=1.8, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(6000*2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9871:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

64.512
L12 att10 kv_heads5 hidden560 intermediate2240 head_dim272 T1024

1 4.400994791666666 tensor(3.2311)

2 2.810853236607143 tensor(3.0252)

3 2.730714099702381 tensor(2.9951)

4 2.7106283482142857 tensor(2.9909)

5 2.7019605654761905 tensor(2.9862)

6 2.6921396949404763 tensor(2.9867)

7 2.6800846354166667 tensor(2.9898)
[ 12, 10, 5, 560, 2240, 272, 128.2, 2.9867, 6, 2.9898, 2.9862, 2.6921, 10500],

In [47]:
import matplotlib.pyplot as plt; import numpy as np; import time, torch; device = 'cuda' if torch.cuda.is_available() else 'cpu'
from transformers import AutoTokenizer, TrainingArguments, DefaultDataCollator, Trainer
vocab_size = 50257 # =tokenizer.vocab_size  # FIX!!! # G256128    ### T=256 for minGemma # G8192 for real Gemma
num_hidden_layers =  12 # 8 # G28 G18 #blocks
num_attention_heads = 9 # 4 # G16 G8
num_key_value_heads = 3 # 4 # G16 G1
hidden_size = num_attention_heads*72 # 128 # G3072 G2048 # embedding dimension
intermediate_size = hidden_size*4 # x4 or x8 # time limiting factor #512 # G24576 G16384  # MLP inner dim
head_dim = 176 # 32 # G256 # dim in attention
rms_norm_eps = 1e-1 # 1e-6
rope_theta = 32000.0 # scale freq is small for S-model. 1000 might work too # G10000.0

def apply_rotary_emb(x: torch.Tensor, dim: int) -> torch.Tensor: # seq_len = x.size(1) # N
    freqs = 1.0 / (rope_theta ** (torch.arange(0, dim, 2, device=device).float() / dim)) # Dynamically compute frequency cis
    t = torch.arange(x.size(1), device=device); freqs = torch.outer(t, freqs).float(); freqs_cis = torch.polar(torch.ones_like(freqs), freqs)  # complex64
    x_ = torch.view_as_complex(torch.stack(torch.chunk(x.transpose(1, 2).float(), 2, dim=-1), dim=-1))
    x_out = torch.view_as_real(x_ * freqs_cis.unsqueeze(0)).type_as(x)  # Ensure batch dimension is handled
    x_out = torch.cat(torch.chunk(x_out, 2, dim=-1), dim=-2)
    return x_out.reshape(x_out.shape[0], x_out.shape[1], x_out.shape[2], -1).transpose(1, 2)

class RMSNorm(torch.nn.Module): # RMS:4.326552, RMS_no_weight:4.410741 # RMS':4.554899
    def __init__(self, dim: int = hidden_size):
        super().__init__(); self.weight = torch.nn.Parameter(torch.zeros(dim)) # one weight per feature to be learned
    def _norm(self, x): # mean square for each feature (across the last dimension)
        return x * torch.rsqrt(x.pow(2).mean(-1, keepdim=True) + rms_norm_eps)
    def forward(self, x): # ensure the data type matches the input.
        return self._norm(x.float()).type_as(x) * (1 + self.weight)

class GemmaAttention(torch.nn.Module): # MQA = K,V shared by 4Qs
    def __init__(self):
        super().__init__(); self.qkv_proj = torch.nn.Linear(hidden_size, (num_attention_heads + 2 * num_key_value_heads) * head_dim, bias=False); self.o_proj = torch.nn.Linear(num_attention_heads * head_dim, hidden_size, bias=False) # concatenated attention outputs back to the hidden size.
    def forward(self, hidden_states: torch.Tensor,) -> torch.Tensor:  # in=(B, T, hidden_size)
        batch_size, input_len, _ = hidden_states.shape
        qkv = self.qkv_proj(hidden_states)
        xq, xk, xv = qkv.split([num_attention_heads * head_dim, num_key_value_heads * head_dim, num_key_value_heads * head_dim],dim=-1)
        xq = xq.view(batch_size, -1, num_attention_heads, head_dim); xk = xk.view(batch_size, -1, num_key_value_heads, head_dim); xv = xv.view(batch_size, -1, num_key_value_heads, head_dim)
        xq = apply_rotary_emb(xq, head_dim); xk = apply_rotary_emb(xk, head_dim)
        if num_key_value_heads != num_attention_heads:  # Q/KV multiples of K and V to match Q
            xk = torch.repeat_interleave(xk, num_attention_heads // num_key_value_heads, dim=2) # [B, T, n_local_heads, head_dim]
            xv = torch.repeat_interleave(xv, num_attention_heads // num_key_value_heads, dim=2)
        q = xq.transpose(1, 2); k = xk.transpose(1, 2); v = xv.transpose(1, 2) # [batch_size, n_local_heads, input_len, head_dim]
        output = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=None, dropout_p=0, is_causal=True) # B nh T hs        
        output = output.transpose(1, 2).contiguous().view(batch_size, input_len, -1)  # [B, T, "hidden_dim"]
        return self.o_proj(output)

class GemmaDecoderLayer(torch.nn.Module): # normalize before and after the attention mechanism
    def __init__(self):
        super().__init__(); self.self_attn = GemmaAttention(); self.input_layernorm = RMSNorm(); self.post_attention_layernorm = RMSNorm(); self.gate_proj = torch.nn.Linear(hidden_size, intermediate_size); self.up_proj = torch.nn.Linear(hidden_size, intermediate_size); self.down_proj = torch.nn.Linear(intermediate_size, hidden_size) # mlp
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:  # input_size = (B, T, hidden_size)
        residual = hidden_states # Self Attention Block
        hidden_states = self.input_layernorm(hidden_states); hidden_states = self.self_attn(hidden_states=hidden_states)
        hidden_states = residual + hidden_states
        residual = hidden_states # MLP Block
        hidden_states = self.post_attention_layernorm(hidden_states); gate = torch.nn.functional.gelu(self.gate_proj(hidden_states)); up = self.up_proj(hidden_states); fuse = gate * up; hidden_states = self.down_proj(fuse) # mlp
        return residual + hidden_states

class minGemma(torch.nn.Module):
    def __init__(self):
        super().__init__(); self.embedder = torch.nn.Embedding(vocab_size, hidden_size); self.layers = torch.nn.ModuleList(GemmaDecoderLayer() for _ in range(num_hidden_layers)); self.norm = RMSNorm();
    def forward(self, input_token_ids: torch.Tensor) -> torch.Tensor: # (B, T)
        hidden_states = self.embedder(input_token_ids[:,:-1]) # (B, T) & (vocab_size, hidden_size) -> (B, T, hidden_size)
        hidden_states = hidden_states * (hidden_size**0.5)
        for i in range(len(self.layers)):
            hidden_states = self.layers[i](hidden_states) # shortened too much???
        hidden_states = self.norm(hidden_states) # -> (B, T, hidden_size)        
        embedder_weight = self.embedder.weight
        logits = torch.matmul(hidden_states, embedder_weight.t()); b,t,v=logits.shape; # (B, T, hidden_size) @ (hidden_size, vocab_size) -> (B, T, vocab_size)
        loss = torch.nn.functional.cross_entropy(logits.view(b*t,v), input_token_ids[:,1:].reshape(b*t)) #, weight=None, ignore_index=-100, reduction='mean')
        return loss, logits # logits, loss

def map_to_array5(ix):
    common = torch.stack([torch.from_numpy((train_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}
def map_to_array_Val(ix):
    common = torch.stack([torch.from_numpy((val_data[i[0]:i[0]+T+1]).astype(np.int64)) for i in ix]); return {'input_token_ids': common}

train_data = np.memmap('train_BabyLM_10M.bin', dtype=np.uint16, mode='r'); val_data = np.memmap('val_BabyLM.bin', dtype=np.uint16, mode='r')
T=1024; B=12//2; N_step=6250*2; print(T * B * N_step / 1000000) # 0.01 B-tokens being calculated
model = minGemma().to(device); print(f'L{num_hidden_layers}' f' att{num_attention_heads}' f' kv_heads{num_key_value_heads}' f' hidden{hidden_size}' f' intermediate{intermediate_size}' f' head_dim{head_dim}' f' T{T}')

loss_prev=10000.0; loss_prev_prev=loss_prev; tloss_prev=10000.0; # Earlystop(2) w/ variable traindata
for ep in range(200):
    X = torch.randint(len(train_data)-T-1, (ep*B*N_step,)); del X;
    training_args = TrainingArguments(gradient_accumulation_steps=2, learning_rate=18.0e-4, weight_decay=1.2, num_train_epochs=1, logging_strategy='epoch', output_dir='./test', bf16=True, per_device_train_batch_size=B, per_device_eval_batch_size=B, eval_strategy='no', save_strategy='no', report_to='none', remove_unused_columns=False, dataloader_pin_memory=True) #, dataloader_num_workers=4
    trainer = Trainer(model=model, args=training_args, train_dataset=torch.utils.data.TensorDataset(torch.randint(len(train_data)-T-1, (B*N_step,))), data_collator=map_to_array5);
    result = trainer.train(); tloss=result[2]["train_loss"]
    # X = torch.randint(len(train_data)-T-1, (1*777,))
    model.eval(); loss = []; B2=12//2 # Evaluation follows
    for k in range(6000*2 *1): # std=0.0056 for 1000 with 89sec #5min
        val_ind = torch.randint(len(val_data)-T-1, (B2,)); common = (torch.stack([torch.from_numpy((val_data[i:i+T+1]).astype(np.int64)) for i in val_ind]))
        loss += [model(common.to('cuda', non_blocking=True))[0].item()]
    loss_current = torch.Tensor(loss).mean(); print(ep+1, tloss, loss_current); del common; torch.cuda.empty_cache(); model.train();
    if loss_current < 2.9974:
        torch.save(model.state_dict(), f'{model.__class__.__name__}' f'-hidden_layers{num_hidden_layers}' f'-att_heads{num_attention_heads}' f'-kv_heads{num_key_value_heads}' f'-hidden{hidden_size}' f'-intermediate{intermediate_size}' f'-head_dim{head_dim}' f'-T{T}' f'--{time.strftime("%Y-%m-%d-%H-%M")}.pth')
    if (loss_current >= loss_prev) and (loss_prev >= loss_prev_prev):
        break
    if (loss_current >= (loss_prev+0.0025)):
        model.load_state_dict(torch.load('test.pth')); loss_current = loss_prev; print("back to previous")
    loss_prev_prev = loss_prev; loss_prev = loss_current; tloss_prev=tloss; torch.save(model.state_dict(), 'test.pth'); # always save

print(f'[ {num_hidden_layers}, {num_attention_heads}, {num_key_value_heads}, {hidden_size}, {intermediate_size}, {head_dim}, {sum(p.numel() for p in model.parameters()) / 10**6:.1f}, {loss_prev:.4f}, {ep}, {loss_current:.4f}, {loss_prev_prev:.4f}, {tloss_prev:.4f}, {N_step}],')

76.8
L12 att9 kv_heads3 hidden648 intermediate2592 head_dim176 T1024

1 4.0886509375 tensor(3.0919)

2 2.862038125 tensor(3.0228)

3 2.815895 tensor(3.0081)

4 2.7990246875 tensor(3.0013)

5 2.8247771875 tensor(2.9984)

6 2.824346875 tensor(2.9973)

7 2.78843 tensor(2.9912)

8 2.78439375 tensor(2.9911)

9 2.81975125 tensor(2.9916)

10 2.7825740625 tensor(2.9907)

11 2.7879828125 tensor(2.9896)

12 2.8026375 tensor(2.9902)

13 2.808205 tensor(2.9877)

14 2.77791625 tensor(2.9837)

15 2.7740109375 tensor(2.9860)

16 2.7917746875 tensor(2.9847)

17 2.78238125 tensor(2.9855)

18 2.7923828125 tensor(2.9873)
[ 12, 9, 3, 648, 2592, 176, 126.0, 2.9855, 17, 2.9873, 2.9847, 2.7824, 12500],